"use client";
import { useState } from "react";
import { trackAnalyticsEvent } from "./AnalyticsEvents";
import type { SiteLocale } from "../i18n";

const labels = {
 en: { title: "Parcel weight worksheet", note: "Weight model only. This is not a live CSSBuy quote. Use your route’s divisor and rounding rule.", actual: "Actual weight (kg)", length: "Length (cm)", width: "Width (cm)", height: "Height (cm)", divisor: "Route divisor", step: "Billing increment (kg)", volume: "Volumetric weight", greater: "Greater of actual and volumetric", billed: "Rounded comparison weight", invalid: "Enter positive numbers in every field.", explain: "Formula: length × width × height ÷ divisor. The comparison rounds the greater weight up to the selected increment. Actual-weight-only lines use their own rule.", button: "Calculate weight" },
 de: { title: "Paketgewicht berechnen", note: "Nur ein Gewichtsmodell, kein aktuelles CSSBuy-Angebot. Verwende den Divisor und die Rundungsregel deiner Versandlinie.", actual: "Tatsächliches Gewicht (kg)", length: "Länge (cm)", width: "Breite (cm)", height: "Höhe (cm)", divisor: "Divisor der Versandlinie", step: "Abrechnungsschritt (kg)", volume: "Volumengewicht", greater: "Höherer Wert aus tatsächlichem und Volumengewicht", billed: "Gerundetes Vergleichsgewicht", invalid: "Gib in jedem Feld eine positive Zahl ein.", explain: "Formel: Länge × Breite × Höhe ÷ Divisor. Der höhere Gewichtswert wird auf den gewählten Abrechnungsschritt aufgerundet. Linien nach tatsächlichem Gewicht haben eigene Regeln.", button: "Gewicht berechnen" },
 "pt-br": { title: "Calculadora de peso da encomenda", note: "Apenas um modelo de peso, sem cotação ao vivo do CSSBuy. Use o divisor e a regra de arredondamento da sua rota.", actual: "Peso real (kg)", length: "Comprimento (cm)", width: "Largura (cm)", height: "Altura (cm)", divisor: "Divisor da rota", step: "Incremento de cobrança (kg)", volume: "Peso volumétrico", greater: "Maior entre peso real e volumétrico", billed: "Peso comparativo arredondado", invalid: "Insira números positivos em todos os campos.", explain: "Fórmula: comprimento × largura × altura ÷ divisor. O maior peso é arredondado para cima conforme o incremento escolhido. Rotas que cobram apenas peso real têm regras próprias.", button: "Calcular peso" },
 es: { title: "Calculadora de peso del paquete", note: "Solo un modelo de peso, sin cotización en vivo de CSSBuy. Usa el divisor y la regla de redondeo de tu ruta.", actual: "Peso real (kg)", length: "Largo (cm)", width: "Ancho (cm)", height: "Alto (cm)", divisor: "Divisor de la ruta", step: "Incremento de facturación (kg)", volume: "Peso volumétrico", greater: "Mayor entre peso real y volumétrico", billed: "Peso comparativo redondeado", invalid: "Introduce números positivos en todos los campos.", explain: "Fórmula: largo × ancho × alto ÷ divisor. El peso mayor se redondea hacia arriba al incremento seleccionado. Las rutas basadas solo en el peso real tienen sus propias reglas.", button: "Calcular peso" },
};
export function ParcelWeightCalculator({ locale = "en" }: { locale?: SiteLocale }) {
 const copy = labels[locale];
 const [values, setValues] = useState({ actual: "3.2", length: "40", width: "30", height: "25", divisor: "6000", step: "0.5" });
 const [result, setResult] = useState<{ volume: number; greater: number; billed: number } | null>(null);
 const [error, setError] = useState(false);
 const format = (value: number) => new Intl.NumberFormat(locale, { maximumFractionDigits: 3 }).format(value);
 return <section className="parcel-calculator" aria-labelledby="parcel-calculator-heading"><h2 id="parcel-calculator-heading">{copy.title}</h2><p>{copy.note}</p>
 <form onSubmit={event => { event.preventDefault(); const n = Object.fromEntries(Object.entries(values).map(([k,v]) => [k, Number(v)])); if (Object.values(n).some(v => !Number.isFinite(v) || v <= 0)) { setError(true); setResult(null); return; } const volume = n.length * n.width * n.height / n.divisor; const greater = Math.max(n.actual, volume); setResult({ volume, greater, billed: Math.ceil((greater - 1e-10) / n.step) * n.step }); setError(false); trackAnalyticsEvent("parcel_weight_calculate", { site_locale: locale }); }}>
 <div className="calculator-fields">{(Object.keys(values) as (keyof typeof values)[]).map(key => <label key={key}>{copy[key]}<input type="number" name={key} min="0.001" step="any" required value={values[key]} onChange={event => { setValues(previous => ({ ...previous, [key]: event.target.value })); setResult(null); }} /></label>)}</div><button type="submit">{copy.button}</button>
 </form><div aria-live="polite">{error ? <p role="alert">{copy.invalid}</p> : null}{result ? <dl className="calculator-results">{(["volume", "greater", "billed"] as const).map(key => <div key={key}><dt>{copy[key]}</dt><dd>{format(result[key])} kg</dd></div>)}</dl> : null}</div><p className="calculator-note">{copy.explain}</p></section>;
}
