export type Product = {
  id: string;
  name: string;
  category: string;
  categoryLabel: string;
  image: string;
  cny: number;
  usd: string;
  checked: string;
  storeUrl: string;
  summary: string;
};

export const categories = [
  { slug: "shoes", name: "Shoes", symbol: "S／", searchLabel: "Runners, loafers, slides", checkSummary: "Compare foot or insole length in centimeters, select the exact size and color, inspect pair alignment and visible finish, and decide whether the box is worth its parcel volume.", storeUrl: "https://www.cnbuycha.com/shoes/" },
  { slug: "hoodies-sweaters", name: "Hoodies", symbol: "H＋", searchLabel: "Hoodies and knitwear", checkSummary: "Use actual garment measurements, confirm the color and graphic option, inspect print placement and visible marks, and plan for the volume of thick or oversized fabric.", storeUrl: "https://www.cnbuycha.com/hoodies-sweaters/" },
  { slug: "t-shirts", name: "T-Shirts", symbol: "T°", searchLabel: "Tees, polos, shirts", checkSummary: "Compare flat chest, shoulder, sleeve, and length measurements; confirm the selected print and color; and inspect collars, seams, alignment, and visible staining.", storeUrl: "https://www.cnbuycha.com/t-shirts/" },
  { slug: "jackets", name: "Jackets", symbol: "J↗", searchLabel: "Light and winter layers", checkSummary: "Check garment measurements, zipper and snap hardware, pockets, visible damage, and any described filling. Bulky layers can affect parcel dimensions even when they are not especially heavy.", storeUrl: "https://www.cnbuycha.com/jackets/" },
  { slug: "jerseys", name: "Jerseys", symbol: "11", searchLabel: "Club and national kits", checkSummary: "Confirm fan or player version, sleeve style, size chart, name and number, and optional patches. Inspect badge and print placement on both the front and back before shipping.", storeUrl: "https://www.cnbuycha.com/Jersey/" },
  { slug: "accessories", name: "Accessories", symbol: "A◇", searchLabel: "Bags, watches, extras", checkSummary: "Verify dimensions, materials described, included parts, closures, straps, and hardware. Batteries, liquids, magnets, or fragile components can change available parcel routes.", storeUrl: "https://www.cnbuycha.com/accessories/" },
  { slug: "headwear", name: "Headwear", symbol: "C⌒", searchLabel: "Caps, hats, beanies", checkSummary: "Check circumference or adjustability, selected color, embroidery or print placement, panel symmetry, brim shape, and packaging that will not crush structured headwear.", storeUrl: "https://www.cnbuycha.com/headwear/" },
  { slug: "electronics", name: "Electronics", symbol: "E□", searchLabel: "Cases, audio, devices", checkSummary: "Confirm the exact model, voltage, plug, battery status, and included parts. Warehouse photos show visible condition but do not prove safety, compliance, battery health, or route eligibility.", storeUrl: "https://www.cnbuycha.com/electronics/" },
] as const;

const base = "https://www.cnbuycha.com";

export const products: Product[] = [
  {
    id: "3402",
    name: "Mixed Runner Sneaker Find",
    category: "shoes",
    categoryLabel: "Shoes",
    image: `${base}/uploads/allimg/20260806/1-260P6164I0217.webp`,
    cny: 289,
    usd: "40.10",
    checked: "Aug 08",
    storeUrl: `${base}/AllProducts/3402.html`,
    summary: "A mixed runner-style footwear listing. Compare the listing photos and request measurements before choosing a size.",
  },
  {
    id: "3401",
    name: "Leather Loafer Find",
    category: "shoes",
    categoryLabel: "Shoes",
    image: `${base}/uploads/allimg/20260806/1-260P616454QM.webp`,
    cny: 303,
    usd: "42.10",
    checked: "Aug 08",
    storeUrl: `${base}/AllProducts/3401.html`,
    summary: "A leather loafer-style listing. Check the insole length, finish, and sole photos rather than relying on the labeled size alone.",
  },
  {
    id: "3387",
    name: "Trail Runner Find",
    category: "shoes",
    categoryLabel: "Shoes",
    image: `${base}/uploads/allimg/20260804/1-260P42200191O.jpg`,
    cny: 218,
    usd: "30.30",
    checked: "Aug 08",
    storeUrl: `${base}/AllProducts/3387.html`,
    summary: "A trail-inspired runner listing. Review outsole, upper material, and pair alignment in warehouse photos.",
  },
  {
    id: "3393",
    name: "Mertra-Style Hoodie",
    category: "hoodies-sweaters",
    categoryLabel: "Hoodies",
    image: `${base}/uploads/allimg/20260806/1-260P616301A57.webp`,
    cny: 212,
    usd: "29.40",
    checked: "Aug 08",
    storeUrl: `${base}/AllProducts/3393.html`,
    summary: "A graphic hoodie listing. Compare chest width and garment length with a hoodie you already own.",
  },
  {
    id: "3380",
    name: "Heavyweight Sweatshirt",
    category: "hoodies-sweaters",
    categoryLabel: "Hoodies",
    image: `${base}/uploads/allimg/20260729/1-260H9212445610.webp`,
    cny: 229,
    usd: "31.80",
    checked: "Aug 08",
    storeUrl: `${base}/AllProducts/3380.html`,
    summary: "A heavyweight sweatshirt listing. Ask for weight and measurements if thickness or fit matters to you.",
  },
  {
    id: "3400",
    name: "Classic Polo Shirt",
    category: "t-shirts",
    categoryLabel: "T-Shirts",
    image: `${base}/uploads/allimg/20260806/1-260P616440O18.webp`,
    cny: 210,
    usd: "29.20",
    checked: "Aug 08",
    storeUrl: `${base}/AllProducts/3400.html`,
    summary: "A classic polo listing. Check collar shape, embroidery placement, and the seller size chart before ordering.",
  },
  {
    id: "3392",
    name: "Resort Print Shirt",
    category: "t-shirts",
    categoryLabel: "T-Shirts",
    image: `${base}/uploads/allimg/20260804/1-260P4220QC04.webp`,
    cny: 110,
    usd: "15.30",
    checked: "Aug 08",
    storeUrl: `${base}/AllProducts/3392.html`,
    summary: "A lightweight resort shirt listing. Check fabric composition, print alignment, and actual garment measurements.",
  },
  {
    id: "3396",
    name: "Winter Down Jacket",
    category: "jackets",
    categoryLabel: "Jackets",
    image: `${base}/uploads/allimg/20260806/1-260P6163I3956.webp`,
    cny: 663,
    usd: "92.10",
    checked: "Aug 08",
    storeUrl: `${base}/AllProducts/3396.html`,
    summary: "A winter jacket listing. Ask about fill, total weight, and compressed parcel volume before planning shipping.",
  },
  {
    id: "3394",
    name: "Workwear Jacket",
    category: "jackets",
    categoryLabel: "Jackets",
    image: `${base}/uploads/allimg/20260806/1-260P616341J10.webp`,
    cny: 178,
    usd: "24.70",
    checked: "Aug 08",
    storeUrl: `${base}/AllProducts/3394.html`,
    summary: "A light workwear jacket listing. Check sleeve length, hardware, seams, and color under neutral lighting.",
  },
  {
    id: "3208",
    name: "Germany Football Jersey 2024",
    category: "jerseys",
    categoryLabel: "Jerseys",
    image: `${base}/uploads/allimg/20260430/1-260430212R11E.jpg`,
    cny: 99,
    usd: "13.80",
    checked: "Aug 08",
    storeUrl: `${base}/AllProducts/3208.html`,
    summary: "A 2024 Germany football jersey listing. Verify player print, patch options, and shirt measurements before checkout.",
  },
  {
    id: "3207",
    name: "Premier League Player Jersey",
    category: "jerseys",
    categoryLabel: "Jerseys",
    image: `${base}/uploads/allimg/20260430/1-2604302126395I.jpg`,
    cny: 88,
    usd: "12.20",
    checked: "Aug 08",
    storeUrl: `${base}/AllProducts/3207.html`,
    summary: "A player-version football jersey listing. Expect a closer cut and compare measurements before selecting a size.",
  },
  {
    id: "3389",
    name: "Sport Crossbody Bag",
    category: "accessories",
    categoryLabel: "Accessories",
    image: `${base}/uploads/allimg/20260804/1-260P4220335407.webp`,
    cny: 179,
    usd: "24.90",
    checked: "Aug 08",
    storeUrl: `${base}/AllProducts/3389.html`,
    summary: "A compact sport bag listing. Review dimensions, zip hardware, strap stitching, and interior photos.",
  },
  {
    id: "3388",
    name: "Runner Tatic Sneaker Listing",
    category: "shoes",
    categoryLabel: "Shoes",
    image: `${base}/uploads/allimg/20260804/1-260P4220203120.webp`,
    cny: 590,
    usd: "81.90",
    checked: "Aug 10",
    storeUrl: `${base}/AllProducts/3388.html`,
    summary: "A runner-style sneaker listing. Confirm the exact color and size option, compare centimeter guidance, and inspect pair alignment before parcel approval.",
  },
  {
    id: "3386",
    name: "Skater Low-Top Sneaker",
    category: "shoes",
    categoryLabel: "Shoes",
    image: `${base}/uploads/allimg/20260804/1-260P4215T51Z.jpg`,
    cny: 268,
    usd: "37.20",
    checked: "Aug 10",
    storeUrl: `${base}/AllProducts/3386.html`,
    summary: "A low-top skater shoe listing. Check the selected variation, usable foot or insole measurements, sole shape, and box-related parcel volume.",
  },
  {
    id: "3375",
    name: "Sports Knit Sweater",
    category: "hoodies-sweaters",
    categoryLabel: "Hoodies",
    image: `${base}/uploads/allimg/20260729/1-260H9211624601.jpg`,
    cny: 264,
    usd: "36.70",
    checked: "Aug 10",
    storeUrl: `${base}/AllProducts/3375.html`,
    summary: "A sports knit sweater listing. Compare flat garment measurements, color options, visible knit condition, and packed volume rather than relying on the size label.",
  },
  {
    id: "3374",
    name: "Technical Pullover Sweatshirt",
    category: "hoodies-sweaters",
    categoryLabel: "Hoodies",
    image: `${base}/uploads/allimg/20260729/1-260H9211449611.webp`,
    cny: 399,
    usd: "55.40",
    checked: "Aug 10",
    storeUrl: `${base}/AllProducts/3374.html`,
    summary: "A technical pullover listing. Confirm the selected design and measurements, then inspect seams, hardware, marks, and the volume of the folded garment.",
  },
  {
    id: "3353",
    name: "Long-Sleeve Polo Shirt",
    category: "t-shirts",
    categoryLabel: "T-Shirts",
    image: `${base}/uploads/allimg/20260713/1-260G31645454b.webp`,
    cny: 168,
    usd: "23.30",
    checked: "Aug 10",
    storeUrl: `${base}/AllProducts/3353.html`,
    summary: "A long-sleeve polo listing. Compare chest, shoulder, sleeve, and length measurements and inspect collar shape, embroidery placement, and visible marks.",
  },
  {
    id: "3347",
    name: "Graphic Short-Sleeve Tee",
    category: "t-shirts",
    categoryLabel: "T-Shirts",
    image: `${base}/uploads/allimg/20260706/1-260F6161541109.webp`,
    cny: 150,
    usd: "20.80",
    checked: "Aug 10",
    storeUrl: `${base}/AllProducts/3347.html`,
    summary: "A graphic tee listing. Save the chosen color and print option, compare the seller's measurement chart, and inspect neckline and print alignment.",
  },
  {
    id: "3362",
    name: "Monogram Tracksuit Jacket",
    category: "jackets",
    categoryLabel: "Jackets",
    image: `${base}/uploads/allimg/20260713/1-260G31F24R06.webp`,
    cny: 433,
    usd: "60.10",
    checked: "Aug 10",
    storeUrl: `${base}/AllProducts/3362.html`,
    summary: "A tracksuit-style jacket listing. Verify what pieces the option includes, compare garment measurements, and inspect zips, seams, color, and overall shape.",
  },
  {
    id: "3356",
    name: "Long Tailored Coat",
    category: "jackets",
    categoryLabel: "Jackets",
    image: `${base}/uploads/allimg/20260713/1-260G31A22I07.webp`,
    cny: 247,
    usd: "34.30",
    checked: "Aug 10",
    storeUrl: `${base}/AllProducts/3356.html`,
    summary: "A long coat listing. Check shoulder, sleeve, chest, and length measurements, visible tailoring, closures, and the likely parcel volume of the folded coat.",
  },
  {
    id: "3206",
    name: "Manchester City 2024 Jersey",
    category: "jerseys",
    categoryLabel: "Jerseys",
    image: `${base}/uploads/allimg/20260430/1-260430212410353.jpg`,
    cny: 99,
    usd: "13.80",
    checked: "Aug 10",
    storeUrl: `${base}/AllProducts/3206.html`,
    summary: "A multi-option 2024 Manchester City jersey listing. Confirm fan or player cut, size chart, name, number, sleeves, and optional patches before paying.",
  },
  {
    id: "3204",
    name: "Premier League 2024 Jersey",
    category: "jerseys",
    categoryLabel: "Jerseys",
    image: `${base}/uploads/allimg/20260428/1-26042Q51456234.jpg`,
    cny: 89,
    usd: "12.40",
    checked: "Aug 10",
    storeUrl: `${base}/AllProducts/3204.html`,
    summary: "A multi-team 2024 jersey listing. Select the exact team and print combination, compare the relevant measurement chart, and inspect both front and back.",
  },
  {
    id: "3365",
    name: "Royal Oak-Style Watch Selection",
    category: "accessories",
    categoryLabel: "Accessories",
    image: `${base}/uploads/allimg/20260722/1-260H220595b51.webp`,
    cny: 328,
    usd: "45.60",
    checked: "Aug 10",
    storeUrl: `${base}/AllProducts/3365.html`,
    summary: "A multi-style watch listing. Confirm the exact model, dimensions, movement and battery description, included parts, visible finish, and current route eligibility.",
  },
  {
    id: "3364",
    name: "Mixed Square-Dial Watch Selection",
    category: "accessories",
    categoryLabel: "Accessories",
    image: `${base}/uploads/allimg/20260722/1-260H2205K3353.webp`,
    cny: 88,
    usd: "12.20",
    checked: "Aug 10",
    storeUrl: `${base}/AllProducts/3364.html`,
    summary: "A mixed square-dial watch listing. Match the exact option and included pieces and remember that photographs cannot prove movement accuracy, battery health, or durability.",
  },
  {
    id: "3373",
    name: "Designer-Style Tie Selection",
    category: "headwear",
    categoryLabel: "Headwear",
    image: `${base}/uploads/allimg/20260729/1-260H9211100531.jpg`,
    cny: 203,
    usd: "28.20",
    checked: "Aug 10",
    storeUrl: `${base}/AllProducts/3373.html`,
    summary: "A multi-style tie listing shown in the store's headwear and accessories department. Confirm the exact pattern, dimensions, material description, and included packaging.",
  },
  {
    id: "3372",
    name: "Snow Ski Goggles",
    category: "headwear",
    categoryLabel: "Headwear",
    image: `${base}/uploads/allimg/20260722/1-260H2211J0L9.webp`,
    cny: 340,
    usd: "47.20",
    checked: "Aug 10",
    storeUrl: `${base}/AllProducts/3372.html`,
    summary: "A snow-goggle listing. Confirm lens and frame option, dimensions, included case or accessories, visible scratches, and protective parcel packing.",
  },
  {
    id: "3371",
    name: "Structured Logo Cap",
    category: "headwear",
    categoryLabel: "Headwear",
    image: `${base}/uploads/allimg/20260722/1-260H221155C13.webp`,
    cny: 75,
    usd: "10.40",
    checked: "Aug 10",
    storeUrl: `${base}/AllProducts/3371.html`,
    summary: "A structured cap listing. Check circumference or adjustability, color, embroidery placement, panel symmetry, brim shape, and crush-resistant packing.",
  },
  {
    id: "3357",
    name: "Galaxy Watch 8 Listing",
    category: "electronics",
    categoryLabel: "Electronics",
    image: `${base}/uploads/allimg/20260713/1-260G31A40J10.webp`,
    cny: 218,
    usd: "30.30",
    checked: "Aug 10",
    storeUrl: `${base}/AllProducts/3357.html`,
    summary: "A smartwatch listing. Confirm the exact model, size, charger, battery description, compatibility, testing scope, and international route eligibility before purchase.",
  },
  {
    id: "3235",
    name: "Luxury Smartwatch Listing",
    category: "electronics",
    categoryLabel: "Electronics",
    image: `${base}/uploads/allimg/20260505/1-260505163Z2360.jpg`,
    cny: 1120,
    usd: "155.60",
    checked: "Aug 10",
    storeUrl: `${base}/AllProducts/3235.html`,
    summary: "A premium-positioned smartwatch listing. Verify specifications, compatible devices, charger, battery details, available testing, route restrictions, and insurance terms.",
  },
  {
    id: "3184",
    name: "Electronic Watch S8 Listing",
    category: "electronics",
    categoryLabel: "Electronics",
    image: `${base}/uploads/allimg/20260425/1-26042515030X51.jpg`,
    cny: 488,
    usd: "67.80",
    checked: "Aug 10",
    storeUrl: `${base}/AllProducts/3184.html`,
    summary: "An electronic watch listing. Confirm the precise option, charging accessories, battery and compatibility claims, visible condition, and eligible shipping routes.",
  },
];
