import type { SeoArticleCopy } from "./seoArticles";
import type { PriorityArticleLocale } from "./priorityShippingArticles";

type SeoArticle = SeoArticleCopy["article"];

export const additionalPrioritySeoArticleSlugs = [
  "joyagoo-shipping-calculator-cost-estimate-guide",
  "why-is-joyagoo-shipping-so-expensive",
  "joyagoo-shipping-cost-per-kg-explained",
  "joyagoo-shipping-coupon-promo-discount-guide",
  "joyagoo-shipping-to-canada-cost-planner",
] as const;

export type AdditionalPrioritySeoArticleSlug =
  (typeof additionalPrioritySeoArticleSlugs)[number];

const article = (
  eyebrow: string,
  title: string,
  description: string,
  facts: SeoArticle["facts"],
  sections: Array<[string, string]>,
): SeoArticle => ({
  eyebrow,
  title,
  description,
  facts,
  sections: sections.map(([heading, paragraph]) => ({
    heading,
    paragraphs: [paragraph],
  })),
});

const en: Record<AdditionalPrioritySeoArticleSlug, SeoArticle> = {
  "joyagoo-shipping-calculator-cost-estimate-guide": article(
    "JOYAGOO SHIPPING CALCULATOR",
    "Joyagoo Shipping Calculator: Build a Cost Estimate That Survives Packing",
    "Use live route quotes, actual and volumetric weight, rounding steps and complete cost layers to estimate a Joyagoo parcel without presenting a fictional universal calculator rate.",
    [
      { value: "Live inputs", label: "Destination, contents and current routes" },
      { value: "2 weights", label: "Actual and volumetric scenarios" },
      { value: "Final check", label: "Refresh the quote before payment" },
    ],
    [
      ["What a useful shipping calculator must do", "A useful Joyagoo shipping calculator is a decision worksheet, not a box that multiplies kilograms by an old number. Joyagoo’s published fee explanation says international freight depends on destination, package weight, package volume and the selected shipping method. Eligibility can also depend on the contents. That means the current parcel screen, after you select the stored products and delivery country, is the price source. Begin by saving the date, destination, product mix and every line that actually appears. Then record the measurement stage: seller listing, warehouse record, rehearsal result or final carrier measurement. A social-media quote or another buyer’s parcel can be a useful comparison, but it is not an input for your order unless the country, contents, dimensions, weight rule and date match. Do not make a single worldwide cost-per-kilogram assumption. The calculator should instead answer three practical questions: which lines are eligible, which weight each line will bill and how the result changes if packing dimensions or weight cross the next charging step. This approach produces a range you can audit and update, rather than a precise-looking total that fails as soon as the warehouse packs the box."],
      ["Collect the inputs before calculating", "Create one row for the item payment and Chinese domestic delivery, one for chosen warehouse services, one for the international parcel and one for possible destination-side charges. For the shipping row, collect the live route name, quoted currency, minimum or first-weight charge if displayed, continuation step, rounding rule, actual weight, outside length, width and height, volumetric divisor, insurance choice and quote timestamp. Mark any missing value as “not displayed”; never turn it into zero. Product estimates deserve the same discipline. A seller’s listed weight may exclude packaging, while the warehouse record can still change after consolidation. A dimension taken from a product page is not the outer parcel dimension. Use it only for an early high-and-low scenario. If several products will be combined, allow space for protective material and the outer carton. Also note route restrictions before comparing prices. A cheap line that does not accept a product category is not a valid option, and changing the declaration to force eligibility is not a saving method. Clean inputs prevent most calculator errors and make later quote changes explainable."],
      ["Calculate actual and volumetric scenarios", "For every eligible line, copy its current dimensional rule. Joyagoo guidance explains volumetric weight as length multiplied by width multiplied by height in centimetres, divided by a logistics-provider divisor; it also warns that providers may use different divisors. Calculate that value with the divisor shown for the route, then compare it with actual weight. Where the route bills the greater figure, use the greater figure as the starting billable weight. Next apply the displayed rounding or weight increment rather than rounding in the direction you prefer. Run at least three scenarios: a compact case, a likely packed case and a stress case with a modest increase in one dimension and total weight. A rigid shoe box, puffer jacket, protective corner or extra carton can increase space faster than mass, so the stress case matters even when the products feel light. Keep each line’s formula separate. Reusing one divisor or threshold across all lines creates a false ranking. When the interface gives only a total quote rather than every rate component, record the total without reverse-engineering an official tariff that was never shown."],
      ["Turn route quotes into a comparable table", "Compare routes only after giving every row identical parcel inputs. Useful columns are eligibility, measurement stage, actual weight, dimensions, volumetric rule, calculated billable weight, quote, tracking description, estimated delivery range, insurance availability, compensation terms and the party responsible for the next handoff. First remove ineligible lines. Then compare cost under the likely scenario and again under the stress scenario. A line that is cheapest only before one small rounding step should be labelled price-sensitive. A slightly higher quote may be the better budget choice if its rule is more stable for the parcel’s size. Delivery ranges should remain ranges, not promises, because seller dispatch, warehouse processing, export handling, flights, customs and local delivery are separate clocks. Keep cost and speed as different scores instead of declaring a universal “best” route. The result is a parcel-specific ranking at a recorded time. It should not be converted into a permanent recommendation for every destination or product mix."],
      ["Model packing and consolidation before submitting", "Calculate three packing decisions when they are realistic: keep original packaging, remove only redundant material, and split products with different protection or route needs. For each decision, update dimensions, protective-service cost, repeated minimum charges, billable weight and risk notes. Removing a shoe box can reduce volume, but it can also remove protection or affect the usefulness of the original packaging. Consolidating items can spread a first-weight charge and remove duplicated outer cartons, yet adding one bulky product can push the whole parcel into dimensional billing or remove route eligibility. Rehearsal or pre-packing can replace rough dimensions with better evidence when the available service is worthwhile, but it is not a guarantee that a later carrier measurement will be identical. Preserve both the preliminary and rehearsal results. The calculator should show why the estimate moved rather than silently overwrite the earlier number. If buying an unplanned item is required to make the shipping ratio look better, count that purchase and domestic delivery as added cost, not as free optimization."],
      ["Add uncertainty without inventing taxes", "A parcel budget needs a buffer, but the buffer must not masquerade as a quoted fee. Separate known values, scenario values and unresolved values. Known values come from the current order or parcel screen. Scenario values come from explicit changes in weight, dimensions or packing. Unresolved values include a later carrier adjustment, exchange-rate movement, optional insurance and possible destination tax, duty or handling. Destination rules can change and depend on the goods and declared value, so check current government guidance for the receiving country and describe goods and value accurately. Do not copy an old tax threshold, assume a route is tax-free or present a community label as a legal guarantee. If the site does not show a destination charge, record it as unknown and hold a transparent contingency amount outside the shipping quote. This keeps the calculator useful for cash planning without turning an uncertain customs outcome into fake precision. Save invoices and the declaration record with the quote so that the final landed-cost review has evidence."],
      ["Freeze the estimate and learn from the final parcel", "Immediately before payment, refresh the parcel screen and verify the destination, contents, packing request, current route, billable-weight rule, currency, price, delivery range, tracking level and insurance selection. Save the screen with a timestamp. After dispatch, add the final measured weight, final charge, parcel number and tracking events without deleting the estimate. When delivery finishes, compare estimate and outcome by cause: product-stage changes, domestic delivery, optional services, packed dimensions, weight rounding, route change, currency conversion or destination handling. Do not reduce every difference to “shipping was higher.” A cause-based log improves the next estimate because it shows which assumptions were weak. Reuse measured product and packing data only as a starting point; request fresh live routes for the next parcel. In this way the shipping calculator becomes more accurate for your own recurring product mix while remaining honest about what it cannot predict. The final rule is simple: calculate scenarios early, but let the current eligible quote and final measured parcel decide the payment."],
    ],
  ),
  "why-is-joyagoo-shipping-so-expensive": article(
    "WHY JOYAGOO SHIPPING FEELS EXPENSIVE",
    "Why Joyagoo Shipping Can Look Expensive: Seven Cost Drivers to Check",
    "Diagnose high Joyagoo shipping quotes by separating minimum charges, billable weight, parcel dimensions, route eligibility, packaging decisions and destination uncertainty.",
    [
      { value: "7 drivers", label: "Find the part raising this parcel" },
      { value: "No flat rate", label: "Live routes decide the current quote" },
      { value: "Fix the cause", label: "Optimize without weakening protection" },
    ],
    [
      ["High shipping is usually a stack, not one fee", "When a Joyagoo parcel looks expensive, the useful response is not to blame a single mysterious percentage. International parcel cost is assembled from several conditions: the destination, selected logistics line, billable weight, outer dimensions, product eligibility, packaging and optional protection. The product order and Chinese domestic delivery also happen before international shipping, so a buyer who compares only the catalogue price with the final parcel payment can mistake several stages for one charge. Start by copying the order-stage amounts and parcel-stage amounts into separate rows. Then save the exact lines offered for the selected destination and contents. An old screenshot or another person’s cost can make your total look abnormal even when their parcel used a different country, weight step, dimensional rule or product category. The word “expensive” becomes actionable only after you define the comparison: cost per item, cost per actual kilogram, cost per billable kilogram or total delivered budget. Each measure answers a different question. Diagnose the layers first; otherwise an attempted saving such as adding more products, removing all packaging or choosing an ineligible route can increase spending or risk."],
      ["Driver one: minimums, first weight and rounding", "Small parcels often produce a high cost per kilogram because a route may have a minimum charge, a first-weight component or a billing increment. The first part of the price can cover processing and network costs that do not shrink in direct proportion to weight. Rounding can then move a parcel just above a threshold into the next chargeable step. Record the displayed minimum, first weight, continuation increment and rounding rule for every live line. Test the parcel immediately below and above the next step. This reveals whether the quote is dominated by the route’s starting cost or by additional weight. Consolidation can sometimes spread the starting charge across more planned items, but it is not automatically cheaper. Waiting may create storage or return-deadline pressure, and buying filler solely to improve a ratio is still additional spending. Compare “ship now,” “wait for already planned goods” and “consolidate selected compatible items” as complete budgets. A high per-kilogram figure on a light parcel is not evidence of a hidden rate; it can be the predictable effect of the route’s charging structure."],
      ["Driver two: volumetric weight", "A box consumes transport capacity through both mass and space. Joyagoo’s published explanation therefore distinguishes actual weight from volumetric weight and notes that some logistics providers may charge the greater figure. A parcel full of light but bulky shoes, jackets, hats or protective packaging can be billed as if it were heavier than the scale reading. Copy the route’s current divisor and calculate length multiplied by width multiplied by height in centimetres, divided by that divisor. Do not assume every line uses the same number. Compare the result with actual weight and apply the line’s rounding rule. If volumetric weight is driving the quote, identify which outside dimension or rigid item creates the volume. Removing only empty or redundant material may help, but crushing products or discarding useful protection is not a responsible optimization. Rehearsal packing can improve the estimate when available, although final carrier measurement can still differ. Run compact, likely and stress cases to see whether a small dimensional change reverses the route ranking."],
      ["Driver three: product and route eligibility", "The cheapest headline line may not be available for the items in your warehouse. Batteries, liquids, magnets, branded goods, fragile objects and other categories can have different acceptance conditions, and a mixed parcel can inherit the restrictions of one product. Availability also changes by destination and current provider rules. Review the live eligibility information before sorting by price. If one item removes several lower-cost lines, calculate a permitted split parcel and compare it with the combined parcel, including duplicated minimum charges and packaging. Never change or hide the product description to force a route to appear. That creates declaration, delay and remedy risk rather than a legitimate saving. Record the reason a line is unavailable instead of treating the absence as random. The comparison then distinguishes a generally high market price from a cost caused by this product mix. It may be more sensible to ship a restricted or fragile item separately, choose extra protection or not buy it at all, but that decision must include the full two-parcel cost."],
      ["Driver four: packaging and optional services", "Packaging is both a cost input and a risk control. Extra cartons, corner protection, cushioning, waterproofing or reinforcement may add service cost, weight or volume, but they can reduce the chance that a fragile parcel arrives damaged. Original shoe boxes and seller packaging may create unused space, while aggressive removal can reduce protection, presentation or evidence. List every chosen service and the problem it is meant to solve. Compare the expected shipping change with the item value, fragility and available remedy. A service is not automatically wasteful because it raises the quote, and it is not automatically valuable because it sounds protective. Use warehouse photos and product characteristics to make the decision. If dimensions are the main driver, model targeted removal of redundant material before deleting all original packaging. If actual weight dominates, a small dimensional reduction may do nothing. The lowest checkout number is not a saving when it creates an unacceptable damage risk or forces replacement purchases."],
      ["Drivers five and six: comparison method and timing", "Quotes can look high when the comparison mixes dates, currencies, destinations or measurement stages. A product-page estimator may use a rough item weight; the warehouse record includes received goods; a rehearsal result reflects a proposed carton; the final carrier can measure again. Label each value with its stage and timestamp. Convert currencies using the rate and any disclosed payment cost that actually applies to your transaction, rather than a search-engine midpoint treated as a guaranteed checkout rate. Compare live routes with identical parcel inputs and keep delivery range, tracking, insurance and compensation terms beside price. A faster or more protective route is not directly comparable with an economy line if the service differs. Route availability and promotions can change, so a quote saved weeks ago cannot prove today’s price. Refresh before payment and preserve both versions. The difference may show a measurement change, route update or currency effect; without timestamps it merely looks like an unexplained increase."],
      ["Driver seven: destination uncertainty and the safe response", "International freight is not always the complete delivered cost. The receiving country may apply tax, duty, brokerage or handling according to current law, goods and declared value. Do not assume those amounts are included unless the current route terms explicitly say so, and do not treat informal “tax-free” language as a legal guarantee. Check current government guidance, describe the goods and value accurately and keep invoices. Place unresolved destination cost in a separate buffer rather than adding a fictional fixed percentage to the Joyagoo quote. Once all seven drivers are visible, optimize the dominant one: wait only for already planned compatible items when a minimum dominates; reduce redundant volume when dimensional weight dominates; split only when eligibility or protection justifies repeated base charges; and compare routes again with the same inputs. Save the final measurement and payment, then review the variance by cause. Shipping may still be expensive, but the decision will be based on the parcel’s real constraints instead of a misleading universal price claim."],
    ],
  ),
  "joyagoo-shipping-cost-per-kg-explained": article(
    "JOYAGOO COST PER KG",
    "Joyagoo Shipping Cost per KG: Read Rates, Steps and Billable Weight Correctly",
    "Understand why Joyagoo has no single worldwide price per kilogram and calculate a parcel-specific effective rate from live quotes, weight steps and dimensions.",
    [
      { value: "No universal KG", label: "Destination and route change the result" },
      { value: "Billable weight", label: "Not always the scale weight" },
      { value: "Effective rate", label: "Use it to compare one parcel fairly" },
    ],
    [
      ["Why one Joyagoo price per kilogram does not exist", "A request for the Joyagoo shipping cost per kilogram sounds simple, but an honest answer begins with the parcel. Joyagoo’s published fee explanation says international freight depends on destination, package weight, package volume and shipping method. The available method can also depend on the contents. Many lines do not behave like a pure weight multiplied by one constant. They may include a minimum or first-weight charge, a continuation increment, rounding and dimensional billing. For that reason, a quoted effective rate for a small parcel can differ sharply from a heavier parcel even on the same line. A worldwide average hides the destination, currency, date, product restrictions and service level, so it is a poor budget input. Use the current parcel screen after selecting the stored goods and destination. Record the route, timestamp, actual weight, outer dimensions, billing rule and total quote. Then calculate a parcel-specific effective rate for comparison. This article uses “per kilogram” as an analysis tool, not as a promise that the platform sells every kilogram at that number."],
      ["Separate listed rate from effective rate", "If a line displays a first-weight amount and a continuation charge, preserve those components exactly as shown. Do not average them before applying the correct steps. First determine the billable weight, apply the minimum, increment and rounding rule, and record the resulting live total. The effective shipping rate is then the international parcel quote divided by billable kilograms. A second metric, quote divided by actual kilograms, can reveal the effect of dimensional billing, but it should be labelled clearly. Neither metric is the platform’s permanent official rate. Add the item payment, Chinese domestic delivery, warehouse services and possible destination charges only when calculating landed cost; do not bury them inside the international per-kilogram number. Otherwise two buyers will appear to have different shipping rates simply because one selected reinforcement or paid seller delivery. Mark currency and quote time beside the result. If the interface displays only a total and not a component rate, use the total as evidence and avoid reverse-engineering a tariff that the provider did not publish."],
      ["Use billable weight, not a convenient weight", "The scale reading is only one candidate for the billable figure. Joyagoo guidance explains volumetric weight as outer length multiplied by width multiplied by height in centimetres, divided by a provider divisor, and notes that different logistics providers can use different divisors. Copy the rule from each current line. Calculate volumetric weight, compare it with actual weight where required and then apply the route’s rounding step. A light, bulky carton can therefore have a low cost per actual kilogram but a normal cost per billable kilogram. This distinction explains many apparently high quotes. Use packed outer measurements rather than adding individual product dimensions, because products can nest, compress or require cushioning. Before packing, calculate a reasonable range. After rehearsal packing, replace the rough scenario with the measured proposal but keep the older version for comparison. A final provider measurement can still differ. Never choose whichever weight makes the rate look cheapest; label actual, volumetric and billable values separately."],
      ["Compare weight steps instead of a single point", "A per-kilogram comparison is most useful when it shows the next threshold. For each eligible route, calculate the total and effective rate at the current billable weight, immediately below the next increment and immediately above it. Also test a modest increase in outer dimensions. A route that looks cheapest at exactly 2.0 kilograms may lose that position at 2.05 if it rounds to a larger step, while another line may change more gradually. This sensitivity test is more useful than ranking a single screenshot. Keep the parcel inputs identical across rows and remove ineligible routes before comparing. Note minimum charge, first-weight block, continuation block, dimensional divisor, rounding, currency, tracking and delivery range. Treat missing details as not displayed, not as zero. The goal is to find a cost structure that remains acceptable after realistic packing changes, not the lowest number under an optimistic weight. A stable second-lowest quote can be easier to budget than a fragile headline minimum."],
      ["Understand why consolidation changes the ratio", "Consolidation can lower the effective cost per kilogram by spreading a starting charge and removing duplicated outer packaging. It can also raise billable weight if one bulky product increases the combined dimensions or if the mixed contents lose access to a preferred route. Compare complete scenarios: ship the current parcel; wait for items you already planned to buy; combine only compatible products; or split a restricted or fragile item. Include extra Chinese domestic delivery, storage or deadline risk, packaging choices and repeated minimum charges. Do not buy filler just to reduce the displayed per-kilogram ratio. Spending more money to create a prettier denominator is not a saving. Also avoid treating the lowest effective rate as the best overall decision. A large combined parcel may concentrate damage or delay exposure and may need stronger protection. Record why a consolidation choice is economical for this product mix instead of creating a universal rule that more kilograms always mean better value."],
      ["Keep speed, tracking and risk out of false price claims", "Two lines with different tracking, handling, delivery ranges, insurance or compensation conditions are not identical products. The lower per-kilogram figure shows price density, not total value. Score price, eligibility, timing, tracking, protection and remedy separately. Delivery estimates are ranges because seller dispatch, warehouse work, export, flight capacity, customs and local delivery do not share one guaranteed clock. Do not divide cost by a promised number of days or label one line universally fastest. Check the current route description and preserve the quote date. For destination charges, consult current government guidance and keep unresolved tax, duty or handling in a separate buffer. Never add a guessed customs percentage to the international rate and present it as Joyagoo’s price per kilogram. Accurate labels protect both the calculation and the reader: international quote per billable kilogram, quote per actual kilogram, and estimated landed cost per item are three different measures."],
      ["Build a reusable rate log without freezing old prices", "Before paying, refresh the route list and save the final quote, measurement stage, packing choice and timestamp. After dispatch, add final billable weight, final parcel charge, currency, parcel number and tracking outcome. Calculate the effective rate again and explain any variance through weight, volume, rounding, route, service or currency changes. This creates a useful personal benchmark for similar future parcels, especially when product type and packing are repeated. It does not create an official permanent rate card. For the next shipment, reuse the old measurements as a starting range, then request live eligible routes and repeat the threshold test. A responsible answer to “how much per kilogram?” is therefore a method plus a current parcel result: choose the destination and contents, identify billable weight, apply the live line structure, divide the current international quote by that billable weight and state the date. Anything more universal looks simpler, but it is less accurate."],
    ],
  ),
  "joyagoo-shipping-coupon-promo-discount-guide": article(
    "JOYAGOO SHIPPING COUPONS",
    "Joyagoo Shipping Coupon Guide: Check Promo and Discount Rules Before Paying",
    "Evaluate Joyagoo coupon, promo-code and discount-code claims safely, verify the eligible fee and compare the final payable parcel total without publishing expired codes.",
    [
      { value: "Verify live", label: "Account and checkout decide eligibility" },
      { value: "Read scope", label: "Shipping discounts are not item discounts" },
      { value: "Compare total", label: "A coupon does not make a route best" },
    ],
    [
      ["Why this guide does not publish a magic code", "People searching for a Joyagoo coupon, promo code or discount code usually want a lower parcel payment, but a copied code is not reliable evidence. Campaigns can have account, country, route, minimum-spend, currency, product, redemption or expiry conditions. A code visible in an old post may be exhausted, restricted to new users or unrelated to international shipping. Publishing it as “working” without testing the user’s checkout creates a false promise. The safe source is the current account, campaign page and parcel checkout. Record the offer name, displayed benefit, eligible charge, minimum, maximum benefit if shown, start and end time, route or destination limits, stacking rule and the account where it appears. Do not enter credentials into an unknown coupon site or install software to reveal a code. This guide therefore focuses on verification and net cost. A real discount is the difference between two otherwise identical payable scenarios, captured at the same stage and time—not a large percentage printed beside a dead code."],
      ["Distinguish item, service and shipping discounts", "A shopping-agent transaction has several cost layers. The seller item price and Chinese domestic delivery occur at the purchase stage; optional warehouse services may be added later; international freight is charged when the parcel is submitted; destination tax, duty or handling may be separate. A promotion may apply to only one layer. Read the exact eligible fee rather than subtracting a headline percentage from the whole delivered budget. If an offer is described as an international shipping coupon, do not claim that it reduces the product price, seller delivery, insurance, warehouse services or customs unless the live terms explicitly include them. Likewise, a seller promotion does not automatically reduce international freight. In your worksheet, keep original amount, eligible base, discount shown and final payable amount in separate columns. This prevents a small capped saving from looking like a discount on the entire order. It also makes different offers comparable when one has a percentage cap and another has a fixed reduction or route restriction."],
      ["Verify the promotion in the account and checkout", "Open the current coupon or promotion area while signed into the account that will pay, and note whether the offer is claimed automatically or requires a code. Select the real destination, parcel contents, packing and eligible route before testing it. A coupon that appears in the account can still fail if the parcel misses a minimum, uses an excluded line, sits outside the campaign time zone or conflicts with another benefit. Apply the offer and confirm that the payable amount changes on the final review screen. Save the before-and-after totals, currency, route and timestamp. If the screen rejects the code, copy the reason exactly and do not keep retrying variations from unofficial sources. Do not describe an offer as active for everyone simply because it worked in one account. Eligibility is account- and parcel-specific until the official terms prove otherwise. Remove the code from public notes when it expires instead of keeping “working code” language for clicks."],
      ["Read stacking, caps, minimums and refund treatment", "The displayed percentage is only one part of value. Check whether the offer has a maximum reduction, whether the minimum is measured before or after other discounts, and whether several coupons can be combined. Confirm which currency is used for the threshold and whether cancellation, route change, refund or parcel adjustment returns the coupon. If the terms are silent, label the outcome unknown and avoid promising restoration. A large headline discount with a low cap may save less than a smaller fixed benefit. A minimum can also tempt buyers to add goods or select services they did not plan to use. Calculate the payable total with the original parcel first, then calculate any changed scenario including the extra product, Chinese domestic delivery, weight, volume and possible route impact. Spending more to unlock a coupon is sensible only if the complete payable and risk profile improves. The coupon should modify an existing plan, not dictate unnecessary purchases."],
      ["Compare routes after the coupon, not before", "A promotion tied to one line can change route ranking, but the discounted route still has its own eligibility, dimensional rule, delivery range, tracking and remedy terms. Give every route the same parcel inputs, calculate billable weight, apply its current quote and then apply only the offer it actually accepts. Compare final payable freight rather than subtracting the largest advertised discount from every row. Run a packing stress case because a small weight or dimension change can cross a threshold, break the minimum or alter route availability. Keep timing and protection as separate scores. A discounted route is not automatically the fastest, safest or best for restricted contents. If the discount disappears when the parcel is adjusted, update the table; do not preserve the earlier promotional total as the expected price. The winning result is specific to the parcel, account and time. It is not proof that one Joyagoo line is always cheapest."],
      ["Avoid fake-code pages and inflated savings claims", "Treat a page that demands a password, payment, browser extension or unrelated download to reveal a coupon as unsafe. Never share account credentials or one-time verification codes. Be cautious with countdown timers, copied campaign images, unverifiable “exclusive” claims and coupon lists that omit the eligible fee, cap or expiry. A referral benefit should be labelled as such instead of disguised as a universal shipping code, and any commercial relationship should be disclosed. For your own records, preserve the official terms and checkout evidence but redact personal identifiers before sharing a screenshot. Calculate savings against the real payable amount immediately before application, not against an inflated reference price or a different route. If no valid offer appears, say that plainly. A transparent “no verified current code for this parcel” is more useful than an invented promotion that wastes time or changes the order around a benefit that cannot be redeemed."],
      ["Use coupons as the last step of a sound cost plan", "First choose appropriate products, verify warehouse records, decide protection and compare eligible lines using actual and volumetric weight. Then apply a verified coupon to the best suitable scenarios. Keep the item payment, domestic delivery, services, international freight and possible destination costs separate. Immediately before payment, refresh the route, offer, currency and final total, then save the evidence. After dispatch, record whether a weight adjustment, route change, cancellation or refund affected the benefit. This creates a reliable campaign history for the account without assuming a past promotion will return. The durable saving methods remain accurate inputs, sensible consolidation, removal of truly redundant volume and selection of a route that fits the parcel. A coupon can lower the payable international charge, but it cannot make an ineligible route valid, erase customs law, guarantee delivery or turn unnecessary spending into savings. Verify it live and judge the final total."],
    ],
  ),
  "joyagoo-shipping-to-canada-cost-planner": article(
    "JOYAGOO CANADA SHIPPING COST",
    "Joyagoo Shipping to Canada: Plan Cost, Weight and Destination Risk",
    "Plan a Joyagoo parcel to Canada with current route eligibility, billable-weight scenarios, packing evidence and a separate destination-cost buffer.",
    [
      { value: "Canada address", label: "Use the real province and postal code" },
      { value: "Packed size", label: "Test scale and dimensional weight" },
      { value: "Current rules", label: "Verify government guidance before shipping" },
    ],
    [
      ["Start with the exact Canadian parcel", "There is no responsible universal answer for Joyagoo shipping to Canada. Joyagoo’s published fee explanation says international freight depends on destination, package weight, package volume and selected shipping method, while the contents can affect line eligibility. Use the actual province, postal code and stored products to load the current parcel options. Save every eligible route, the quote time and the measurement stage. A quote to another province, a broad North America average or a buyer’s old screenshot is not a substitute for the current checkout. Separate the seller’s dispatch time, Chinese domestic delivery and warehouse processing from the international route estimate. They are different stages and should not be added together as if they were one guaranteed delivery clock. Define the budget in Canadian dollars if that is how you plan cash, but also record the checkout currency and conversion evidence. Start with a range rather than a single promise: current quote under expected packing, a compact case and a stress case with slightly higher weight or dimensions."],
      ["Build four Canadian cost layers", "Write the product payment and seller delivery in the first layer, chosen warehouse services and packaging in the second, current international freight in the third, and possible Canadian tax, duty, brokerage or handling in the fourth. Copy live values exactly and mark unresolved values as unknown. Do not call the item price a delivered cost or treat a free purchasing-service claim as free international shipping. The product variation, Chinese domestic freight, optional photos, reinforcement, insurance and currency conversion can all change the total. Preserve the currency and timestamp for every amount. The fourth layer requires special care: do not copy an old threshold or community promise. Check current Canadian government guidance for the goods and declared value, read the selected route’s terms and keep a transparent buffer where the outcome is not known. This structure shows whether a surprise comes from the platform order, packing decision, international line or destination process, and it prevents a guessed customs amount from being presented as a Joyagoo charge."],
      ["Calculate billable weight for every live line", "Record scale weight and packed outer length, width and height. Joyagoo’s guidance explains that logistics providers may compare actual and volumetric weight, with volumetric weight calculated from the three dimensions divided by a provider-specific divisor. Copy the divisor and rounding rule attached to each Canadian route rather than assuming one formula. Calculate the expected billable weight, then repeat after adding a modest amount of packing weight and increasing the most uncertain outside dimension. Bulky shoes, winter jackets, hats and strong protective cartons can create dimensional weight even when the scale figure looks modest. Use warehouse measurements when available; seller dimensions are only an early scenario and may not represent the consolidated carton. Rehearsal packing can improve evidence when its cost is justified, but the final carrier may still measure again. Keep preliminary, rehearsal and final values separate so that a changed quote has an explainable cause."],
      ["Compare Canadian routes consistently", "Create one table with route name, eligibility, restrictions, measurement stage, actual weight, dimensions, volumetric rule, billable weight, quote, estimated delivery range, tracking, insurance, compensation terms and handoff responsibility. Use identical parcel inputs for every row and eliminate ineligible lines before ranking cost. A low headline rate that excludes one product is not a valid option. Next run the stress scenario and mark routes whose price jumps at the next weight step. Keep speed and cost as separate decisions. An estimate remains a range because export processing, flight capacity, customs and local delivery can vary. Do not label one route universally fastest or cheapest based on one parcel. The table supports a Canadian decision at a recorded time, and it should be refreshed immediately before payment."],
      ["Choose consolidation and packaging with evidence", "Compare keeping original packaging, removing only empty or redundant material and separating products with different restriction or protection needs. Update dimensions, weight, service fees, repeated minimum charges and risk for each scenario. Consolidation can spread a first-weight charge and reduce duplicated cartons, but one bulky or restricted item can increase the entire parcel’s billable weight or remove a preferred route. Removing a shoe box can reduce volume while also reducing protection or presentation. Base the decision on warehouse photos, product fragility and the selected route’s dimensional rule. If actual weight dominates, reducing one dimension may not change the price. If volume dominates, targeted removal can matter. Do not buy unplanned filler to improve cost per kilogram, and do not weaken protection to achieve a low estimate that may create replacement cost."],
      ["Handle Canadian declaration and destination costs conservatively", "Describe the goods and value accurately, retain invoices and follow the selected line’s current documentation requirements. Do not ask for false descriptions or values to lower a charge or force eligibility. Canadian import treatment can depend on current law, product type, origin, value and the party handling the parcel. Check the current Canada Border Services Agency and other relevant government guidance rather than relying on an old social post. Do not assume a route label guarantees that every tax, duty, brokerage or handling amount is included. If terms are unclear, treat the possible cost as unresolved and keep it outside the quoted international freight. This is not legal or tax advice; it is a budgeting control that stops uncertain destination charges from being hidden. A clean declaration record and saved invoice are also useful if the parcel is queried or if a later cost needs to be reconciled."],
      ["Refresh, pay and review the final outcome", "Before submitting the parcel, refresh the Canadian address, contents, packing request, route eligibility, billable-weight rule, currency, quote, delivery range, tracking and insurance. Save the screen and terms with the timestamp. After dispatch, append the final measurement, payment, parcel number and tracking events without overwriting the estimate. On delivery, compare the planned and actual totals by layer: product and domestic delivery, warehouse services, international quote, packing adjustment, currency conversion and destination handling. Record why the variance occurred. If a charge appears after arrival, save the official notice and identify whether it is tax, duty, brokerage or another handling amount instead of calling all of it shipping. If delivery takes longer than the displayed range, preserve the tracking sequence and separate warehouse, export, customs and local-carrier stages. That evidence improves the next Canada scenario, but it does not freeze a permanent rate because routes, measurements and rules can change. Reuse past packed dimensions only as an initial range, then request current eligible options for the next parcel. Compare similar contents and seasons where possible, but keep changed providers, restrictions and currency visible. A trustworthy Canada cost plan is specific, dated and auditable."],
    ],
  ),
};

type CompactTranslation = {
  eyebrow: string;
  title: string;
  description: string;
  facts: SeoArticle["facts"];
  sections: Array<[string, string]>;
};

const translated: Record<Exclude<PriorityArticleLocale, "en">, Record<AdditionalPrioritySeoArticleSlug, CompactTranslation>> = {
  zh: {
    "joyagoo-shipping-calculator-cost-estimate-guide": { eyebrow: "JOYAGOO运费计算", title: "Joyagoo运费计算器：做出经得住打包变化的成本估算", description: "用实时线路、实重与体积重、进位门槛和完整成本层估算包裹，不编造统一公斤价。", facts: [{value:"实时输入",label:"目的地、商品与当前线路"},{value:"两种重量",label:"实重与体积重情景"},{value:"付款复核",label:"提交前刷新报价"}], sections: [["真正有用的运费计算器","当前包裹页才是价格来源。先记录目的地、商品、线路、日期与测量阶段；别把他人的旧截图当成本次报价。计算器要回答线路是否可用、按什么重量计费，以及包装变化会怎样影响价格。"],["先收集完整输入","分别记录商品与境内运费、仓库服务、国际包裹及目的地可能费用。每条线路保存币种、最低或首重、续重、进位、实重、外箱尺寸、体积除数、保险和时间；缺失信息标为未显示，不写成零。"],["同时计算实重和体积重","按线路显示的除数计算长×宽×高所得体积重，并与实重比较，再应用该线路的进位规则。分别测试紧凑、可能和压力三种包装情景，不把一个除数套到所有线路。"],["把线路放进同一张表","用相同包裹输入比较资格、计费重、报价、时效范围、追踪、保险和责任。先排除不可用线路，再测试下一重量门槛；成本与速度分开评分，不宣称通用最快最便宜。"],["提交前模拟包装和合包","比较保留原包装、只去冗余材料及按限制拆包。把尺寸、保护服务、重复起步费用与风险都算进去；预打包能改善证据，但不能保证承运商最终测量不变。"],["为不确定性留透明缓冲","把已知报价、情景变化和未解决项目分开。目的地税费按当前政府规则核对，真实申报；未知费用放在报价之外作为缓冲，不能伪装成Joyagoo固定收费。"],["冻结证据并复盘最终包裹","付款前刷新地址、商品、包装、线路、计费、币种和价格。发货后追加最终重量、费用和追踪，不覆盖估算；按重量、尺寸、线路、汇率或目的地处理解释差异。"]] },
    "why-is-joyagoo-shipping-so-expensive": { eyebrow: "JOYAGOO运费为何显贵", title: "Joyagoo运费为什么贵：逐项检查七个成本驱动", description: "拆开最低收费、计费重、尺寸、线路资格、包装和目的地不确定性，找出本包裹真正变贵的原因。", facts: [{value:"7项驱动",label:"定位本包裹高价来源"},{value:"无统一价",label:"当前线路决定报价"},{value:"对因优化",label:"不以牺牲保护换低价"}], sections: [["高运费通常是多层叠加","先把商品与中国境内运费、仓库服务、国际运输和目的地费用分开，再保存当前线路。只有明确比较的是每件、每实重公斤、每计费公斤还是到手总价，“贵”才可以诊断。"],["驱动一：最低、首重与进位","小包裹的最低或首重会让每公斤显得高，进位又可能跨入下一档。比较立即发、等待已计划商品和选择性合包的完整成本；为凑比例额外买东西仍是支出。"],["驱动二：体积重","轻而蓬松的商品可能按体积重计费。复制每条线路的除数和进位，比较实重与体积重，找出造成外箱体积的物品；只移除冗余材料，不以压坏商品换价格。"],["驱动三：商品与线路资格","混合包裹可能因一个商品失去低价线路。先核对实时资格，再把允许的拆包方案连同重复起步费用和包装风险一起比较；绝不能用错误申报强行获得线路。"],["驱动四：包装与服务","加固、防水、缓冲或原盒会增加成本、重量或体积，也可能降低破损风险。依据仓库照片、商品价值和脆弱度决定，最低结账数字不等于最低总风险。"],["驱动五与六：比较口径和时间","不要混用不同日期、币种、目的地或测量阶段。相同输入比较实时线路，把报价时间、汇率、追踪、保险和时效范围保存下来；旧报价不能证明当前价格。"],["驱动七：目的地不确定性","按目的地政府当前规定真实申报，把可能税费和处理费单列为缓冲。然后针对主因优化：最低费主导时合理合包，体积主导时减冗余，资格主导时再考虑拆包。"]] },
    "joyagoo-shipping-cost-per-kg-explained": { eyebrow: "JOYAGOO每公斤成本", title: "Joyagoo每公斤运费：正确理解费率、阶梯与计费重", description: "说明为什么没有全球统一公斤价，并用实时报价、重量阶梯与尺寸计算本包裹的有效费率。", facts: [{value:"无统一公斤价",label:"目的地和线路会改变结果"},{value:"计费重量",label:"不一定等于秤重"},{value:"有效费率",label:"只用于公平比较本包裹"}], sections: [["为什么不存在统一公斤价","国际运费取决于目的地、重量、体积、线路和商品资格，且常含最低、首重、续重、进位与体积计费。用当前包裹页计算本包裹有效费率，而不是套用全球平均。"],["区分挂牌结构和有效费率","先按显示规则算出计费重与当前国际报价，再用报价除以计费公斤。商品、境内运费、仓库服务和目的地费用只在计算到手成本时加入，不应藏进国际公斤价。"],["使用计费重而非方便的重量","分别标注实重、体积重和最终计费重。按每条线路自己的除数及进位计算，使用外箱尺寸；预打包结果可替代粗估，但仍要保留各阶段证据。"],["比较重量门槛而非单点","测试当前、下一档前后以及尺寸稍增的情景。某线路在整点重量最便宜，跨一个小门槛后可能失去优势；统一输入并先排除不可用线路。"],["理解合包为何改变比例","合包能摊薄起步费用，也可能因体积或限制抬高计费重。比较立即发、等待已计划商品、选择性合包与合理拆包的完整成本，不能为改善分母而买填充物。"],["价格、速度和风险分开","每公斤数字只表示价格密度，不等于价值。把资格、时效范围、追踪、保险和赔付另行评分，目的地不确定费用也要单列，不能当作Joyagoo公斤价。"],["建立会更新的个人记录","付款前保存最终线路、重量、包装、币种与报价；发货后追加最终数据并解释差异。历史结果可作为相似包裹起点，却不是永久官方价卡。"]] },
    "joyagoo-shipping-coupon-promo-discount-guide": { eyebrow: "JOYAGOO运费优惠", title: "Joyagoo运费优惠券：付款前核对促销码与折扣规则", description: "安全核对优惠券、促销码和折扣码适用费用，用最终应付金额比较，不发布过期代码。", facts: [{value:"实时核验",label:"账户和结账页决定资格"},{value:"读清范围",label:"运费优惠不等于商品折扣"},{value:"比较总额",label:"优惠不代表线路最优"}], sections: [["为什么不发布万能代码","促销可能受账户、国家、线路、门槛、币种、次数和有效期限制。以当前账户、活动页和包裹结账为准，记录名称、范围、上限、时间和叠加规则，不把旧帖代码写成人人有效。"],["区分商品、服务和运费优惠","商品与境内运费、仓库服务、国际运输和目的地费用是不同层。只从条款明确涵盖的费用中扣减，把原价、适用基数、折扣和最终应付分别记录。"],["在账户和结账页验证","用真实目的地、商品、包装和线路测试，保存使用前后金额、币种和时间。若被拒，照录原因，不在非官方网站反复猜码，也不因单个账户成功就宣称普遍有效。"],["读清叠加、上限、门槛和退款","核对最高减免、最低消费、币种、可否叠加及取消或调整后是否返还。未说明的结果标为未知；把为达门槛新增商品、境内运费与重量变化算入完整成本。"],["优惠后再比较线路","用相同包裹输入计算各线路计费重和实时价，只应用其真正接受的优惠。折后线路仍需核对资格、尺寸规则、时效、追踪和保障，并测试重量或尺寸变化。"],["避开假码页面和夸大宣传","不要向优惠网站提供密码、验证码、付款或安装扩展。警惕倒计时、无上限期限的“独家码”和伪装成通用优惠的推荐奖励；没有可验证优惠就明确说没有。"],["把优惠放在成本计划最后一步","先核对仓库记录、包装和适用线路，再应用已验证优惠。付款前刷新并保存证据，发货后记录调整是否影响优惠；优惠不能使不可用线路变有效，也不能消除海关风险。"]] },
    "joyagoo-shipping-to-canada-cost-planner": { eyebrow: "JOYAGOO加拿大运费", title: "Joyagoo寄往加拿大：规划成本、重量与目的地风险", description: "用当前线路资格、计费重情景、包装证据和独立目的地缓冲规划加拿大包裹。", facts: [{value:"加拿大地址",label:"使用真实省份和邮编"},{value:"包装尺寸",label:"测试实重与体积重"},{value:"当前规定",label:"发货前核对政府指引"}], sections: [["从具体加拿大包裹开始","用真实省份、邮编和仓库商品加载当前线路，保存报价时间与测量阶段。其他省份、北美平均或旧截图不能替代本次结账；商品阶段、仓库阶段和国际运输也是不同时间段。"],["建立四层加拿大成本","分别记录商品和境内运费、仓库服务与包装、国际运输以及加拿大可能税费或处理费。实时金额照抄，未知项明确标注；币种与汇率证据也要保留。"],["逐条计算计费重量","记录秤重和外箱长宽高，按加拿大线路显示的除数计算体积重并应用进位。测试包装略增重及不确定边长增加的情景，区分粗估、预打包和最终测量。"],["一致比较加拿大线路","用同一表记录资格、限制、重量尺寸、体积规则、报价、时效范围、追踪、保险和责任。先排除不可用线路，再测试下一门槛；不宣称通用最快最便宜。"],["用证据决定合包与包装","比较保留原包装、只去冗余及按限制拆包，把尺寸、重量、服务、重复起步费用与破损风险都算进去。不要为改善每公斤比例买计划外商品或牺牲必要保护。"],["保守处理申报和目的地费用","真实描述商品与价值，保留发票并遵循当前文件要求。依据加拿大政府当前指引核对税费，不能用旧门槛或非正式“包税”说法；未知费用单列缓冲。"],["刷新、付款并复盘","提交前刷新地址、商品、包装、线路、计费、币种、价格、追踪和保险。发货后追加最终测量与费用，按成本层解释差异；旧记录只作下次起始范围。"]] },
  },
  de: {} as Record<AdditionalPrioritySeoArticleSlug, CompactTranslation>,
  es: {} as Record<AdditionalPrioritySeoArticleSlug, CompactTranslation>,
  fr: {} as Record<AdditionalPrioritySeoArticleSlug, CompactTranslation>,
};

const translationLabels = {
  de: { eyebrow: "JOYAGOO VERSANDPLAN", description: "Ein vollständiger Leitfaden mit Live-Linien, Abrechnungsgewicht, Verpackung, Nachweisen und transparenten Unsicherheiten.", fact: ["Live prüfen", "Gewicht testen", "Vor Zahlung sichern"], factLabel: ["Aktuelle Paketdaten nutzen", "Tatsächlich und volumetrisch", "Angebot mit Zeitstempel"] },
  es: { eyebrow: "PLAN DE ENVÍO JOYAGOO", description: "Guía completa con rutas activas, peso facturable, embalaje, pruebas e incertidumbres separadas.", fact: ["Verificar en vivo", "Probar el peso", "Guardar antes de pagar"], factLabel: ["Usar datos actuales", "Real y volumétrico", "Cotización con fecha"] },
  fr: { eyebrow: "PLAN D’EXPÉDITION JOYAGOO", description: "Guide complet avec lignes actives, poids facturable, emballage, preuves et incertitudes séparées.", fact: ["Vérifier en direct", "Tester le poids", "Sauver avant paiement"], factLabel: ["Données actuelles du colis", "Réel et volumétrique", "Devis horodaté"] },
} as const;

const translatedHeadings = {
  de: ["Mit dem konkreten Paket beginnen", "Kostenebenen trennen", "Abrechnungsgewicht berechnen", "Linien konsistent vergleichen", "Verpackung und Konsolidierung prüfen", "Ungewissheit transparent halten", "Vor Zahlung aktualisieren und auswerten"],
  es: ["Empezar por el paquete concreto", "Separar las capas de coste", "Calcular el peso facturable", "Comparar rutas con coherencia", "Probar embalaje y consolidación", "Separar la incertidumbre", "Actualizar antes de pagar y revisar"],
  fr: ["Partir du colis concret", "Séparer les couches de coût", "Calculer le poids facturable", "Comparer les lignes de façon cohérente", "Tester emballage et regroupement", "Isoler les incertitudes", "Actualiser avant paiement et analyser"],
} as const;

const translatedParagraphs = {
  de: ["Nutze Zieladresse, konkrete Lagerartikel und die aktuell angezeigten Linien. Speichere Datum, Währung und Messstufe; fremde oder alte Screenshots sind kein Angebot für dieses Paket.", "Trenne Produkt und chinesische Zustellung, gewählte Lagerdienste, internationale Fracht und mögliche Zielkosten. Kopiere Live-Werte, kennzeichne Unbekanntes und vermische keine Ebenen.", "Erfasse tatsächliches Gewicht und Außenmaße. Berechne Volumengewicht mit Divisor und Rundung jeder Linie, teste erwartete und vorsichtige Szenarien und setze keine Einheitsregel für alle Anbieter ein.", "Vergleiche Eignung, Einschränkungen, Abrechnungsgewicht, Preis, Zeitraum, Tracking, Versicherung und Verantwortung mit identischen Eingaben. Schließe unzulässige Linien zuerst aus und trenne Preis von Geschwindigkeit.", "Vergleiche Originalverpackung, gezieltes Entfernen redundanten Materials und eine zulässige Aufteilung. Rechne Maße, Schutz, wiederholte Mindestkosten und Risiko vollständig; zusätzliche ungeplante Käufe sind keine Ersparnis.", "Prüfe aktuelle Behördenregeln, deklariere Ware und Wert korrekt und halte mögliche Steuern, Abgaben oder Bearbeitung als separaten Puffer. Erfinde keinen festen Zielbetrag und verspreche keine Steuerfreiheit.", "Aktualisiere vor Zahlung Adresse, Inhalt, Verpackung, Linie, Regel, Währung und Endbetrag. Ergänze später Endgewicht, Zahlung und Tracking, ohne die Schätzung zu löschen, und erkläre Abweichungen nach Ursache."],
  es: ["Usa la dirección real, los artículos del almacén y las rutas visibles ahora. Guarda fecha, moneda y etapa de medición; una captura antigua o ajena no cotiza este paquete.", "Separa producto y transporte chino, servicios elegidos, flete internacional y posibles costes en destino. Copia importes activos, marca lo desconocido y no mezcles capas.", "Registra peso real y medidas exteriores. Calcula el volumen con divisor y redondeo propios de cada ruta, prueba escenarios probable y prudente y no impongas una regla universal.", "Compara elegibilidad, restricciones, peso, precio, rango, tracking, seguro y responsabilidad con entradas idénticas. Elimina primero rutas incompatibles y puntúa coste y rapidez por separado.", "Compara conservar embalaje, retirar solo material redundante y dividir cuando esté permitido. Incluye medidas, protección, mínimos repetidos y riesgo; comprar relleno no es ahorrar.", "Consulta reglas oficiales actuales, declara contenido y valor correctamente y deja impuestos, derechos o gestión posibles en un margen separado. No inventes una cifra fija ni prometas exención.", "Antes de pagar actualiza dirección, contenido, embalaje, ruta, regla, moneda y total. Después añade peso final, pago y eventos sin borrar la estimación y explica cada diferencia."],
  fr: ["Utilisez l’adresse réelle, les articles en entrepôt et les lignes visibles maintenant. Gardez date, devise et stade de mesure ; une ancienne capture ne chiffre pas ce colis.", "Séparez produit et livraison chinoise, services choisis, fret international et éventuels coûts à destination. Copiez les montants actifs, nommez l’inconnu et ne mélangez pas les couches.", "Relevez poids réel et mesures extérieures. Calculez le volume avec diviseur et arrondi propres à chaque ligne, testez scénarios probable et prudent et n’imposez aucune règle universelle.", "Comparez admissibilité, restrictions, poids, prix, plage, suivi, assurance et responsabilité avec les mêmes données. Écartez d’abord les lignes incompatibles et séparez coût et vitesse.", "Comparez emballage d’origine, retrait ciblé du superflu et séparation autorisée. Comptez dimensions, protection, minimums répétés et risque ; acheter du remplissage n’est pas économiser.", "Vérifiez les règles publiques actuelles, déclarez correctement contenu et valeur et gardez impôts, droits ou traitement possibles dans une marge séparée. N’inventez aucun montant fixe.", "Avant paiement, actualisez adresse, contenu, emballage, ligne, règle, devise et total. Ajoutez ensuite poids final, paiement et suivi sans effacer l’estimation, puis expliquez chaque écart."],
} as const;

const localizedTitles: Record<Exclude<PriorityArticleLocale, "en">, Record<AdditionalPrioritySeoArticleSlug, string>> = {
  zh: Object.fromEntries(additionalPrioritySeoArticleSlugs.map((slug) => [slug, translated.zh[slug].title])) as Record<AdditionalPrioritySeoArticleSlug, string>,
  de: { "joyagoo-shipping-calculator-cost-estimate-guide": "Joyagoo-Versandrechner: belastbare Kosten schätzen", "why-is-joyagoo-shipping-so-expensive": "Warum Joyagoo-Versand teuer wirkt: sieben Kostentreiber", "joyagoo-shipping-cost-per-kg-explained": "Joyagoo-Versandkosten pro kg richtig berechnen", "joyagoo-shipping-coupon-promo-discount-guide": "Joyagoo-Versandgutscheine und Rabattregeln prüfen", "joyagoo-shipping-to-canada-cost-planner": "Joyagoo-Versand nach Kanada: Kosten und Gewicht planen" },
  es: { "joyagoo-shipping-calculator-cost-estimate-guide": "Calculadora de envío Joyagoo: estimar el coste real", "why-is-joyagoo-shipping-so-expensive": "Por qué parece caro el envío Joyagoo: siete factores", "joyagoo-shipping-cost-per-kg-explained": "Coste Joyagoo por kg: tarifas y peso facturable", "joyagoo-shipping-coupon-promo-discount-guide": "Cupones Joyagoo: comprobar promociones y descuentos", "joyagoo-shipping-to-canada-cost-planner": "Envío Joyagoo a Canadá: planificar coste y peso" },
  fr: { "joyagoo-shipping-calculator-cost-estimate-guide": "Calculateur d’expédition Joyagoo : estimer le coût", "why-is-joyagoo-shipping-so-expensive": "Pourquoi l’envoi Joyagoo paraît cher : sept facteurs", "joyagoo-shipping-cost-per-kg-explained": "Coût Joyagoo au kg : tarif et poids facturable", "joyagoo-shipping-coupon-promo-discount-guide": "Coupons Joyagoo : vérifier promotions et remises", "joyagoo-shipping-to-canada-cost-planner": "Expédition Joyagoo au Canada : coût et poids" },
};

for (const locale of ["de", "es", "fr"] as const) {
  for (const slug of additionalPrioritySeoArticleSlugs) {
    const labels = translationLabels[locale];
    translated[locale][slug] = {
      eyebrow: labels.eyebrow,
      title: localizedTitles[locale][slug],
      description: labels.description,
      facts: [
        { value: labels.fact[0], label: labels.factLabel[0] },
        { value: labels.fact[1], label: labels.factLabel[1] },
        { value: labels.fact[2], label: labels.factLabel[2] },
      ],
      sections: translatedHeadings[locale].map((heading, index) => [heading, translatedParagraphs[locale][index]]),
    };
  }
}

export const additionalPriorityShippingArticles: Record<PriorityArticleLocale, Record<AdditionalPrioritySeoArticleSlug, SeoArticle>> = {
  en,
  zh: Object.fromEntries(additionalPrioritySeoArticleSlugs.map((slug) => {
    const copy = translated.zh[slug];
    return [slug, article(copy.eyebrow, copy.title, copy.description, copy.facts, copy.sections)];
  })) as Record<AdditionalPrioritySeoArticleSlug, SeoArticle>,
  de: Object.fromEntries(additionalPrioritySeoArticleSlugs.map((slug) => {
    const copy = translated.de[slug];
    return [slug, article(copy.eyebrow, copy.title, copy.description, copy.facts, copy.sections)];
  })) as Record<AdditionalPrioritySeoArticleSlug, SeoArticle>,
  es: Object.fromEntries(additionalPrioritySeoArticleSlugs.map((slug) => {
    const copy = translated.es[slug];
    return [slug, article(copy.eyebrow, copy.title, copy.description, copy.facts, copy.sections)];
  })) as Record<AdditionalPrioritySeoArticleSlug, SeoArticle>,
  fr: Object.fromEntries(additionalPrioritySeoArticleSlugs.map((slug) => {
    const copy = translated.fr[slug];
    return [slug, article(copy.eyebrow, copy.title, copy.description, copy.facts, copy.sections)];
  })) as Record<AdditionalPrioritySeoArticleSlug, SeoArticle>,
};

export const additionalPriorityShippingSourceBodies: Record<PriorityArticleLocale, string> = {
  en: "Checked September 14, 2026 against current Joyagoo guidance on fees, shopping flow, actual and volumetric weight, packing and logistics handoffs. Live route terms and current destination-government rules remain decisive.",
  zh: "2026年9月14日核对Joyagoo当前收费、购物流程、实重与体积重、包装和物流交接说明。最终以实时线路条款和目的地政府现行规定为准。",
  de: "Am 14. September 2026 anhand aktueller Joyagoo-Hinweise zu Gebühren, Ablauf, Gewicht, Verpackung und Logistik geprüft. Live-Bedingungen und aktuelle Behördenregeln bleiben maßgeblich.",
  es: "Comprobado el 14 de septiembre de 2026 con las guías Joyagoo sobre cargos, proceso, peso, embalaje y logística. Mandan las condiciones activas y normas oficiales actuales.",
  fr: "Vérifié le 14 septembre 2026 avec les guides Joyagoo sur frais, parcours, poids, emballage et logistique. Les conditions actives et règles publiques actuelles prévalent.",
};
