import type { Locale } from "./i18n";
import type { SeoArticleCopy } from "./seoArticles";

type SeoArticle = SeoArticleCopy["article"];

const en: SeoArticle = {
  eyebrow: "JOYAGOO CURRENCY CONVERSION GUIDE",
  title: "Joyagoo Exchange Rate: How to Audit Currency Conversion Cost",
  description: "Measure the effective cost of a Joyagoo top-up or payment using the live checkout, credited balance and card statement without assuming a fixed exchange-rate markup.",
  facts: [
    { value: "Live", label: "The payment screen is decisive for available methods and currencies" },
    { value: "4 records", label: "Keep the order, quote, balance credit and provider statement" },
    { value: "No guess", label: "Do not publish a fixed markup when the current pages do not state one" },
  ],
  sections: [
    {
      heading: "Separate display currency from the money that actually moves",
      paragraphs: [
        "A Joyagoo exchange-rate question sounds simple: how many units of your currency buy one Chinese yuan on the platform? In practice, one order can show several different currency contexts. The product and Chinese domestic delivery are ultimately obligations to a Chinese seller, the site may display an approximate amount in a selected currency, a top-up channel may accept a particular settlement currency, and your bank may convert that settlement into the currency of your account. Those numbers answer different questions and should not be treated as one published Joyagoo rate.",
        "Joyagoo’s current service description says international users can pay with a credit card or local currency instead of manually acquiring Chinese payment access. Its live help center also publishes payment-method and currency pairings, but warns that channels can be suspended and that the options shown during top-up govern. That makes the live screen the operational evidence. A method named on a help page is not a promise that it will appear for every country, account or transaction on the day you pay.",
        "Use four labels in your worksheet: CNY obligation, site display, payment-channel amount and final account debit. The CNY obligation is the item-stage or parcel-stage amount you need to settle. The site display helps with navigation. The channel amount is what the payment provider requests. The final debit is what actually left your card or bank account, including any separately posted provider or issuer fee. Only the last two can reveal what the conversion cost was for your transaction.",
      ],
    },
    {
      heading: "Capture the quote before you confirm payment",
      paragraphs: [
        "Before pressing the final payment button, record the date and time, CNY amount being settled, selected payment method, settlement currency, quoted settlement amount and every fee line visible on the screen. If you top up an account balance, also record the CNY or other balance amount the interface says will be credited. A screenshot can preserve the display, but copy the values into a table as well so they can be compared without relying on image memory.",
        "Do not calculate from a product-card approximation. The current shopping guidance separates the product-order payment from the later international-parcel payment, and an order may also receive an outstanding-balance request when additional seller-side costs arise. Match the quote to the exact order or top-up reference. Otherwise, a changed order total can look like currency slippage even though the underlying CNY obligation changed between two screens.",
        "If the live flow does not show enough information to identify what will be credited or debited, stop before confirmation. Choose another displayed method only if its terms are clearer and it suits your account. Never infer a permanent percentage from a logo, an old review or a previous top-up. The goal of the capture step is not to predict every charge; it is to create a timestamped promise that can later be reconciled with the actual result.",
      ],
    },
    {
      heading: "Calculate your effective conversion rate",
      paragraphs: [
        "After the transaction settles, calculate an effective cost rather than searching for a hidden universal rate. Let L be the total debit in your local account currency, including any issuer fee posted for that transaction. Let C be the CNY balance credited or CNY obligation paid. Your effective local cost per CNY is L divided by C. The inverse, C divided by L, shows how many CNY you obtained per local unit. Always name the direction because a rate of 0.14 and its inverse of 7.14 describe the same relationship very differently.",
        "Consider a deliberately abstract example. A user needs to settle CNY 500. The payment screen requests 71.40 local units. The final account statement shows 72.60, and a separate 1.10 issuer fee is linked to the transaction. Total local cost is therefore 73.70 units. The effective cost is 73.70 divided by 500, or 0.1474 local units per CNY. These are teaching numbers, not a current Joyagoo quote, bank rate or expected result.",
        "Run the same calculation for each transaction instead of blending unlike events. A card payment, a local bank method and an e-wallet top-up may settle in different currencies or apply fees in different places. If you load more balance than one order requires, use the amount actually credited as C, not the merchandise subtotal. If a transaction is reversed, keep it outside the successful-payment average until every debit and refund has finished posting.",
      ],
    },
    {
      heading: "Find the source of the difference",
      paragraphs: [
        "When the final debit exceeds the pre-payment quote, compare records in order. First ask whether the CNY obligation changed. Joyagoo’s help page on outstanding balances says a paid shopping-agent order can still require additional costs and directs users to the order detail for the breakdown. A seller price or domestic-delivery adjustment is a purchase-cost change, not automatically a currency-conversion fee. Keep that difference in the order column rather than the rate column.",
        "Second, compare the payment-channel quote with the completed channel receipt. If those differ, preserve the transaction reference and exact labels. Third, compare the channel receipt with the bank statement. A bank can convert a foreign settlement currency or post its own fee; that part belongs to the issuer record, not to a claim about Joyagoo. If the channel settled in your account currency and the bank debit still differs, the statement description and fee breakdown matter more than a guessed cause.",
        "Finally, compare the credited balance or paid-order status with the receipt. Joyagoo’s card top-up guidance directs users to the Balance area and Top Up flow. A successful provider authorization without the expected balance credit is a reconciliation problem, not an invitation to pay twice. Keep the provider ID, platform reference, time, amount and currency together, then ask support to match the specific transaction.",
      ],
    },
    {
      heading: "Compare payment methods on total cost, not labels",
      paragraphs: [
        "The current payment-method page lists several method-and-currency combinations, including international card or wallet options and region-specific bank methods. Because the page also says channels can be suspended, do not build a permanent ranking. At the moment of payment, compare only the options actually displayed to your account. For each, record settlement currency, quoted amount, platform or provider fee shown, likely issuer conversion and refund path. An option described as local can still be expensive if your account uses another currency.",
        "Use a two-stage comparison. Before payment, compare the visible cost for the same CNY obligation. After settlement, replace the quoted result with the final debit and calculate the effective rate. Over several transactions, compare like with like: same account currency, similar CNY amount and similar date. A method that wins on one small payment may lose on a larger payment if fee structure differs, while market currency values can move between dates.",
        "Convenience and evidence quality are valid decision factors. A slightly higher confirmed total can be preferable when the method gives a clear receipt, a recognizable statement entry and an understandable refund route. Conversely, the lowest-looking display is not useful if the settlement currency is unclear. Do not select a method solely because another buyer called it cheapest; their country, issuer, transaction date and account currency may all be different.",
      ],
    },
    {
      heading: "Audit refunds without assuming the original rate returns",
      paragraphs: [
        "A refund can travel differently from an original payment. Joyagoo’s current service-charge page says that after return-related deductions, the remainder is credited to the account balance. That statement means a seller return may resolve inside the platform balance rather than recreating the original card transaction. Check the order and balance records before waiting for a card credit that the published workflow does not promise for that event.",
        "Record the original CNY payment, confirmed deduction, CNY refund or balance credit and the date each appeared. If you later withdraw or spend that balance, treat the later currency conversion as a separate event. Do not compare a refunded CNY balance directly with the old local-currency card debit and call the difference a loss until you know what was deducted, where the refund landed and whether any later conversion occurred.",
        "For a payment reversal or provider refund, compare the local amount returned with the original local debit after both are final. Foreign-exchange movement and issuer rules can make them differ even when the same foreign-currency amount is reversed. Assign each difference to a documented source where possible: seller deduction, platform balance, channel refund or bank conversion. Leave unresolved differences marked as unresolved instead of attributing them to the platform without evidence.",
      ],
    },
    {
      heading: "Use a repeatable payment audit",
      paragraphs: [
        "Create one row per payment event with these fields: date, purpose, order or parcel reference, CNY obligation, method, settlement currency, quoted settlement amount, displayed fee, credited balance, final account debit, separately posted issuer fee and effective cost per CNY. Add a notes column for an outstanding-balance adjustment or refund. This worksheet works for product orders, balance top-ups and international-parcel payments without pretending they share one fixed rate.",
        "Before confirming, verify that the purpose and CNY amount match the intended order. After confirming, save the receipt and check the balance or paid status once; if it does not reconcile, do not create a duplicate payment. When the statement posts, enter the final debit and formula. Review several comparable rows before changing methods. One transaction can identify a discrepancy, but it cannot prove a permanent platform markup.",
        "The defensible answer to “What is the Joyagoo exchange rate?” is therefore a method, not a number copied into an article. Check the live method and currency, preserve the quote, reconcile the credit, read the final statement and calculate the effective result. This produces a value tied to your date, account and transaction—and avoids publishing a rate that could already be wrong for the next buyer.",
      ],
    },
  ],
};

type NonEnglish = Exclude<Locale, "en">;
function make(eyebrow: string, title: string, description: string, facts: SeoArticle["facts"], headings: string[], paragraphs: string[][]): SeoArticle {
  return { eyebrow, title, description, facts, sections: headings.map((heading, index) => ({ heading, paragraphs: paragraphs[index] })) };
}

const localized: Record<NonEnglish, SeoArticle> = {
  zh: make("JOYAGOO 货币换算指南", "Joyagoo汇率：如何核算货币换算成本", "通过实时支付页、到账余额和银行卡账单计算实际成本，不猜测固定汇率加价。", [{ value: "实时", label: "支付页决定可用方式和币种" }, { value: "四项记录", label: "保存订单、报价、到账和账单" }, { value: "不猜测", label: "官方未公布固定加价时不编造数字" }], ["区分显示币种与实际资金流", "付款前保存报价", "计算实际换算率", "定位差额来源", "按总成本比较支付方式", "核算退款而不假设原汇率", "建立可重复的支付审计"], [
    ["Joyagoo订单可能同时出现人民币义务、网站显示币种、支付渠道结算币种和银行卡账户币种，它们不是同一个汇率。商品和中国境内运费最终对应人民币义务，银行还可能再次换算。", "当前服务说明用户可使用银行卡或本地货币，支付帮助页列出渠道和币种组合，也明确渠道可能暂停，实际Top Up页面为准。帮助页名称不能保证每个国家和账户都可用。", "表格分四栏：人民币应付、网站显示、渠道要求和最终账户扣款。只有渠道收据与最终扣款能说明本次换算成本。"],
    ["确认前记录日期、人民币金额、方式、结算币种、报价、费用行和预计到账余额。截图之外还应抄入表格，便于核对。", "不要从商品卡估算。商品付款和国际包裹付款是两个阶段，追加成本也会改变人民币义务。必须把报价对应到具体订单或充值编号。", "信息不足就先停止。不要从支付图标、旧评价或上次充值推导永久比例；报价记录的作用是建立可核对的时间点。"],
    ["设本地最终总扣款为L，支付或到账的人民币为C，实际每人民币成本=L÷C；反向为C÷L。必须标明方向。", "抽象示例：支付500元，页面报71.40本地单位，账单为72.60并另收1.10，则总计73.70，实际成本为0.1474本地单位/人民币。此数字不是Joyagoo当前报价。", "逐笔计算，不混合银行卡、本地银行和钱包。充值多于订单时用实际到账余额作为C；撤销交易要等扣款和退款全部入账后再统计。"],
    ["先确认人民币义务是否变化。官方欠款说明表示已付款的代购订单仍可能因追加成本补款，应查看订单明细。这属于订单成本变化，不应自动归为汇兑费。", "再比较支付页报价与渠道收据、渠道收据与银行账单。银行换算或银行费用应归入发卡行记录，不能直接写成Joyagoo费用。", "最后核对余额或已付款状态。渠道授权成功但余额未到账时，保存渠道号、平台编号、时间、金额和币种，请支持匹配，不能盲目重复付款。"],
    ["当前支付页列出多种渠道和币种，但也说明渠道会暂停，所以只比较账户当时实际显示的选项。记录结算币种、报价、可见费用、银行可能换算和退款路径。", "付款前比较同一人民币义务的可见成本，入账后改用最终扣款计算。只有账户币种、金额和日期接近的交易才适合比较。", "凭证清楚也有价值。略高但收据和退款路径清晰的方式可能更合适；不要因为其他买家说便宜就照搬，其国家、银行和日期可能不同。"],
    ["官方服务费页说明退货扣除相关费用后，剩余款进入账户余额，因此卖家退款不一定原路回银行卡。先看订单和余额记录。", "记录原人民币付款、扣除、人民币退款或余额到账及日期。之后消费或提现是新的换算事件，不应混为一次。", "支付撤销则等原扣款和退款都最终入账。把差额按卖家扣除、平台余额、渠道退款或银行换算归类；无法证明的标记未解决。"],
    ["每笔记录日期、用途、编号、人民币义务、方式、结算币种、报价、费用、到账余额、最终扣款、银行费用和实际成本，并单列补款与退款。", "付款前核对用途和人民币金额；付款后保存收据并核对一次状态，未匹配不要重复付。账单入账后填入公式，多笔同类交易后再判断。", "所以Joyagoo汇率的可靠答案不是一个固定数字，而是核算方法：看实时币种、保存报价、核对到账、读取账单并计算与日期和账户绑定的结果。"],
  ]),
  de: make("JOYAGOO-WÄHRUNGSLEITFADEN", "Joyagoo-Wechselkurs: Umrechnungskosten prüfen", "Effektive Kosten aus Live-Kasse, Guthaben und Kartenabrechnung berechnen, ohne einen festen Aufschlag zu behaupten.", [{ value: "Live", label: "Zahlungsseite entscheidet über Methode und Währung" }, { value: "4 Belege", label: "Auftrag, Angebot, Gutschrift und Abrechnung sichern" }, { value: "Keine Schätzung", label: "Ohne Veröffentlichung keinen festen Aufschlag nennen" }], ["Anzeigewährung und echten Geldfluss trennen", "Das Angebot vor Zahlung sichern", "Den effektiven Kurs berechnen", "Die Differenz einer Quelle zuordnen", "Methoden nach Gesamtkosten vergleichen", "Erstattungen ohne alten Kurs prüfen", "Eine wiederholbare Zahlungsprüfung nutzen"], [
    ["Ein Auftrag kann CNY-Verpflichtung, Seitenanzeige, Abrechnungswährung und Kontowährung zeigen. Das sind verschiedene Ebenen, nicht ein veröffentlichter Joyagoo-Kurs.", "Der aktuelle Service erlaubt Karte oder lokale Währung; die Hilfeseite nennt Kombinationen, warnt aber vor ausgesetzten Kanälen. Maßgeblich ist die Live-Top-up-Seite.", "Führe CNY-Soll, Anzeige, Kanalforderung und finale Kontobelastung getrennt. Kanalbeleg und Belastung zeigen das Transaktionsergebnis."],
    ["Notiere Zeit, CNY-Betrag, Methode, Abrechnungswährung, Angebot, Gebührenzeilen und erwartete Gutschrift.", "Nutze nicht die Produktkarte: Produkt- und Paketzahlung sind getrennt, und eine Nachforderung kann das CNY-Soll ändern. Ordne jedes Angebot einer Referenz zu.", "Fehlen klare Angaben, pausiere. Ein Logo, eine alte Bewertung oder frühere Zahlung beweist keinen dauerhaften Prozentsatz."],
    ["Mit finaler lokaler Belastung L und gutgeschriebenem oder bezahltem CNY C gilt Kosten je CNY=L/C; der Kehrwert ist C/L. Nenne die Richtung.", "Abstrakt: 500 CNY, Angebot 71,40 Einheiten, Belastung 72,60 plus 1,10 Bankgebühr ergeben 73,70 und 0,1474 je CNY. Das ist kein aktuelles Angebot.", "Berechne jede Methode einzeln. Bei Guthaben nutze die echte Gutschrift; stornierte Vorgänge erst nach vollständiger Buchung."],
    ["Prüfe zuerst Änderungen am CNY-Soll. Laut offizieller Hilfe kann ein bezahlter Auftrag Zusatzkosten haben; das ist nicht automatisch Währungsgebühr.", "Vergleiche danach Angebot, Kanalbeleg und Bankabrechnung. Eine Bankumrechnung gehört zum Emittentenbeleg, nicht ungeprüft zu Joyagoo.", "Prüfe zuletzt Guthaben oder Zahlstatus. Bei Autorisierung ohne Gutschrift sichere IDs, Zeit, Betrag und Währung und bitte um Zuordnung statt doppelt zu zahlen."],
    ["Vergleiche nur aktuell angezeigte Optionen: Abrechnungswährung, Angebot, sichtbare Gebühr, mögliche Bankumrechnung und Erstattungsweg.", "Vor Zahlung zählt das Angebot für dasselbe CNY-Soll, nach Buchung die finale Belastung. Vergleiche nur ähnliche Beträge, Termine und Kontowährungen.", "Klare Belege und Rückzahlung sind ebenfalls Wert. Die Empfehlung eines anderen Nutzers passt wegen Land, Bank und Datum nicht automatisch."],
    ["Die offizielle Gebührenseite sagt, dass nach Rückgabekosten der Rest ins Kontoguthaben geht. Eine Verkäufererstattung muss daher nicht auf die Karte zurücklaufen.", "Notiere Zahlung, Abzug, CNY-Gutschrift und Datum. Spätere Nutzung oder Auszahlung ist ein neues Umrechnungsereignis.", "Bei Provider-Rückzahlung warte auf endgültige Buchungen. Ordne Unterschiede Verkäufer, Guthaben, Kanal oder Bank zu; Unbelegtes bleibt offen."],
    ["Eine Zeile enthält Datum, Zweck, Referenz, CNY-Soll, Methode, Währung, Angebot, Gebühren, Gutschrift, Belastung und effektiven Kurs.", "Vor Zahlung Zweck und Betrag prüfen, danach Beleg und Status einmal abgleichen, bei Abweichung nicht doppelt zahlen. Später die finale Belastung einsetzen.", "Eine belastbare Antwort zum Joyagoo-Wechselkurs ist diese Methode: Live-Währung prüfen, Angebot sichern, Gutschrift und Abrechnung abgleichen und den datierten Wert berechnen."],
  ]),
  pl: make("PRZEWODNIK WALUTOWY JOYAGOO", "Kurs Joyagoo: jak sprawdzić koszt przewalutowania", "Oblicz efektywny koszt z bieżącej płatności, salda i wyciągu bez zgadywania stałej marży.", [{ value: "Na żywo", label: "Ekran płatności decyduje o metodzie i walucie" }, { value: "4 zapisy", label: "Zachowaj zamówienie, wycenę, saldo i wyciąg" }, { value: "Bez zgadywania", label: "Nie publikuj marży bez źródła" }], ["Oddziel walutę wyświetlaną od przepływu pieniędzy", "Zapisz wycenę przed płatnością", "Oblicz efektywny kurs", "Znajdź źródło różnicy", "Porównuj metody według całości", "Sprawdź zwrot bez założenia starego kursu", "Stosuj powtarzalny audyt"], [
    ["Zamówienie może pokazywać zobowiązanie CNY, walutę strony, walutę kanału i walutę konta. To różne liczby, nie jeden kurs Joyagoo.", "Aktualna pomoc pozwala na kartę lub lokalną walutę i publikuje pary metod, ale ostrzega o zawieszeniu kanałów. Decyduje ekran Top Up.", "Zapisuj osobno CNY, wyświetlenie, kwotę kanału i finalne obciążenie. Ostatnie dwa pokazują rzeczywisty wynik."],
    ["Przed potwierdzeniem zapisz czas, CNY, metodę, walutę rozliczenia, kwotę, opłaty i oczekiwane saldo.", "Nie licz z karty produktu. Płatność produktu i paczki są osobne, a dopłata może zmienić zobowiązanie. Powiąż wycenę z numerem.", "Przy niejasnych danych zatrzymaj się. Logo, stara opinia i poprzednia płatność nie dowodzą stałej marży."],
    ["Jeśli L to finalne lokalne obciążenie, a C to CNY, koszt jednego CNY=L/C; odwrotność to C/L. Podaj kierunek.", "Abstrakcyjnie: 500 CNY, oferta 71,40, obciążenie 72,60 plus 1,10 daje 73,70 i 0,1474 za CNY. To nie jest oferta Joyagoo.", "Licz każdą transakcję osobno. Dla salda użyj faktycznej kwoty kredytu; zwrotów nie uśredniaj przed zakończeniem."],
    ["Najpierw sprawdź zmianę CNY. Oficjalna pomoc mówi, że opłacone zamówienie może dostać koszty dodatkowe; to nie musi być przewalutowanie.", "Następnie porównaj ofertę, potwierdzenie kanału i wyciąg. Przeliczenie banku przypisz bankowi, nie platformie bez dowodu.", "Na końcu uzgodnij saldo. Autoryzacja bez kredytu wymaga numerów, czasu, kwoty i waluty, nie drugiej płatności."],
    ["Porównuj tylko opcje widoczne teraz: walutę, kwotę, opłatę, możliwe przeliczenie banku i ścieżkę zwrotu.", "Przed płatnością porównaj to samo CNY, po rozliczeniu finalne obciążenie. Zestawiaj podobne daty, kwoty i konta.", "Czytelny dowód i zwrot też mają wartość. Rada innej osoby może nie pasować do kraju, banku i daty."],
    ["Strona opłat mówi, że po potrąceniach zwrot trafia do salda konta, więc nie musi wrócić na kartę.", "Zapisz płatność CNY, potrącenie, saldo i datę. Późniejsze wydanie lub wypłata to nowe zdarzenie.", "Dla zwrotu kanału poczekaj na finalne księgowanie. Klasyfikuj różnice; niewyjaśnionych nie przypisuj bez dowodu."],
    ["Wiersz obejmuje datę, cel, numer, CNY, metodę, walutę, ofertę, opłatę, saldo, obciążenie i kurs efektywny.", "Sprawdź cel przed płatnością, potem potwierdzenie i status; nie płać drugi raz przy rozbieżności. Wpisz wyciąg po zaksięgowaniu.", "Wiarygodny kurs Joyagoo to metoda: sprawdź ekran, zapisz ofertę, uzgodnij saldo i wyciąg oraz oblicz wynik dla daty i konta."],
  ]),
  es: make("GUÍA DE CONVERSIÓN JOYAGOO", "Tipo de cambio Joyagoo: audita el coste de conversión", "Calcula el coste efectivo con checkout, saldo y extracto sin atribuir un margen fijo no publicado.", [{ value: "En vivo", label: "La pantalla decide método y moneda" }, { value: "4 registros", label: "Guarda pedido, cotización, saldo y extracto" }, { value: "Sin suponer", label: "No publiques un margen sin fuente" }], ["Separa moneda mostrada y dinero real", "Captura la cotización antes de pagar", "Calcula la conversión efectiva", "Localiza el origen de la diferencia", "Compara métodos por coste total", "Audita reembolsos sin asumir el tipo original", "Usa una auditoría repetible"], [
    ["Un pedido puede mostrar obligación CNY, moneda de la web, moneda del canal y moneda de tu cuenta. No son un único tipo Joyagoo.", "El servicio actual admite tarjeta o moneda local; la ayuda publica combinaciones pero avisa que los canales pueden suspenderse. Manda Top Up en vivo.", "Registra por separado CNY, visualización, importe del canal y débito final. Los dos últimos revelan el resultado real."],
    ["Antes de confirmar guarda fecha, CNY, método, moneda de liquidación, importe, cargos y saldo esperado.", "No uses la tarjeta de producto. Producto y paquete se pagan en etapas distintas, y un saldo pendiente puede cambiar el CNY. Vincula la cotización a una referencia.", "Si falta claridad, detente. Un logo, reseña antigua o recarga previa no demuestra un porcentaje permanente."],
    ["Si L es el débito local final y C el CNY pagado, coste por CNY=L/C; la inversa es C/L. Indica la dirección.", "Ejemplo abstracto: CNY 500, cotización 71,40, extracto 72,60 más 1,10 da 73,70 y 0,1474 por CNY. No es una cotización actual.", "Calcula cada operación. Para recarga usa el saldo acreditado; excluye reversiones hasta que terminen."],
    ["Primero mira si cambió el CNY. La ayuda oficial permite costes adicionales en un pedido pagado; no son automáticamente conversión.", "Luego compara checkout, recibo y banco. Una conversión bancaria pertenece al emisor, no a Joyagoo sin prueba.", "Por último concilia saldo y estado. Autorización sin crédito requiere referencias, hora, importe y moneda, no pagar dos veces."],
    ["Compara solo opciones visibles: moneda, importe, cargos, posible conversión bancaria y reembolso.", "Antes compara el mismo CNY; después usa el débito final. Contrasta fechas, importes y cuentas similares.", "La claridad del recibo también vale. La opción barata de otra persona puede no servir por país, banco y fecha."],
    ["La página de cargos dice que tras deducciones el resto vuelve al saldo, no necesariamente a la tarjeta.", "Registra CNY original, deducción, saldo y fecha. Gastar o retirar después es otra conversión.", "En reembolso del canal espera los asientos finales. Clasifica diferencias y deja sin atribuir lo no probado."],
    ["Cada fila incluye fecha, objetivo, referencia, CNY, método, moneda, oferta, cargos, saldo, débito y coste efectivo.", "Verifica antes, conserva recibo y concilia una vez; si no coincide, no dupliques. Añade el extracto final.", "La respuesta defendible al tipo Joyagoo es el método: pantalla activa, cotización, saldo, extracto y cálculo fechado."],
  ]),
  it: make("GUIDA CAMBIO JOYAGOO", "Cambio Joyagoo: verificare il costo di conversione", "Calcola il costo effettivo da checkout, saldo e estratto senza inventare un ricarico fisso.", [{ value: "Live", label: "La schermata decide metodo e valuta" }, { value: "4 registri", label: "Conserva ordine, preventivo, accredito ed estratto" }, { value: "Nessuna ipotesi", label: "Non pubblicare un ricarico senza fonte" }], ["Separare valuta mostrata e denaro reale", "Salvare il preventivo prima del pagamento", "Calcolare il cambio effettivo", "Individuare l’origine della differenza", "Confrontare i metodi sul totale", "Verificare i rimborsi senza vecchio cambio", "Usare un audit ripetibile"], [
    ["Un ordine può mostrare obbligo CNY, valuta del sito, valuta del canale e valuta del conto. Non sono un unico cambio Joyagoo.", "Il servizio attuale consente carta o valuta locale; l’aiuto pubblica combinazioni ma avvisa che i canali possono sospendersi. Decide il Top Up live.", "Registra CNY, display, importo del canale e addebito finale separatamente. Gli ultimi due mostrano il risultato."],
    ["Prima di confermare salva data, CNY, metodo, valuta di regolamento, importo, costi e accredito previsto.", "Non usare la scheda prodotto. Prodotto e pacco sono due pagamenti, e un saldo residuo può cambiare il CNY. Collega l’offerta a un riferimento.", "Se i dati sono poco chiari fermati. Logo, vecchia recensione o pagamento precedente non provano una percentuale fissa."],
    ["Con addebito locale L e CNY C, costo per CNY=L/C; l’inverso è C/L. Indica la direzione.", "Esempio astratto: CNY 500, offerta 71,40, addebito 72,60 più 1,10 = 73,70 e 0,1474 per CNY. Non è un’offerta attuale.", "Calcola ogni operazione. Per saldo usa l’accredito reale; escludi gli storni fino alla chiusura."],
    ["Prima controlla se l’obbligo CNY è cambiato. L’aiuto ufficiale ammette costi aggiuntivi dopo il pagamento; non sono automaticamente conversione.", "Poi confronta offerta, ricevuta e banca. La conversione della banca appartiene all’emittente, non alla piattaforma senza prova.", "Infine concilia saldo e stato. Autorizzazione senza accredito richiede riferimenti, ora, importo e valuta, non un doppio pagamento."],
    ["Confronta solo opzioni live: valuta, importo, costi, possibile cambio bancario e percorso rimborso.", "Prima confronta lo stesso CNY, dopo usa l’addebito finale. Raffronta date, importi e conti simili.", "Una ricevuta chiara ha valore. Il metodo economico di un altro utente può non valere per paese, banca e data."],
    ["La pagina costi dice che, dopo le detrazioni, il resto va al saldo, non necessariamente alla carta.", "Registra pagamento CNY, detrazione, saldo e data. Uso o prelievo successivo è un nuovo evento.", "Per un rimborso del canale attendi le scritture finali. Classifica le differenze e lascia aperto ciò che non è provato."],
    ["Ogni riga include data, scopo, riferimento, CNY, metodo, valuta, offerta, costi, accredito, addebito e tasso effettivo.", "Verifica prima, salva la ricevuta e riconcilia una volta; non duplicare se manca il saldo. Inserisci poi l’estratto finale.", "Il cambio Joyagoo difendibile è un metodo: schermo live, preventivo, accredito, estratto e calcolo legato a data e conto."],
  ]),
  fr: make("GUIDE DE CHANGE JOYAGOO", "Taux de change Joyagoo : auditer le coût de conversion", "Calculez le coût effectif avec paiement, solde et relevé sans inventer de majoration fixe.", [{ value: "En direct", label: "L’écran décide méthode et devise" }, { value: "4 dossiers", label: "Gardez commande, devis, crédit et relevé" }, { value: "Sans supposer", label: "Ne publiez pas de marge sans source" }], ["Séparer devise affichée et flux réel", "Capturer le devis avant paiement", "Calculer le taux effectif", "Trouver la source de l’écart", "Comparer les moyens sur le coût total", "Auditer un remboursement sans ancien taux", "Utiliser un audit répétable"], [
    ["Une commande peut montrer obligation CNY, devise du site, devise du canal et devise du compte. Ce n’est pas un taux Joyagoo unique.", "Le service actuel accepte carte ou devise locale; l’aide publie des associations mais indique que les canaux peuvent être suspendus. L’écran Top Up fait foi.", "Notez séparément CNY, affichage, montant du canal et débit final. Les deux derniers donnent le résultat réel."],
    ["Avant validation, gardez date, CNY, moyen, devise, montant, frais et crédit attendu.", "Ne calculez pas depuis une fiche produit. Produit et colis sont deux paiements, et un solde dû peut changer le CNY. Reliez le devis à sa référence.", "Si les informations sont floues, arrêtez. Logo, ancien avis ou ancien paiement ne prouve pas un pourcentage permanent."],
    ["Avec débit local L et CNY C, coût par CNY=L/C; l’inverse est C/L. Précisez le sens.", "Exemple abstrait : CNY 500, devis 71,40, débit 72,60 plus 1,10 = 73,70 et 0,1474 par CNY. Ce n’est pas un devis actuel.", "Calculez chaque opération. Pour un solde, prenez le crédit réel; excluez les annulations incomplètes."],
    ["Vérifiez d’abord le CNY. L’aide officielle autorise des coûts supplémentaires sur une commande payée; ce n’est pas automatiquement du change.", "Comparez ensuite devis, reçu et banque. Une conversion bancaire appartient au dossier de l’émetteur, pas à Joyagoo sans preuve.", "Enfin rapprochez le solde. Autorisation sans crédit exige références, heure, montant et devise, pas un second paiement."],
    ["Comparez seulement les options affichées : devise, montant, frais, conversion bancaire possible et remboursement.", "Avant paiement comparez le même CNY; après, le débit final. Utilisez dates, montants et comptes semblables.", "La qualité de preuve compte. Le moyen le moins cher d’un autre acheteur peut différer selon pays, banque et date."],
    ["La page des frais dit qu’après déductions le reste revient au solde, pas forcément à la carte.", "Notez paiement CNY, déduction, crédit et date. Une utilisation ou un retrait futur est une nouvelle conversion.", "Pour un remboursement de canal, attendez les écritures finales. Classez les écarts et laissez sans attribution ce qui n’est pas prouvé."],
    ["Chaque ligne contient date, but, référence, CNY, moyen, devise, devis, frais, crédit, débit et taux effectif.", "Vérifiez avant, gardez le reçu et rapprochez une fois; ne doublez pas si le solde manque. Ajoutez le relevé final.", "Le taux Joyagoo défendable est une méthode : écran direct, devis, crédit, relevé et calcul lié à la date et au compte."],
  ]),
  pt: make("GUIA CAMBIAL JOYAGOO", "Câmbio Joyagoo: audite o custo de conversão", "Calcule o custo efetivo com checkout, saldo e extrato sem inventar uma margem fixa.", [{ value: "Ao vivo", label: "A tela decide método e moeda" }, { value: "4 registros", label: "Guarde pedido, cotação, crédito e extrato" }, { value: "Sem suposição", label: "Não publique margem sem fonte" }], ["Separar moeda exibida e dinheiro real", "Capturar a cotação antes do pagamento", "Calcular o câmbio efetivo", "Encontrar a origem da diferença", "Comparar métodos pelo custo total", "Auditar reembolsos sem o câmbio antigo", "Usar uma auditoria repetível"], [
    ["Um pedido pode mostrar obrigação CNY, moeda do site, moeda do canal e moeda da conta. Não são uma taxa Joyagoo única.", "O serviço atual aceita cartão ou moeda local; a ajuda publica combinações, mas avisa que canais podem ser suspensos. A tela Top Up ao vivo decide.", "Registre CNY, exibição, valor do canal e débito final separadamente. Os dois últimos mostram o resultado real."],
    ["Antes de confirmar salve data, CNY, método, moeda, valor, tarifas e crédito esperado.", "Não calcule pelo cartão do produto. Produto e pacote têm pagamentos separados, e saldo pendente pode mudar o CNY. Vincule a cotação ao número.", "Se faltarem dados, pare. Logotipo, avaliação antiga ou recarga anterior não provam percentual permanente."],
    ["Com débito local L e CNY C, custo por CNY=L/C; o inverso é C/L. Indique a direção.", "Exemplo abstrato: CNY 500, cotação 71,40, débito 72,60 mais 1,10 = 73,70 e 0,1474 por CNY. Não é cotação atual.", "Calcule cada operação. Para saldo use o crédito real; exclua estornos até a conclusão."],
    ["Primeiro veja se o CNY mudou. A ajuda oficial admite custos adicionais após pagamento; não são automaticamente câmbio.", "Depois compare cotação, recibo e banco. Conversão do banco pertence ao emissor, não à plataforma sem prova.", "Por fim concilie o saldo. Autorização sem crédito exige referências, hora, valor e moeda, não pagamento duplicado."],
    ["Compare só opções exibidas: moeda, valor, tarifas, possível conversão bancária e reembolso.", "Antes compare o mesmo CNY; depois use o débito final. Compare datas, valores e contas semelhantes.", "Recibo claro também tem valor. O método barato de outro usuário pode não valer para país, banco e data."],
    ["A página de taxas diz que após deduções o restante volta ao saldo, não necessariamente ao cartão.", "Registre pagamento CNY, dedução, saldo e data. Uso ou saque posterior é nova conversão.", "Para reembolso do canal espere lançamentos finais. Classifique diferenças e deixe aberto o que não tem prova."],
    ["Cada linha inclui data, finalidade, referência, CNY, método, moeda, cotação, tarifa, crédito, débito e custo efetivo.", "Verifique antes, guarde recibo e concilie uma vez; não duplique se faltar saldo. Depois adicione o extrato final.", "O câmbio Joyagoo defensável é método: tela ao vivo, cotação, crédito, extrato e cálculo ligado à data e à conta."],
  ]),
  ro: make("GHID VALUTAR JOYAGOO", "Curs Joyagoo: verificarea costului de conversie", "Calculează costul efectiv din checkout, sold și extras fără a inventa o marjă fixă.", [{ value: "Live", label: "Ecranul decide metoda și moneda" }, { value: "4 înregistrări", label: "Păstrează comanda, oferta, creditul și extrasul" }, { value: "Fără presupuneri", label: "Nu publica marjă fără sursă" }], ["Separă moneda afișată de fluxul real", "Salvează oferta înainte de plată", "Calculează conversia efectivă", "Găsește sursa diferenței", "Compară metodele după costul total", "Verifică rambursarea fără cursul vechi", "Folosește un audit repetabil"], [
    ["O comandă poate arăta obligație CNY, moneda site-ului, moneda canalului și moneda contului. Nu sunt un singur curs Joyagoo.", "Serviciul actual acceptă card sau monedă locală; ajutorul publică perechi, dar spune că unele canale pot fi suspendate. Ecranul Top Up decide.", "Notează separat CNY, afișajul, suma canalului și debitul final. Ultimele două arată rezultatul real."],
    ["Înainte de confirmare salvează data, CNY, metoda, moneda, suma, taxele și creditul așteptat.", "Nu calcula din fișa produsului. Produsul și coletul au plăți separate, iar un sold restant poate schimba CNY. Leagă oferta de referință.", "Dacă datele nu sunt clare, oprește-te. Sigla, recenzia veche sau plata anterioară nu dovedesc procent permanent."],
    ["Cu debit local L și CNY C, cost per CNY=L/C; inversul este C/L. Spune direcția.", "Exemplu abstract: CNY 500, ofertă 71,40, debit 72,60 plus 1,10 = 73,70 și 0,1474 per CNY. Nu este ofertă actuală.", "Calculează fiecare tranzacție. Pentru sold folosește creditul real; exclude anulările până la final."],
    ["Întâi verifică dacă CNY s-a schimbat. Ajutorul oficial permite costuri suplimentare după plată; nu sunt automat conversie.", "Apoi compară oferta, chitanța și banca. Conversia băncii aparține emitentului, nu platformei fără dovadă.", "La final reconciliază soldul. Autorizarea fără credit cere referințe, oră, sumă și monedă, nu o plată dublă."],
    ["Compară doar opțiunile afișate: monedă, sumă, taxe, conversie bancară posibilă și rambursare.", "Înainte compară același CNY; după, debitul final. Folosește date, sume și conturi similare.", "O chitanță clară are valoare. Metoda ieftină a altui utilizator poate diferi după țară, bancă și dată."],
    ["Pagina taxelor spune că după deduceri restul intră în sold, nu neapărat pe card.", "Notează plata CNY, deducerea, creditul și data. Folosirea sau retragerea ulterioară este altă conversie.", "Pentru rambursarea canalului așteaptă înregistrările finale. Clasifică diferențele și lasă neatribuit ce nu e dovedit."],
    ["Fiecare rând conține data, scopul, referința, CNY, metoda, moneda, oferta, taxa, creditul, debitul și costul efectiv.", "Verifică înainte, păstrează chitanța și reconciliază o dată; nu dubla dacă lipsește soldul. Adaugă extrasul final.", "Cursul Joyagoo defensabil este o metodă: ecran live, ofertă, credit, extras și calcul legat de dată și cont."],
  ]),
  sv: make("JOYAGOO VALUTAGUIDE", "Joyagoo växelkurs: granska omräkningskostnaden", "Beräkna effektiv kostnad från betalning, saldo och kontoutdrag utan att hitta på ett fast påslag.", [{ value: "Live", label: "Betalsidan avgör metod och valuta" }, { value: "4 poster", label: "Spara order, offert, kreditering och utdrag" }, { value: "Ingen gissning", label: "Publicera inte påslag utan källa" }], ["Skilj visningsvaluta från verkligt flöde", "Spara offerten före betalning", "Beräkna effektiv växling", "Hitta källan till skillnaden", "Jämför metoder på total kostnad", "Granska återbetalning utan gammal kurs", "Använd en upprepbar betalningskontroll"], [
    ["En order kan visa CNY-skyldighet, webbvaluta, kanalvaluta och kontovaluta. Det är inte en enda Joyagoo-kurs.", "Nuvarande tjänst godtar kort eller lokal valuta; hjälpen visar kombinationer men säger att kanaler kan pausas. Live Top Up avgör.", "Registrera CNY, visning, kanalbelopp och slutlig debitering separat. De sista två visar resultatet."],
    ["Före bekräftelse sparar du datum, CNY, metod, avräkningsvaluta, belopp, avgifter och väntad kreditering.", "Räkna inte från produktkortet. Produkt och paket betalas separat, och ett restbelopp kan ändra CNY. Knyt offerten till referensen.", "Om data är oklara, stanna. Logotyp, gammal recension eller tidigare betalning bevisar ingen fast procentsats."],
    ["Med lokal debitering L och CNY C är kostnad per CNY=L/C; inversen är C/L. Ange riktningen.", "Abstrakt exempel: CNY 500, offert 71,40, debit 72,60 plus 1,10 = 73,70 och 0,1474 per CNY. Det är ingen aktuell offert.", "Räkna varje händelse. För saldo använd faktisk kreditering; uteslut återföringar tills de är klara."],
    ["Kontrollera först om CNY ändrats. Officiell hjälp medger tilläggskostnader efter betalning; de är inte automatiskt växling.", "Jämför sedan offert, kanalens kvitto och banken. Bankens omräkning hör till utgivarens post, inte plattformen utan bevis.", "Stäm sist av saldo. Auktorisation utan kredit kräver referenser, tid, belopp och valuta, inte dubbel betalning."],
    ["Jämför bara visade alternativ: valuta, belopp, avgift, möjlig bankväxling och återbetalning.", "Före betalning jämför samma CNY; efteråt slutlig debitering. Jämför liknande datum, belopp och konton.", "Tydliga bevis har värde. En annan användares billigaste metod kan skilja sig genom land, bank och datum."],
    ["Avgiftssidan säger att resten efter avdrag går till kontosaldot, inte nödvändigtvis kortet.", "Registrera CNY-betalning, avdrag, kreditering och datum. Senare användning eller uttag är en ny omräkning.", "För kanalåterbetalning vänta på slutbokningar. Klassificera skillnader och lämna sådant utan bevis öppet."],
    ["Varje rad innehåller datum, syfte, referens, CNY, metod, valuta, offert, avgift, kredit, debit och effektiv kostnad.", "Kontrollera före, spara kvittot och stäm av en gång; dubbla inte om saldo saknas. Lägg sedan in slutligt utdrag.", "Ett försvarbart Joyagoo-svar är metoden: live-skärm, offert, kredit, kontoutdrag och en beräkning knuten till datum och konto."],
  ]),
};

export const exchangeRateArticles: Record<Locale, SeoArticle> = { en, ...localized };

export const exchangeRateSourceBodies: Record<Locale, string> = {
  en: "Fact-checked on 13 August 2026 against Joyagoo’s current service-charge, payment-method, international-card top-up, service-description and outstanding-balance help pages. Live payment options and the user’s completed provider statement remain decisive.",
  zh: "事实核查于2026年8月13日，依据Joyagoo当前服务费、支付方式、国际卡充值、服务说明和欠款帮助页；最终以实时支付选项和用户完成入账的渠道账单为准。",
  de: "Am 13. August 2026 anhand aktueller Joyagoo-Seiten zu Gebühren, Zahlungsarten, Kartenguthaben, Service und Restbetrag geprüft; maßgeblich bleiben Live-Option und endgültige Abrechnung.",
  pl: "Sprawdzono 13 sierpnia 2026 z aktualnymi stronami Joyagoo o opłatach, metodach, doładowaniu kartą, usłudze i saldzie; decydują opcje na żywo i finalny wyciąg.",
  es: "Verificado el 13 de agosto de 2026 con páginas actuales de tarifas, pagos, recarga con tarjeta, servicio y saldo pendiente; mandan la opción activa y el extracto final.",
  it: "Verificato il 13 agosto 2026 sulle pagine Joyagoo attuali per costi, pagamenti, ricarica carta, servizio e saldo; decidono l’opzione live e l’estratto finale.",
  fr: "Vérifié le 13 août 2026 avec les pages Joyagoo actuelles sur frais, paiements, recharge par carte, service et solde dû ; l’option en direct et le relevé final font foi.",
  pt: "Verificado em 13 de agosto de 2026 nas páginas atuais de taxas, pagamentos, recarga por cartão, serviço e saldo; valem a opção ao vivo e o extrato final.",
  ro: "Verificat la 13 august 2026 cu paginile actuale Joyagoo despre taxe, plăți, alimentare cu cardul, serviciu și sold; decid opțiunea live și extrasul final.",
  sv: "Kontrollerad 13 augusti 2026 mot aktuella Joyagoo-sidor om avgifter, betalning, kortpåfyllning, service och saldo; live-alternativet och slutligt utdrag avgör.",
};
