import type { Locale } from "./i18n";
import type { SeoArticleCopy } from "./seoArticles";

type Article = SeoArticleCopy["article"];

const en: Article = {
  eyebrow: "JOYAGOO PARCEL CONSOLIDATION GUIDE",
  title: "Joyagoo Parcel Consolidation: How to Combine and Pack Warehouse Items",
  description:
    "A practical guide to choosing which stored items to combine, handling route and separate-packing restrictions, writing packaging instructions and checking the parcel before payment.",
  facts: [
    { value: "Stored", label: "Status items should reach before parcel selection" },
    { value: "≥90 cm", label: "Published trigger for an individually packaged item" },
    { value: "2 plans", label: "Combined and split scenarios worth comparing" },
  ],
  sections: [
    {
      heading: "Start with the parcel goal, not the number of items",
      paragraphs: [
        "Parcel consolidation means selecting several accepted products in the Joyagoo warehouse and submitting them as one international shipment. Joyagoo’s current public guidance says items purchased at different times can be combined or shipped in batches once they are available in the Warehouse area. That flexibility is useful because one parcel can avoid repeating the first-weight charge or per-parcel handling on several small shipments. It does not mean that the largest possible box is automatically the cheapest, safest or most suitable parcel. The useful question is: which grouping gives these particular products compatible routes, sensible protection and an acceptable billed size for this destination?",
        "Set that goal before clicking every checkbox. A buyer with two folded shirts, a compact bag and a pair of boxed shoes may test one combined plan and a second plan that sends the shoes separately. A buyer with a battery accessory and ordinary clothing may need different groups because route eligibility can differ. A buyer with fragile goods may accept extra protective volume instead of chasing the smallest box. Consolidation is therefore a packaging and route decision, not merely a warehouse housekeeping step. This guide uses official workflow facts as the boundary and editorial calculations as planning tools; the live parcel screen remains decisive for route availability and price.",
      ],
      callout: {
        title: "The decision rule",
        text: "Combine items when the shared parcel saves repeated charges without creating a worse route, unsafe packaging or excessive dimensional weight.",
      },
    },
    {
      heading: "Build an eligible item list before comparing parcels",
      paragraphs: [
        "Open the Warehouse area and make a small table for every candidate item: stored date, recorded weight, visible dimensions if supplied, product category, return decision, packaging preference and any mailing restriction. Only include an item after its QC and return decision are resolved. Joyagoo publishes a separate five-day return-request window after QC completion and a longer warehouse-storage period; combining an item into a parcel should not be used to avoid an unresolved mismatch. Items bought on different dates can be selected together, but each item keeps its own storage clock, so record the oldest stored date rather than assuming the newest arrival resets the group.",
        "Next remove ineligible combinations. Joyagoo’s help center says stored goods may fail to submit together when a product has a mailing restriction or is marked for separate packaging. Another current help page states that an item with any side measuring at least 90 centimetres is automatically tagged for individual packaging. Treat that threshold as a platform rule checked on 9 August 2026, not as a universal carrier law. The route screen can impose additional product and size conditions. If two items cannot share the same available line, create separate groups before calculating cost; a cheaper theoretical box is irrelevant if the system cannot submit it.",
      ],
    },
    {
      heading: "Compare a combined plan with a realistic split plan",
      paragraphs: [
        "For each eligible group, write two scenarios. Plan A combines everything that can travel together. Plan B splits the group where route, size or protection suggests a natural boundary. Compare more than the sum of warehouse weights: note the number of first-weight increments, possible per-parcel charges, likely box dimensions, packaging material, route choices and the value of separating fragile or restricted contents. Joyagoo’s warehouse page provides estimated weight and volume for reference, while the finished parcel is weighed and measured after packing. Use the estimate to rank options, not to present a guaranteed delivered total.",
        "Here is a deliberately hypothetical calculation, not a Joyagoo quote. Suppose a route charges $20 for the first 500 grams, $6 for each additional 500 grams and $1 per parcel. Three packed items might be billed at 1.0, 1.5 and 2.0 kilograms separately: $27 + $33 + $39 = $99. If one combined 4.5-kilogram parcel stays on the same route, the arithmetic would be $20 + eight additional increments × $6 + $1 = $69. The $30 difference explains why consolidation can help, but the conclusion changes if the combined box triggers dimensional billing, loses that route or needs substantially more protection. Replace every hypothetical input with the live route figures before deciding.",
      ],
      callout: {
        title: "Calculate twice",
        text: "Run the same current route rules against a combined box and a credible split. A single estimate cannot show the trade-off.",
      },
    },
    {
      heading: "Write packaging instructions that solve a defined risk",
      paragraphs: [
        "Joyagoo’s shopping guidance lists options such as removing packaging, parcel reinforcement and insurance. Select each service for a reason. Removing a seller’s outer shipping box may cut empty space while keeping a retail box; removing a shoe box may reduce volume more but also removes structure and presentation. Reinforcement may suit fragile, heavy or irregular goods, yet additional board, corner protection or filling can increase physical and dimensional weight. Insurance addresses covered financial loss under its current terms; it does not prevent crushing. Never write a broad instruction such as “make it as small and safe as possible” when those goals conflict.",
        "Use item-level instructions instead: retain the retail box for the fragile figure; discard only the seller’s courier bag around the garment; fold the hoodie without removing its tags; keep liquids upright if the selected line permits them; fill voids around the hard accessory; do not place a heavy shoe box on a soft hat. Joyagoo’s published packing standard describes selecting a suitable box, ordering the contents, adding protection, sealing and reinforcing, with special handling for food, fragile and irregular items. That is a general standard, not a guarantee against every carrier event. Your instructions should identify what must remain, what may be removed and which product needs separation inside the shared carton.",
      ],
    },
    {
      heading: "Control dimensional weight without stripping useful protection",
      paragraphs: [
        "A consolidation plan can reduce repeated outer boxes and still become expensive if it creates one bulky carton. The existing Joyagoo shipping guidance explains that some routes compare actual weight with volumetric weight, calculated from length × width × height using the divisor shown for that line. Think in shapes before asking for packaging removal. Soft clothing can fill space around a protected box; several rigid shoe boxes may stack poorly; a long object can determine the entire carton length; a puffy jacket may be compressible only if compression will not damage it. The goal is less unused volume, not the smallest possible package at any cost.",
        "Use a simple decision matrix. Keep retail packaging when it protects a fragile item, preserves required accessories or matters to the product’s use. Consider removal when the box is mostly empty, the item is durable and you have already closed the return decision. Add reinforcement when impact or crushing risk outweighs the extra size. Split the parcel when one item forces a much larger carton, requires a different route or could damage the other contents. If exact packed dimensions could change the route choice, compare the rehearsal-packing option shown in the account. Its live description and price should control; do not rely on an old article or another buyer’s checkout.",
      ],
    },
    {
      heading: "Check customs profile, address and route before submission",
      paragraphs: [
        "A parcel that is efficient for freight can still be poorly grouped for the destination. Joyagoo’s consolidation help page cautions that parcel weight and repeated quantities can influence whether customs views a shipment as personal or commercial, and it specifically warns that parcels above 10 kilograms may attract more scrutiny in some countries. This is platform guidance, not a universal legal threshold or clearance guarantee. Check the destination’s current import rules, truthful declaration requirements, restricted goods and tax treatment. Splitting a parcel solely to evade duties or inspection is not a legitimate planning method; grouping should reflect actual personal use, compatible contents and accurate declarations.",
        "Then verify the delivery mechanics. Re-enter the recipient name, phone number, postcode, region and street details exactly as the chosen carrier requires. Confirm that every selected item appears in the parcel, every exclusion remains in the warehouse and the displayed route accepts the contents. Check any line-specific size, weight, insurance and declaration conditions. Save a dated record of the item list, packaging instructions, route and estimate before payment. If the system removes a route after one item is added, use that evidence to isolate the incompatible product instead of repeatedly submitting the same impossible combination.",
      ],
    },
    {
      heading: "Reconcile the packed parcel before the final hand-off",
      paragraphs: [
        "Ordinary parcel submission begins with an estimated international fee under Joyagoo’s published workflow. After the warehouse packs, weighs and measures the carton, the actual amount can differ; a carrier may also adjust the billing measurement later. Review the updated parcel detail rather than treating the first screen as final. Compare the packed weight and dimensions with your scenario, confirm that requested packaging was applied where the account shows it, and follow any balance instruction. A higher charge is a prompt to inspect the measurements and route basis, not proof by itself that an error occurred.",
        "Use this final checklist: all items passed QC; no return is open; oldest storage date is known; route restrictions are compatible; separately packaged items are excluded; retain/remove instructions are specific; fragile goods have appropriate protection; combined and split costs were compared; recipient and declaration details are accurate; and the budget allows the estimate to change. Keep the parcel record until delivery and inspect visible damage with the carrier where possible. A good consolidated parcel is not simply full. It is a documented group of compatible products whose route, protection, size and cost were each chosen deliberately.",
      ],
      callout: {
        title: "Pre-payment checklist",
        text: "Resolved QC, compatible items, explicit packaging, valid route, accurate address and declaration, two cost scenarios, and room for the packed measurement to change.",
      },
    },
  ],
};

const localized: Record<Exclude<Locale, "en">, Article> = {
  zh: {
    eyebrow: "JOYAGOO 合箱与包装指南", title: "Joyagoo包裹合箱：如何组合并包装仓库商品", description: "从仓库商品分组、线路与单独包装限制，到包装备注、成本比较及付款前检查的实用指南。",
    facts: [{ value: "已入库", label: "选择包裹前商品应达到的状态" }, { value: "≥90厘米", label: "平台公布的单独包装触发条件" }, { value: "两套方案", label: "应比较合箱与拆分情形" }],
    sections: [
      { heading: "先确定包裹目标，而不是追求件数最多", paragraphs: ["合箱是把仓库中已经验收的多件商品选入一个国际包裹。官方说明，不同时间购买的商品入库后可一起寄送或分批寄送；这样可能减少重复首重和每包操作费，但最大箱子不一定最便宜、安全或适合目的地。", "点击商品前先判断共同线路、保护需求和计费体积。普通服装与带电配件、鞋盒与柔软衣物、易碎品与重物可能需要不同分组。合箱是包装和线路决策，实时包裹页面的可用线路与价格才是最终依据。"], callout: { title: "判断原则", text: "只有在不牺牲线路、保护和体积效率时，合箱节省重复费用才有意义。" } },
      { heading: "比较前先建立可合并商品清单", paragraphs: ["为每件候选商品记录入库日期、重量、尺寸、品类、退货决定、包装偏好和邮寄限制。QC与退货问题解决后再加入包裹；不同日期商品可一起选，但各自仓储时钟不会因新商品到达而重置。", "官方帮助中心指出，带邮寄限制或“单独包装”标记的商品不能一起提交；任何一边达到90厘米的商品会自动标记为单独包装。该数字是2026年8月9日核查的平台规则，并非所有承运商的通用法律，线路页面还可能有额外条件。"] },
      { heading: "把合箱方案与现实的拆分方案比较", paragraphs: ["方案A组合所有兼容商品，方案B按线路、尺寸或保护需要拆分。比较首重次数、每包费用、可能箱体、包装材料和可选线路，而不是只加仓库重量。系统估算的重量和体积用于排序方案，打包后的测量才更接近最终账单。", "假设线路首500克20美元、每续500克6美元、每包1美元，这只是编辑示例而非Joyagoo报价。三个包裹分别按1、1.5、2公斤计为99美元；合并4.5公斤按同一规则为69美元。若合箱触发体积重、失去线路或需要更多保护，结论会改变。"], callout: { title: "计算两次", text: "用同一实时线路规则分别计算合箱和可信的拆分方案。" } },
      { heading: "让每条包装指令对应一个风险", paragraphs: ["官方流程列出拆包装、加固和保险等选项。拆卖家快递箱可能减少空隙，拆鞋盒则同时失去结构；加固提高保护也可能增加重量和体积；保险只处理条款覆盖的经济损失，不能防止挤压。不要写目标冲突的模糊要求。", "应按商品写明：保留易碎摆件零售盒、只丢弃衣服外层快递袋、帽子上方不要压重物。官方包装标准包括选择合适箱体、按顺序放置、加填充、封箱与加固；你的备注要明确保留什么、可拆什么、哪个商品需要箱内隔离。"] },
      { heading: "控制体积重，但不要拆掉必要保护", paragraphs: ["合箱减少外箱后仍可能形成大体积。部分线路比较实际重和体积重，体积重按线路显示的长×宽×高及除数计算。柔软衣物可填充受保护盒子周围，多个硬鞋盒或长物体可能决定整个箱体。目标是减少无用空隙，而不是不计风险地缩到最小。", "决策矩阵是：保护易碎品、配件完整或使用需要时保留包装；耐用商品且退货已结束时考虑拆除空盒；碰撞风险更高时加固；某件商品迫使箱体变大、需要不同线路或会伤及其他商品时拆包。尺寸会改变线路时，查看账户中的预打包实时说明。"] },
      { heading: "提交前核对海关特征、地址与线路", paragraphs: ["官方合箱页面提醒，重量和重复数量可能影响部分国家把包裹判断为个人或商业用途，并提示10公斤以上可能受到更多关注。这不是全球统一法律。应核对目的地最新进口、申报、限制和税费规则，准确申报，不能为了规避税费而人为拆包。", "再次核对收件人、电话、邮编、地区与街道，确认每件选中商品和线路兼容，检查尺寸、重量、保险和申报条件，并保存商品清单、包装备注、线路与估算的日期记录。如果加入某件后线路消失，应找出不兼容商品而非反复提交。"] },
      { heading: "交运前核对打包后的包裹", paragraphs: ["普通提交先收预估国际运费，仓库打包称重测量后金额可能变化，承运商也可能调整计费数据。查看更新后的包裹详情、重量、尺寸和余额指令；费用上升首先意味着需要核对测量与线路依据，并不自动证明出错。", "最终清单：QC已通过、无未结退货、最早仓储日期已知、线路兼容、单独包装商品已排除、包装备注具体、易碎品得到保护、合箱与拆分成本已比较、地址和申报准确、预算允许测量变化。好包裹不是塞得最满，而是每项选择都有依据。"], callout: { title: "付款前清单", text: "QC解决、商品兼容、包装明确、线路有效、地址申报准确、比较两套成本并预留测量差额。" } },
    ],
  },
  de: {
    eyebrow: "JOYAGOO KONSOLIDIERUNG", title: "Joyagoo-Paketkonsolidierung: Lagerartikel sinnvoll kombinieren und verpacken", description: "Praxisleitfaden zu Artikelgruppen, Routen- und Einzelverpackungsgrenzen, Verpackungsanweisungen und der Prüfung vor Zahlung.",
    facts: [{ value: "Eingelagert", label: "Status vor der Paketauswahl" }, { value: "≥90 cm", label: "Veröffentlichter Auslöser für Einzelverpackung" }, { value: "2 Pläne", label: "Kombination und Aufteilung vergleichen" }],
    sections: [
      { heading: "Mit dem Paketziel beginnen, nicht mit der Stückzahl", paragraphs: ["Konsolidierung verbindet mehrere angenommene Lagerartikel zu einer internationalen Sendung. Laut aktueller Hilfe können zu verschiedenen Zeiten gekaufte Waren gemeinsam oder in Etappen versandt werden. Wiederholte Grundgewichte lassen sich sparen, doch der größte Karton ist nicht automatisch günstig oder sicher.", "Prüfe vor der Auswahl gemeinsame Routen, Schutz und Abrechnungsvolumen. Kleidung, Batteriezubehör, Schuhkartons oder Zerbrechliches können getrennte Gruppen brauchen. Die Live-Paketseite entscheidet über verfügbare Linien und Preise."], callout: { title: "Entscheidungsregel", text: "Nur kombinieren, wenn eingesparte Wiederholungsgebühren nicht durch Route, Schutz oder Volumengewicht aufgehoben werden." } },
      { heading: "Zuerst eine zulässige Artikelliste erstellen", paragraphs: ["Notiere Einlagerungsdatum, Gewicht, Maße, Kategorie, Retourenentscheidung, Verpackungswunsch und Versandbeschränkung. Nimm nur abgeschlossene QC-Entscheidungen auf; verschiedene Kaufdaten setzen die jeweilige Lagerfrist nicht zurück.", "Artikel mit Versandbeschränkung oder Kennzeichnung zur Einzelverpackung lassen sich laut Hilfe nicht gemeinsam einreichen. Eine Seite von mindestens 90 Zentimetern löst die Einzelverpackung aus. Das ist der am 9. August 2026 geprüfte Plattformwert, keine allgemeine Transportgesetzgebung." ] },
      { heading: "Kombination und realistische Aufteilung vergleichen", paragraphs: ["Plan A verbindet kompatible Waren, Plan B trennt nach Route, Größe oder Schutz. Vergleiche Grundgewichte, Paketgebühren, Kartonform, Material und Linien statt nur Lagergewichte zu addieren. Schätzwerte ordnen Optionen; erst das gepackte Paket wird gemessen.", "Ein rein hypothetischer Tarif von 20 Dollar für 500 g, 6 Dollar je weitere 500 g und 1 Dollar pro Paket ergäbe für 1, 1,5 und 2 kg getrennt 99 Dollar, kombiniert bei 4,5 kg 69 Dollar. Volumengewicht, Routenverlust oder Schutzbedarf können das Ergebnis umkehren."], callout: { title: "Zweimal rechnen", text: "Wende dieselben aktuellen Linienregeln auf Kombination und plausible Aufteilung an." } },
      { heading: "Verpackungsanweisungen an ein Risiko binden", paragraphs: ["Entfernen von Verpackung, Verstärkung und Versicherung lösen verschiedene Probleme. Ein Versandkarton kann entfallen, ein Schuhkarton bietet dagegen Struktur. Verstärkung schützt, kann aber Gewicht und Volumen erhöhen; Versicherung verhindert keine Quetschung.", "Formuliere pro Artikel: Einzelhandelsbox der Figur behalten, nur Versandbeutel des Pullovers entfernen, keinen schweren Karton auf den Hut legen. Der veröffentlichte Standard beschreibt passenden Karton, geordnete Platzierung, Füllung, Versiegelung und Verstärkung; benenne ausdrücklich, was bleibt oder getrennt liegt." ] },
      { heading: "Volumengewicht ohne unnötigen Schutzverlust steuern", paragraphs: ["Ein Sammelkarton kann trotz weniger Außenboxen sperrig sein. Manche Linien vergleichen Ist- und Volumengewicht. Weiche Kleidung füllt Hohlräume, starre Kartons oder lange Gegenstände bestimmen dagegen die Außenmaße. Ziel ist weniger Leerraum, nicht minimale Größe um jeden Preis.", "Verpackung bei Zerbrechlichem und wichtigen Zubehörteilen behalten; leere Boxen bei robusten, endgültig akzeptierten Waren erwägen; bei Stoßrisiko verstärken; trennen, wenn ein Artikel Karton oder Route dominiert. Bei entscheidenden Maßen gilt die aktuelle Probepack-Anzeige im Konto." ] },
      { heading: "Zollprofil, Adresse und Route prüfen", paragraphs: ["Joyagoo weist darauf hin, dass Gewicht und gleiche Stückzahlen die persönliche oder gewerbliche Einordnung beeinflussen können und über 10 kg in manchen Ländern mehr Aufmerksamkeit erhalten. Das ist keine weltweite Rechtsgrenze. Prüfe Einfuhr-, Deklarations-, Verbots- und Steuerregeln und deklariere wahrheitsgemäß.", "Kontrolliere Name, Telefon, Postleitzahl, Region und Straße sowie Inhalt, Linienzulässigkeit, Maße, Gewicht, Versicherung und Deklaration. Speichere Artikelliste, Anweisungen, Linie und Schätzung. Verschwindet eine Linie nach einem Artikel, isoliere den inkompatiblen Inhalt." ] },
      { heading: "Das gepackte Paket vor Übergabe abstimmen", paragraphs: ["Bei normaler Einreichung wird zunächst eine Schätzung bezahlt. Nach Packen und Messen kann sich der Betrag ändern; auch der Beförderer kann das Abrechnungsmaß korrigieren. Prüfe Details, Maße, Anweisungen und Saldo statt den ersten Bildschirm als Endpreis zu behandeln.", "Checkliste: QC erledigt, keine offene Retoure, ältestes Lagerdatum bekannt, Routen kompatibel, Einzelverpacktes ausgeschlossen, Anweisungen konkret, Schutz passend, beide Kostenpläne verglichen, Adresse und Deklaration korrekt, Reserve für Messänderung vorhanden."], callout: { title: "Vor der Zahlung", text: "Kompatible Waren, klare Verpackung, gültige Route, korrekte Daten, zwei Kostenpläne und Reserve." } },
    ],
  },
  pl: {
    eyebrow: "KONSOLIDACJA PACZKI JOYAGOO", title: "Konsolidacja paczki Joyagoo: jak łączyć i pakować towary z magazynu", description: "Praktyczny przewodnik po grupowaniu towarów, ograniczeniach tras, instrukcjach pakowania i kontroli przed płatnością.",
    facts: [{ value: "W magazynie", label: "Status przed wyborem paczki" }, { value: "≥90 cm", label: "Opublikowany próg osobnego pakowania" }, { value: "2 plany", label: "Porównaj łączenie i podział" }],
    sections: [
      { heading: "Zacznij od celu paczki, nie liczby rzeczy", paragraphs: ["Konsolidacja łączy zaakceptowane towary magazynowe w jedną przesyłkę. Aktualna pomoc pozwala łączyć zakupy z różnych terminów lub wysyłać je partiami. Może to ograniczyć powtarzane opłaty początkowe, lecz największy karton nie zawsze jest najtańszy i bezpieczny.", "Przed zaznaczeniem wszystkiego sprawdź wspólną trasę, ochronę i rozmiar rozliczeniowy. Odzież, akcesorium z baterią, pudełka po butach i rzeczy kruche mogą wymagać osobnych grup. Decydują bieżące opcje na ekranie paczki."], callout: { title: "Reguła decyzji", text: "Łącz tylko wtedy, gdy oszczędność nie pogarsza trasy, ochrony ani wagi wymiarowej." } },
      { heading: "Najpierw utwórz listę rzeczy kwalifikujących się", paragraphs: ["Zapisz datę magazynowania, wagę, wymiary, kategorię, decyzję o zwrocie, opakowanie i ograniczenia. Dodawaj tylko towary po zakończonym QC; późniejszy zakup nie zeruje terminu starszego towaru.", "Towary z ograniczeniem pocztowym albo oznaczeniem osobnego pakowania nie mogą być złożone razem. Bok co najmniej 90 cm uruchamia osobne pakowanie. To reguła platformy sprawdzona 9 sierpnia 2026 r., a nie uniwersalne prawo przewoźników." ] },
      { heading: "Porównaj konsolidację z realnym podziałem", paragraphs: ["Plan A łączy zgodne towary, plan B dzieli je według trasy, rozmiaru lub ochrony. Porównaj opłaty początkowe, opłaty za paczkę, karton, materiały i dostępne linie, nie tylko sumę wag magazynowych. Szacunek służy do wyboru, pomiar po pakowaniu do rozliczenia.", "Hipotetyczna stawka 20 USD za pierwsze 500 g, 6 USD za kolejne i 1 USD za paczkę dałaby 99 USD dla paczek 1, 1,5 i 2 kg, a 69 USD dla wspólnej 4,5 kg. To nie oferta Joyagoo; waga objętościowa, utrata trasy lub ochrona mogą zmienić wynik."], callout: { title: "Policz dwa razy", text: "Zastosuj te same bieżące zasady do wariantu wspólnego i rozsądnego podziału." } },
      { heading: "Każda instrukcja ma rozwiązywać określone ryzyko", paragraphs: ["Usunięcie opakowania, wzmocnienie i ubezpieczenie mają różne cele. Karton kurierski może być zbędny, pudełko butów zapewnia konstrukcję. Wzmocnienie chroni, lecz zwiększa masę i objętość; ubezpieczenie nie zapobiega zgnieceniu.", "Pisz na poziomie towaru: zachowaj pudełko kruchej figurki, usuń tylko worek kurierski ubrania, nie kładź ciężkiego pudełka na czapce. Standard opisuje odpowiedni karton, kolejność, wypełnienie, zamknięcie i wzmocnienie; wskaż, co zachować i oddzielić." ] },
      { heading: "Kontroluj wagę wymiarową bez utraty potrzebnej ochrony", paragraphs: ["Jedna paczka może pozostać duża mimo mniejszej liczby pudeł. Niektóre linie porównują wagę rzeczywistą i wymiarową. Miękka odzież wypełnia luki, natomiast sztywne pudełka i długie przedmioty wyznaczają karton. Celem jest mniej pustej przestrzeni, nie minimalny rozmiar za wszelką cenę.", "Zachowaj opakowanie przy kruchości i ważnych akcesoriach; rozważ usunięcie pustego pudełka po zamknięciu zwrotu; wzmocnij przy ryzyku uderzeń; podziel, gdy jeden towar wymusza większy karton lub inną trasę. Gdy wymiary decydują, sprawdź aktualne pakowanie próbne." ] },
      { heading: "Sprawdź profil celny, adres i trasę", paragraphs: ["Pomoc ostrzega, że waga i wiele identycznych sztuk mogą wpływać na ocenę osobistego lub handlowego charakteru, a ponad 10 kg bywa dokładniej sprawdzane. Nie jest to globalny próg prawny. Sprawdź aktualne przepisy importowe, deklaracje, ograniczenia i podatki.", "Zweryfikuj odbiorcę, telefon, kod, region, ulicę, zawartość, linię, limity rozmiaru i wagi, ubezpieczenie oraz deklarację. Zapisz listę, instrukcje, trasę i wycenę. Jeśli trasa znika po dodaniu produktu, oddziel niezgodny towar." ] },
      { heading: "Rozlicz zapakowaną paczkę przed przekazaniem", paragraphs: ["Zwykłe złożenie zaczyna się od opłaty szacunkowej. Po pakowaniu i pomiarze kwota może się zmienić, a przewoźnik może skorygować wagę rozliczeniową. Sprawdź dane, instrukcje i saldo zamiast uznawać pierwszy ekran za cenę końcową.", "Lista: zakończone QC, brak otwartego zwrotu, znana najstarsza data, zgodne trasy, brak rzeczy pakowanych osobno, konkretne instrukcje, właściwa ochrona, porównane dwa koszty, poprawny adres i deklaracja oraz rezerwa na zmianę pomiaru."], callout: { title: "Przed płatnością", text: "Zgodne towary, jasne pakowanie, ważna linia, poprawne dane, dwa plany i rezerwa." } },
    ],
  },
  es: {
    eyebrow: "CONSOLIDACIÓN DE PAQUETES JOYAGOO", title: "Consolidación Joyagoo: cómo combinar y embalar artículos del almacén", description: "Guía práctica para agrupar artículos, respetar rutas y embalajes separados, dar instrucciones y revisar antes del pago.",
    facts: [{ value: "Almacenado", label: "Estado previo a seleccionar el paquete" }, { value: "≥90 cm", label: "Umbral publicado de embalaje individual" }, { value: "2 planes", label: "Compara consolidado y dividido" }],
    sections: [
      { heading: "Empieza por el objetivo, no por la cantidad", paragraphs: ["Consolidar une varios productos aceptados del almacén en un envío internacional. La ayuda actual permite combinar compras de fechas distintas o enviarlas por lotes. Puede ahorrar cargos iniciales repetidos, pero la caja más grande no siempre es la opción más barata ni segura.", "Antes de marcar todo, valora ruta común, protección y volumen facturable. Ropa, baterías, cajas de zapatos o productos frágiles pueden necesitar grupos distintos. La pantalla activa del paquete decide las líneas y el precio."], callout: { title: "Regla de decisión", text: "Combina solo si el ahorro no empeora ruta, protección ni peso dimensional." } },
      { heading: "Crea primero una lista de artículos elegibles", paragraphs: ["Anota fecha de almacenamiento, peso, medidas, categoría, devolución, preferencia de embalaje y restricciones. Incluye solo artículos con QC resuelto; una llegada posterior no reinicia el plazo individual de almacenamiento.", "La ayuda indica que una restricción postal o la etiqueta de embalaje separado impiden enviar juntos. Cualquier lado de al menos 90 cm activa embalaje individual. Es una regla de plataforma revisada el 9 de agosto de 2026, no una ley universal del transportista." ] },
      { heading: "Compara consolidación con una división realista", paragraphs: ["El plan A reúne productos compatibles y el B separa por ruta, tamaño o protección. Compara tramos iniciales, cargos por paquete, forma de caja, materiales y líneas; no sumes solo pesos del almacén. La estimación orienta y la medición tras embalar factura.", "Con una tarifa hipotética de 20 USD por 500 g iniciales, 6 USD por cada tramo y 1 USD por paquete, 1, 1,5 y 2 kg separados sumarían 99 USD y 4,5 kg unidos 69 USD. No es una tarifa Joyagoo; volumen, ruta y protección pueden invertir el resultado."], callout: { title: "Calcula dos veces", text: "Aplica las mismas reglas actuales al paquete unido y a una división creíble." } },
      { heading: "Vincula cada instrucción a un riesgo", paragraphs: ["Quitar embalaje, reforzar y asegurar resuelven problemas distintos. Se puede desechar una caja de mensajería, mientras una caja de zapatos aporta estructura. El refuerzo protege pero añade peso y volumen; el seguro no evita el aplastamiento.", "Especifica por artículo: conservar caja de figura frágil, retirar solo bolsa exterior de prenda, no poner peso sobre una gorra. El estándar publicado contempla caja adecuada, orden, relleno, sellado y refuerzo; indica qué conservar y separar." ] },
      { heading: "Controla el peso volumétrico sin perder protección", paragraphs: ["Una caja consolidada puede seguir siendo voluminosa. Algunas líneas comparan peso real y dimensional. La ropa blanda rellena huecos; cajas rígidas y objetos largos fijan las medidas. El objetivo es reducir espacio inútil, no minimizar a cualquier coste.", "Conserva embalaje para objetos frágiles y accesorios necesarios; considera retirar cajas vacías tras cerrar la devolución; refuerza frente a golpes; divide si un producto impone caja o ruta. Si las medidas cambian la decisión, consulta el ensayo de embalaje actual en la cuenta." ] },
      { heading: "Revisa aduana, dirección y ruta", paragraphs: ["Joyagoo advierte que peso y cantidades repetidas pueden influir en la consideración personal o comercial, y que más de 10 kg puede recibir más atención en algunos países. No es un límite legal mundial. Consulta importación, declaración, restricciones e impuestos y declara con exactitud.", "Comprueba nombre, teléfono, código postal, región, calle, contenido, línea, límites, seguro y declaración. Guarda lista, instrucciones, ruta y estimación. Si una línea desaparece al añadir un artículo, aísla el producto incompatible." ] },
      { heading: "Concilia el paquete embalado antes de entregarlo", paragraphs: ["El envío normal comienza con una tarifa estimada. Tras embalar y medir, el importe puede cambiar y el transportista puede corregir el peso facturable. Revisa detalles, medidas, instrucciones y saldo; la primera pantalla no es el total final.", "Lista final: QC resuelto, sin devolución abierta, fecha más antigua conocida, rutas compatibles, artículos individuales excluidos, instrucciones precisas, protección adecuada, dos costes comparados, dirección y declaración correctas y margen para cambios."], callout: { title: "Antes de pagar", text: "Artículos compatibles, embalaje claro, ruta válida, datos exactos, dos planes y margen." } },
    ],
  },
  it: {
    eyebrow: "CONSOLIDAMENTO PACCHI JOYAGOO", title: "Consolidamento Joyagoo: come unire e imballare gli articoli in magazzino", description: "Guida pratica a gruppi, limiti di linea e imballaggio separato, istruzioni e controlli prima del pagamento.",
    facts: [{ value: "In deposito", label: "Stato prima della selezione" }, { value: "≥90 cm", label: "Soglia pubblicata per imballaggio singolo" }, { value: "2 piani", label: "Confronta unione e divisione" }],
    sections: [
      { heading: "Parti dall’obiettivo, non dal numero di articoli", paragraphs: ["Il consolidamento riunisce più prodotti accettati in un’unica spedizione internazionale. La guida attuale permette di unire acquisti di date diverse o spedirli a lotti. Può evitare costi iniziali ripetuti, ma il pacco più grande non è sempre economico o sicuro.", "Prima di selezionare tutto, valuta linea comune, protezione e volume fatturabile. Abiti, batterie, scatole da scarpe e fragili possono richiedere gruppi distinti. La schermata live determina linee e prezzo."], callout: { title: "Regola", text: "Unisci solo quando il risparmio non peggiora linea, protezione o peso volumetrico." } },
      { heading: "Crea prima l’elenco degli articoli compatibili", paragraphs: ["Registra data, peso, misure, categoria, decisione sul reso, preferenza e restrizioni. Inserisci solo articoli con QC risolto; un arrivo nuovo non azzera il tempo di deposito di quello vecchio.", "Una restrizione postale o l’etichetta di imballaggio separato impedisce l’invio comune. Un lato di almeno 90 cm attiva l’imballaggio individuale. È la regola di piattaforma verificata il 9 agosto 2026, non una legge universale." ] },
      { heading: "Confronta unione e divisione realistica", paragraphs: ["Il piano A unisce gli articoli compatibili, il B divide per linea, misura o protezione. Confronta scatti iniziali, costo per pacco, cartone, materiale e linee, non solo il peso. La stima orienta; il pacco finito viene misurato.", "Con un’ipotesi di 20 USD per i primi 500 g, 6 USD per ogni seguito e 1 USD a pacco, 1, 1,5 e 2 kg separati costerebbero 99 USD, 4,5 kg uniti 69 USD. Non è una tariffa Joyagoo; volume, linea e protezione possono cambiare l’esito."], callout: { title: "Calcola due volte", text: "Applica le stesse regole correnti al gruppo e a una divisione credibile." } },
      { heading: "Collega ogni istruzione a un rischio", paragraphs: ["Rimozione, rinforzo e assicurazione hanno scopi diversi. Si può togliere il cartone del corriere, mentre una scatola da scarpe dà struttura. Il rinforzo protegge ma aggiunge peso; l’assicurazione non evita lo schiacciamento.", "Specifica: conservare scatola della statuina, togliere solo busta esterna del capo, non mettere peso sul cappello. Lo standard include scatola adatta, ordine, riempimento, chiusura e rinforzo; indica cosa resta e cosa va separato." ] },
      { heading: "Riduci il volume senza eliminare la protezione utile", paragraphs: ["Un pacco unico può restare voluminoso. Alcune linee confrontano peso reale e volumetrico. Gli abiti morbidi riempiono vuoti; scatole rigide e oggetti lunghi determinano le misure. Riduci lo spazio inutile, non la sicurezza.", "Mantieni l’imballo per fragili e accessori importanti; valuta scatole vuote solo dopo il reso; rinforza per urti; dividi quando un articolo impone scatola o linea. Se le misure decidono, controlla il pre-imballaggio live." ] },
      { heading: "Controlla dogana, indirizzo e linea", paragraphs: ["Joyagoo avverte che peso e quantità uguali possono influire sulla valutazione personale o commerciale e che oltre 10 kg può attirare più controlli in alcuni paesi. Non è una soglia legale mondiale. Verifica importazione, dichiarazione, restrizioni e tasse.", "Controlla destinatario, telefono, CAP, regione, via, contenuto, linea, limiti, assicurazione e dichiarazione. Salva elenco, istruzioni, rotta e stima. Se una linea scompare con un articolo, separa quello incompatibile." ] },
      { heading: "Riconcilia il pacco finito prima dell’affidamento", paragraphs: ["L’invio normale parte da una tariffa stimata. Dopo imballaggio e misura l’importo può cambiare, e il vettore può correggere il peso. Verifica dettagli, misure, istruzioni e saldo: la prima schermata non è il totale definitivo.", "Lista: QC chiuso, nessun reso aperto, data più vecchia nota, linee compatibili, articoli singoli esclusi, istruzioni chiare, protezione adeguata, due costi confrontati, indirizzo e dichiarazione corretti, margine disponibile."], callout: { title: "Prima di pagare", text: "Prodotti compatibili, imballo chiaro, linea valida, dati corretti, due piani e margine." } },
    ],
  },
  fr: {
    eyebrow: "CONSOLIDATION DE COLIS JOYAGOO", title: "Consolidation Joyagoo : combiner et emballer les articles en entrepôt", description: "Guide pratique des groupes d’articles, restrictions de ligne, emballage séparé, consignes et vérification avant paiement.",
    facts: [{ value: "Stocké", label: "Statut avant sélection du colis" }, { value: "≥90 cm", label: "Seuil publié d’emballage individuel" }, { value: "2 plans", label: "Comparer groupé et séparé" }],
    sections: [
      { heading: "Commencer par l’objectif, pas le nombre d’articles", paragraphs: ["La consolidation réunit plusieurs produits acceptés en un envoi international. L’aide actuelle autorise les achats de dates différentes ensemble ou par lots. Cela peut éviter des tranches initiales répétées, mais le plus gros carton n’est pas forcément moins cher ni plus sûr.", "Avant de tout cocher, examinez ligne commune, protection et volume facturable. Vêtements, batterie, boîtes à chaussures et fragiles peuvent exiger des groupes distincts. L’écran actif du colis décide des lignes et prix."], callout: { title: "Règle", text: "Regroupez si l’économie ne dégrade ni ligne, ni protection, ni poids volumétrique." } },
      { heading: "Établir d’abord une liste admissible", paragraphs: ["Notez date de stockage, poids, dimensions, catégorie, retour, emballage et restrictions. Ajoutez seulement les articles dont le QC est résolu ; une arrivée récente ne réinitialise pas le délai des plus anciens.", "Une restriction postale ou l’étiquette d’emballage séparé empêche la soumission commune. Un côté d’au moins 90 cm déclenche l’emballage individuel. C’est la règle vérifiée le 9 août 2026, pas une loi universelle des transporteurs." ] },
      { heading: "Comparer colis groupé et séparation réaliste", paragraphs: ["Le plan A réunit les produits compatibles, le B sépare selon ligne, taille ou protection. Comparez tranches initiales, frais par colis, carton, matériaux et lignes, pas seulement le poids de stock. L’estimation classe les options ; le colis fini est mesuré.", "Avec un tarif purement hypothétique de 20 USD les 500 premiers g, 6 USD chaque tranche et 1 USD par colis, 1, 1,5 et 2 kg séparés donnent 99 USD, contre 69 USD pour 4,5 kg réunis. Ce n’est pas un tarif Joyagoo ; volume, ligne et protection peuvent inverser le résultat."], callout: { title: "Calculer deux fois", text: "Appliquez les mêmes règles actuelles au regroupement et à une séparation crédible." } },
      { heading: "Relier chaque consigne à un risque", paragraphs: ["Retrait d’emballage, renfort et assurance répondent à des risques différents. Un carton d’expédition peut partir, une boîte à chaussures apporte une structure. Le renfort protège mais augmente poids et volume ; l’assurance n’empêche pas l’écrasement.", "Précisez : conserver la boîte de la figurine, retirer seulement le sac extérieur du vêtement, ne pas placer de poids sur le chapeau. La norme prévoit carton adapté, ordre, remplissage, fermeture et renfort ; dites ce qui reste ou doit être séparé." ] },
      { heading: "Maîtriser le volume sans perdre la protection", paragraphs: ["Un carton consolidé peut rester volumineux. Certaines lignes comparent poids réel et volumétrique. Les vêtements comblent les vides ; boîtes rigides et objets longs fixent les dimensions. Réduisez le vide inutile, pas la sécurité.", "Gardez l’emballage des fragiles et accessoires utiles ; retirez une boîte vide après décision de retour ; renforcez face aux chocs ; séparez si un article impose carton ou ligne. Si les mesures changent le choix, consultez le pré-emballage affiché en direct." ] },
      { heading: "Vérifier douane, adresse et ligne", paragraphs: ["Joyagoo avertit que poids et quantités répétées peuvent influencer le caractère personnel ou commercial et que plus de 10 kg peut attirer davantage d’attention dans certains pays. Ce n’est pas un seuil légal mondial. Vérifiez importation, déclaration, restrictions et taxes.", "Contrôlez nom, téléphone, code postal, région, rue, contenu, ligne, limites, assurance et déclaration. Enregistrez liste, consignes, ligne et estimation. Si une ligne disparaît avec un article, isolez le produit incompatible." ] },
      { heading: "Rapprocher le colis emballé avant remise", paragraphs: ["La soumission ordinaire commence par un montant estimé. Après emballage et mesure, il peut changer ; le transporteur peut corriger le poids facturable. Vérifiez détails, mesures, consignes et solde plutôt que de considérer le premier écran comme final.", "Liste : QC clos, aucun retour ouvert, date la plus ancienne connue, lignes compatibles, articles séparés exclus, consignes précises, protection adaptée, deux coûts comparés, adresse et déclaration exactes, marge disponible."], callout: { title: "Avant paiement", text: "Articles compatibles, emballage clair, ligne valide, données exactes, deux plans et marge." } },
    ],
  },
  pt: {
    eyebrow: "CONSOLIDAÇÃO DE PACOTES JOYAGOO", title: "Consolidação Joyagoo: como combinar e embalar artigos do armazém", description: "Guia prático para agrupar artigos, respeitar rotas e embalagens separadas, instruir e verificar antes do pagamento.",
    facts: [{ value: "Armazenado", label: "Estado antes de selecionar" }, { value: "≥90 cm", label: "Limiar publicado de embalagem individual" }, { value: "2 planos", label: "Compare unido e dividido" }],
    sections: [
      { heading: "Comece pelo objetivo, não pela quantidade", paragraphs: ["A consolidação reúne vários produtos aceites num envio internacional. A ajuda atual permite juntar compras de datas diferentes ou enviá-las em lotes. Pode evitar cobranças iniciais repetidas, mas a maior caixa nem sempre é barata ou segura.", "Antes de marcar tudo, avalie rota comum, proteção e volume faturável. Roupa, bateria, caixas de sapatos e frágeis podem precisar de grupos distintos. O ecrã ativo do pacote decide linhas e preço."], callout: { title: "Regra", text: "Consolide apenas se a poupança não piorar rota, proteção ou peso volumétrico." } },
      { heading: "Crie primeiro uma lista elegível", paragraphs: ["Registe data, peso, dimensões, categoria, devolução, embalagem e restrições. Inclua só artigos com QC resolvido; uma chegada recente não reinicia o prazo de armazenamento dos anteriores.", "Uma restrição postal ou etiqueta de embalagem separada impede o envio conjunto. Um lado de pelo menos 90 cm aciona embalagem individual. É a regra da plataforma verificada em 9 de agosto de 2026, não lei universal." ] },
      { heading: "Compare consolidação e divisão realista", paragraphs: ["O plano A une produtos compatíveis, o B divide por rota, tamanho ou proteção. Compare escalões iniciais, taxas por pacote, caixa, materiais e linhas, não só os pesos. A estimativa orienta; o pacote final é medido.", "Numa tarifa hipotética de 20 USD pelos primeiros 500 g, 6 USD por incremento e 1 USD por pacote, 1, 1,5 e 2 kg separados dariam 99 USD e 4,5 kg juntos 69 USD. Não é preço Joyagoo; volume, rota ou proteção podem inverter o resultado."], callout: { title: "Calcule duas vezes", text: "Aplique as mesmas regras atuais ao conjunto e a uma divisão credível." } },
      { heading: "Associe cada instrução a um risco", paragraphs: ["Remoção, reforço e seguro resolvem riscos diferentes. A caixa do correio pode sair, enquanto a caixa de sapatos estrutura. Reforço protege mas aumenta peso e volume; seguro não evita esmagamento.", "Especifique: manter caixa da figura, retirar apenas saco exterior da roupa, não pôr peso no chapéu. O padrão prevê caixa adequada, ordem, enchimento, fecho e reforço; diga o que fica e o que deve ser separado." ] },
      { heading: "Controle o volume sem perder proteção", paragraphs: ["Uma caixa consolidada pode continuar volumosa. Algumas linhas comparam peso real e volumétrico. Roupa preenche espaços; caixas rígidas e objetos longos definem as medidas. Reduza vazio, não segurança.", "Mantenha embalagens de frágeis e acessórios; retire caixas vazias após fechar a devolução; reforce contra impactos; divida quando um artigo impõe caixa ou linha. Se as medidas mudarem a escolha, consulte o ensaio de embalagem atual." ] },
      { heading: "Verifique alfândega, endereço e rota", paragraphs: ["Joyagoo alerta que peso e quantidades iguais podem influenciar a classificação pessoal ou comercial, e mais de 10 kg pode receber maior atenção nalguns países. Não é limite legal mundial. Verifique importação, declaração, restrições e impostos.", "Confirme nome, telefone, código postal, região, rua, conteúdo, linha, limites, seguro e declaração. Guarde lista, instruções, rota e estimativa. Se uma linha desaparecer com um artigo, isole o incompatível." ] },
      { heading: "Reconcilie o pacote embalado antes da entrega", paragraphs: ["A submissão normal começa por um valor estimado. Depois de embalar e medir, pode mudar; a transportadora pode corrigir o peso. Verifique detalhes, medidas, instruções e saldo, em vez de tratar o primeiro ecrã como total final.", "Lista: QC fechado, sem devolução aberta, data mais antiga conhecida, rotas compatíveis, artigos separados excluídos, instruções claras, proteção adequada, dois custos comparados, endereço e declaração corretos, margem disponível."], callout: { title: "Antes de pagar", text: "Artigos compatíveis, embalagem clara, linha válida, dados exatos, dois planos e margem." } },
    ],
  },
  ro: {
    eyebrow: "CONSOLIDARE COLET JOYAGOO", title: "Consolidarea Joyagoo: cum combini și ambalezi articolele din depozit", description: "Ghid practic pentru grupare, restricții de rută și ambalare separată, instrucțiuni și verificarea înainte de plată.",
    facts: [{ value: "Depozitat", label: "Stare înainte de selecție" }, { value: "≥90 cm", label: "Prag publicat pentru ambalare individuală" }, { value: "2 planuri", label: "Compară gruparea și împărțirea" }],
    sections: [
      { heading: "Pornește de la scop, nu de la număr", paragraphs: ["Consolidarea reunește mai multe produse acceptate într-o expediere internațională. Ajutorul actual permite combinarea cumpărăturilor din date diferite sau expedierea în loturi. Poate evita taxe inițiale repetate, dar cutia cea mai mare nu este automat ieftină sau sigură.", "Înainte de a selecta tot, verifică ruta comună, protecția și volumul taxabil. Hainele, bateriile, cutiile de pantofi și fragilele pot cere grupuri distincte. Ecranul activ decide liniile și prețul."], callout: { title: "Regulă", text: "Combină numai dacă economia nu afectează ruta, protecția sau greutatea volumetrică." } },
      { heading: "Construiește mai întâi lista eligibilă", paragraphs: ["Notează data, greutatea, dimensiunile, categoria, returul, ambalarea și restricțiile. Include doar articole cu QC rezolvat; o sosire nouă nu resetează perioada celor vechi.", "O restricție poștală sau eticheta de ambalare separată împiedică trimiterea comună. O latură de cel puțin 90 cm declanșează ambalarea individuală. Este regula verificată la 9 august 2026, nu lege universală." ] },
      { heading: "Compară consolidarea cu o împărțire realistă", paragraphs: ["Planul A unește produsele compatibile, B le separă după rută, mărime sau protecție. Compară praguri inițiale, taxe, cutie, materiale și linii, nu doar greutățile. Estimarea ordonează opțiunile; coletul ambalat este măsurat.", "Cu un tarif ipotetic de 20 USD pentru primele 500 g, 6 USD pe interval și 1 USD pe colet, 1, 1,5 și 2 kg separate ar costa 99 USD, iar 4,5 kg împreună 69 USD. Nu este ofertă Joyagoo; volumul, ruta și protecția pot schimba rezultatul."], callout: { title: "Calculează de două ori", text: "Aplică aceleași reguli actuale grupului și unei împărțiri credibile." } },
      { heading: "Leagă fiecare instrucțiune de un risc", paragraphs: ["Îndepărtarea ambalajului, întărirea și asigurarea rezolvă riscuri diferite. Cutia de curier poate fi eliminată, cea de pantofi oferă structură. Întărirea protejează dar adaugă volum; asigurarea nu previne strivirea.", "Precizează: păstrează cutia figurinei, elimină doar punga exterioară, nu pune greutate pe pălărie. Standardul prevede cutie potrivită, ordine, umplere, sigilare și întărire; spune ce rămâne și ce se separă." ] },
      { heading: "Controlează volumul fără a pierde protecția", paragraphs: ["O cutie consolidată poate rămâne voluminoasă. Unele linii compară greutatea reală și volumetrică. Hainele umplu golurile; cutiile rigide și obiectele lungi stabilesc dimensiunile. Redu spațiul inutil, nu siguranța.", "Păstrează ambalajul pentru fragile și accesorii; elimină cutii goale după retur; întărește contra impactului; separă când un articol impune cutia sau ruta. Dacă dimensiunile decid, verifică preambalarea live." ] },
      { heading: "Verifică vama, adresa și ruta", paragraphs: ["Joyagoo avertizează că greutatea și cantitățile repetate pot influența clasificarea personală sau comercială și că peste 10 kg poate atrage atenție în unele țări. Nu este prag legal global. Verifică importul, declarația, restricțiile și taxele.", "Confirmă nume, telefon, cod, regiune, stradă, conținut, linie, limite, asigurare și declarație. Salvează lista, instrucțiunile, ruta și estimarea. Dacă o linie dispare după un articol, izolează produsul incompatibil." ] },
      { heading: "Reconciliază coletul ambalat înainte de predare", paragraphs: ["Trimiterea normală începe cu o taxă estimată. După ambalare și măsurare, suma se poate schimba, iar transportatorul poate corecta greutatea. Verifică detaliile, măsurile, instrucțiunile și soldul; primul ecran nu este totalul final.", "Listă: QC închis, fără retur, cea mai veche dată cunoscută, rute compatibile, articole separate excluse, instrucțiuni clare, protecție adecvată, două costuri comparate, adresă și declarație corecte, rezervă disponibilă."], callout: { title: "Înainte de plată", text: "Articole compatibile, ambalare clară, linie validă, date exacte, două planuri și rezervă." } },
    ],
  },
  sv: {
    eyebrow: "JOYAGOO PAKETKONSOLIDERING", title: "Joyagoo-konsolidering: kombinera och packa lagervaror rätt", description: "Praktisk guide till grupper, rutt- och separatpackningsgränser, instruktioner och kontroll före betalning.",
    facts: [{ value: "Lagrad", label: "Status före paketval" }, { value: "≥90 cm", label: "Publicerad gräns för separat packning" }, { value: "2 planer", label: "Jämför samlat och delat" }],
    sections: [
      { heading: "Börja med målet, inte antalet varor", paragraphs: ["Konsolidering samlar flera godkända lagervaror i en internationell försändelse. Aktuell hjälp tillåter köp från olika datum tillsammans eller i omgångar. Det kan undvika upprepade startavgifter, men största lådan är inte automatiskt billig eller säker.", "Kontrollera gemensam rutt, skydd och debiterad volym innan allt markeras. Kläder, batterier, skokartonger och ömtåligt kan behöva olika grupper. Den aktuella paketsidan avgör linjer och pris."], callout: { title: "Regel", text: "Samla bara om besparingen inte försämrar rutt, skydd eller volymvikt." } },
      { heading: "Bygg först en lista över kompatibla varor", paragraphs: ["Anteckna lagringsdatum, vikt, mått, kategori, retur, emballage och begränsningar. Ta bara med varor med löst QC; en ny ankomst nollställer inte äldre varors lagringstid.", "Postbegränsning eller märkning för separat packning hindrar gemensam inlämning. En sida på minst 90 cm utlöser individuell packning. Det är plattformsregeln verifierad 9 augusti 2026, inte allmän transportlag." ] },
      { heading: "Jämför samling med en realistisk uppdelning", paragraphs: ["Plan A samlar kompatibla varor, B delar efter rutt, storlek eller skydd. Jämför startsteg, paketavgifter, kartong, material och linjer, inte bara lagervikt. Uppskattningen rangordnar; det färdiga paketet mäts.", "Med en hypotetisk taxa på 20 USD för första 500 g, 6 USD per steg och 1 USD per paket skulle 1, 1,5 och 2 kg separat bli 99 USD och 4,5 kg samlat 69 USD. Det är inte Joyagoo-pris; volym, rutt och skydd kan ändra resultatet."], callout: { title: "Räkna två gånger", text: "Använd samma aktuella regler på samlat paket och trovärdig delning." } },
      { heading: "Knyt varje packinstruktion till en risk", paragraphs: ["Borttagning, förstärkning och försäkring löser olika risker. En fraktkartong kan tas bort medan en skokartong ger struktur. Förstärkning skyddar men ökar vikt och volym; försäkring hindrar inte krosskador.", "Ange per vara: behåll figurens låda, ta bara bort plaggets ytterpåse, lägg inget tungt på hatten. Standarden beskriver lämplig låda, ordning, fyllning, försegling och förstärkning; säg vad som ska behållas och separeras." ] },
      { heading: "Styr volymvikten utan att förlora skydd", paragraphs: ["En samlad låda kan ändå bli skrymmande. Vissa linjer jämför faktisk vikt och volymvikt. Mjuka kläder fyller hålrum; styva lådor och långa saker sätter måtten. Minska tomrum, inte säkerhet.", "Behåll emballage för ömtåligt och tillbehör; överväg tomma lådor efter returval; förstärk mot slag; dela när en vara styr kartong eller rutt. Om måtten avgör, kontrollera aktuell provpackning i kontot." ] },
      { heading: "Kontrollera tullprofil, adress och rutt", paragraphs: ["Joyagoo varnar att vikt och upprepade antal kan påverka personlig eller kommersiell bedömning och att över 10 kg kan få mer uppmärksamhet i vissa länder. Det är ingen global juridisk gräns. Kontrollera import, deklaration, förbud och skatt.", "Bekräfta namn, telefon, postnummer, region, gata, innehåll, linje, gränser, försäkring och deklaration. Spara lista, instruktioner, rutt och uppskattning. Om en linje försvinner med en vara, isolera den oförenliga produkten." ] },
      { heading: "Stäm av det packade paketet före överlämning", paragraphs: ["Normal inlämning börjar med uppskattad avgift. Efter packning och mätning kan beloppet ändras, och transportören kan korrigera vikten. Kontrollera detaljer, mått, instruktioner och saldo; första skärmen är inte slutpriset.", "Lista: QC klart, ingen öppen retur, äldsta datum känt, kompatibla rutter, separatvaror uteslutna, tydliga instruktioner, rätt skydd, två kostnader jämförda, korrekt adress och deklaration samt reserv."], callout: { title: "Före betalning", text: "Kompatibla varor, tydlig packning, giltig linje, korrekta data, två planer och reserv." } },
    ],
  },
};

export const parcelConsolidationArticles: Record<Locale, Article> = {
  en,
  ...localized,
};

export const parcelConsolidationSourceBodies: Record<Locale, string> = {
  en: "Reviewed on 9 August 2026 against Joyagoo Shopping Guidance, Shipping Products Purchased at Different Times, Why Combine Deliveries, Why Stored Goods Cannot Always Be Submitted Together, Why Some Goods Need Separate Shipping, the Parcel Packing Standard, and estimated-versus-actual billing guidance. Live route, packaging and destination rules remain decisive.",
  zh: "2026年8月9日核对Joyagoo购物指南、不同时期商品发货、合箱原因、不可共同提交、单独包装、包裹包装标准及预估与实际计费说明；实时线路、包装和目的地规则为准。",
  de: "Am 9. August 2026 mit Joyagoo-Hilfen zu Einkaufsablauf, zeitversetzten Käufen, Konsolidierung, unzulässigen Kombinationen, Einzelverpackung, Packstandard und Schätz-/Istabrechnung abgeglichen. Aktuelle Linien- und Zielregeln bleiben maßgeblich.",
  pl: "Sprawdzono 9 sierpnia 2026 r. z pomocą Joyagoo o zakupach z różnych dat, konsolidacji, niedozwolonych połączeniach, osobnym pakowaniu, standardzie paczek i rozliczeniu szacunkowym. Decydują bieżące zasady trasy i kraju.",
  es: "Revisado el 9 de agosto de 2026 con las guías de Joyagoo sobre compras en fechas distintas, consolidación, combinaciones no válidas, embalaje separado, estándar de paquete y facturación estimada. Mandan la ruta y el destino actuales.",
  it: "Verificato il 9 agosto 2026 con le guide Joyagoo su acquisti in date diverse, consolidamento, combinazioni non valide, imballaggio separato, standard pacchi e fatturazione stimata. Decidono linea e destinazione live.",
  fr: "Vérifié le 9 août 2026 avec les guides Joyagoo sur achats à dates différentes, consolidation, associations impossibles, emballage séparé, norme colis et facturation estimée. Les règles actuelles de ligne et destination priment.",
  pt: "Revisto em 9 de agosto de 2026 com as ajudas Joyagoo sobre compras em datas diferentes, consolidação, combinações inválidas, embalagem separada, padrão de pacote e faturação estimada. Prevalecem rota e destino atuais.",
  ro: "Verificat la 9 august 2026 cu ghidurile Joyagoo despre achiziții la date diferite, consolidare, combinații nepermise, ambalare separată, standardul coletului și facturarea estimată. Regulile live sunt decisive.",
  sv: "Granskad 9 augusti 2026 mot Joyagoo-hjälp om olika köpdatum, konsolidering, ogiltiga kombinationer, separat packning, paketstandard och uppskattad fakturering. Aktuella rutt- och destinationsregler gäller.",
};
