import type { Locale } from "./i18n";
import type { SeoArticleCopy } from "./seoArticles";

type SeoArticle = SeoArticleCopy["article"];

const en: SeoArticle = {
  eyebrow: "JOYAGOO SHIPPING LINE COMPARISON",
  title: "Joyagoo Shipping Line Comparison: Choose by Eligibility, Billing and Handoffs",
  description: "Compare the Joyagoo shipping lines actually available to a parcel by eligibility, billing basis, provider responsibility, tracking handoffs and evidence—not an old headline price.",
  facts: [
    { value: "Live list", label: "Compare only routes shown for this parcel" },
    { value: "5 fields", label: "Eligibility, billing, handling, tracking and remedy" },
    { value: "No winner", label: "The right line depends on the actual parcel" },
  ],
  sections: [
    {
      heading: "Start with the routes the parcel can actually use",
      paragraphs: [
        "A useful Joyagoo shipping line comparison begins after the stored items, destination and parcel plan are known. The official shopping guidance says the system screens the shipping lines available for the selected products. That means a route mentioned in an old guide, another buyer's parcel or a general estimator is not a candidate until it appears for the current parcel. Product restrictions, destination coverage, weight, dimensions and packaging can all change the displayed set. Save the date, destination, selected items and visible route list before comparing anything else.",
        "Treat an absent route as unavailable for this submission, not as a technical promise that it will never return. First check whether one product is causing the restriction, whether the address is complete and whether the parcel measurements are still estimates. Do not remove a restriction label or describe goods inaccurately to make a preferred line appear. If separating an item changes the route set, compare the new parcel as a separate scenario with its own packaging and repeated charges rather than pretending it is the same shipment.",
        "This first gate prevents false bargains. A low historical price has no value when the real product mix cannot enter that line. It also keeps this framework separate from a route ranking: the comparison does not crown a universal winner. It records which current options can accept the parcel and which facts would make each one unsuitable before price or delivery estimates receive attention.",
      ],
    },
    {
      heading: "Build one evidence row for every live option",
      paragraphs: [
        "Create a row for each route currently displayed and capture the exact line name, quote time, destination, declared parcel contents, estimated or packed weight, dimensions and visible charge. Add the billing unit, first-weight and additional-weight steps when the interface shows them. Never reduce the record to a single price-per-kilogram number: stepped charges, minimum billable units, rounding and dimensional rules can make that shortcut misleading, especially near a threshold.",
        "Next record eligibility notes, maximum weight or size, excluded product types, packaging conditions, tracking description, insurance choice, estimated delivery range and the party providing the line. Use 'not displayed' when a field is absent. Zero means the interface explicitly shows no charge; blank means the evidence is missing. Keep screenshots or exported details for decisive fields, but retain the route name and text as searchable notes because a screenshot alone is difficult to compare later.",
        "Use the same parcel facts across every row. If one quote uses seller weights, another uses warehouse measurements and a third uses rehearsal-packed dimensions, the totals are not directly comparable. Label the measurement stage and either normalize the input or keep scenarios separate. A clean table makes uncertainty visible instead of hiding it behind precise-looking totals.",
      ],
    },
    {
      heading: "Compare the billing rule before the displayed total",
      paragraphs: [
        "Joyagoo's published weighing table divides services into postal, express and exclusive-route categories, while individual lines can apply different actual-weight, volumetric-weight, threshold and packaging-bag rules. The table is useful evidence that route names cannot share one universal divisor or trigger. It is not a permanent quote sheet. Copy the current rule attached to each selectable line and recalculate only with the dimensions and rounding method shown for that route on the decision date.",
        "For each option, record actual weight, volumetric weight when applicable, the greater figure used for billing and the next charging threshold. Then run a sensitivity check: what happens if final packing adds a small amount of weight or one outer dimension grows? The purpose is not to predict the warehouse perfectly. It is to identify a route whose apparent advantage disappears after a plausible packing change. Bulky shoes, rigid boxes and puffer garments deserve more dimensional margin than compact dense items.",
        "When measurements could change the ranking, rehearsal packing can improve the evidence before final submission. Current official guidance describes it as packing selected items and updating weight and freight for the chosen line. It still cannot guarantee that a logistics provider will never remeasure the parcel. Keep the initial estimate, rehearsal result, warehouse result and any provider adjustment as separate events rather than overwriting the first number.",
      ],
    },
    {
      heading: "Separate speed estimates from the handoff chain",
      paragraphs: [
        "The official logistics overview maps a parcel through warehouse packing, collection, security screening, flight arrangement, transport, airport processing, customs clearance, local courier and delivery. A route's displayed delivery range covers a chain with several responsible parties, not one continuous Joyagoo-controlled movement. Compare the stated range as a planning reference and record when its clock begins. Do not turn it into a guaranteed arrival date or compare it with an anecdote that starts at product purchase rather than parcel dispatch.",
        "Ask what tracking evidence should appear at each handoff. A collection event supports logistics-provider receipt; an export or flight event supports movement out of the origin network; customs events show a border process; a local-carrier number supports the last-mile transfer. The absence of one scan does not by itself prove loss, but it tells you which party and reference number to check. Save both the Joyagoo parcel number and any carrier identifiers shown after dispatch.",
        "A faster-looking line may be less suitable when the parcel has an inflexible deadline and the handoff record is unclear. Conversely, a wider published range is not automatically poor value when eligibility, tracking and remedy terms fit the shipment. Compare evidence quality and deadline tolerance alongside the estimate. Leave buffer for weather, customs and provider errors because the official overview explicitly identifies those sources of delay.",
      ],
    },
    {
      heading: "Identify who operates the line and who handles a problem",
      paragraphs: [
        "Joyagoo's logistics overview distinguishes self-operated lines provided with business partners from other lines provided by logistics companies. The page describes different after-sales paths: issues on partner lines are handled under Joyagoo's stated standards, while other-line compensation requests depend on the relevant provider's policy. Record that relationship as a comparison field. A familiar carrier name does not automatically tell you which contract, exclusions or remedy applies to the parcel.",
        "Read the current insurance and compensation terms before payment and keep them separate from the route price. Note covered events, exclusions, declared-value requirements, evidence, reporting clock and any cap shown for the selected line. Insurance is not a quality guarantee, customs guarantee or promise of immediate reimbursement. If the relevant terms are not visible, mark the remedy field unresolved and ask support before choosing when that uncertainty changes the decision.",
        "Match documentation effort to consequence. For a replaceable low-value soft-goods parcel, basic tracking may be enough. For fragile, time-sensitive or difficult-to-replace contents, the buyer may value clearer handoffs, parcel photos, suitable packaging and a documented claim path more than the smallest displayed total. This is a decision preference, not proof that the more expensive route is safer.",
      ],
    },
    {
      heading: "Use a weighted score without manufacturing certainty",
      paragraphs: [
        "Set weights before reading the totals. One buyer might assign 35 points to eligibility and restrictions, 25 to billable-weight stability, 20 to tracking and handoffs, 15 to remedy evidence and only 5 to the delivery estimate. Another parcel with a flexible deadline and low consequence may place more weight on the current charge. Pre-setting the weights prevents the cheapest visible number from quietly becoming the answer to every question.",
        "Score only fields supported by current evidence and show unresolved items separately. For example, Route A may pass eligibility, have a stable actual-weight basis and clear tracking but a higher displayed charge. Route B may be cheaper while its final dimensional result and claim terms remain unclear. Do not award Route B optimistic points. Either obtain the missing evidence, run a packed scenario or accept the uncertainty explicitly. A blank should never receive the same score as a confirmed favourable term.",
        "Run one break test after scoring. Increase weight or one dimension to the next plausible packed value, remove a route that rejects one item, or assume the delivery estimate uses its slower end. If the chosen line changes immediately, the decision is fragile and deserves more evidence. If it remains suitable across reasonable changes, the comparison is more robust without claiming a guaranteed outcome.",
      ],
    },
    {
      heading: "Freeze the decision record at parcel payment",
      paragraphs: [
        "Immediately before payment, refresh the live parcel page and confirm that the selected items, address country, packing request, measured stage and candidate routes have not changed. Recheck the chosen line's current name, charge, billing rule, restriction notes, estimate, tracking description, insurance selection and remedy terms. If any decisive field differs from the comparison, update the table and make the choice again instead of relying on an older screenshot.",
        "After packing and dispatch, append the final weight, dimensions, billable basis, payment, parcel status, tracking identifiers and first carrier event. Do not edit the original estimate into the final number. The difference explains whether packaging, measurement, rounding or a provider adjustment changed the result and gives the next parcel a better starting point. Keep personal address, phone and account identifiers out of any public version of the record.",
        "The defensible conclusion is narrow: this line best matched the parcel's verified eligibility, billing exposure, handoff needs and remedy evidence at the recorded time. It is not the best Joyagoo line for every buyer and it does not guarantee price, speed, customs treatment or delivery. Rebuilding the short table from live fields is slower than choosing the first number, but it produces a decision that can be checked and explained.",
      ],
    },
  ],
};

type NonEnglish = Exclude<Locale, "en">;
const make = (eyebrow:string,title:string,description:string,facts:SeoArticle["facts"],headings:string[],paragraphs:string[][]):SeoArticle => ({eyebrow,title,description,facts,sections:headings.map((heading,index)=>({heading,paragraphs:paragraphs[index]}))});

const translated: Record<NonEnglish, SeoArticle> = {
  zh: make("JOYAGOO运输线路比较","Joyagoo运输线路比较：按资格、计费和交接选择","只比较当前包裹实际显示的线路，核对资格、计费方式、承运关系、追踪交接和处理证据。",[{value:"实时列表",label:"只比较本包裹可选线路"},{value:"五项字段",label:"资格、计费、处理、追踪和补救"},{value:"没有通用赢家",label:"选择取决于真实包裹"}], ["从包裹真正可用的线路开始","为每个实时选项建立证据行","先比较计费规则再看总价","把时效参考与交接链分开","确认谁运营线路、谁处理问题","用权重评分但不制造确定性","付款时冻结决策记录"], [
    ["商品、目的地和包裹方案确定后才开始比较。官方指南说明系统会按所选商品筛出可用线路；旧攻略、他人包裹或估算器中的线路只有在当前页面出现后才算候选。保存日期、目的地、商品和实时列表。","线路缺失只说明本次提交不可选，不代表永久取消。检查限制商品、地址和测量阶段；不要误报商品来换取线路。拆出商品后应建立新的包裹方案，并计入重复包装和费用。","这样可先排除虚假的低价：不能承运的历史价格没有决策价值。本文不排名通用最佳线路，只记录当前资格和淘汰条件。"],
    ["每条线路记录准确名称、报价时间、目的地、内容、重量阶段、尺寸和显示费用；如界面提供，再记首重、续重、单位与进位。不要只算每公斤，因为门槛和取整会误导。","补充限制、尺寸重量上限、包装条件、追踪、保险、时效参考和线路提供方。未显示就写‘未显示’，不能把空白当零。截图保存关键字段，同时保留可搜索文字。","所有线路使用同一包裹输入。卖家估重、仓库实测和预演尺寸不能直接混比；标明阶段，无法统一时就分开情景。"],
    ["官方称邮政、快递和专线的称重规则不同，单条线路还可能使用不同实重、体积重、门槛和包装袋条件。复制当日可选线路的实时规则，不使用永久通用除数。","记录实重、适用的体积重、计费取值和下一门槛，并测试包装稍增重或某边变长后的结果。鞋盒、硬箱和蓬松衣物需要更大的尺寸余量。","排名可能因测量改变时，预演包装可提高证据，但不能保证承运人不复测。分别保存初估、预演、仓库和物流调整。"],
    ["官方流程包含打包、揽收、安检、航班、运输、机场、清关、本地快递和派送。时效是多方交接的参考，不是Joyagoo全程控制的保证，也不能与从商品购买开始计算的个案直接比较。","记录各阶段应出现的扫描、包裹号和承运编号。缺少扫描不等于丢失，但能指出应向哪一方查询。","把追踪证据质量和截止日期容忍度与时效一起比较。天气、清关和物流错误都可能造成官方所述的延误。"],
    ["官方区分合作伙伴线路与其他物流商线路，并说明售后路径不同。把运营关系单独记录，熟悉的承运商名称并不能证明具体合同和赔付规则。","付款前读取保险与赔付条件，记录覆盖、排除、申报、证据、时限和上限。看不到就标为未解决，不能把保险写成海关或赔付保证。","低风险软货可能只需基础追踪；易碎或难替换商品可能更重视交接、包裹照、包装和索赔路径。这是偏好，不证明贵线路更安全。"],
    ["看总价前先设权重，例如资格35、计费稳定25、追踪20、补救15、时效5。另一包裹可调整权重，但应避免最低价自动成为答案。","只给有证据的字段打分，缺失项单列。便宜但体积结果和索赔条件未知的线路不能得到乐观分数，应补证、预演或明确接受不确定性。","做一次破坏测试：增加合理重量或尺寸、移除不合资格线路，或采用时效区间较慢端。选择立刻改变时，说明决策脆弱。"],
    ["付款前刷新页面，重新核对商品、国家、包装、测量阶段、线路名称、费用、计费、限制、时效、追踪、保险和补救。关键字段改变就更新表格并重选。","打包发出后追加最终重量尺寸、计费依据、付款、状态、追踪号和首次扫描，不覆盖原估算。差异能说明包装、测量、取整或承运调整。公开记录必须删除个人资料。","结论只能说该线路在记录时间最符合本包裹的资格、计费、交接与补救需求；不声称全局最佳，也不保证价格、时效、海关或送达。"]
  ]),
  de: make("JOYAGOO-VERSANDLINIENVERGLEICH","Joyagoo-Versandlinien vergleichen: Eignung, Abrechnung und Übergaben","Vergleiche nur live verfügbare Linien nach Eignung, Abrechnung, Betreiber, Tracking und Nachweisen.",[{value:"Live-Liste",label:"Nur Linien dieses Pakets"},{value:"5 Felder",label:"Eignung, Abrechnung, Ablauf, Tracking, Abhilfe"},{value:"Kein Sieger",label:"Das echte Paket entscheidet"}], ["Mit wirklich verfügbaren Linien beginnen","Für jede Option eine Beweiszeile anlegen","Abrechnungsregel vor Gesamtpreis prüfen","Zeitschätzung und Übergaben trennen","Betreiber und Problemweg bestimmen","Gewichten ohne Gewissheit zu erfinden","Datensatz bei Zahlung einfrieren"], [
    ["Vergleiche erst nach Festlegung von Inhalt, Ziel und Paketplan. Laut offizieller Anleitung filtert das System verfügbare Linien nach den Produkten; alte Listen zählen erst, wenn die Linie live erscheint.","Eine fehlende Linie ist für diese Einreichung nicht verfügbar, aber nicht zwingend dauerhaft beendet. Prüfe Artikelbeschränkung, Adresse und Messstand; beschreibe Ware nie falsch.","So verschwindet der falsche Vorteil historischer Preise. Das Modell kürt keinen allgemeinen Gewinner, sondern dokumentiert Eignung und Ausschlussgründe."],
    ["Notiere je Linie Name, Zeit, Ziel, Inhalt, Messstand, Maße, Preis sowie sichtbare Gewichts- und Rundungsstufen. Preis pro Kilo allein kann täuschen.","Ergänze Grenzen, Verpackungsbedingungen, Tracking, Versicherung, Zeitraum und Anbieter. Fehlende Felder heißen ‚nicht angezeigt‘, nicht null; sichere Text und entscheidende Ansichten.","Nutze identische Paketdaten. Verkäufergewicht, Lagermaß und Probeverpackung sind verschiedene Szenarien und müssen gekennzeichnet werden."],
    ["Offizielle Tabellen zeigen unterschiedliche Regeln für Post, Express und Sonderlinien. Übernimm die aktuelle Regel der auswählbaren Linie statt eines universellen Divisors.","Berechne tatsächliches und gegebenenfalls Volumengewicht, Abrechnungswert und nächste Stufe. Teste etwas zusätzliches Gewicht oder ein größeres Außenmaß.","Probeverpackung verbessert den Vergleich, garantiert aber keine spätere Messung. Bewahre Schätzung, Probe-, Lager- und Anbieterwert getrennt auf."],
    ["Die offizielle Kette umfasst Packen, Abholung, Kontrolle, Flug, Transport, Flughafen, Zoll, lokalen Kurier und Zustellung. Der Zeitraum ist Referenz, keine Garantie.","Ordne erwartete Scans den Übergaben zu und speichere Paket- sowie Carrier-Nummern. Ein fehlender Scan beweist keinen Verlust, zeigt aber den Prüfpunkt.","Bewerte Trackingqualität und Termintoleranz neben der Spanne. Wetter, Zoll und Anbieterfehler benötigen Puffer."],
    ["Joyagoo unterscheidet Partnerlinien von anderen Logistikanbietern und beschreibt unterschiedliche Abhilfewege. Erfasse diese Beziehung ausdrücklich.","Prüfe Deckung, Ausschlüsse, Erklärung, Nachweise, Frist und Grenze der Versicherung. Ein ungelöstes Feld bleibt ungelöst; Versicherung garantiert weder Zoll noch Erstattung.","Weiche Ersatzware braucht vielleicht nur Basistracking; fragile oder schwer ersetzbare Inhalte rechtfertigen mehr Nachweise. Teurer bedeutet nicht automatisch sicherer."],
    ["Lege Gewichte vor dem Preisblick fest, etwa Eignung 35, Abrechnung 25, Tracking 20, Abhilfe 15 und Zeitraum 5. Passe sie an das Paket an.","Bewerte nur belegte Felder. Eine billige Linie mit unbekanntem Volumenergebnis oder Anspruchsweg erhält keine optimistischen Punkte.","Teste eine plausible Gewichts-, Größen- oder Eignungsänderung. Wechselt die Wahl sofort, fehlen robuste Belege."],
    ["Aktualisiere vor Zahlung Inhalt, Land, Packauftrag, Messstand, Linie, Preis, Regel, Einschränkung, Zeitraum, Tracking, Versicherung und Abhilfe.","Füge nach Versand Endgewicht, Maße, Abrechnung, Zahlung, Status und erste Scans hinzu, ohne die Schätzung zu überschreiben. Öffentliche Notizen enthalten keine Personendaten.","Die Aussage bleibt eng: Diese Linie passte zu diesem Zeitpunkt am besten zu diesem Paket. Sie garantiert weder Preis, Zeit, Zoll noch Zustellung."]
  ]),
  pl: make("PORÓWNANIE LINII JOYAGOO","Porównanie linii Joyagoo: kwalifikacja, rozliczenie i przekazania","Porównuj tylko bieżące linie według kwalifikacji, rozliczenia, operatora, śledzenia i dowodów.",[{value:"Lista live",label:"Tylko linie tej paczki"},{value:"5 pól",label:"Kwalifikacja, rozliczenie, obsługa, tracking, roszczenie"},{value:"Brak zwycięzcy",label:"Decyduje konkretna paczka"}], ["Zacznij od dostępnych linii","Zbuduj wiersz dowodowy","Sprawdź regułę rozliczenia","Oddziel czas od przekazań","Ustal operatora i pomoc","Stosuj wagi bez gwarancji","Zamroź zapis przy płatności"], [
    ["Porównuj po ustaleniu rzeczy, kraju i planu paczki. Oficjalny przewodnik mówi, że system filtruje linie według produktów; stara lista liczy się dopiero po pojawieniu się w koncie.","Brak oznacza niedostępność dla tej paczki, nie wieczne usunięcie. Sprawdź ograniczenia, adres i etap pomiaru; nie opisuj towaru nieprawdziwie.","Historyczna niska cena bez kwalifikacji nie ma wartości. Ramy nie wybierają uniwersalnie najlepszej linii."],
    ["Zapisz nazwę, czas, kraj, zawartość, etap wagi, wymiary, cenę oraz widoczne progi i zaokrąglenia. Jedna cena za kilogram bywa myląca.","Dodaj limity, opakowanie, tracking, ubezpieczenie, zakres czasu i operatora. Brak pola to ‚nie pokazano‘, nie zero; zachowaj tekst i kluczowe obrazy.","Porównuj te same dane. Waga sprzedawcy, magazynu i próbnego pakowania to osobne scenariusze."],
    ["Oficjalna tabela pokazuje odmienne reguły dla poczty, kuriera i linii specjalnych. Kopiuj aktualną regułę wybranej linii, nie uniwersalny dzielnik.","Zapisz wagę rzeczywistą, objętościową, rozliczeniową i kolejny próg; sprawdź wpływ małego wzrostu wagi lub wymiaru.","Próbne pakowanie zwiększa wiedzę, lecz nie wyklucza ponownego pomiaru. Zachowaj wszystkie etapy oddzielnie."],
    ["Łańcuch obejmuje pakowanie, odbiór, kontrolę, lot, transport, lotnisko, odprawę, kuriera lokalnego i dostawę. Zakres czasu jest odniesieniem, nie gwarancją.","Przypisz skany do przekazań i zapisz numery Joyagoo oraz przewoźnika. Brak skanu nie dowodzi zagubienia.","Porównuj jakość śledzenia i tolerancję terminu. Pogoda, odprawa i błędy operatora wymagają zapasu."],
    ["Joyagoo rozróżnia linie partnerskie i innych operatorów oraz różne drogi reklamacji. Zapisz relację, nie zakładaj jej z samej nazwy przewoźnika.","Sprawdź zakres, wyłączenia, deklarację, dowody, termin i limit ubezpieczenia. Ubezpieczenie nie gwarantuje odprawy ani wypłaty.","Przy towarze kruchym lub trudnym do zastąpienia przejrzyste przekazania i roszczenie mogą być ważniejsze od najniższej ceny; droższe nie znaczy bezpieczne."],
    ["Ustal wagi przed ceną: kwalifikacja, stabilność rozliczenia, tracking, pomoc i czas. Zmień je świadomie dla konkretnej paczki.","Punktuj tylko potwierdzone pola. Tania linia z nieznanym wynikiem objętościowym nie dostaje korzystnych punktów.","Zwiększ realistycznie wagę lub wymiar albo usuń linię niezgodną. Natychmiastowa zmiana wyboru oznacza kruchą decyzję."],
    ["Przed płatnością odśwież zawartość, kraj, pakowanie, pomiar, linię, cenę, regułę, ograniczenia, czas, tracking, ubezpieczenie i pomoc.","Po wysyłce dopisz końcowe dane i skany, nie nadpisując szacunku. W publicznym zapisie usuń adres i identyfikatory.","Wniosek dotyczy tylko tej paczki i chwili. Nie gwarantuje ceny, czasu, odprawy ani dostawy."]
  ]),
  es: make("COMPARACIÓN DE LÍNEAS JOYAGOO","Comparar líneas Joyagoo: elegibilidad, facturación y traspasos","Compara solo líneas activas por elegibilidad, facturación, operador, seguimiento y pruebas.",[{value:"Lista en vivo",label:"Solo rutas de este paquete"},{value:"5 campos",label:"Elegibilidad, cobro, gestión, seguimiento y recurso"},{value:"Sin ganador",label:"Decide el paquete real"}], ["Empieza por las líneas realmente disponibles","Crea una fila de pruebas por opción","Compara la regla antes del total","Separa plazo y cadena de traspasos","Identifica operador y solución","Pondera sin fabricar certeza","Congela el registro al pagar"], [
    ["Compara después de fijar artículos, destino y plan. La guía oficial dice que el sistema filtra las líneas según los productos; una ruta antigua no es candidata hasta aparecer en el paquete actual.","Una ruta ausente no está disponible para este envío, pero no tiene por qué haber desaparecido para siempre. Revisa restricciones, dirección y etapa de medición; nunca falsees la mercancía.","Así se elimina el falso ahorro de un precio histórico no elegible. El marco no declara una mejor línea universal."],
    ["Anota nombre, hora, destino, contenido, etapa del peso, dimensiones, precio y escalones visibles. Un precio por kilo puede ocultar mínimos y redondeos.","Añade límites, embalaje, seguimiento, seguro, plazo y proveedor. Un campo ausente es ‘no mostrado’, no cero; conserva texto y capturas decisivas.","Usa los mismos datos para todas. Peso del vendedor, almacén y ensayo son escenarios diferentes."],
    ["La tabla oficial muestra reglas distintas para postal, exprés y rutas exclusivas. Copia la regla vigente de cada línea seleccionable, no un divisor universal.","Registra peso real, volumétrico, facturable y próximo umbral; prueba un pequeño aumento de peso o dimensión.","El embalaje de ensayo mejora la evidencia pero no impide una nueva medición. Guarda estimación, ensayo, almacén y ajuste por separado."],
    ["La cadena oficial incluye embalaje, recogida, seguridad, vuelo, transporte, aeropuerto, aduana, mensajero local y entrega. El plazo es una referencia, no garantía.","Relaciona los escaneos con cada traspaso y guarda números de paquete y transportista. Falta de escaneo no prueba pérdida.","Compara claridad del seguimiento y tolerancia al plazo. Deja margen para clima, aduana y errores logísticos."],
    ["Joyagoo distingue líneas asociadas y otros proveedores con vías de posventa distintas. Registra esa relación; el nombre del transportista no define el contrato.","Lee cobertura, exclusiones, declaración, pruebas, plazo y límite del seguro. Un campo no visible queda sin resolver; el seguro no garantiza aduana ni pago.","Para bienes frágiles o difíciles de sustituir, traspasos claros y una vía documentada pueden pesar más que el precio mínimo, sin probar mayor seguridad."],
    ["Define pesos antes de mirar totales: elegibilidad, estabilidad de cobro, seguimiento, recurso y plazo. Ajústalos al paquete conscientemente.","Puntúa solo hechos confirmados. Una ruta barata con peso dimensional o reclamación desconocidos no recibe puntos optimistas.","Prueba un aumento plausible o elimina una ruta incompatible. Si la elección cambia enseguida, necesita más evidencia."],
    ["Antes de pagar, actualiza artículos, país, embalaje, etapa, línea, coste, regla, límites, plazo, tracking, seguro y recurso.","Tras el envío añade medidas finales, cobro, estado, identificadores y primer escaneo sin borrar la estimación. Elimina datos personales de toda versión pública.","La conclusión solo dice qué línea encajó mejor con ese paquete y fecha; no garantiza coste, rapidez, aduana ni entrega."]
  ]),
  it: make("CONFRONTO LINEE JOYAGOO","Confronto linee Joyagoo: idoneità, addebito e passaggi","Confronta solo le linee visibili per idoneità, addebito, operatore, tracking e prove.",[{value:"Lista live",label:"Solo linee del pacco"},{value:"5 campi",label:"Idoneità, addebito, gestione, tracking, rimedio"},{value:"Nessun vincitore",label:"Decide il pacco reale"}], ["Parti dalle linee davvero disponibili","Crea una riga di prova","Controlla prima la regola di addebito","Separa stima e passaggi","Identifica operatore e rimedio","Usa pesi senza certezze false","Blocca il record al pagamento"], [
    ["Confronta dopo aver definito articoli, destinazione e piano. La guida ufficiale dice che il sistema filtra le linee in base ai prodotti; una vecchia rotta conta solo se appare ora.","Una linea assente non è disponibile per questo invio, non necessariamente per sempre. Controlla restrizioni, indirizzo e misure; non descrivere mai la merce in modo falso.","Un vecchio prezzo basso senza idoneità non serve. Il metodo non proclama una linea migliore per tutti."],
    ["Registra nome, ora, paese, contenuto, fase del peso, dimensioni, prezzo e scaglioni visibili. Il solo prezzo al chilo può nascondere minimi e arrotondamenti.","Aggiungi limiti, imballaggio, tracking, assicurazione, intervallo e fornitore. Un campo mancante è ‘non mostrato’, non zero; conserva testo e schermate decisive.","Usa gli stessi dati. Peso del venditore, magazzino e prova sono scenari separati."],
    ["La tabella ufficiale mostra regole diverse per posta, espresso e linee esclusive. Copia la regola corrente, non un divisore universale.","Annota peso reale, volumetrico, fatturabile e prossima soglia; prova un piccolo aumento di peso o misura.","La prova d'imballaggio migliora le prove ma non impedisce una nuova misurazione. Conserva ogni fase separata."],
    ["La catena include imballaggio, ritiro, sicurezza, volo, trasporto, aeroporto, dogana, corriere locale e consegna. Il tempo è indicativo, non garantito.","Associa le scansioni ai passaggi e salva numeri Joyagoo e vettore. Una scansione mancante non prova la perdita.","Confronta qualità del tracking e tolleranza della scadenza, lasciando margine per meteo, dogana ed errori."],
    ["Joyagoo distingue linee partner e altri vettori con percorsi post-vendita diversi. Registra il rapporto e non dedurlo solo dal nome.","Verifica copertura, esclusioni, dichiarazione, prove, termine e limite assicurativo. L'assicurazione non garantisce dogana o rimborso.","Per contenuti fragili o difficili da sostituire, passaggi chiari e rimedi documentati possono valere più del totale minimo senza provare maggiore sicurezza."],
    ["Imposta i pesi prima del prezzo: idoneità, stabilità di addebito, tracking, rimedio e tempo. Adattali consapevolmente.","Valuta solo campi provati. Una linea economica con volume o reclamo incerti non riceve punti ottimistici.","Aumenta plausibilmente peso o misura o elimina una linea incompatibile. Un cambio immediato indica decisione fragile."],
    ["Prima del pagamento aggiorna contenuto, paese, imballaggio, fase, linea, prezzo, regola, limiti, tempo, tracking, assicurazione e rimedio.","Dopo la spedizione aggiungi dati finali e scansioni senza sovrascrivere la stima. Rimuovi dati personali dalla versione pubblica.","La conclusione vale solo per quel pacco e momento; non garantisce prezzo, velocità, dogana o consegna."]
  ]),
  fr: make("COMPARAISON DES LIGNES JOYAGOO","Comparer les lignes Joyagoo : admissibilité, facturation et relais","Comparez seulement les lignes affichées selon admissibilité, facturation, opérateur, suivi et preuves.",[{value:"Liste active",label:"Seulement les lignes de ce colis"},{value:"5 champs",label:"Admissibilité, facturation, gestion, suivi, recours"},{value:"Pas de gagnant",label:"Le colis réel décide"}], ["Commencer par les lignes réellement disponibles","Créer une ligne de preuve par option","Comparer la règle avant le total","Séparer délai et chaîne de relais","Identifier opérateur et recours","Pondérer sans fabriquer de certitude","Figer le dossier au paiement"], [
    ["Comparez après avoir fixé articles, destination et plan. Le guide officiel indique que le système filtre les lignes selon les produits ; une ancienne route ne compte que si elle apparaît maintenant.","Une ligne absente est indisponible pour cet envoi, pas forcément supprimée. Vérifiez restrictions, adresse et stade de mesure ; ne décrivez jamais faussement la marchandise.","Un ancien prix bas sans admissibilité n'a aucune valeur. Ce cadre ne désigne pas une meilleure ligne universelle."],
    ["Notez nom, heure, destination, contenu, stade du poids, dimensions, prix et paliers visibles. Un prix au kilo peut masquer minimums et arrondis.","Ajoutez limites, emballage, suivi, assurance, délai et fournisseur. Un champ absent signifie ‘non affiché’, pas zéro ; gardez texte et captures décisives.","Utilisez les mêmes données. Poids vendeur, entrepôt et répétition sont des scénarios séparés."],
    ["Le tableau officiel montre des règles différentes pour postal, express et lignes exclusives. Copiez la règle actuelle de chaque ligne, sans diviseur universel.","Inscrivez poids réel, volumétrique, facturable et prochain seuil ; testez une faible hausse de poids ou dimension.","La répétition améliore la preuve sans empêcher une nouvelle mesure. Conservez estimation, répétition, entrepôt et ajustement séparément."],
    ["La chaîne officielle couvre emballage, collecte, sécurité, vol, transport, aéroport, douane, coursier local et livraison. Le délai est une référence, non une garantie.","Associez les scans aux relais et gardez les numéros Joyagoo et transporteur. Un scan absent ne prouve pas la perte.","Comparez qualité du suivi et tolérance de date, avec marge pour météo, douane et erreurs logistiques."],
    ["Joyagoo distingue lignes partenaires et autres prestataires avec des recours différents. Notez cette relation au lieu de la déduire du seul nom.","Vérifiez couverture, exclusions, déclaration, preuves, délai et plafond d'assurance. L'assurance ne garantit ni douane ni paiement.","Pour des biens fragiles ou difficiles à remplacer, relais clairs et recours documenté peuvent compter plus que le total minimal, sans prouver plus de sécurité."],
    ["Fixez les pondérations avant les totaux : admissibilité, stabilité de facturation, suivi, recours et délai. Adaptez-les au colis.","Ne notez que les champs prouvés. Une ligne bon marché avec volume ou recours inconnus ne reçoit pas de points optimistes.","Testez une hausse plausible ou retirez une ligne incompatible. Si le choix change aussitôt, il manque des preuves."],
    ["Avant paiement, actualisez contenu, pays, emballage, stade, ligne, prix, règle, limites, délai, suivi, assurance et recours.","Après expédition, ajoutez mesures finales, facturation, statut, identifiants et premier scan sans effacer l'estimation. Retirez les données personnelles d'une version publique.","La conclusion vaut pour ce colis et cette date ; elle ne garantit ni prix, ni délai, ni douane, ni livraison."]
  ]),
  pt: make("COMPARAÇÃO DE LINHAS JOYAGOO","Comparar linhas Joyagoo: elegibilidade, cobrança e transferências","Compare apenas linhas ativas por elegibilidade, cobrança, operador, rastreio e evidência.",[{value:"Lista ao vivo",label:"Só linhas deste pacote"},{value:"5 campos",label:"Elegibilidade, cobrança, operação, rastreio, recurso"},{value:"Sem vencedor",label:"O pacote real decide"}], ["Comece pelas linhas realmente disponíveis","Crie uma linha de evidência","Compare a regra antes do total","Separe prazo e transferências","Identifique operador e solução","Use pesos sem certeza falsa","Congele o registo no pagamento"], [
    ["Compare depois de definir itens, destino e plano. A orientação oficial diz que o sistema filtra linhas pelos produtos; uma rota antiga só é candidata quando aparece agora.","Linha ausente não está disponível para este envio, mas pode voltar. Verifique restrições, endereço e medição; nunca descreva a mercadoria incorretamente.","Preço histórico baixo sem elegibilidade não ajuda. O método não declara uma melhor linha universal."],
    ["Registe nome, hora, país, conteúdo, fase do peso, dimensões, preço e escalões visíveis. Preço por quilo pode ocultar mínimos e arredondamentos.","Adicione limites, embalagem, rastreio, seguro, intervalo e fornecedor. Campo ausente é ‘não mostrado’, não zero; guarde texto e imagens decisivas.","Use os mesmos dados. Peso do vendedor, armazém e ensaio são cenários separados."],
    ["A tabela oficial mostra regras diferentes para postal, expresso e linhas exclusivas. Copie a regra atual, não um divisor universal.","Registe peso real, volumétrico, faturável e próximo limiar; teste pequeno aumento de peso ou dimensão.","O ensaio melhora a evidência, mas não impede nova medição. Guarde estimativa, ensaio, armazém e ajuste separadamente."],
    ["A cadeia inclui embalagem, recolha, segurança, voo, transporte, aeroporto, alfândega, correio local e entrega. O prazo é referência, não garantia.","Associe eventos aos repasses e guarde números Joyagoo e transportador. Falta de evento não prova perda.","Compare qualidade de rastreio e tolerância de prazo, deixando margem para clima, alfândega e erros."],
    ["Joyagoo distingue linhas de parceiros e outros operadores com caminhos de pós-venda diferentes. Registe a relação sem a inferir apenas do nome.","Verifique cobertura, exclusões, declaração, provas, prazo e limite do seguro. Seguro não garante alfândega nem pagamento.","Para bens frágeis ou difíceis de substituir, transferências claras e recurso documentado podem valer mais que o menor total sem provar maior segurança."],
    ["Defina pesos antes do preço: elegibilidade, estabilidade da cobrança, rastreio, recurso e prazo. Adapte conscientemente.","Pontue só campos provados. Linha barata com volume ou reclamação incertos não recebe pontos otimistas.","Teste aumento plausível ou retire linha incompatível. Mudança imediata indica decisão frágil."],
    ["Antes de pagar, atualize itens, país, embalagem, fase, linha, preço, regra, limites, prazo, rastreio, seguro e recurso.","Após envio, acrescente dados finais e eventos sem apagar a estimativa. Retire dados pessoais de qualquer versão pública.","A conclusão vale apenas para aquele pacote e momento; não garante preço, rapidez, alfândega ou entrega."]
  ]),
  ro: make("COMPARAȚIE LINII JOYAGOO","Compararea liniilor Joyagoo: eligibilitate, facturare și predări","Compară numai liniile active după eligibilitate, facturare, operator, urmărire și dovezi.",[{value:"Listă live",label:"Doar liniile coletului"},{value:"5 câmpuri",label:"Eligibilitate, facturare, operare, urmărire, remediu"},{value:"Fără câștigător",label:"Coletul real decide"}], ["Pornește de la liniile disponibile","Construiește un rând de dovezi","Verifică regula înaintea totalului","Separă timpul de predări","Identifică operatorul și remediul","Folosește ponderi fără certitudini false","Fixează evidența la plată"], [
    ["Compară după stabilirea produselor, destinației și planului. Ghidul oficial spune că sistemul filtrează liniile după produse; o rută veche contează doar dacă apare acum.","O linie absentă nu este disponibilă pentru această trimitere, nu neapărat definitiv. Verifică restricții, adresă și etapa măsurării; nu descrie marfa fals.","Un preț istoric mic fără eligibilitate nu ajută. Cadrul nu alege o linie universală."],
    ["Notează nume, oră, țară, conținut, etapă, dimensiuni, preț și praguri. Prețul pe kilogram poate ascunde minime și rotunjiri.","Adaugă limite, ambalare, tracking, asigurare, interval și furnizor. Câmp absent înseamnă ‘neafișat’, nu zero; păstrează text și imagini decisive.","Folosește aceleași date. Greutatea vânzătorului, depozitului și repetiției sunt scenarii separate."],
    ["Tabelul oficial arată reguli diferite pentru poștă, expres și linii exclusive. Copiază regula actuală, nu un divizor universal.","Înregistrează greutatea reală, volumetrică, facturabilă și pragul următor; testează o creștere mică.","Repetiția îmbunătățește dovada fără a opri o remăsurare. Păstrează toate etapele separat."],
    ["Lanțul include ambalare, colectare, securitate, zbor, transport, aeroport, vamă, curier local și livrare. Intervalul este referință, nu garanție.","Leagă scanările de predări și salvează numerele Joyagoo și transportatorului. Lipsa unei scanări nu dovedește pierderea.","Compară calitatea urmăririi și toleranța termenului, cu rezervă pentru vreme, vamă și erori."],
    ["Joyagoo distinge linii partenere și alți transportatori cu căi diferite de soluționare. Înregistrează relația, nu o deduce doar din nume.","Verifică acoperire, excluderi, declarație, dovezi, termen și limită de asigurare. Asigurarea nu garantează vama sau plata.","Pentru bunuri fragile, predările clare și un remediu documentat pot conta mai mult decât totalul minim fără a dovedi siguranță mai mare."],
    ["Stabilește ponderi înainte de preț: eligibilitate, stabilitate, urmărire, remediu și timp. Adaptează-le conștient.","Punctează doar câmpuri dovedite. O linie ieftină cu volum sau reclamație necunoscute nu primește puncte optimiste.","Testează o creștere plauzibilă sau elimină o linie incompatibilă. Schimbarea imediată arată o decizie fragilă."],
    ["Înainte de plată actualizează produse, țară, ambalare, etapă, linie, preț, regulă, limite, timp, tracking, asigurare și remediu.","După expediere adaugă datele finale și scanările fără a șterge estimarea. Elimină datele personale din versiunea publică.","Concluzia este valabilă doar pentru acel colet și moment; nu garantează preț, timp, vamă sau livrare."]
  ]),
  sv: make("JÄMFÖRELSE AV JOYAGOO-LINJER","Jämför Joyagoo-fraktlinjer: behörighet, debitering och överlämningar","Jämför bara aktiva linjer efter behörighet, debitering, operatör, spårning och bevis.",[{value:"Live-lista",label:"Bara linjer för paketet"},{value:"5 fält",label:"Behörighet, debitering, hantering, spårning, åtgärd"},{value:"Ingen vinnare",label:"Det verkliga paketet avgör"}], ["Börja med linjer som faktiskt är tillgängliga","Bygg en bevisrad per alternativ","Jämför regeln före totalsumman","Skilj tidsintervall från överlämningar","Identifiera operatör och åtgärd","Vikta utan falsk säkerhet","Frys posten vid betalning"], [
    ["Jämför efter att varor, mål och paketplan är bestämda. Officiell vägledning säger att systemet filtrerar linjer efter produkterna; en gammal rutt räknas först när den visas nu.","En saknad linje är otillgänglig för denna inlämning, inte nödvändigtvis för alltid. Kontrollera restriktion, adress och mätsteg; beskriv aldrig varan felaktigt.","Ett lågt historiskt pris utan behörighet saknar värde. Modellen utser ingen universellt bästa linje."],
    ["Spara namn, tid, land, innehåll, viktsteg, mått, pris och synliga trösklar. Pris per kilo kan dölja miniminivåer och avrundning.","Lägg till gränser, packning, spårning, försäkring, intervall och leverantör. Saknat fält är ‘visas inte’, inte noll; spara text och avgörande bilder.","Använd samma data. Säljarvikt, lagermått och provpackning är separata scenarier."],
    ["Den officiella tabellen visar olika regler för post, express och exklusiva linjer. Kopiera aktuell regel i stället för en universell divisor.","Notera faktisk, volym- och debiterbar vikt samt nästa tröskel; testa en liten vikt- eller måttökning.","Provpackning förbättrar beviset men hindrar inte ommätning. Behåll uppskattning, prov, lager och justering separat."],
    ["Kedjan omfattar packning, hämtning, säkerhet, flyg, transport, flygplats, tull, lokal kurir och leverans. Intervallet är referens, inte garanti.","Koppla skanningar till överlämningar och spara Joyagoo- och transportörsnummer. En saknad skanning bevisar inte förlust.","Jämför spårningskvalitet och tidstolerans och lämna marginal för väder, tull och fel."],
    ["Joyagoo skiljer partnerlinjer från andra transportörer med olika efterköpsvägar. Spara relationen och anta den inte från namnet.","Kontrollera täckning, undantag, deklaration, bevis, tidsgräns och försäkringstak. Försäkring garanterar inte tull eller ersättning.","För ömtåligt eller svårersatt innehåll kan tydliga överlämningar och dokumenterad åtgärd väga tyngre än lägsta total utan att bevisa säkerhet."],
    ["Bestäm vikter före priset: behörighet, debiteringsstabilitet, spårning, åtgärd och tid. Anpassa medvetet.","Poängsätt bara bevisade fält. En billig linje med okänd volym eller reklamation får inga optimistiska poäng.","Testa en rimlig ökning eller ta bort en inkompatibel linje. Omedelbart byte visar ett skört beslut."],
    ["Före betalning uppdaterar du innehåll, land, packning, steg, linje, pris, regel, gränser, tid, spårning, försäkring och åtgärd.","Efter sändning lägger du till slutdata och skanningar utan att skriva över uppskattningen. Ta bort personuppgifter ur en offentlig version.","Slutsatsen gäller bara paketet och tidpunkten; den garanterar inte pris, fart, tull eller leverans."]
  ]),
};

export const shippingLineComparisonArticles: Record<Locale, SeoArticle> = { en, ...translated };

export const shippingLineComparisonSourceBodies: Record<Locale, string> = {
  en: "Checked September 12, 2026 against current Joyagoo Shopping Guidance, Logistics Platform Overview, Delivery Fees, weighing standards and mail-restriction pages. Live parcel eligibility and current line terms control the decision.",
  zh: "2026年9月12日核对当前Joyagoo购物指南、物流平台、运费、称重标准和邮寄限制。以实时包裹资格与当前线路条款为准。",
  de: "Am 12. September 2026 anhand aktueller Joyagoo-Seiten zu Einkauf, Logistik, Gebühren, Wiegen und Einschränkungen geprüft. Live-Eignung und aktuelle Linienbedingungen sind maßgeblich.",
  pl: "Sprawdzono 12 września 2026 r. w aktualnych materiałach Joyagoo o zakupach, logistyce, opłatach, ważeniu i ograniczeniach. Decydują dane bieżącej paczki.",
  es: "Comprobado el 12 de septiembre de 2026 con las páginas actuales de Joyagoo sobre compra, logística, tarifas, pesaje y restricciones. Mandan la elegibilidad y condiciones en vivo.",
  it: "Verificato il 12 settembre 2026 sulle pagine Joyagoo attuali per acquisto, logistica, tariffe, pesatura e restrizioni. Contano idoneità e condizioni live.",
  fr: "Vérifié le 12 septembre 2026 sur les pages Joyagoo actuelles relatives à l'achat, la logistique, les frais, la pesée et les restrictions. L'admissibilité et les conditions en direct prévalent.",
  pt: "Verificado em 12 de setembro de 2026 nas páginas atuais da Joyagoo sobre compra, logística, taxas, pesagem e restrições. Valem elegibilidade e condições ao vivo.",
  ro: "Verificat la 12 septembrie 2026 în paginile Joyagoo actuale despre cumpărare, logistică, taxe, cântărire și restricții. Contează eligibilitatea și condițiile live.",
  sv: "Kontrollerad 12 september 2026 mot aktuella Joyagoo-sidor om köp, logistik, avgifter, vägning och begränsningar. Live-behörighet och aktuella villkor styr.",
};
