import type { Locale } from "./i18n";
import type { SeoArticleCopy } from "./seoArticles";

type SeoArticle = SeoArticleCopy["article"];

const en: SeoArticle = {
  eyebrow: "JOYAGOO SHOEBOX DECISION GUIDE",
  title: "Joyagoo Shoebox Removal: Shipping Cost vs Damage Risk",
  description: "Decide whether to remove or keep shoe boxes in a Joyagoo parcel using packed dimensions, product protection, presentation value and live route costs.",
  facts: [
    { value: "2 plans", label: "Compare keep-box and remove-box scenarios" },
    { value: "4 roles", label: "Separate protection, identity, presentation and empty volume" },
    { value: "Live quote", label: "Use current packed data instead of a guessed saving" },
  ],
  sections: [
    {
      heading: "Treat the shoe box as part of the parcel decision",
      paragraphs: [
        "Removing a shoe box can sound like an automatic Joyagoo shipping-cost saving. It is not. Joyagoo’s current shopping guidance confirms that package removal is an available parcel-stage option, while its fee explanation says international freight depends on weight, package volume, shipping method and destination. Those facts support a comparison, not a universal instruction. The useful question is whether this particular box adds more billable space than protection or product value for this particular parcel and eligible line.",
        "Make the decision after the shoes have arrived, the ordered pair has been checked and the visible packaging is known. A seller listing may show a box that does not arrive, or a warehouse photo may reveal a thin, damaged or oversized box. Do not request disposal based only on a product-page image. Review the warehouse evidence, confirm accessories and decide whether the packaging is structural, collectible, useful for identification or simply empty volume around a product that can be protected another way.",
        "Keep the product decision separate from the shipping decision. Accepting the shoes after QC does not mean every piece of retail packaging must travel internationally. Conversely, a high freight estimate does not prove that removing the box is safe. Write down what the box contributes and what would replace it. A good removal request names the protection that must remain; a bad request says only ‘remove all packaging’ and leaves the packed condition to assumption.",
      ],
    },
    {
      heading: "Audit the four jobs a box may perform",
      paragraphs: [
        "First, protection: a rigid box can spread pressure, keep the pair together and reduce direct contact with heavier items. It may also be weak, partly crushed or much larger than the shoes. Second, identity: labels, model text, size information or seller markings can help connect the received item with the order record. If identity evidence matters, preserve clear warehouse photos before discarding anything and specify whether a label should be retained.",
        "Third, presentation: gifting, collecting or resale may make the retail box part of the desired product condition. This is a user value, not a shipping rule, but it belongs in the decision. Fourth, volume: the box can create air space and force a larger outer carton. Joyagoo’s published packing standard says irregularly shaped items may receive extra filling and that cartons may be cut to reduce volume. The final packed shape, not the shoe-box dimensions alone, determines whether removal actually improves the international parcel.",
        "Score each role from zero to two. Zero means no meaningful value, one means replaceable value, and two means important value. A box scoring high for protection and presentation deserves a keep-box plan. A badly damaged generic box with no needed label may deserve a remove-box plan. The score does not calculate freight; it prevents a small, uncertain saving from silently overruling the reason the packaging exists.",
      ],
    },
    {
      heading: "Build two comparable packing plans",
      paragraphs: [
        "Plan K keeps the retail box. Record whether the warehouse should preserve its shape, add an outer carton, protect it from moisture or isolate it from heavy goods. Plan R removes the retail box. State what remains: both shoes, insoles, laces, dust bags, tags, accessories and any label you deliberately keep. Then state replacement protection, such as keeping the pair together, filling the toe area with suitable material and preventing direct contact with hard edges.",
        "Do not compare Plan K for one parcel with Plan R after also changing consolidation, shipping line and insurance. That makes the cause of any price difference unknowable. Hold the same items, destination, route family and necessary protection constant. If removing the box makes a different route appear, record that as a second effect rather than mixing it into the first calculation. Each row should show contents, packed or estimated dimensions, billable weight, line, packing choices and current quote.",
        "Use neutral scenario numbers to understand the model. Suppose the keep-box plan is 64 cost units and the remove-box plan is 57, but replacement protection adds four units. The comparable difference is three units, not seven. If the box has high presentation value, three units may be a weak reason to discard it. If the box is already unusable and the smaller plan restores a suitable route, the same difference may support removal. These are teaching units, not Joyagoo prices.",
      ],
    },
    {
      heading: "Understand when volume can change the billable result",
      paragraphs: [
        "Joyagoo’s current fee page states that international parcel shipping depends on weight, volume, method and destination. Its published volumetric guidance explains that some logistics providers compare physical and volumetric weight, with the applicable calculation depending on the provider. Therefore a light shoe box can matter even when it adds little scale weight. The effect depends on the packed outer dimensions and the selected line’s current charging standard, not a universal price per centimetre.",
        "A box removal helps most when the retail boxes determine one or more outer-carton dimensions and the shoes can be packed safely into a meaningfully smaller shape. It helps less when the parcel already contains a rigid or oversized item that controls the carton, or when replacement protection fills most of the removed space. Removing one of several identical boxes may not cross a billing increment. Avoid calculating a guaranteed saving before the packed measurements exist.",
        "Rehearsal packing can be useful when the decision could change the route or a meaningful portion of the shipping budget. Joyagoo’s dedicated current page says the service packs selected orders using the chosen packing methods and line, then updates parcel weight and shipping fee. It currently lists a fee and notification target, but this article does not turn either into a permanent promise; verify the live service page and account screen before ordering it. Use rehearsal when better measurement could change the decision, not by habit.",
      ],
    },
    {
      heading: "Write instructions that the warehouse can verify",
      paragraphs: [
        "A useful instruction is specific and internally consistent. For removal: ‘Remove the retail shoe box, keep both shoes, spare laces, tags and dust bags, keep the pair together, protect the toe shape and prevent contact with metal items.’ For retention: ‘Keep the retail box and its label, do not fold it, place it inside protective outer packaging and keep heavy items from pressing on it.’ Adapt the instruction to visible contents; do not copy a template that mentions accessories the order never included.",
        "Avoid requests such as ‘remove all packaging but keep original presentation’ or ‘minimize volume with no compression.’ The warehouse cannot satisfy contradictory goals. If one part matters more, state the priority. Also distinguish the seller’s external courier bag, retail box, internal paper, fitted insert and product accessories. ‘Packaging’ is too broad when some layers may be disposable and others are part of the desired condition.",
        "Use the parcel-photo or other current account evidence only when it answers a decision-relevant question. Joyagoo publishes a parcel-photo service in its value-added table, but a photo cannot prove hidden cushioning or future damage resistance. It can help confirm whether the requested box was retained or removed and whether visible parcel shape matches the instruction. Save the instruction, result and parcel reference together in case later support needs the timeline.",
      ],
    },
    {
      heading: "Use decision rules for common shoe-parcel situations",
      paragraphs: [
        "Keep the box when it is a meaningful part of the purchase, when the structure is needed to resist pressure, when its label is important and has not been documented, or when the live cost difference is small after replacement protection. Consider removal when the box is generic or badly damaged, the shoes are robust enough for a defined alternative, the parcel is otherwise soft and compatible, and packed data shows a material reduction rather than a hypothetical one.",
        "For multiple pairs, do not make one rule for every box. A presentation box may stay while ordinary boxes are removed. A rigid pair can be separated from a delicate pair. If a heavy product shares the parcel, calculate whether isolation or a split is safer than simply discarding shoe boxes. Joyagoo’s packing standard mentions ordered packing, extra bubble wrap for the top of the parcel, additional treatment for fragile goods and volume reduction for irregular shapes; use those as process context, not a guarantee for every custom instruction.",
        "For returns or unresolved QC, do not submit the parcel decision yet. Packaging removal can reduce the evidence or condition needed for a seller-side resolution. Confirm the item decision first, while current return controls are available, then create the international parcel. Free storage and parcel planning do not extend a return window. The lowest-risk sequence is identity, QC outcome, after-sales closure, packaging decision, route check and final submission.",
      ],
    },
    {
      heading: "Run a final keep-or-remove checklist",
      paragraphs: [
        "Before choosing, confirm that QC and any after-sales question are closed; warehouse photos show the actual box and accessories; the box’s protection, identity and presentation roles are scored; both plans use the same contents and destination; replacement protection is explicit; current eligible lines are recorded; and the live quote or packed result shows whether the dimensions truly change. Leave unknown savings as unknown rather than inventing a percentage.",
        "After packing, reconcile the result. Match every pair and accessory to the parcel, check the retained or removed packaging instruction, compare packed weight and dimensions with the plan, confirm the selected line remains available and review the final charge. If the result changes materially, pause and determine which input changed. A box-removal decision succeeds when it produces an eligible, protectable and lower-risk total cost—not merely when the warehouse throws away cardboard.",
        "Save a compact evidence set: order reference, selected size and colour, QC photos, packaging instruction, before-and-after parcel data where available, live line quote, payment and tracking number. This makes the trade-off auditable. It also keeps this article in its proper role: a decision framework. The current account and packed parcel remain the sources for the actual service, route and cost.",
      ],
    },
  ],
};

type NonEnglish = Exclude<Locale, "en">;
function make(eyebrow: string, title: string, description: string, facts: SeoArticle["facts"], headings: string[], paragraphs: string[][]): SeoArticle {
  return { eyebrow, title, description, facts, sections: headings.map((heading, index) => ({ heading, paragraphs: paragraphs[index] })) };
}

const localized: Record<NonEnglish, SeoArticle> = {
  zh: make("JOYAGOO鞋盒决策指南", "Joyagoo鞋盒去留：运费与损坏风险如何权衡", "根据打包尺寸、保护作用、展示价值和实时线路成本决定保留或移除鞋盒。", [{ value: "两个方案", label: "分别比较保留与移除" }, { value: "四项作用", label: "保护、识别、展示与空体积" }, { value: "实时数据", label: "不用猜测的节省比例" }], ["把鞋盒视为包裹决策的一部分", "检查鞋盒的四项作用", "建立两个可比打包方案", "理解体积如何影响计费", "写出仓库可执行的指令", "按常见场景做决定", "完成最终检查"], [
    ["Joyagoo当前购物指南确认包裹阶段可选择移除包装，费用说明则指出国际运费取决于重量、体积、线路和目的地。这支持比较，不代表所有鞋盒都该扔掉。", "等鞋子到仓、QC完成且看清实际鞋盒后再决定。商品页图片不能证明仓库收到同样的包装。", "先写明鞋盒提供的保护、识别或展示价值，以及移除后用什么替代。不要只写‘移除全部包装’。"],
    ["保护作用包括分散压力、固定一双鞋并隔离重物；也要判断鞋盒是否已经压坏或明显过大。识别作用包括尺码、型号与卖家标签，移除前应留存清楚证据。", "展示作用适用于送礼、收藏或转售；体积作用则看鞋盒是否迫使外箱变大。官方打包标准提到异形物可能填充并裁减纸箱体积。", "每项按0到2分：无价值、可替代、重要。高保护或展示分更支持保留，破损普通盒更支持移除。"],
    ["K方案保留鞋盒，注明是否保持形状、加外箱、防潮和隔离重物。R方案移除鞋盒，列明必须保留的鞋、鞋垫、鞋带、吊牌、袋子和配件以及替代保护。", "两方案必须使用相同商品、目的地、线路范围和必要保护。若移除后出现新线路，把它单列为第二个影响。", "抽象示例中，保留64单位、移除57但替代保护4，实际差额是3而非7。教学数字不是Joyagoo报价。"],
    ["官方说明运费受重量、体积、方式和目的地影响，部分物流比较实际重与体积重。鞋盒很轻也可能因外箱尺寸影响计费。", "只有鞋盒决定外箱尺寸且鞋子可安全缩小打包时收益最大；若其他硬物已经决定箱体，或保护材料填回空间，收益较小。", "当尺寸可能改变线路或预算时可考虑预打包。官方专页说明按所选方式与线路打包后更新重量和运费；费用与通知时间仍应查看实时页面。"],
    ["移除指令应明确保留哪些配件、如何固定鞋子、保护鞋头并隔离硬物；保留指令应说明盒子和标签不能折叠、需要外层保护。", "避免‘移除全部包装但保持原始展示’等矛盾要求。区分快递袋、零售盒、内纸、定型支撑和商品配件。", "包裹照片可确认可见结果，但不能证明隐藏填充或未来抗损。把指令、结果与包裹编号一起保存。"],
    ["鞋盒是商品价值、结构保护或重要标签时保留；替代保护明确、鞋盒普通破损且打包数据证实明显缩小时才考虑移除。", "多双鞋可以分别决定，不必全留或全删。重物同包时，也要比较隔离或拆包，而不是只扔鞋盒。", "退货或QC未解决时不要提交包裹。先完成商品与售后决定，再做包装和线路选择。"],
    ["确认QC和售后关闭、照片显示真实鞋盒、四项作用已评分、两个方案条件一致、替代保护明确、线路与实时数据已记录。", "打包后核对鞋与配件、指令、重量、尺寸、线路和最终费用。变化较大就先找出哪个输入改变。", "保存订单、规格、QC、包装指令、包裹数据、报价、付款与追踪。文章只提供方法，实际服务与费用以账户和成包数据为准。"],
  ]),
  de: make("JOYAGOO-SCHUHKARTON-RATGEBER", "Joyagoo-Schuhkarton entfernen: Fracht gegen Schadensrisiko", "Schuhkarton anhand von Packmaßen, Schutz, Präsentationswert und Live-Routenkosten behalten oder entfernen.", [{ value: "2 Pläne", label: "Behalten und Entfernen vergleichen" }, { value: "4 Rollen", label: "Schutz, Identität, Präsentation, Volumen" }, { value: "Live-Angebot", label: "Keine Ersparnis schätzen" }], ["Den Karton als Paketentscheidung behandeln", "Vier Aufgaben des Kartons prüfen", "Zwei vergleichbare Packpläne bauen", "Volumen und Abrechnung verstehen", "Prüfbare Lageranweisungen schreiben", "Regeln für typische Schuhpakete", "Abschließende Prüfung"], [
    ["Joyagoo nennt Verpackungsentfernung als Paketoption und berechnet Auslandsfracht nach Gewicht, Volumen, Methode und Ziel. Das begründet einen Vergleich, keine allgemeine Entfernungsregel.", "Entscheide nach Lagereingang und QC anhand der echten Verpackung, nicht des Verkäuferbildes.", "Trenne Produktannahme und Versand. Notiere Nutzen des Kartons und Ersatzschutz; ‘alles entfernen’ ist keine ausreichende Anweisung."],
    ["Bewerte Schutz gegen Druck und Kontakt sowie Identitätsdaten wie Größe und Modell. Sichere Fotos wichtiger Etiketten.", "Präsentation kann für Geschenk, Sammlung oder Wiederverkauf zählen; Volumen zählt nur, wenn der Karton den Außenkarton vergrößert.", "Bewerte jede Rolle 0–2. Hoher Schutz- oder Präsentationswert spricht fürs Behalten, ein beschädigter generischer Karton eher fürs Entfernen."],
    ["Plan K behält Karton und nennt Formschutz, Außenkarton, Feuchte und schwere Nachbarn. Plan R listet Schuhe, Zubehör, Etiketten und Ersatzschutz.", "Inhalt, Ziel, Routenfamilie und Schutz müssen gleich bleiben. Eine neu verfügbare Linie wird als eigener Effekt dokumentiert.", "Abstrakt: 64 gegen 57 plus 4 Schutz ergibt drei Einheiten Unterschied. Das ist keine Joyagoo-Rate."],
    ["Gewicht, Volumen, Methode und Ziel bestimmen den Preis; einige Anbieter vergleichen reales und volumetrisches Gewicht.", "Entfernung hilft, wenn Kartons die Außenmaße bestimmen. Ein anderes starres Gut oder Ersatzfüllung kann den Effekt aufheben.", "Probelauf ist sinnvoll, wenn Messdaten Route oder Budget ändern. Aktuelle Gebühr und Frist müssen live bestätigt werden."],
    ["Nenne beim Entfernen Zubehör, Paarbindung, Zehenform und Trennung von Metall; beim Behalten Karton, Label, Form und Außenschutz.", "Vermeide widersprüchliche Wünsche und unterscheide Versandbeutel, Verkaufskarton, Papier, Einsatz und Zubehör.", "Ein Paketfoto kann sichtbare Ausführung zeigen, nicht versteckten Schutz beweisen. Sichere Anweisung und Ergebnis."],
    ["Behalte bei Produktwert, strukturellem Schutz, wichtigem Label oder kleinem Netto-Unterschied. Entferne bei ersetzbarem Schutz und belegter Volumenreduktion.", "Mehrere Paare dürfen unterschiedliche Entscheidungen haben; schwere Mitware kann Trennung statt bloßer Kartonentfernung verlangen.", "Offenes QC oder Rückgabe blockiert die Paketeinreichung. Erst Artikelentscheidung, dann Verpackung und Route."],
    ["Prüfe abgeschlossene Nachbearbeitung, echte Fotos, Rollenbewertung, gleiche Pläne, Ersatzschutz, Linien und Live-Daten.", "Gleiche nach dem Packen Inhalt, Zubehör, Anweisung, Maße, Linie und Endbetrag ab.", "Sichere Auftrag, Variante, QC, Anweisung, Paketdaten, Angebot, Zahlung und Tracking."],
  ]),
  pl: make("JOYAGOO — PUDEŁKO PO BUTACH", "Joyagoo: usunąć czy zachować pudełko po butach?", "Porównaj koszt wysyłki i ryzyko szkody według wymiarów, ochrony, wartości opakowania i bieżącej trasy.", [{ value: "2 plany", label: "Z pudełkiem i bez" }, { value: "4 role", label: "Ochrona, identyfikacja, prezentacja, objętość" }, { value: "Dane live", label: "Bez zgadywania oszczędności" }], ["Pudełko jako decyzja o paczce", "Cztery funkcje pudełka", "Dwa porównywalne plany", "Objętość i masa rozliczeniowa", "Instrukcje możliwe do sprawdzenia", "Reguły dla typowych sytuacji", "Końcowa lista"], [
    ["Joyagoo oferuje usuwanie opakowań na etapie paczki, a koszt zależy od masy, objętości, metody i celu. To wymaga porównania, nie automatycznego wyrzucenia.", "Decyduj po przyjęciu i QC, gdy widać rzeczywiste pudełko i dodatki.", "Zapisz wartość pudełka i ochronę zastępczą. Akceptacja butów nie rozstrzyga o opakowaniu."],
    ["Oceń ochronę przed naciskiem i kontaktami oraz dane identyfikacyjne. Zrób dowód etykiet przed usunięciem.", "Prezentacja ma znaczenie przy prezencie, kolekcji lub odsprzedaży; objętość tylko gdy zmienia karton zewnętrzny.", "Skala 0–2 dla każdej roli chroni przed utratą ważnej wartości dla małej niepewnej oszczędności."],
    ["Plan K zachowuje pudełko i definiuje ochronę kształtu. Plan R wymienia wszystkie buty, sznurówki, wkładki, worki, metki i ochronę zastępczą.", "Zachowaj te same towary, cel, trasę i konieczną ochronę. Nowa linia po usunięciu jest osobnym skutkiem.", "Przykładowe jednostki pokazują, że koszt ochrony zmniejsza różnicę; nie są ceną Joyagoo."],
    ["Oficjalna strona wiąże fracht z masą, objętością, metodą i celem; zasada logistyczna może porównywać masę fizyczną i objętościową.", "Usunięcie pomaga, gdy pudełka sterują wymiarami i można bezpiecznie zmniejszyć kształt. Inny sztywny przedmiot lub wypełnienie ogranicza efekt.", "Pakowanie próbne stosuj, gdy lepszy pomiar zmieni decyzję. Aktualną opłatę i czas sprawdź na żywo."],
    ["W instrukcji usuń pudełko, ale zachowaj konkretne dodatki, kształt i izolację; albo zachowaj pudełko, etykietę i zewnętrzną ochronę.", "Unikaj sprzeczności i odróżniaj worek kurierski, pudełko, papier, wkład i akcesoria.", "Zdjęcie paczki potwierdza wynik widoczny, nie ukrytą amortyzację. Zachowaj instrukcję i numer."],
    ["Zachowaj pudełko dla wartości, ochrony, ważnej etykiety lub małej różnicy. Usuń przy jasnej ochronie zastępczej i potwierdzonej redukcji.", "Dla wielu par wybieraj osobno. Ciężki towar może wymagać rozdzielenia, nie tylko wyrzucenia pudełka.", "Otwarty QC lub zwrot blokuje paczkę. Najpierw zamknij decyzję o produkcie."],
    ["Sprawdź QC, zdjęcia, ocenę ról, zgodność planów, ochronę, linie i dane.", "Po pakowaniu uzgodnij towary, dodatki, instrukcję, masę, wymiary, trasę i kwotę.", "Zachowaj zamówienie, wariant, QC, instrukcję, dane paczki, płatność i śledzenie."],
  ]),
  es: make("GUÍA JOYAGOO DE CAJAS", "Joyagoo: quitar la caja de zapatos o conservarla", "Decide con dimensiones, protección, valor de presentación y coste activo, no con un ahorro supuesto.", [{ value: "2 planes", label: "Con caja y sin caja" }, { value: "4 funciones", label: "Protección, identidad, presentación y volumen" }, { value: "Cotización activa", label: "No inventar el ahorro" }], ["La caja forma parte de la decisión", "Audita cuatro funciones", "Crea dos planes comparables", "Cuándo cambia el peso facturable", "Escribe instrucciones verificables", "Reglas para casos comunes", "Lista final"], [
    ["Joyagoo confirma la opción de retirar embalaje y que el flete depende de peso, volumen, método y destino. Eso exige comparar, no retirar siempre.", "Decide tras la llegada y el QC, cuando ves la caja real y los accesorios.", "Separa aceptación del producto y diseño del paquete; anota qué aporta la caja y qué protección la sustituye."],
    ["Evalúa protección contra presión e identidad mediante etiquetas. Conserva evidencia antes de desechar.", "La presentación puede importar para regalo, colección o reventa; el volumen importa si obliga a una caja exterior mayor.", "Puntúa cada función de 0 a 2 para que un ahorro incierto no elimine valor importante."],
    ["Plan K conserva caja y protección; Plan R enumera zapatos, cordones, plantillas, bolsas, etiquetas y sustitución protectora.", "Mantén iguales contenido, destino, línea y protección. Una línea nueva es un segundo efecto.", "Los números abstractos muestran cómo el coste protector reduce la diferencia; no son tarifas Joyagoo."],
    ["El flete depende de peso, volumen, método y destino; algunos operadores comparan peso real y volumétrico.", "Quitar ayuda si las cajas determinan las dimensiones y el calzado puede reducirse con seguridad. Otros objetos rígidos o relleno pueden anularlo.", "Usa ensayo de embalaje si una mejor medición cambia ruta o presupuesto; verifica precio y plazo actuales."],
    ["Al quitar, especifica accesorios, forma y separación; al conservar, caja, etiqueta, forma y protección exterior.", "Evita objetivos contradictorios y distingue bolsa, caja, papel, inserto y accesorios.", "La foto confirma lo visible, no el acolchado oculto. Guarda instrucción y resultado."],
    ["Conserva por valor, estructura, etiqueta o poca diferencia neta. Quita con sustitución clara y reducción demostrada.", "Decide cada par por separado; un artículo pesado puede justificar separar el paquete.", "No embales con QC o devolución abiertos. Cierra primero la decisión del artículo."],
    ["Comprueba QC, fotos, funciones, planes iguales, protección, líneas y datos activos.", "Tras embalar, concilia artículos, accesorios, instrucción, medidas, ruta e importe.", "Guarda pedido, variante, QC, instrucción, datos, pago y seguimiento."],
  ]),
  it: make("GUIDA JOYAGOO ALLE SCATOLE", "Joyagoo: rimuovere o tenere la scatola delle scarpe", "Decidi con misure imballate, protezione, valore e costo live, non con un risparmio ipotetico.", [{ value: "2 piani", label: "Con e senza scatola" }, { value: "4 ruoli", label: "Protezione, identità, presentazione, volume" }, { value: "Dati live", label: "Nessun risparmio inventato" }], ["La scatola è una decisione del pacco", "Valuta quattro funzioni", "Costruisci due piani comparabili", "Volume e peso fatturabile", "Istruzioni verificabili", "Regole per casi comuni", "Controllo finale"], [
    ["Joyagoo offre la rimozione dell’imballo e lega il nolo a peso, volume, metodo e destinazione. Serve un confronto, non una regola universale.", "Decidi dopo arrivo e QC vedendo scatola e accessori reali.", "Separa accettazione e spedizione; scrivi funzione della scatola e protezione alternativa."],
    ["Valuta protezione e identità tramite etichette, conservando prove prima della rimozione.", "Presentazione conta per regalo, collezione o rivendita; volume conta se aumenta il cartone esterno.", "Punteggia 0–2 per evitare che un risparmio incerto elimini valore importante."],
    ["Piano K tiene scatola e forma; Piano R elenca scarpe, lacci, solette, sacche, etichette e protezione sostitutiva.", "Tieni uguali contenuto, destinazione, linea e protezione. Una nuova linea è un effetto separato.", "Le unità astratte insegnano il calcolo e non sono prezzi Joyagoo."],
    ["Il nolo dipende da peso, volume, metodo e destinazione; alcuni vettori confrontano reale e volumetrico.", "Rimuovere aiuta se le scatole determinano le misure e la forma può ridursi in sicurezza. Oggetti rigidi o riempimento riducono l’effetto.", "Usa il pre-imballaggio se il dato cambia rotta o budget; verifica costo e tempi live."],
    ["In rimozione specifica accessori, forma e separazione; in conservazione scatola, etichetta, forma e protezione esterna.", "Evita contraddizioni e distingui busta, scatola, carta, inserto e accessori.", "La foto conferma il visibile, non l’imbottitura nascosta. Salva istruzione e risultato."],
    ["Tieni per valore, struttura, etichetta o piccolo divario. Rimuovi con alternativa chiara e riduzione provata.", "Decidi per ogni paio; merce pesante può richiedere una divisione.", "QC o reso aperto bloccano l’invio. Chiudi prima la decisione articolo."],
    ["Controlla QC, foto, ruoli, piani uguali, protezione, linee e dati.", "Dopo l’imballo riconcilia articoli, accessori, istruzione, misure, rotta e importo.", "Salva ordine, variante, QC, istruzione, dati, pagamento e tracking."],
  ]),
  fr: make("GUIDE JOYAGOO DES BOÎTES", "Joyagoo : retirer ou garder la boîte à chaussures", "Décidez avec dimensions, protection, valeur de présentation et coût actif, sans supposer une économie.", [{ value: "2 plans", label: "Avec et sans boîte" }, { value: "4 rôles", label: "Protection, identité, présentation, volume" }, { value: "Devis actif", label: "Aucune économie inventée" }], ["La boîte fait partie du colis", "Auditer quatre fonctions", "Construire deux plans comparables", "Volume et poids facturable", "Écrire des consignes vérifiables", "Règles pour cas courants", "Contrôle final"], [
    ["Joyagoo confirme l’option de retrait et un fret dépendant du poids, volume, mode et pays. Cela justifie une comparaison, pas un retrait systématique.", "Décidez après arrivée et QC avec la vraie boîte et les accessoires.", "Séparez acceptation du produit et colis ; notez la fonction de la boîte et la protection de remplacement."],
    ["Évaluez protection contre pression et identité par étiquette, en gardant la preuve avant retrait.", "La présentation compte pour cadeau, collection ou revente ; le volume compte si la boîte agrandit le carton extérieur.", "Notez chaque rôle de 0 à 2 afin qu’une économie incertaine n’efface pas une valeur importante."],
    ["Plan K garde boîte et forme ; Plan R liste chaussures, lacets, semelles, sacs, étiquettes et protection.", "Gardez mêmes contenu, pays, ligne et protection. Une nouvelle ligne est un effet distinct.", "Les unités abstraites enseignent la méthode ; elles ne sont pas des tarifs Joyagoo."],
    ["Le fret dépend du poids, volume, mode et pays ; certains prestataires comparent poids réel et volumétrique.", "Le retrait aide si les boîtes déterminent les dimensions et si la forme peut diminuer sans risque. Un objet rigide ou le calage limite l’effet.", "Utilisez l’emballage d’essai si la mesure peut changer ligne ou budget ; vérifiez prix et délai en direct."],
    ["Pour retirer, précisez accessoires, forme et séparation ; pour garder, boîte, étiquette, forme et protection extérieure.", "Évitez les contradictions et distinguez sac, boîte, papier, insert et accessoires.", "La photo confirme le visible, pas le calage caché. Sauvegardez consigne et résultat."],
    ["Gardez pour valeur, structure, étiquette ou faible différence. Retirez avec remplacement clair et réduction prouvée.", "Décidez par paire ; un objet lourd peut justifier une séparation.", "QC ou retour ouvert bloque le colis. Fermez d’abord la décision produit."],
    ["Vérifiez QC, photos, rôles, plans identiques, protection, lignes et données.", "Après emballage, rapprochez articles, accessoires, consigne, mesures, ligne et montant.", "Conservez commande, variante, QC, consigne, données, paiement et suivi."],
  ]),
  pt: make("GUIA JOYAGOO DE CAIXAS", "Joyagoo: remover ou manter a caixa dos sapatos", "Decida com dimensões, proteção, valor e custo ao vivo, não com poupança presumida.", [{ value: "2 planos", label: "Com e sem caixa" }, { value: "4 funções", label: "Proteção, identidade, apresentação e volume" }, { value: "Cotação live", label: "Sem inventar poupança" }], ["A caixa faz parte da decisão", "Avaliar quatro funções", "Criar dois planos comparáveis", "Volume e peso faturável", "Instruções verificáveis", "Regras para situações comuns", "Verificação final"], [
    ["Joyagoo confirma remoção de embalagem e frete dependente de peso, volume, método e destino. Isso exige comparação, não remoção automática.", "Decida após chegada e QC, vendo caixa e acessórios reais.", "Separe aceitação e envio; registe a função da caixa e a proteção substituta."],
    ["Avalie proteção e identidade pelas etiquetas, preservando prova antes de remover.", "Apresentação conta para presente, coleção ou revenda; volume conta se aumenta a caixa exterior.", "Pontue 0–2 para impedir que uma poupança incerta elimine valor importante."],
    ["Plano K mantém caixa; Plano R lista sapatos, atacadores, palmilhas, sacos, etiquetas e proteção.", "Mantenha conteúdo, destino, linha e proteção iguais. Nova linha é efeito separado.", "Unidades abstratas ensinam o método, não são preços Joyagoo."],
    ["Frete depende de peso, volume, método e destino; alguns operadores comparam peso real e volumétrico.", "Remover ajuda se as caixas definem dimensões e a forma pode diminuir com segurança. Objeto rígido ou enchimento reduz o efeito.", "Use ensaio se a medição mudar linha ou orçamento; confirme preço e prazo ao vivo."],
    ["Ao remover, especifique acessórios, forma e separação; ao manter, caixa, etiqueta, forma e proteção exterior.", "Evite contradições e distinga saco, caixa, papel, inserto e acessórios.", "Foto confirma o visível, não acolchoamento oculto. Guarde instrução e resultado."],
    ["Mantenha por valor, estrutura, etiqueta ou pequena diferença. Remova com alternativa clara e redução provada.", "Decida cada par; item pesado pode exigir divisão.", "QC ou devolução aberta bloqueia o pacote. Feche primeiro a decisão."],
    ["Verifique QC, fotos, funções, planos iguais, proteção, linhas e dados.", "Após embalar, reconcilie artigos, acessórios, instrução, medidas, linha e valor.", "Guarde ordem, variante, QC, instrução, dados, pagamento e tracking."],
  ]),
  ro: make("GHID JOYAGOO PENTRU CUTII", "Joyagoo: scoți sau păstrezi cutia de pantofi", "Decide pe baza dimensiunilor, protecției, valorii și costului live, nu a unei economii presupuse.", [{ value: "2 planuri", label: "Cu și fără cutie" }, { value: "4 roluri", label: "Protecție, identitate, prezentare, volum" }, { value: "Ofertă live", label: "Fără economie inventată" }], ["Cutia este o decizie de colet", "Evaluează patru funcții", "Construiește două planuri", "Volum și greutate facturabilă", "Instrucțiuni verificabile", "Reguli pentru cazuri comune", "Control final"], [
    ["Joyagoo confirmă îndepărtarea ambalajului și un transport dependent de greutate, volum, metodă și destinație. Este nevoie de comparație, nu de eliminare automată.", "Decide după sosire și QC, când vezi cutia și accesoriile reale.", "Separă acceptarea produsului de colet; notează rolul cutiei și protecția alternativă."],
    ["Evaluează protecția și identitatea etichetelor, păstrând dovada înainte de eliminare.", "Prezentarea contează pentru cadou, colecție sau revânzare; volumul contează dacă mărește cutia exterioară.", "Notează 0–2 fiecare rol pentru ca o economie incertă să nu elimine valoare."],
    ["Planul K păstrează cutia; R listează pantofi, șireturi, branțuri, saci, etichete și protecție.", "Păstrează aceleași produse, destinație, linie și protecție. O linie nouă este efect separat.", "Unitățile abstracte explică metoda, nu sunt tarife Joyagoo."],
    ["Transportul depinde de greutate, volum, metodă și destinație; unii transportatori compară greutatea reală și volumetrică.", "Eliminarea ajută când cutiile controlează dimensiunile și forma poate scădea sigur. Un obiect rigid sau umplutura limitează efectul.", "Folosește împachetarea de probă dacă măsura schimbă linia sau bugetul; verifică prețul și timpul live."],
    ["La eliminare precizează accesoriile, forma și separarea; la păstrare cutia, eticheta, forma și protecția exterioară.", "Evită contradicțiile și separă punga, cutia, hârtia, inserția și accesoriile.", "Fotografia confirmă vizibilul, nu protecția ascunsă. Păstrează instrucțiunea și rezultatul."],
    ["Păstrează pentru valoare, structură, etichetă sau diferență mică. Elimină cu alternativă clară și reducere dovedită.", "Decide fiecare pereche; un obiect greu poate cere divizare.", "QC sau retur deschis blochează coletul. Închide întâi decizia."],
    ["Verifică QC, fotografii, roluri, planuri egale, protecție, linii și date.", "După ambalare reconciliază articole, accesorii, instrucțiune, măsuri, linie și sumă.", "Păstrează comanda, varianta, QC, instrucțiunea, datele, plata și urmărirea."],
  ]),
  sv: make("JOYAGOO SKOKARTONGUIDE", "Joyagoo: ta bort eller behålla skokartongen", "Avgör med packmått, skydd, presentationsvärde och livekostnad, inte antagen besparing.", [{ value: "2 planer", label: "Med och utan kartong" }, { value: "4 roller", label: "Skydd, identitet, presentation, volym" }, { value: "Liveoffert", label: "Ingen påhittad besparing" }], ["Kartongen är ett paketbeslut", "Granska fyra funktioner", "Bygg två jämförbara planer", "Volym och debiterad vikt", "Skriv verifierbara instruktioner", "Regler för vanliga fall", "Slutlig kontroll"], [
    ["Joyagoo bekräftar borttagning av förpackning och frakt beroende på vikt, volym, metod och mål. Det kräver jämförelse, inte automatisk borttagning.", "Avgör efter ankomst och QC när verklig kartong och tillbehör syns.", "Skilj produktgodkännande från paketval; skriv kartongens nytta och ersättningsskydd."],
    ["Bedöm tryckskydd och identitet från etiketter, och spara bevis före borttagning.", "Presentation kan gälla gåva, samling eller vidareförsäljning; volym gäller om ytterkartongen växer.", "Poängsätt 0–2 så att osäker besparing inte tar bort viktigt värde."],
    ["Plan K behåller kartong; R listar skor, snören, sulor, påsar, etiketter och skydd.", "Håll innehåll, mål, linje och skydd lika. Ny linje är en separat effekt.", "Abstrakta enheter lär ut metoden och är inte Joyagoo-priser."],
    ["Frakt beror på vikt, volym, metod och mål; vissa operatörer jämför faktisk och volymetrisk vikt.", "Borttagning hjälper när kartonger styr måtten och formen kan minskas säkert. Styvt gods eller fyllning begränsar effekten.", "Använd provpackning om mätningen ändrar linje eller budget; kontrollera pris och tid live."],
    ["Vid borttagning ange tillbehör, form och separation; vid behållning kartong, etikett, form och yttre skydd.", "Undvik motsägelser och skilj fraktpåse, kartong, papper, insats och tillbehör.", "Foto bekräftar synligt resultat, inte dold dämpning. Spara instruktion och resultat."],
    ["Behåll för värde, struktur, etikett eller liten skillnad. Ta bort med tydligt alternativ och bevisad minskning.", "Avgör per par; tungt gods kan kräva delning.", "Öppen QC eller retur blockerar paketet. Avsluta produktbeslutet först."],
    ["Kontrollera QC, bilder, roller, lika planer, skydd, linjer och data.", "Efter packning stäm av varor, tillbehör, instruktion, mått, linje och belopp.", "Spara order, variant, QC, instruktion, data, betalning och spårning."],
  ]),
};

export const shoeboxDecisionArticles: Record<Locale, SeoArticle> = { en, ...localized };

export const shoeboxDecisionSourceBodies: Record<Locale, string> = {
  en: "Fact-checked on 27 August 2026 against Joyagoo’s current Shopping Guidance, service-charge explanation, Value Added Services, Rehearsal Packing and Parcel Packing Standard pages. Live parcel options, selected line and packed measurements remain decisive.",
  zh: "事实核查于2026年8月27日，依据Joyagoo当前购物指南、费用说明、增值服务、预打包和包裹标准；实际选项、线路与成包数据为准。",
  de: "Am 27. August 2026 anhand aktueller Joyagoo-Seiten zu Einkauf, Gebühren, Zusatzleistungen, Probeverpackung und Packstandard geprüft; Live-Optionen und Packmaße entscheiden.",
  pl: "Sprawdzono 27 sierpnia 2026 z aktualnymi stronami Joyagoo o zakupie, opłatach, usługach, pakowaniu próbnym i standardzie; decydują opcje i wymiary live.",
  es: "Verificado el 27 de agosto de 2026 con las páginas actuales de compra, tarifas, servicios, ensayo y embalaje Joyagoo; mandan opciones y medidas activas.",
  it: "Verificato il 27 agosto 2026 sulle pagine Joyagoo attuali per acquisto, costi, servizi, pre-imballaggio e standard; decidono opzioni e misure live.",
  fr: "Vérifié le 27 août 2026 avec les pages Joyagoo actuelles d’achat, frais, services, pré-emballage et norme de colis ; options et mesures en direct font foi.",
  pt: "Verificado em 27 de agosto de 2026 nas páginas atuais Joyagoo de compra, taxas, serviços, ensaio e embalagem; valem opções e medidas ao vivo.",
  ro: "Verificat la 27 august 2026 cu paginile actuale Joyagoo despre cumpărare, taxe, servicii, probă și ambalare; decid opțiunile și măsurile live.",
  sv: "Kontrollerad 27 augusti 2026 mot aktuella Joyagoo-sidor om köp, avgifter, tjänster, provpackning och packstandard; livealternativ och packmått avgör.",
};
