import type { ArticlePageContent } from "./site-articles";
import type { Locale } from "./site-content";

const en: ArticlePageContent = {
  label: "Shipping line decision guide",
  title: "KameyMall Shipping Lines: Compare Cost, Speed and Restrictions",
  intro: "A practical framework for comparing the routes that actually appear for a packed warehouse parcel, without treating an estimate or delivery range as a guarantee.",
  updated: "Updated August 27, 2026",
  readTime: "15 minute read",
  sourceNote: "Fact-check basis: KameyMall’s current public purchasing and parcel-submission guidance, reviewed August 27, 2026. Available lines, restrictions, estimates, delivery ranges and final charges can change by parcel and destination; the live parcel screen is decisive.",
  primaryKeyword: "kameymall shipping lines",
  sections: [
    {
      heading: "Start with the parcel, not a remembered route name",
      paragraphs: [
        "The useful KameyMall shipping-line comparison begins only after the warehouse items are known. KameyMall’s published process separates the product order from the later international parcel: items arrive, receive a warehouse check, and are selected for parcel submission. The public parcel guidance says the user enters the destination and chooses from available delivery types. That sequence matters because a route mentioned in an old guide, a friend’s order or a general calculator may not be offered for your exact contents and address.",
        "Build a parcel record before comparing anything. List the warehouse item numbers, destination country and postal code, current warehouse weight, shown dimensions, packaging instructions and any product restriction label. Then open the live route list for that parcel. The comparison set is the lines actually displayed—not every line the platform has ever used. If a desired line is absent, treat it as unavailable until the live workflow or support identifies a correctable reason. Do not rename or misclassify an item merely to make a route appear.",
      ],
    },
    {
      heading: "Use four gates before looking for the cheapest quote",
      paragraphs: [
        "Gate one is eligibility. Every product in the parcel must be accepted by the selected line. KameyMall’s public guide warns that some products are restricted from certain delivery types, so a line visible for ordinary clothing cannot be assumed to accept a battery, liquid, magnet, fragile item or unusually large package. Gate two is destination coverage. Country-level service does not prove coverage for every postal code, remote area or address format. Confirm the exact delivery details in the live submission.",
        "Gate three is billable shape. A parcel may be compared by physical weight, dimensions or another route-specific charging rule. Do not import a volumetric divisor from a different line. Gate four is protection compatibility. A route that looks inexpensive may be a poor match if the required packaging removes the saving or if the product needs protection that the chosen plan does not preserve. Only lines passing all four gates belong in the price table. An ineligible quote is not a bargain; it is a non-option.",
      ],
    },
    {
      heading: "Compare cost on one worksheet and one set of assumptions",
      paragraphs: [
        "For each eligible line, record the quote time, currency, estimated billable weight, freight estimate, visible parcel-level charge, selected packaging service and any insurance amount shown. Keep the parcel contents and packing assumptions identical across rows. Comparing one line after box removal with another line while keeping every retail box mixes two decisions and produces a false winner. If you want to test another packing plan, create a second table and label it clearly.",
        "Use a normalized comparison rather than dividing every quote by warehouse kilograms. The warehouse figure may not equal packed or billable weight, and routes can use different increments. A simple decision score works better: current payable estimate, uncertainty before final measurement, packaging cost, protection fit and eligibility confidence. Do not fill missing cells with numbers from a forum post. Mark them unknown and ask whether the uncertainty is large enough to change the decision.",
        "Consider an abstract example, not a KameyMall rate. Line A shows 80 cost units with strong eligibility evidence and a narrow estimated-to-final uncertainty. Line B shows 74 units but depends on an unconfirmed size rule and extra reinforcement worth 9 units. Under the same protection requirement, B is not six units cheaper; its comparable planning cost is 83, and its measurement risk is higher. The example teaches the method, not a live price.",
      ],
    },
    {
      heading: "Read speed as a range with separate stages",
      paragraphs: [
        "A delivery estimate is not one uninterrupted clock. Separate warehouse processing, carrier acceptance, export handling, international movement, customs, local-carrier handoff and final delivery. A route can have a short published transit range yet still wait before the first carrier scan. Another route may move slowly abroad but update frequently. Compare the stage that matters to your deadline instead of reducing every line to one optimistic number.",
        "Record the displayed estimate with the date you checked and note what the page says the range covers. Do not convert a range into a promised arrival day. Weekends, peak periods, customs review, remote delivery and third-party carrier operations sit outside a simple calculation. If an item is genuinely time-sensitive, add a buffer and define a latest acceptable dispatch date. Once that date passes, paying more for a nominally faster line may no longer solve the underlying timing problem.",
      ],
    },
    {
      heading: "Turn restrictions into a parcel-design decision",
      paragraphs: [
        "When one item removes otherwise suitable lines, compare a targeted split rather than discarding the whole haul plan. Keep ordinary, route-compatible items together and isolate only the product creating the restriction, shape or protection conflict. Then compare the total of both valid parcels with the best valid consolidated option. This preserves a factual cost comparison and avoids the common mistake of comparing one complete parcel with only half of a split plan.",
        "Do not assume splitting always wins. Repeating initial weight brackets, packaging and parcel-level charges can offset the benefit. It is justified when it restores a meaningful line, prevents unsafe contact, releases urgent items or reduces an oversized shape enough to change billable weight. Save screenshots or notes showing which lines appeared for each plan. A defensible split has a named constraint and a complete two-parcel total, not a vague belief that smaller packages are always safer or cheaper.",
      ],
    },
    {
      heading: "Reconcile the estimate with the packed result",
      paragraphs: [
        "KameyMall’s public parcel guidance describes an international shipping deposit based on estimated item weight, selected shipping method and destination, followed by a final shipping cost based on the parcel’s confirmed size and weight. Treat the first screen as a planning estimate. After packing, compare the final parcel data with the saved assumptions: item count, route, packaging request, weight, dimensions and charge. A difference is a signal to reconcile the inputs before paying or accepting an adjustment.",
        "Ask five questions in order. Did the contents change? Did the warehouse add or retain packaging? Did the packed dimensions change the billable basis? Did the route or destination selection change? Is the new amount clearly identified as an estimate, deposit, adjustment or final charge? Keep the original quote and final record together. The goal is not to prove that every change is an error; it is to understand which input changed and whether the selected line remains the strongest valid choice.",
      ],
    },
    {
      heading: "Choose by priority, then run a final submission check",
      paragraphs: [
        "Choose the line that best fits the parcel’s dominant priority after eligibility. For a low-value, non-urgent, compact parcel, current total cost may lead. For a deadline, the useful comparison may be the most defensible delivery range plus tracking visibility and buffer. For fragile or high-value goods, protection compatibility and any clearly stated coverage conditions can outweigh a small price difference. Write the priority before viewing the quotes so the lowest number does not silently change the goal.",
        "Before submission, verify the recipient name, address, postal code and phone format; match every warehouse item to the parcel; confirm the selected line still appears; reread restriction notices; review package removal, reinforcement and insurance choices; save the dated quote; and leave a budget margin until final measurement. After dispatch, keep the parcel number and carrier handoff record separate from the original seller orders. One international parcel can contain several purchases, and that mapping matters when tracking or support questions arise.",
      ],
      bullets: [
        "Compare only lines displayed for the exact parcel and destination.",
        "Reject any line that fails product, address, shape or protection eligibility.",
        "Use identical contents and packing assumptions across cost rows.",
        "Treat delivery time as a range across several operational stages.",
        "Reconcile packed weight, dimensions and final charge with the saved estimate.",
        "Save the route decision, final parcel map, payment and tracking record.",
      ],
    },
  ],
  conclusionTitle: "The best shipping line is the best valid fit",
  conclusion: "A reliable KameyMall shipping-line choice is not the globally cheapest or fastest name. It is the eligible line that best fits this parcel’s destination, billable shape, protection needs, timing and verified live cost. Compare like with like, preserve the evidence and reconcile the packed result before treating the decision as final.",
  seoTitle: "KameyMall Shipping Lines: Cost, Speed & Restrictions",
  seoDescription: "Compare KameyMall shipping lines using live eligibility, parcel cost, delivery ranges, restrictions, packed dimensions and final-charge checks.",
};

type Translation = Omit<ArticlePageContent, "sections"> & { headings: string[]; paragraphs: string[][]; bullets: string[] };

function translated(base: Omit<Translation, "headings" | "paragraphs" | "bullets">, headings: string[], paragraphs: string[][], bullets: string[]): Translation {
  return { ...base, headings, paragraphs, bullets };
}

const translations: Record<Exclude<Locale, "en">, Translation> = {
  de: translated({ ...en, label: "Versandlinien-Ratgeber", title: "KameyMall-Versandlinien: Kosten, Laufzeit und Einschränkungen", intro: "Ein praktischer Vergleich der für das konkrete Lagerpaket angezeigten Linien – ohne Schätzungen als Garantie zu behandeln.", updated: "Aktualisiert am 27. August 2026", readTime: "15 Minuten Lesezeit", sourceNote: "Faktenbasis: aktuelle öffentliche KameyMall-Kauf- und Pakethinweise, geprüft am 27. August 2026. Linien, Einschränkungen, Schätzungen und Endkosten können sich ändern; die Live-Paketseite entscheidet.", primaryKeyword: "kameymall versandlinien", conclusionTitle: "Die beste Linie ist die beste gültige Passung", conclusion: "Wähle die zulässige Linie, die Ziel, abrechenbare Form, Schutz, Zeit und aktuellen Preis dieses Pakets am besten verbindet. Vergleiche gleiche Annahmen und gleiche Packdaten vor der endgültigen Entscheidung ab.", seoTitle: "KameyMall-Versandlinien vergleichen", seoDescription: "KameyMall-Linien nach Zulässigkeit, Kosten, Laufzeit, Einschränkungen, Packmaßen und Endbetrag vergleichen." }, ["Mit dem Paket beginnen, nicht mit einem alten Liniennamen", "Vier Filter vor dem billigsten Angebot", "Kosten mit identischen Annahmen vergleichen", "Laufzeit als Bereich mehrerer Stufen lesen", "Einschränkungen in Paketplanung übersetzen", "Schätzung und Packresultat abgleichen", "Priorität festlegen und final prüfen"], [
    ["Der Vergleich beginnt nach Lagereingang und QC. Die öffentliche Anleitung trennt Produktkauf und internationales Paket; Ziel und verfügbare Lieferart werden erst bei der Paketeinreichung gewählt. Eine alte oder fremde Route gehört nicht automatisch zur Auswahl.", "Notiere Lagernummern, Land, Postleitzahl, Gewicht, Maße, Verpackung und Kennzeichnungen. Vergleiche nur live angezeigte Linien. Eine fehlende Linie bleibt unzulässig, bis die aktuelle Oberfläche oder der Support einen korrigierbaren Grund bestätigt."],
    ["Prüfe Produktzulässigkeit und genaue Zielabdeckung. Eine Linie für Kleidung muss Batterie, Flüssigkeit, Magnet, zerbrechliche oder große Ware nicht annehmen.", "Prüfe danach abrechenbare Form und Schutz. Übertrage keinen Volumendivisor einer anderen Linie. Nur Optionen, die Produkt, Adresse, Form und Schutz bestehen, gehören in die Preistabelle."],
    ["Notiere je Linie Zeitpunkt, Währung, geschätztes Abrechnungsgewicht, Fracht, Paketgebühren, Verpackung und Versicherung. Inhalte und Verpackungsannahmen müssen gleich bleiben; ein anderer Packplan erhält eine neue Tabelle.", "Bewerte Gesamtangebot, Messunsicherheit, Verpackungskosten, Schutz und Zulässigkeit. Fehlende Werte bleiben offen.", "Abstrakte Vergleichseinheiten können die Methode zeigen, sind aber keine KameyMall-Tarife oder Live-Angebote."],
    ["Trenne Lagerbearbeitung, Übergabe, Export, internationalen Lauf, Zoll, lokalen Carrier und Zustellung. Eine kurze Spanne kann trotzdem vor dem ersten Scan warten.", "Speichere die angezeigte Spanne mit Datum und Umfang. Sie ist kein Ankunftsversprechen. Plane Puffer für Wochenende, Hochsaison, Zoll und Drittanbieter ein."],
    ["Blockiert ein Artikel passende Linien, vergleiche eine gezielte Trennung: kompatible Ware zusammen, Konfliktartikel separat. Vergleiche die vollständige Summe beider Pakete mit dem gültigen Gesamtpaket.", "Teilung lohnt nur bei wiederhergestellter Linie, besserem Schutz, dringender Freigabe oder günstigerer Packform. Wiederholte Start- und Paketkosten können den Vorteil aufheben."],
    ["Die öffentliche Anleitung beschreibt eine Schätzung nach Gewicht, Methode und Ziel und einen Endbetrag nach bestätigten Maßen und Gewicht. Sichere die erste Ansicht und vergleiche Inhalt, Verpackung, Gewicht, Maße, Linie und Betrag nach dem Packen.", "Frage, ob Inhalt, Verpackung, Abrechnungsbasis, Route oder Ziel wechselten und wie der Betrag bezeichnet ist. Eine Änderung ist nicht automatisch ein Fehler, muss aber erklärbar sein."],
    ["Lege zuerst die Priorität fest: Preis für unkritische Ware, belastbare Laufzeit mit Puffer für Termine oder Schutz und klare Bedingungen für empfindliche Werte.", "Prüfe Empfänger, Adresse, Artikel, Linie, Hinweise, Verpackung, Versicherung und Budgetreserve. Bewahre Paketnummer und Carrier-Übergabe getrennt von Verkäuferaufträgen auf."],
  ], ["Nur Linien für genaues Paket und Ziel vergleichen.", "Produkt, Adresse, Form und Schutz prüfen.", "Gleiche Inhalte und Verpackung verwenden.", "Laufzeit als mehrstufige Spanne behandeln.", "Packdaten und Endbetrag abgleichen.", "Entscheidung, Paketplan, Zahlung und Tracking sichern."]),
  fr: translated({ ...en, label: "Guide des lignes d’expédition", title: "Lignes KameyMall : comparer coût, délai et restrictions", intro: "Une méthode pratique pour comparer les lignes réellement proposées au colis, sans transformer une estimation en garantie.", updated: "Mis à jour le 27 août 2026", readTime: "15 minutes de lecture", sourceNote: "Base factuelle : guide d’achat et de soumission de colis KameyMall, vérifié le 27 août 2026. Les lignes, restrictions, estimations et montants finaux peuvent changer ; l’écran actif fait foi.", primaryKeyword: "lignes d’expédition kameymall", conclusionTitle: "La meilleure ligne est la meilleure option valide", conclusion: "Choisissez la ligne admissible qui correspond au pays, à la forme facturable, à la protection, au délai et au coût actif de ce colis. Comparez les mêmes hypothèses et rapprochez le résultat emballé.", seoTitle: "Comparer les lignes KameyMall", seoDescription: "Comparez les lignes KameyMall par admissibilité, coût, délai, restrictions, dimensions emballées et montant final." }, ["Partir du colis, pas d’un ancien nom de ligne", "Quatre filtres avant le prix", "Comparer les coûts sur les mêmes hypothèses", "Lire le délai comme une plage d’étapes", "Transformer les restrictions en plan de colis", "Rapprocher estimation et colis emballé", "Choisir la priorité et vérifier"], [
    ["La comparaison commence après arrivée et QC. Le processus public sépare achat et colis international ; la destination et les types disponibles apparaissent lors de la soumission. Une ligne vue ailleurs n’est pas automatiquement disponible.", "Notez numéros d’entrepôt, pays, code postal, poids, dimensions, emballage et restrictions. Comparez uniquement les lignes affichées. Une ligne absente reste indisponible sans confirmation actuelle."],
    ["Vérifiez l’admissibilité de chaque produit et l’adresse exacte. Vêtements, batteries, liquides, aimants, fragiles et hors format peuvent différer.", "Vérifiez ensuite forme facturable et protection. N’empruntez pas le diviseur d’une autre ligne. Seules les options qui passent les quatre filtres entrent dans le tableau."],
    ["Enregistrez heure, devise, poids facturable estimé, fret, frais visibles, emballage et assurance. Gardez contenu et hypothèses identiques ; créez un second tableau pour un autre emballage.", "Évaluez total, incertitude de mesure, coût de protection et confiance d’admissibilité. Laissez les inconnues ouvertes.", "Les unités abstraites expliquent la méthode et ne sont ni des tarifs ni des devis KameyMall."],
    ["Séparez traitement, prise en charge, export, trajet, douane, relais local et livraison. Une plage courte peut encore attendre son premier scan.", "Sauvegardez la plage et ce qu’elle couvre. Ce n’est pas une date promise ; ajoutez une marge pour week-ends, pointe, douane et tiers."],
    ["Si un article bloque les lignes, comparez une séparation ciblée : groupe compatible et article conflictuel. Additionnez les deux colis avant de comparer.", "La séparation se justifie par ligne restaurée, protection, urgence ou meilleure forme. Les frais initiaux et colis répétés peuvent annuler le gain."],
    ["Le guide public distingue dépôt estimé et coût final selon dimensions et poids confirmés. Comparez contenu, emballage, poids, mesures, ligne et montant après emballage.", "Identifiez tout changement de contenu, protection, base de calcul, ligne ou destination et le libellé du montant. Une différence doit être comprise, pas automatiquement contestée."],
    ["Fixez la priorité : coût, délai défendable avec marge, ou protection et conditions pour un objet sensible.", "Vérifiez destinataire, adresse, articles, ligne, avis, emballage, assurance et réserve. Conservez le lien entre commandes et numéro de colis."],
  ], ["Comparer seulement les lignes du colis exact.", "Valider produit, adresse, forme et protection.", "Garder les mêmes hypothèses.", "Traiter le délai comme une plage.", "Rapprocher mesures et montant final.", "Conserver décision, paiement et suivi."]),
  es: translated({ ...en, label: "Guía de líneas de envío", title: "Líneas KameyMall: compara coste, plazo y restricciones", intro: "Un marco práctico para comparar las líneas que aparecen para el paquete real sin convertir estimaciones en garantías.", updated: "Actualizado el 27 de agosto de 2026", readTime: "15 minutos de lectura", sourceNote: "Base factual: guías públicas de compra y envío de paquetes KameyMall, revisadas el 27 de agosto de 2026. Líneas, restricciones, estimaciones e importes pueden cambiar; manda la pantalla activa.", primaryKeyword: "líneas de envío kameymall", conclusionTitle: "La mejor línea es la opción válida que mejor encaja", conclusion: "Elige la línea elegible que mejor una destino, forma facturable, protección, tiempo y coste activo del paquete. Compara las mismas condiciones y concilia el resultado embalado.", seoTitle: "Comparar líneas de envío KameyMall", seoDescription: "Compara líneas KameyMall por elegibilidad, coste, plazo, restricciones, dimensiones e importe final." }, ["Empieza por el paquete, no por un nombre antiguo", "Cuatro filtros antes del precio", "Compara costes con iguales supuestos", "Lee el plazo como varias etapas", "Convierte restricciones en diseño del paquete", "Concilia estimación y embalaje final", "Fija la prioridad y revisa"], [
    ["La comparación empieza tras llegada y QC. El proceso separa compra y paquete internacional; destino y tipos disponibles se eligen al enviarlo. Una ruta antigua o ajena no forma parte automática de tu lista.", "Anota números, país, código postal, peso, medidas, embalaje y restricciones. Compara solo líneas visibles. Si no aparece, trátala como no disponible hasta una confirmación actual."],
    ["Comprueba elegibilidad de cada producto y cobertura de la dirección. Ropa, baterías, líquidos, imanes, frágiles y bultos grandes pueden tener reglas distintas.", "Comprueba forma facturable y protección. No copies un divisor de otra línea. Solo opciones que pasan producto, dirección, forma y protección llegan al precio."],
    ["Registra hora, moneda, peso facturable estimado, flete, cargos, embalaje y seguro. Mantén idénticos contenido y supuestos; otro plan de embalaje necesita otra tabla.", "Valora total, incertidumbre, coste de protección y confianza. Deja vacíos los datos no probados.", "Las unidades abstractas enseñan el método y no son tarifas ni cotizaciones KameyMall."],
    ["Separa preparación, aceptación, exportación, tránsito, aduana, operador local y entrega. Un plazo corto puede esperar antes del primer escaneo.", "Guarda la franja con fecha y alcance. No es una promesa; añade margen por fines de semana, temporada, aduanas y terceros."],
    ["Si un artículo bloquea líneas, compara una división dirigida: compatibles juntos y conflicto aparte. Suma ambos paquetes frente al plan unido válido.", "Divide solo si recupera una línea, protege, adelanta lo urgente o mejora forma. Los cargos iniciales repetidos pueden anularlo."],
    ["La guía pública distingue depósito estimado y coste final por tamaño y peso confirmados. Revisa contenido, embalaje, peso, medidas, línea e importe tras empaquetar.", "Identifica cambios de contenido, material, base, ruta o destino y el tipo de cifra. Una diferencia exige conciliación, no una acusación automática."],
    ["Define primero si domina coste, plazo con margen o protección y condiciones claras.", "Verifica destinatario, dirección, artículos, línea, avisos, embalaje, seguro y reserva. Guarda número y traspaso del transportista."],
  ], ["Compara solo líneas del paquete exacto.", "Valida producto, dirección, forma y protección.", "Usa los mismos supuestos.", "Trata el plazo como una franja.", "Concilia medidas e importe final.", "Guarda decisión, pago y seguimiento."]),
  it: translated({ ...en, label: "Guida alle linee di spedizione", title: "Linee KameyMall: confrontare costo, tempi e restrizioni", intro: "Un metodo pratico per confrontare le linee mostrate per il pacco reale, senza trasformare una stima in garanzia.", updated: "Aggiornato il 27 agosto 2026", readTime: "15 minuti di lettura", sourceNote: "Base dei fatti: attuali guide pubbliche KameyMall per acquisto e invio, verificate il 27 agosto 2026. Linee, restrizioni, stime e importi possono cambiare; vale la schermata live.", primaryKeyword: "linee di spedizione kameymall", conclusionTitle: "La linea migliore è l’opzione valida più adatta", conclusion: "Scegli la linea ammessa che meglio unisce destinazione, forma fatturabile, protezione, tempi e costo attuale. Confronta ipotesi uguali e riconcilia il risultato imballato.", seoTitle: "Confronto linee KameyMall", seoDescription: "Confronta linee KameyMall per idoneità, costo, tempi, restrizioni, dimensioni e importo finale." }, ["Partire dal pacco, non da un vecchio nome", "Quattro filtri prima del prezzo", "Confrontare costi con ipotesi uguali", "Leggere i tempi come più fasi", "Tradurre le restrizioni nel piano pacco", "Riconciliare stima e pacco finito", "Stabilire la priorità e controllare"], [
    ["Il confronto inizia dopo arrivo e QC. Il flusso separa acquisto e pacco internazionale; destinazione e tipi disponibili si scelgono alla presentazione. Una linea vista altrove non è automaticamente disponibile.", "Registra articoli, paese, CAP, peso, misure, imballo e restrizioni. Confronta solo linee live. Una linea assente resta non disponibile senza conferma attuale."],
    ["Verifica idoneità del prodotto e copertura dell’indirizzo. Abbigliamento, batteria, liquido, magnete, fragile e fuori misura possono differire.", "Verifica forma fatturabile e protezione. Non copiare il divisore di un’altra linea. Solo le opzioni che superano i quattro filtri vanno al prezzo."],
    ["Annota ora, valuta, peso fatturabile stimato, nolo, costi, imballo e assicurazione. Mantieni contenuti e ipotesi uguali; un altro imballo richiede nuova tabella.", "Valuta totale, incertezza, costo protezione e fiducia. Lascia ignoti i dati non provati.", "Le unità astratte spiegano il metodo e non sono tariffe o preventivi KameyMall."],
    ["Separa lavorazione, presa in carico, export, transito, dogana, corriere locale e consegna. Una finestra breve può attendere il primo scan.", "Salva intervallo, data e significato. Non è una promessa; aggiungi margine per weekend, picchi, dogana e terzi."],
    ["Se un articolo blocca linee, confronta una divisione mirata: compatibili insieme e conflitto separato. Somma entrambi i pacchi.", "Dividi se recupera una linea, protegge, libera l’urgenza o migliora la forma. I costi iniziali ripetuti possono annullare il vantaggio."],
    ["La guida distingue deposito stimato e costo finale secondo misure e peso confermati. Confronta contenuto, imballo, peso, dimensioni, linea e importo dopo l’imballo.", "Individua variazioni di contenuto, materiali, base, linea o destinazione e il tipo di importo. La differenza va spiegata."],
    ["Definisci se conta soprattutto costo, tempo con margine oppure protezione e condizioni.", "Verifica destinatario, indirizzo, articoli, linea, avvisi, imballo, assicurazione e riserva. Conserva numero e passaggio al vettore."],
  ], ["Confronta solo linee del pacco esatto.", "Valida prodotto, indirizzo, forma e protezione.", "Usa ipotesi uguali.", "Tratta i tempi come intervallo.", "Riconcilia misure e importo.", "Salva decisione, pagamento e tracking."]),
  pl: translated({ ...en, label: "Poradnik linii wysyłkowych", title: "Linie KameyMall: porównaj koszt, czas i ograniczenia", intro: "Praktyczna metoda porównania linii pokazanych dla rzeczywistej paczki bez traktowania szacunku jak gwarancji.", updated: "Zaktualizowano 27 sierpnia 2026", readTime: "15 minut czytania", sourceNote: "Podstawa faktów: aktualne publiczne instrukcje zakupu i wysyłki KameyMall, sprawdzone 27 sierpnia 2026. Linie, ograniczenia, szacunki i kwoty mogą się zmieniać; decyduje ekran bieżący.", primaryKeyword: "linie wysyłkowe kameymall", conclusionTitle: "Najlepsza linia to najlepsze prawidłowe dopasowanie", conclusion: "Wybierz dopuszczoną linię pasującą do celu, kształtu rozliczeniowego, ochrony, czasu i bieżącego kosztu. Porównuj te same założenia i uzgodnij wynik pakowania.", seoTitle: "Porównanie linii KameyMall", seoDescription: "Porównaj linie KameyMall według dopuszczenia, kosztu, czasu, ograniczeń, wymiarów i kwoty końcowej." }, ["Zacznij od paczki, nie starej nazwy linii", "Cztery filtry przed ceną", "Porównuj koszt przy tych samych założeniach", "Czytaj czas jako ciąg etapów", "Zamień ograniczenia w plan paczki", "Uzgodnij szacunek z gotową paczką", "Ustal priorytet i sprawdź"], [
    ["Porównanie zaczyna się po przyjęciu i QC. Proces oddziela zakup od paczki międzynarodowej; cel i dostępne typy wybiera się przy nadaniu. Dawna lub cudza linia nie musi być dostępna.", "Zapisz numery, kraj, kod, masę, wymiary, pakowanie i ograniczenia. Porównuj tylko linie wyświetlone na żywo. Brak linii oznacza brak opcji bez aktualnego potwierdzenia."],
    ["Sprawdź dopuszczenie produktu i adresu. Odzież, bateria, płyn, magnes, kruche i duże towary mogą mieć inne reguły.", "Sprawdź kształt rozliczeniowy i ochronę. Nie kopiuj dzielnika z innej linii. Do tabeli cen trafiają tylko opcje przechodzące cztery filtry."],
    ["Zapisz czas, walutę, szacowaną masę rozliczeniową, fracht, opłaty, pakowanie i ubezpieczenie. Zachowaj te same towary i założenia; inny plan wymaga osobnej tabeli.", "Oceń łączną kwotę, niepewność, koszt ochrony i pewność dopuszczenia. Braków nie zgaduj.", "Abstrakcyjne jednostki wyjaśniają metodę i nie są stawką ani wyceną KameyMall."],
    ["Rozdziel obróbkę, przyjęcie przez przewoźnika, eksport, trasę, cło, lokalne przekazanie i dostawę. Krótki zakres może czekać na pierwszy skan.", "Zachowaj zakres z datą i znaczeniem. To nie gwarancja; dodaj zapas na weekendy, szczyt, cło i strony trzecie."],
    ["Gdy jeden towar blokuje linie, porównaj celowy podział: zgodne razem, konflikt osobno. Zsumuj obie paczki względem ważnego planu wspólnego.", "Podział ma sens, gdy odzyskuje linię, chroni, przyspiesza pilne lub poprawia kształt. Powtórzone opłaty mogą zniwelować zysk."],
    ["Publiczna instrukcja rozróżnia depozyt szacowany i koszt końcowy według potwierdzonej masy i wymiarów. Po pakowaniu sprawdź zawartość, materiały, wagę, wymiary, linię i kwotę.", "Ustal, co się zmieniło i jak opisano kwotę. Różnica nie dowodzi błędu, ale wymaga zrozumienia."],
    ["Najpierw określ priorytet: koszt, czas z buforem lub ochrona i jasne warunki.", "Sprawdź odbiorcę, adres, towary, linię, ostrzeżenia, pakowanie, ubezpieczenie i rezerwę. Zachowaj numer oraz przekazanie przewoźnikowi."],
  ], ["Porównuj tylko linie dla dokładnej paczki.", "Sprawdź produkt, adres, kształt i ochronę.", "Użyj tych samych założeń.", "Traktuj czas jako zakres.", "Uzgodnij wymiary i kwotę.", "Zachowaj decyzję, płatność i śledzenie."]),
};

export const shippingLineArticles: Record<Locale, ArticlePageContent> = {
  en,
  ...Object.fromEntries(Object.entries(translations).map(([locale, article]) => {
    const { headings, paragraphs, bullets, ...base } = article;
    return [locale, { ...base, sections: headings.map((heading, index) => ({ heading, paragraphs: paragraphs[index], bullets: index === headings.length - 1 ? bullets : undefined })) }];
  })) as Record<Exclude<Locale, "en">, ArticlePageContent>,
};
