import type { ArticlePageContent } from "./site-articles";
import type { Locale } from "./site-content";

const en: ArticlePageContent = {
  label: "Tracking troubleshooting guide",
  title: "KameyMall Tracking Statuses: Diagnose a Parcel With No Updates",
  intro: "A stage-by-stage method for reading KameyMall parcel tracking, separating normal handoffs from actionable gaps, and building a useful evidence timeline.",
  updated: "Updated August 29, 2026",
  readTime: "14 minute read",
  sourceNote: "Fact-check basis: KameyMall’s current public purchase, warehouse and parcel workflow, reviewed August 29, 2026. Carrier scans, customs handling and delivery timing are controlled by third parties; the live parcel and carrier records remain decisive.",
  primaryKeyword: "KameyMall tracking status",
  sections: [
    { heading: "First identify which order you are tracking", paragraphs: [
      "A KameyMall purchase produces more than one journey. The marketplace seller first sends an item to the warehouse in China. After warehouse arrival, inspection and storage, the buyer can create an international parcel. Seller tracking, warehouse order status and international parcel tracking describe different objects. A seller number does not follow the later consolidated parcel, and an international parcel number does not explain why one original seller has not dispatched.",
      "Start by writing down the product order number, seller tracking number if available, warehouse item number, international parcel number and the carrier reference shown after dispatch. Map each number to its stage. If several purchases were consolidated, record which warehouse items are inside the parcel. This simple map prevents support from investigating a seller delivery when the real question concerns international carrier acceptance, or treating one item’s delay as a problem with the whole parcel."
    ]},
    { heading: "Read status as evidence of the last completed event", paragraphs: [
      "A status is evidence that one recorded event occurred; it is not a promise that the next event will happen by a fixed hour. Purchased means the buying step was recorded, not that the seller has shipped. Seller-dispatched information concerns movement toward the warehouse. Warehouse arrival and QC concern the item record. Parcel submission, payment, packing, dispatch and carrier scans belong to the international shipment. Always ask: what is the last event confirmed, and who controls the next one?",
      "Build a timeline with four columns: timestamp, exact status text, responsible party and missing next event. Preserve the original wording instead of translating every label into ‘in transit.’ A gap after purchase points toward seller dispatch; a gap after a carrier label is created may mean the parcel has not yet received its first physical scan; a gap after export or airline handling is different again. This classification makes the next check specific rather than emotional."
    ]},
    { heading: "Why tracking can pause without proving loss", paragraphs: [
      "International tracking is assembled from multiple systems. A warehouse or shipping partner may create a label before the carrier scans the parcel. Export processing can batch parcels. A line may use one logistics provider in China and another after arrival, producing a handoff gap or a second reference number. Customs can hold a shipment without publishing a detailed public message. Weekends, peak periods, weather and delayed data exchange can also create silence after real movement.",
      "None of these possibilities proves that a particular parcel is safe. They explain why ‘no update’ is a symptom, not a diagnosis. Compare the silence with the last meaningful event, the live line’s current guidance and any estimated range shown for that shipment. Do not copy a waiting threshold from another route, country or old forum post. If KameyMall or the carrier displays an escalation date, use that current date; otherwise ask support which next scan is expected for this exact line."
    ]},
    { heading: "Run the no-update checklist in the right order", paragraphs: [
      "First confirm that you are entering the international tracking number rather than a product order or seller number. Copy it without spaces and open the carrier linked from the current parcel record. Second, compare KameyMall’s last status with the carrier’s last event and timestamp. Third, look for a replacement or local-carrier number in the event text. Fourth, confirm that the recipient address and contact details saved at submission are correct. Fifth, check whether the parcel is awaiting carrier acceptance, export, customs, local handoff or final delivery.",
      "Refreshes do not create evidence, so save one dated snapshot rather than checking every few minutes. Record the line, destination, dispatch date, last event, last event location if shown, tracking number, any local number and the date you checked. Search the carrier only after confirming its identity from the parcel record; similarly named tracking sites can be unofficial. Do not publish your full tracking number, name, phone or address in a public post."
    ]},
    { heading: "Decide whether to wait, ask, or escalate", paragraphs: [
      "Wait when the parcel is still inside the current line’s stated range, the last scan fits a known stage and no action request appears. Ask KameyMall for clarification when platform and carrier records conflict, a handoff number is missing, the shown stage is ambiguous or the current route guidance indicates that a next scan should exist. Contact the local carrier when it has accepted the shipment, attempted delivery, requested address information or posted an exception that only the recipient can resolve.",
      "Escalate as a possible loss or claim only under the current route, carrier or insurance conditions. Insurance eligibility and evidence requirements can vary, so do not assume that silence alone opens a claim. Preserve the parcel contents, packing choices, declared information, payment, insurance selection and full tracking history. If a deadline is shown, act before it. A useful escalation states what has been checked and asks for a defined next action rather than demanding an unsupported delivery guarantee."
    ]},
    { heading: "Write a support request that can be investigated", paragraphs: [
      "Use a compact evidence packet: international parcel number; destination country and postal-code prefix; selected line; dispatch date; last exact KameyMall status with timestamp; last carrier event with timestamp; any local-carrier reference; and the requested outcome. A strong request might ask whether the carrier has physically accepted the parcel, whether a new reference was assigned, or whether the current gap meets the line’s investigation rule.",
      "Avoid mixing unrelated product issues into the same message. A missing warehouse item, a packing complaint and an international scan gap can involve different records and teams. Also avoid conclusions such as stolen, seized or lost unless a responsible party has confirmed them. Describe observable facts: no carrier event after label creation, export event with no later handoff, customs request awaiting recipient response, or delivery attempt at the wrong address. Facts are easier to route and verify."
    ]},
    { heading: "Close the record after delivery or resolution", paragraphs: [
      "When tracking resumes, add the new event rather than deleting the gap. The full timeline helps you distinguish a delayed scan from delayed physical movement on future parcels. At delivery, preserve the label and photograph the outer carton before opening if damage is visible. Match the received contents to the warehouse-item map. Tracking proves recorded movement; it does not by itself prove that every item arrived undamaged or that the carrier caused a product issue.",
      "For the next parcel, choose the shipping line using the evidence that mattered this time: clarity of handoffs, useful tracking detail, destination coverage and the parcel’s protection needs, alongside price and estimated speed. One experience is not a universal route rating, but it can improve your own decision record. The durable method is to identify the stage, save the exact event, contact the party responsible for the next event and keep private information out of public troubleshooting.",
      "Keep one private ledger row per international parcel. Include the warehouse-item map, route as displayed, destination, parcel-payment date, dispatch date, first carrier scan, export event, handoff number, customs event if any, delivery attempt and final result. Link to saved evidence rather than placing an address, phone number or full tracking reference in a public document. This produces a reusable record without exposing personal data.",
      "After several parcels, compare stages instead of declaring one line universally fast or slow. You may learn that one route provides clearer handoffs for your destination or that label-to-first-scan gaps are common within a bounded range in your own records. Those observations improve future questions, but they remain dated personal evidence—not a promise about another season, destination, carrier or parcel.",
    ], bullets: [
      "Map seller, warehouse and international tracking numbers before diagnosing.",
      "Save exact status text, timestamp and the party responsible for the next event.",
      "Check the carrier and any local handoff number shown in the parcel record.",
      "Use the current line’s guidance instead of an old universal waiting threshold.",
      "Send a compact evidence packet and request one defined next action.",
      "Preserve insurance, parcel contents and tracking history until resolution."
    ]}
  ],
  conclusionTitle: "A tracking gap needs a stage, not a guess",
  conclusion: "Treat KameyMall tracking as a chain of recorded events across seller, warehouse, export, carrier, customs and local delivery systems. Identify the last completed event, verify the number and responsible party, preserve the evidence, and escalate only under the current line’s rules.",
  seoTitle: "KameyMall Tracking Status & No-Update Checklist",
  seoDescription: "Understand KameyMall tracking statuses, carrier handoffs and no-update gaps with a practical evidence checklist and support escalation workflow."
};

type Local = Omit<ArticlePageContent,"sections"> & { headings:string[]; paragraphs:string[][]; bullets:string[] };
const build=(x:Local):ArticlePageContent=>({...x,sections:x.headings.map((heading,i)=>({heading,paragraphs:x.paragraphs[i],...(i===x.headings.length-1?{bullets:x.bullets}:{})}))});
const shared=(title:string,intro:string,updated:string,keyword:string,seoTitle:string,seoDescription:string,headings:string[],paragraphs:string[][],bullets:string[]):Local=>({label:title,title,intro,updated,readTime:"14 min",sourceNote:intro,primaryKeyword:keyword,headings,paragraphs,bullets,conclusionTitle:headings[headings.length-1],conclusion:paragraphs[paragraphs.length-1][1],seoTitle,seoDescription});
const de=build(shared("KameyMall Tracking-Status: Paket ohne Updates prüfen","Ein stufenweiser Leitfaden für Status, Übergaben und belegbare Supportanfragen.","Aktualisiert am 29. August 2026","kameymall tracking status","KameyMall Tracking ohne Update prüfen","KameyMall Tracking-Status, Übergaben und Belege richtig prüfen.",["Zuerst das richtige Objekt bestimmen","Status als letztes bestätigtes Ereignis lesen","Warum Scans pausieren können","Checkliste in richtiger Reihenfolge","Warten, fragen oder eskalieren","Eine prüfbare Anfrage schreiben","Den Datensatz abschließen"],[
["Verkäuferweg, Lagerartikel und internationales Paket haben verschiedene Nummern. Ordne Bestellnummer, China-Tracking, Lager-ID, Paketnummer und Carrier-Referenz jeweils der richtigen Stufe zu.","Bei Konsolidierung notierst du alle enthaltenen Lagerartikel. So untersucht der Support nicht die Verkäuferzustellung, wenn die Frage bereits den internationalen Carrier betrifft."],
["Ein Status bestätigt ein Ereignis, garantiert aber keinen Zeitpunkt des nächsten. Notiere Wortlaut, Zeitstempel, verantwortliche Partei und fehlendes Folgeereignis.","Nach Kauf ist der Verkäufer zuständig, nach Lagerankunft Empfang und QC, nach internationalem Versand Carrier, Zoll oder lokaler Zusteller. Diese Trennung bestimmt die richtige Anfrage."],
["Label-Erstellung kann vor dem ersten Scan erfolgen; Exportbündelung, Carrierwechsel, Zoll, Wochenende und Datenaustausch können Lücken erzeugen.","Das beweist weder Verlust noch Sicherheit. Vergleiche die Lücke mit der letzten Stufe und den aktuellen Angaben der sichtbaren Linie; übernimm keine Wartefrist einer anderen Route."],
["Prüfe internationale Nummer, verknüpften Carrier, letzte Ereignisse in beiden Systemen, mögliche lokale Nummer, Adresse und aktuelle Stufe.","Speichere einen datierten Stand mit Linie, Ziel, Versanddatum, Ereignis und Ort. Veröffentliche niemals vollständige Nummer, Name, Telefon oder Adresse."],
["Warte innerhalb der aktuellen Spanne ohne Warnung. Frage bei widersprüchlichen Daten oder fehlender Übergabe. Kontaktiere den lokalen Carrier nach Annahme, Zustellversuch oder Empfängeranforderung.","Eine Verlust- oder Versicherungsprüfung folgt nur den aktuellen Bedingungen. Bewahre Inhalt, Verpackung, Zahlung, Versicherung und Verlauf bis zur Lösung auf."],
["Nenne Paketnummer, Land, Linie, Versanddatum, letzte Plattform- und Carrier-Ereignisse, lokale Nummer und gewünschte nächste Aktion.","Mische keine Produkt-, Pack- und Trackingprobleme. Beschreibe beobachtbare Fakten und behaupte Verlust oder Beschlagnahme erst nach Bestätigung."],
["Ergänze neue Scans, statt die Lücke zu löschen. Prüfe bei Zustellung Karton, Label und Inhalt gegen die Lagerliste.","Nutze die Erfahrung später für Übergabeklarheit und Trackingqualität, aber nicht als allgemeine Routengarantie. Entscheidend bleiben Stufe, Beleg und zuständige Partei.","Führe je Paket eine private Zeile mit Lagerartikeln, Route, Ziel, Zahlung, Versand, erstem Scan, Export, Übergabe, Zollereignis und Ergebnis. Persönliche Daten gehören nicht in öffentliche Tabellen.","Vergleiche nach mehreren Paketen einzelne Stufen statt pauschaler Routennoten. Eigene Muster sind datierte Erfahrungen, keine Zusage für andere Ziele oder Saisons."]],
["Nummern den Stufen zuordnen.","Wortlaut und Zeit sichern.","Carrier und lokale Nummer prüfen.","Aktuelle Linienregel verwenden.","Eine klare Aktion erfragen.","Belege bis zur Lösung behalten."]));
const fr=build(shared("Suivi KameyMall sans mise à jour : méthode de diagnostic","Lire les statuts, relais transporteurs et silences avec une chronologie vérifiable.","Mis à jour le 29 août 2026","statut suivi kameymall","Suivi KameyMall sans mise à jour","Diagnostiquer un suivi KameyMall et préparer une demande utile.",["Identifier le bon objet","Lire le dernier événement confirmé","Pourquoi un suivi peut se taire","Exécuter la liste dans l’ordre","Attendre, demander ou escalader","Rédiger une demande exploitable","Clore le dossier"],[
["Commande vendeur, article d’entrepôt et colis international possèdent des références distinctes. Associez numéro de commande, suivi chinois, ID d’entrepôt, colis et transporteur à leur étape.","Pour un colis consolidé, listez tous les articles. Le support pourra ainsi examiner le bon parcours et non une livraison vendeur déjà terminée."],
["Un statut prouve un événement, sans promettre l’heure du suivant. Notez le texte exact, l’heure, la partie responsable et l’événement attendu.","Après achat intervient le vendeur; après arrivée, réception et QC; après expédition, transporteur, douane ou opérateur local. Cette attribution détermine la bonne question."],
["Une étiquette peut précéder le premier scan; regroupement export, relais, douane, week-end et échange de données peuvent créer un silence.","Cela ne prouve ni perte ni sécurité. Comparez avec la dernière étape et les indications actuelles de la ligne; n’empruntez pas un délai à une autre route."],
["Vérifiez numéro international, transporteur lié, derniers événements des deux systèmes, numéro local, adresse et étape actuelle.","Conservez une capture datée avec ligne, destination, date, événement et lieu. Ne publiez jamais numéro complet, nom, téléphone ou adresse."],
["Attendez si la plage active reste normale. Demandez une clarification si les systèmes divergent. Contactez l’opérateur local après prise en charge, tentative ou demande au destinataire.","Une enquête perte ou assurance suit uniquement les conditions actuelles. Gardez contenu, emballage, paiement, couverture et historique."],
["Donnez colis, pays, ligne, date, derniers événements, relais local et résultat demandé.","Séparez problèmes produit, emballage et suivi. Décrivez des faits; n’affirmez perte ou saisie qu’après confirmation."],
["Ajoutez la reprise du suivi à la chronologie. À réception, vérifiez carton, étiquette et contenu contre la liste d’entrepôt.","Utilisez cette expérience pour vos prochains critères, sans en faire une note universelle. Étape, preuve et responsable restent la méthode durable.","Conservez une ligne privée par colis avec articles, ligne, destination, paiement, départ, premier scan, export, relais, douane et résultat. Les données personnelles restent hors des tableaux publics.","Après plusieurs colis, comparez les étapes plutôt qu’une note globale. Vos tendances sont des preuves datées, jamais une promesse pour une autre saison ou destination."]],
["Associer chaque numéro.","Sauvegarder texte et heure.","Contrôler le relais local.","Utiliser la règle actuelle.","Demander une action définie.","Conserver les preuves."]));
const es=build(shared("Seguimiento KameyMall sin actualizaciones: diagnóstico por etapas","Una guía para interpretar estados, traspasos y silencios con pruebas.","Actualizado el 29 de agosto de 2026","estado de seguimiento kameymall","Seguimiento KameyMall sin actualización","Comprueba estados y traspasos de seguimiento KameyMall.",
["Identifica primero qué pedido sigues","Lee el estado como último evento confirmado","Por qué puede detenerse el seguimiento","Ejecuta la lista en orden","Decide si esperar, preguntar o escalar","Escribe una solicitud investigable","Cierra el registro"],[
["El viaje del vendedor, el artículo de almacén y el paquete internacional tienen referencias diferentes. Asocia pedido, seguimiento chino, ID de almacén, paquete y transportista con su etapa.","Si el paquete agrupa compras, anota todos los artículos incluidos. Así soporte investigará el trayecto correcto y no una entrega nacional ya terminada."],
["Un estado demuestra un evento, pero no promete la hora del siguiente. Guarda el texto exacto, la fecha, la parte responsable y el evento que falta.","Después de la compra controla el vendedor; tras la llegada intervienen recepción y QC; después del envío internacional pueden intervenir transportista, aduana y operador local."],
["Una etiqueta puede crearse antes del primer escaneo; la exportación por lotes, los relevos, la aduana, el fin de semana y el intercambio de datos pueden crear silencio.","Eso no demuestra pérdida ni seguridad. Compara la pausa con la última fase y la información actual de esa línea, no con un plazo antiguo de otra ruta."],
["Confirma el número internacional, el transportista enlazado, los últimos eventos en ambos sistemas, cualquier número local, la dirección y la etapa actual.","Guarda una captura fechada con línea, destino, salida, evento y lugar. Nunca publiques número completo, nombre, teléfono o dirección."],
["Espera si sigue dentro del intervalo actual sin aviso. Pregunta si los sistemas discrepan. Contacta al operador local tras aceptación, intento de entrega o petición al destinatario.","Una investigación de pérdida o seguro solo sigue las condiciones vigentes. Conserva contenido, embalaje, pago, cobertura e historial."],
["Incluye paquete, país, línea, fecha de salida, últimos eventos, número local y la acción solicitada.","No mezcles producto, embalaje y seguimiento. Describe hechos observables y no afirmes pérdida o incautación sin confirmación."],
["Añade los nuevos escaneos a la cronología. Al recibir, compara cartón, etiqueta y contenido con la lista de almacén.","Usa la experiencia para mejorar tus criterios, no como una nota universal de la ruta. La etapa, la prueba y el responsable siguen siendo la base.","Guarda una fila privada por paquete con artículos, línea, destino, pago, salida, primer escaneo, exportación, relevo, aduana y resultado. No publiques datos personales.","Después de varios paquetes compara etapas, no una nota total. Tus patrones son pruebas fechadas, no promesas para otra temporada o destino."]],
["Asocia cada número.","Guarda texto y hora.","Comprueba el operador local.","Usa la regla actual.","Pide una acción concreta.","Conserva las pruebas."]));
const it=build(shared("Tracking KameyMall senza aggiornamenti: diagnosi per fasi","Una guida per leggere stati, passaggi e silenzi con prove verificabili.","Aggiornato il 29 agosto 2026","stato tracking kameymall","Tracking KameyMall senza aggiornamenti","Controlla stati, passaggi e prove del tracking KameyMall.",
["Identifica l’oggetto che stai seguendo","Leggi l’ultimo evento confermato","Perché il tracking può fermarsi","Esegui la lista nell’ordine corretto","Decidi se attendere, chiedere o segnalare","Scrivi una richiesta verificabile","Chiudi il registro"],[
["Percorso del venditore, articolo in magazzino e pacco internazionale hanno riferimenti diversi. Collega ordine, tracking cinese, ID di magazzino, pacco e vettore alla fase corretta.","Per un pacco consolidato elenca tutti gli articoli inclusi. L’assistenza potrà così esaminare il percorso giusto."],
["Uno stato prova un evento, non garantisce l’orario del successivo. Salva testo esatto, data, parte responsabile ed evento mancante.","Dopo l’acquisto risponde il venditore; dopo l’arrivo ricezione e QC; dopo la partenza internazionale vettore, dogana o corriere locale."],
["L’etichetta può precedere il primo scan; raggruppamento export, passaggi tra vettori, dogana, fine settimana e dati possono creare silenzio.","Non prova perdita né sicurezza. Confronta con la fase e le indicazioni attuali della linea, non con attese copiate da un’altra rotta."],
["Controlla numero internazionale, vettore collegato, ultimi eventi dei due sistemi, numero locale, indirizzo e fase.","Salva una schermata datata con linea, destinazione, partenza, evento e luogo. Non pubblicare numero completo o dati personali."],
["Attendi entro l’intervallo attuale senza avvisi. Chiedi chiarimenti se i sistemi discordano. Contatta il corriere locale dopo presa in carico o tentativo.","Perdita e assicurazione seguono solo le condizioni vigenti. Conserva contenuto, imballo, pagamento, copertura e cronologia."],
["Indica pacco, paese, linea, data, ultimi eventi, numero locale e azione richiesta.","Separa problemi di prodotto, imballo e tracking. Descrivi fatti e non dichiarare perdita o sequestro senza conferma."],
["Aggiungi i nuovi scan alla cronologia. Alla consegna confronta cartone, etichetta e contenuto con l’elenco di magazzino.","Usa l’esperienza per migliorare i criteri personali, non come voto universale. Fase, prova e responsabile restano il metodo.","Conserva una riga privata per pacco con articoli, linea, destinazione, pagamento, partenza, primo scan, export, passaggio, dogana e risultato. Non pubblicare dati personali.","Dopo più pacchi confronta le fasi, non un voto generale. Le tendenze personali sono prove datate, non promesse per altre stagioni o destinazioni."]],
["Collega ogni numero.","Salva testo e ora.","Controlla il corriere locale.","Usa la regola attuale.","Chiedi un’azione precisa.","Conserva le prove."]));
const pl=build(shared("Śledzenie KameyMall bez aktualizacji: diagnoza etapów","Metoda odczytu statusów, przekazań i przerw na podstawie dowodów.","Aktualizacja 29 sierpnia 2026","status śledzenia kameymall","Śledzenie KameyMall bez aktualizacji","Sprawdź statusy i przekazania KameyMall.",
["Najpierw ustal, co śledzisz","Czytaj ostatnie potwierdzone zdarzenie","Dlaczego aktualizacje mogą zniknąć","Wykonaj listę we właściwej kolejności","Zdecyduj: czekać, pytać czy eskalować","Napisz sprawdzalne zgłoszenie","Zamknij zapis"],[
["Droga sprzedawcy, produkt magazynowy i paczka międzynarodowa mają inne numery. Przypisz zamówienie, śledzenie w Chinach, ID magazynu, paczkę i przewoźnika do etapów.","Przy konsolidacji zapisz wszystkie produkty. Obsługa zbada wtedy właściwy odcinek, a nie zakończoną dostawę krajową."],
["Status potwierdza zdarzenie, lecz nie obiecuje czasu następnego. Zachowaj dokładny tekst, czas, odpowiedzialną stronę i brakujący krok.","Po zakupie odpowiada sprzedawca, po przyjęciu magazyn i QC, po wysyłce międzynarodowej przewoźnik, urząd celny lub operator lokalny."],
["Etykieta może powstać przed pierwszym skanem; grupowanie eksportu, przekazanie, odprawa, weekend i wymiana danych tworzą przerwy.","Nie dowodzi to zagubienia ani bezpieczeństwa. Porównuj z aktualnym etapem i zasadą tej linii, a nie z terminem innej trasy."],
["Sprawdź numer międzynarodowy, wskazanego przewoźnika, ostatnie zdarzenia, numer lokalny, adres i etap.","Zapisz datowany ekran z linią, celem, wysyłką, zdarzeniem i miejscem. Nie publikuj pełnego numeru ani danych osobowych."],
["Czekaj w aktualnym zakresie bez ostrzeżenia. Pytaj przy rozbieżnościach. Kontaktuj operatora lokalnego po przyjęciu lub próbie doręczenia.","Dochodzenie i ubezpieczenie działają tylko według bieżących warunków. Zachowaj zawartość, opakowanie, płatność, ochronę i historię."],
["Podaj paczkę, kraj, linię, datę, ostatnie zdarzenia, numer lokalny i oczekiwane działanie.","Oddziel problem produktu, pakowania i śledzenia. Opisuj fakty, nie stwierdzaj utraty lub zajęcia bez potwierdzenia."],
["Dopisuj nowe skany do osi czasu. Przy odbiorze porównaj karton, etykietę i zawartość z listą magazynową.","Wykorzystaj doświadczenie do własnych kryteriów, nie jako uniwersalną ocenę. Etap, dowód i odpowiedzialna strona pozostają podstawą.","Prowadź prywatny wiersz dla paczki: produkty, linia, cel, płatność, wysyłka, pierwszy skan, eksport, przekazanie, odprawa i wynik. Nie publikuj danych osobowych.","Po kilku paczkach porównuj etapy, nie ogólną ocenę trasy. Własne wzorce są datowanym dowodem, nie obietnicą dla innych sezonów lub krajów."]],
["Połącz numery z etapami.","Zapisz tekst i czas.","Sprawdź lokalnego przewoźnika.","Użyj aktualnej reguły.","Poproś o konkretną czynność.","Zachowaj dowody."]));

export const trackingArticles:Record<Locale,ArticlePageContent>={en,de,fr,es,it,pl};
