import type { ArticlePageContent } from "./site-articles";
import type { Locale } from "./site-content";

const en: ArticlePageContent = {
  label: "Parcel planning guide",
  title: "KameyMall Consolidation vs Split Parcels: A Decision Guide",
  intro: "A practical method for deciding which warehouse items belong together, when a split is worth considering and which facts to confirm before paying international freight.",
  updated: "Updated August 13, 2026",
  readTime: "15 minute read",
  sourceNote: "Fact-check basis: KameyMall’s current Shopping Agent Service page and public purchasing guide, reviewed August 13, 2026. Route availability, restrictions, packing options and final charges can change; confirm them in the live parcel submission before payment.",
  primaryKeyword: "kameymall consolidation",
  sections: [
    {
      heading: "Start with the real decision: which items should share one parcel?",
      paragraphs: [
        "KameyMall consolidation is the warehouse step where eligible purchases from different sellers can be grouped for international shipment. The platform’s current purchasing guide also says users may ask for items to be consolidated or shipped separately, while its Shopping Agent Service page describes the warehouse receiving, inspecting, weighing, packing and then dispatching a submitted parcel. Those statements confirm that grouping is part of the published workflow. They do not mean that one large parcel is automatically cheaper, safer or available on every route.",
        "Make the decision only after the relevant items have reached the warehouse and their inspection evidence is acceptable. Before that point, listing weights and seller packaging are estimates. After receipt, you have a better record of item identity, condition and warehouse data. Think of consolidation as a compatibility problem first and a cost problem second. Items that can use the same destination, route and protection strategy are candidates for one parcel. Items with conflicting restrictions, deadlines or damage risks deserve a separate decision even if another postage charge is inconvenient.",
      ],
    },
    {
      heading: "Apply four gates before comparing prices",
      paragraphs: [
        "First, confirm route eligibility for every item. A route available for ordinary clothing may not accept a battery, liquid, magnet, food, branded-sensitive item or an unusually long package. KameyMall’s live parcel screen is the decisive source because routes and restrictions can change by destination and parcel contents. If one item removes every suitable option for the rest of the haul, compare a split that isolates it. Do not assume the restricted item can travel simply because it entered the warehouse successfully; domestic receipt and international acceptance are different checks.",
        "Second, check address and timing. Everything in one parcel must go to one destination, and a late seller can delay a group that is otherwise ready. Third, check after-sales status: do not pack an item while a return or QC question remains open. Fourth, check physical compatibility. A rigid object, crushable box, sharp component and soft garment may require different protection. Passing all four gates does not prove consolidation wins, but failing one gate gives a concrete reason to split rather than relying on a vague preference for smaller or larger parcels.",
      ],
    },
    {
      heading: "Model the cost without inventing a shipping rate",
      paragraphs: [
        "A useful comparison includes the charge for each proposed parcel, any confirmed packing option, and the cost of repeating parcel-level overhead. Use the live quote rather than a rate copied from an old post. Create two columns: Plan A combines all compatible items; Plan B separates a defined group. For each plan, record the route, estimated billable weight, quoted freight, selected packing services and any charge displayed before payment. Leave unknown cells blank. A blank is more honest than a guessed exchange rate, dimensional divisor or handling fee.",
        "Use abstract numbers to understand the logic. Suppose one combined plan is quoted at 92 cost units. A split produces Parcel 1 at 58 units and Parcel 2 at 39, for 97 units total. The consolidation advantage is five units, not the difference between 92 and either individual parcel. Now add the decision value: if the split prevents a fragile box from being compressed, releases a time-sensitive item earlier or preserves an eligible route, five units may be a reasonable premium. If both plans use the same route and protection with no timing benefit, the combined plan is stronger on the facts available.",
      ],
    },
    {
      heading: "Watch billable shape, not only item weight",
      paragraphs: [
        "International freight can depend on weight, volume and route rules. Consolidation may reduce repeated outer packaging, but a poorly shaped combination can create a larger carton. Imagine two dense, compact items and one long lightweight item. Adding the long item may determine the length of the entire box and create empty space around the compact goods. A separate narrow parcel could therefore compare differently from three parcels made only to keep every purchase apart. The useful question is not how many seller packages arrived, but what packed shapes the warehouse can reasonably produce.",
        "Do not calculate a final dimensional charge unless the chosen line publishes the necessary formula and the packed dimensions are available. Instead, run a shape audit. Record each item’s warehouse measurements when shown, whether retail packaging must be kept, whether an item can fold, and whether protective material will expand the parcel. If the live system offers a packing or rehearsal step, use its resulting data for the final comparison. An estimate is a planning signal; the packed measurement and confirmed charge are the payment decision.",
      ],
    },
    {
      heading: "Treat box removal as a product decision",
      paragraphs: [
        "KameyMall’s current guide mentions de-boxing and consolidation, but removing retail packaging is not a universal saving. A shoe box, collector package or fitted insert may be part of the item’s value or its protection. Removing it can reduce bulk, yet it can also expose the product to pressure or make resale and gifting less attractive. Decide item by item. Separate disposable seller mailers from packaging that supports, identifies or preserves the product, and never ask for removal until warehouse photos confirm what the packaging actually contains.",
        "Write packing instructions that can be checked: keep the molded insert around the fragile item; remove only the external courier bag; do not discard accessories; protect metal hardware from rubbing against fabric. Avoid contradictory requests such as remove all boxes and preserve the retail presentation. When several items share a parcel, think about contact between them. Hard edges can mark leather, liquids can affect textiles, and a heavy object can crush a hollow one. A split is justified when no reasonable packing arrangement resolves that conflict, not merely because the product categories have different names.",
      ],
    },
    {
      heading: "Balance storage timing against parcel efficiency",
      paragraphs: [
        "Waiting for more purchases can make consolidation possible, but waiting is not free of constraints. Record the warehouse arrival date of every item and check the current storage terms shown by the platform before delaying a ready parcel. The oldest item sets the practical deadline for the group. Also consider seller uncertainty: an unshipped presale or replacement can keep several accepted items idle. Set a review date rather than waiting indefinitely for the imagined perfect haul.",
        "Use a simple rule: wait only when the expected addition is compatible and the remaining time is comfortably inside the current storage conditions. Otherwise ship the ready group and treat the late item as a later parcel. This is especially important when addresses may change, seasonal demand is approaching or an after-sales question is unresolved. Do not publish a permanent storage-day number from this article; the account and current policy are the places to verify it. The decision record should contain the date you checked, not a rule remembered from a previous order.",
      ],
    },
    {
      heading: "Compare three parcel plans, not just one and many",
      paragraphs: [
        "For a mixed haul, test three plans. Plan 1 is maximum compatible consolidation. Plan 2 isolates only the item that creates a route, shape, timing or protection conflict. Plan 3 uses separate parcels for clearly distinct groups. This middle plan is often overlooked. If four garments and one long accessory are waiting, the useful alternative may be a garment parcel plus an accessory parcel, not five individual shipments. The same method works when one item is urgent: release that one and keep the rest consolidated.",
        "Score each plan on five lines: live total quote, route eligibility, protection fit, dispatch readiness and evidence quality. A plan with no confirmed route is not a cheap plan; it is incomplete. A plan built on estimated measurements should be marked provisional. A plan containing an unresolved QC item should be blocked. Choose the lowest-cost plan only after it passes the non-price lines. This order prevents a small quoted saving from overruling an actual restriction or a visible damage risk.",
      ],
    },
    {
      heading: "Use a final submission checklist",
      paragraphs: [
        "Before submitting, match every warehouse item number to the intended parcel and make sure none is duplicated or omitted. Confirm the delivery address, item count, declared description requested by the workflow, selected route and current eligibility. Review packaging requests for clarity, then capture the quote with its date and the estimated weight or dimensions displayed. If the packed result or final charge changes, compare the new data with that record before paying rather than assuming the difference is an error.",
        "After payment, keep the parcel record separate from the original seller orders. One international parcel may contain several product orders, while one haul may create several parcel numbers. That mapping is what makes later tracking or a claim understandable. Consolidation is successful when the chosen grouping remains eligible, protectable and explainable at the final price—not simply when the warehouse fits the largest possible number of items into one carton.",
      ],
      bullets: [
        "Include only warehouse items whose QC and after-sales decisions are complete.",
        "Confirm that every item can use the selected destination and live route.",
        "Compare combined, conflict-isolated and grouped-split plans.",
        "Use current packed data and live quotes instead of remembered rates.",
        "Write packaging instructions that preserve important parts and prevent contact damage.",
        "Save the final item-to-parcel map, quote, payment and tracking record.",
      ],
    },
  ],
  conclusionTitle: "The best parcel is the smallest defensible plan",
  conclusion: "Consolidate items that are ready, route-compatible and safe to pack together; split only where timing, eligibility, shape or protection creates a measurable reason. Compare the current live plans, preserve the evidence behind the choice and reconcile the packed result before payment. That produces a decision you can explain even when routes and prices later change.",
  seoTitle: "KameyMall Consolidation vs Split Parcels Guide",
  seoDescription: "Decide when to consolidate or split KameyMall warehouse items using route, billable shape, packaging, timing and live-cost checks.",
};

const translations: Record<Exclude<Locale, "en">, Omit<ArticlePageContent, "sections"> & { headings: string[]; paragraphs: string[][]; bullets: string[] }> = {
  de: {
    ...en, label: "Leitfaden zur Paketplanung", title: "KameyMall-Konsolidierung oder Teilpakete: Entscheidungshilfe", intro: "Eine praktische Methode, um Lagerartikel sinnvoll zu gruppieren, begründete Teilungen zu erkennen und die Fakten vor der Auslandsfrachtzahlung zu prüfen.", updated: "Aktualisiert am 13. August 2026", readTime: "15 Minuten Lesezeit", sourceNote: "Faktenbasis: aktuelle KameyMall-Seiten Shopping Agent Service und öffentlicher Einkaufsleitfaden, geprüft am 13. August 2026. Routen, Einschränkungen, Verpackungsoptionen und Endbeträge können sich ändern; maßgeblich ist die Live-Paketeinreichung.", primaryKeyword: "kameymall konsolidierung", seoTitle: "KameyMall-Konsolidierung oder Teilpakete", seoDescription: "KameyMall-Lagerartikel anhand von Route, abrechenbarer Form, Verpackung, Zeit und Live-Kosten konsolidieren oder aufteilen.", conclusionTitle: "Das beste Paket ist der kleinste belastbare Plan", conclusion: "Konsolidiere versandbereite, routenkompatible und gemeinsam sicher verpackbare Artikel. Teile nur, wenn Zeit, Zulässigkeit, Form oder Schutz einen messbaren Grund liefern. Vergleiche aktuelle Live-Pläne, sichere die Belege und gleiche das Packresultat vor Zahlung ab.",
    headings: ["Die echte Frage: Welche Artikel gehören in ein Paket?", "Vier Prüfungen vor jedem Preisvergleich", "Kosten modellieren, ohne Tarife zu erfinden", "Abrechenbare Form statt nur Gewicht prüfen", "Kartonentfernung als Produktentscheidung", "Lagerzeit und Paketeffizienz ausbalancieren", "Drei Paketpläne statt nur eins oder viele", "Abschließende Einreichungscheckliste"],
    paragraphs: [
      ["KameyMall-Konsolidierung gruppiert geeignete Käufe verschiedener Verkäufer im Lager für den Auslandsversand. Der aktuelle Leitfaden erlaubt konsolidierten oder getrennten Versand; die Serviceseite nennt Empfang, Prüfung, Wiegen, Verpacken und Versand. Das bestätigt den Ablauf, nicht automatisch den günstigsten oder sichersten Plan.", "Entscheide erst nach Lagereingang und akzeptierter Prüfung. Vorher sind Verkäufergewicht und Verpackung Schätzungen. Prüfe zuerst Kompatibilität: Ziel, Route und Schutz müssen zusammenpassen. Gegensätzliche Einschränkungen, Fristen oder Schadensrisiken können eine Teilung rechtfertigen."],
      ["Prüfe zuerst die Live-Routenzulässigkeit jedes Artikels. Gewöhnliche Kleidung und Batterie, Flüssigkeit, Magnet oder überlanges Gut können andere Regeln haben. Kann ein Artikel alle passenden Routen blockieren, isoliere ihn im Vergleich. Lagereingang beweist keine internationale Zulässigkeit.", "Prüfe danach Adresse und Zeit, offenen After-Sales-Status und physische Verträglichkeit. Alles im Paket braucht dasselbe Ziel; eine späte Ware hält die Gruppe auf. Starre, zerbrechliche, scharfe und weiche Waren brauchen eventuell gegensätzlichen Schutz. Ein gescheiterter Test ist ein konkreter Teilungsgrund."],
      ["Vergleiche je Plan Live-Fracht, bestätigte Verpackungsoptionen und wiederholte Paketkosten. Plan A bündelt kompatible Waren, Plan B trennt eine definierte Gruppe. Notiere Route, geschätztes Abrechnungsgewicht, Angebot und Optionen. Unbekannte Felder bleiben leer statt mit alten Kursen, Divisoren oder Gebühren gefüllt zu werden.", "Beispiel in neutralen Einheiten: Zusammen 92, getrennt 58 plus 39, also 97. Der Bündelvorteil beträgt fünf Einheiten. Verhindert die Teilung Druckschäden, beschleunigt Dringendes oder erhält eine Route, kann der Aufpreis sinnvoll sein. Ohne solchen Nutzen spricht das aktuelle Angebot für die Bündelung."],
      ["Fracht kann von Gewicht, Volumen und Route abhängen. Bündeln spart möglicherweise äußere Verpackung, doch ein langer leichter Artikel kann den ganzen Karton verlängern. Zwei dichte Waren plus eine lange Ware können als kompakter Karton und schmales Paket besser vergleichbar sein als drei Einzelpakete.", "Berechne keine endgültige Volumengebühr ohne veröffentlichte Formel und Packmaße. Notiere Lagermaße, notwendige Verkaufsverpackung, Faltbarkeit und Schutzvolumen. Wenn ein Pack- oder Probelauf angeboten wird, nutze dessen Ergebnis. Die Schätzung plant; Packmaß und bestätigter Betrag entscheiden."],
      ["Der aktuelle Leitfaden erwähnt Entkartonieren, doch Verkaufsverpackung ist nicht immer Abfall. Schuhkarton, Sammlerbox oder Formeinsatz können Wert und Schutz erhalten. Entscheide einzeln und erst nach Fotos, was entfernt werden darf.", "Formuliere prüfbare Wünsche: Formeinsatz behalten, nur Versandbeutel entfernen, Zubehör nicht entsorgen, Metall von Stoff trennen. Vermeide Widersprüche. Harte Kanten, Flüssigkeit oder schwere Gegenstände können andere Waren schädigen; trenne, wenn keine vernünftige Verpackung den Konflikt löst."],
      ["Mehr Einkäufe abzuwarten ermöglicht Konsolidierung, aber das älteste Lagerdatum begrenzt die Gruppe. Prüfe aktuelle Lagerbedingungen im Konto. Ein Vorverkauf oder Ersatz kann akzeptierte Ware unnötig festhalten. Setze ein Prüfdatum statt unbegrenzt auf den perfekten Haul zu warten.", "Warte nur, wenn die erwartete Ware kompatibel ist und genügend Zeit bleibt. Sonst versende die fertige Gruppe und behandle Nachzügler später. Veröffentliche keine dauerhafte Zahl aus Erinnerung; sichere Prüfdatum und aktuelle Regel im Entscheidungsnachweis."],
      ["Teste maximale kompatible Bündelung, Isolierung nur des Konfliktartikels und getrennte sinnvolle Gruppen. Bei vier Kleidungsstücken und langem Zubehör kann Kleidung plus Zubehör sinnvoller sein als fünf Pakete. Dasselbe gilt für einen dringenden Artikel.", "Bewerte Live-Gesamtangebot, Zulässigkeit, Schutz, Versandbereitschaft und Datenqualität. Ohne bestätigte Route ist ein Plan unvollständig; Schätzmaße bleiben vorläufig; offenes QC blockiert. Wähle erst nach diesen Prüfungen den günstigeren gültigen Plan."],
      ["Ordne jede Lagernummer genau einem Paket zu. Prüfe Adresse, Zahl, verlangte Beschreibung, Route und Live-Zulässigkeit. Kontrolliere Verpackungstext und sichere datiertes Angebot samt Schätzdaten. Ändern sich Packresultat oder Endbetrag, vergleiche vor Zahlung mit diesem Datensatz.", "Bewahre Paket und Verkäuferaufträge getrennt auf. Ein Paket kann viele Aufträge enthalten, ein Haul mehrere Paketnummern. Erfolgreich ist die Bündelung, wenn sie beim Endpreis zulässig, schützbar und erklärbar bleibt – nicht wenn nur möglichst viel in einen Karton passt."],
    ], bullets: ["Nur Artikel mit abgeschlossener QC- und After-Sales-Entscheidung einbeziehen.", "Ziel und Live-Route für jeden Artikel bestätigen.", "Bündel-, Konflikt- und Gruppenplan vergleichen.", "Aktuelle Packdaten und Angebote statt alter Tarife nutzen.", "Verpackungswünsche klar und schadenvermeidend schreiben.", "Artikel-Paket-Zuordnung, Angebot, Zahlung und Tracking sichern."],
  },
  fr: {
    ...en, label: "Guide de planification des colis", title: "Consolidation KameyMall ou colis séparés : guide de décision", intro: "Une méthode pratique pour regrouper les articles en entrepôt, justifier une séparation et vérifier les faits avant de payer le transport international.", updated: "Mis à jour le 13 août 2026", readTime: "15 minutes de lecture", sourceNote: "Base factuelle : pages actuelles Shopping Agent Service et guide d’achat public de KameyMall, vérifiés le 13 août 2026. Les lignes, restrictions, options d’emballage et montants finaux peuvent changer ; confirmez-les lors de la soumission en direct.", primaryKeyword: "consolidation kameymall", seoTitle: "Consolidation KameyMall ou colis séparés", seoDescription: "Décidez de consolider ou séparer les articles KameyMall selon la ligne, la forme facturable, l’emballage, le délai et le devis en direct.", conclusionTitle: "Le meilleur colis est le plus petit plan défendable", conclusion: "Consolidez les articles prêts, compatibles avec la même ligne et sûrs ensemble. Séparez seulement lorsqu’un délai, une restriction, une forme ou une protection fournit une raison mesurable. Comparez les plans en direct et rapprochez le résultat emballé avant paiement.",
    headings: ["La vraie décision : quels articles dans le même colis ?", "Quatre filtres avant de comparer les prix", "Modéliser le coût sans inventer de tarif", "Observer la forme facturable, pas seulement le poids", "Le retrait des boîtes est une décision produit", "Équilibrer stockage et efficacité du colis", "Comparer trois plans, pas seulement un ou plusieurs", "Liste de contrôle avant soumission"],
    paragraphs: [
      ["La consolidation KameyMall regroupe à l’entrepôt des achats admissibles provenant de vendeurs différents. Le guide actuel prévoit l’envoi consolidé ou séparé, et le service décrit réception, contrôle, pesée, emballage puis expédition. Cela confirme le processus, pas qu’un grand colis sera toujours moins cher ou plus sûr.", "Décidez après réception et validation du contrôle. Avant cela, poids et emballage vendeur restent estimatifs. Traitez d’abord la compatibilité : destination, ligne et protection communes. Restrictions, délais ou risques contradictoires méritent une décision séparée."],
      ["Vérifiez d’abord l’admissibilité de chaque article sur les lignes affichées. Vêtement ordinaire, batterie, liquide, aimant ou objet long peuvent suivre des règles différentes. Si un article supprime toutes les lignes adaptées, isolez-le dans le calcul. L’entrée en entrepôt ne garantit pas l’acceptation internationale.", "Vérifiez ensuite adresse et calendrier, dossier après-vente et compatibilité physique. Tout doit aller à une adresse; un vendeur tardif retarde le groupe. Objets rigides, fragiles, pointus et textiles peuvent exiger des protections opposées. L’échec d’un filtre donne un motif précis de séparation."],
      ["Comparez pour chaque plan le devis en direct, les options d’emballage confirmées et les coûts répétés par colis. Le plan A regroupe, le plan B sépare un groupe défini. Notez ligne, poids facturable estimé, fret et options. Laissez vide ce qui est inconnu plutôt que d’inventer taux, diviseur ou frais.", "Exemple abstrait : regroupé 92 unités; séparé 58 plus 39, soit 97. L’avantage réel est cinq unités. Si la séparation protège une boîte, libère un article urgent ou maintient une ligne admissible, ce supplément peut être rationnel. Sans bénéfice, le plan regroupé est mieux étayé."],
      ["Le fret peut dépendre du poids, du volume et de la ligne. La consolidation réduit parfois les emballages externes, mais un objet long et léger peut allonger tout le carton. Deux objets denses et un long article peuvent mieux fonctionner en carton compact plus colis étroit qu’en trois envois.", "Ne calculez pas de volume final sans formule publiée et dimensions emballées. Relevez mesures d’entrepôt, emballage à conserver, pliage et volume de protection. Si une étape d’emballage ou de répétition fournit des données, utilisez-les. L’estimation prépare; le colis emballé décide."],
      ["Le guide actuel mentionne le retrait de boîte, mais une boîte à chaussures, un coffret de collection ou un insert peut conserver valeur et protection. Décidez article par article, après avoir vu les photos, ce qui est réellement jetable.", "Donnez des consignes vérifiables : garder l’insert, retirer seulement le sac transport, conserver les accessoires, isoler le métal du tissu. Évitez les demandes contradictoires. Séparez lorsque aucun emballage raisonnable ne résout le contact entre bords durs, liquide, poids et article fragile."],
      ["Attendre d’autres achats favorise le regroupement, mais la date d’arrivée la plus ancienne limite le groupe. Vérifiez les conditions de stockage actuelles. Une précommande ou un remplacement incertain peut immobiliser les articles prêts. Fixez une date de révision.", "Attendez seulement si l’ajout est compatible et si le délai restant est confortable. Sinon expédiez le groupe prêt. Ne transformez pas un ancien nombre de jours en règle permanente; conservez la date et la condition réellement vérifiées."],
      ["Testez la consolidation compatible maximale, l’isolement du seul conflit et des groupes séparés cohérents. Quatre vêtements et un accessoire long peuvent devenir un colis vêtements et un colis accessoire, pas cinq envois. Un seul article urgent peut aussi partir.", "Notez devis total, admissibilité, protection, disponibilité et qualité des données. Sans ligne confirmée, le plan est incomplet; avec mesures estimées, provisoire; avec QC ouvert, bloqué. Comparez le prix seulement entre plans valides."],
      ["Affectez chaque numéro d’entrepôt à un seul colis. Vérifiez adresse, quantité, description demandée, ligne et admissibilité. Relisez les consignes, puis conservez devis daté et données estimées. Rapprochez toute modification après emballage avant de payer.", "Séparez le dossier du colis des commandes vendeur. Un colis peut contenir plusieurs commandes et un haul plusieurs numéros. Une consolidation réussie reste admissible, protégeable et explicable au prix final; elle ne consiste pas à remplir le plus grand carton."],
    ], bullets: ["Inclure seulement les articles dont QC et après-vente sont clos.", "Confirmer destination et ligne en direct pour chaque article.", "Comparer regroupement, isolement du conflit et groupes séparés.", "Utiliser données emballées et devis actuels.", "Rédiger des consignes protégeant les pièces importantes.", "Conserver correspondance article-colis, devis, paiement et suivi."],
  },
  es: {
    ...en, label: "Guía de planificación de paquetes", title: "Consolidación KameyMall o paquetes separados: guía práctica", intro: "Un método para agrupar artículos del almacén, justificar una división y comprobar los datos antes de pagar el envío internacional.", updated: "Actualizado el 13 de agosto de 2026", readTime: "15 minutos de lectura", sourceNote: "Base factual: páginas actuales Shopping Agent Service y guía pública de compra de KameyMall, revisadas el 13 de agosto de 2026. Rutas, restricciones, embalaje e importes finales pueden cambiar; confírmalos al crear el paquete.", primaryKeyword: "consolidación kameymall", seoTitle: "Consolidación KameyMall o paquetes separados", seoDescription: "Decide si consolidar o separar artículos KameyMall según ruta, forma facturable, embalaje, tiempo y cotización activa.", conclusionTitle: "El mejor paquete es el plan mínimo defendible", conclusion: "Consolida artículos listos, compatibles con la ruta y seguros juntos. Separa solo si el plazo, la elegibilidad, la forma o la protección aportan una razón medible. Compara planes activos y concilia el resultado embalado antes de pagar.",
    headings: ["La decisión real: qué artículos deben compartir paquete", "Cuatro filtros antes de comparar precios", "Modela el coste sin inventar tarifas", "Mira la forma facturable, no solo el peso", "Quitar cajas es una decisión sobre el producto", "Equilibra almacenamiento y eficiencia", "Compara tres planes, no solo uno o muchos", "Lista final antes de enviar"],
    paragraphs: [
      ["La consolidación KameyMall agrupa en almacén compras elegibles de distintos vendedores. La guía actual permite consolidarlas o enviarlas por separado; el servicio describe recepción, inspección, pesaje, embalaje y despacho. Eso confirma el proceso, no que un paquete grande siempre sea más barato o seguro.", "Decide después de recibir y aceptar el control. Antes, peso y embalaje del vendedor son estimaciones. Primero comprueba compatibilidad de destino, ruta y protección. Restricciones, plazos o riesgos opuestos justifican estudiar una división."],
      ["Confirma la elegibilidad activa de cada artículo. Ropa común, batería, líquido, imán u objeto largo pueden tener reglas distintas. Si uno elimina todas las rutas adecuadas, aíslalo en la comparación. Entrar al almacén no demuestra aceptación internacional.", "Comprueba dirección y tiempo, estado posventa y compatibilidad física. Todo va a un destino; un vendedor tardío retrasa al grupo. Objetos rígidos, frágiles, afilados y blandos pueden exigir protección diferente. Fallar un filtro aporta un motivo concreto para separar."],
      ["Compara cotización activa, embalaje confirmado y costes repetidos por paquete. El plan A reúne compatibles; el B separa un grupo definido. Anota ruta, peso facturable estimado, flete y opciones. Deja vacíos los datos desconocidos en vez de adivinar cambio, divisor o cargos.", "Ejemplo abstracto: combinado 92 unidades; separado 58 más 39, total 97. La ventaja son cinco unidades. Si dividir evita daños, adelanta algo urgente o conserva una ruta, el extra puede valer la pena. Sin beneficio, gana el plan combinado con los datos disponibles."],
      ["El flete puede depender de peso, volumen y ruta. Consolidar puede reducir envoltorios, pero un artículo largo puede alargar toda la caja. Dos objetos densos y uno largo quizá se comparen mejor como caja compacta más paquete estrecho que como tres paquetes.", "No calcules un volumen final sin fórmula publicada y medidas embaladas. Registra medidas de almacén, caja que debe conservarse, posibilidad de plegado y protección. Usa los datos del embalaje o ensayo si están disponibles. La estimación orienta; la medida final decide."],
      ["La guía menciona quitar cajas, pero una caja de zapatos, estuche o inserto puede aportar valor y protección. Decide por artículo y después de ver las fotos qué envoltorio es desechable.", "Escribe instrucciones verificables: conserva inserto, quita solo bolsa exterior, no tires accesorios, separa metal de tela. Evita contradicciones. Divide cuando ningún embalaje razonable evite el conflicto entre bordes, líquido, peso y producto delicado."],
      ["Esperar más compras facilita consolidar, pero manda la llegada más antigua. Comprueba las condiciones actuales de almacén. Una preventa o reemplazo incierto puede retener artículos aceptados. Fija una fecha de revisión.", "Espera solo si la futura compra es compatible y queda tiempo suficiente. Si no, envía lo listo. No publiques como permanente un número recordado; guarda la fecha y la condición vigente que comprobaste."],
      ["Prueba máxima consolidación compatible, aislamiento del único conflicto y grupos separados coherentes. Cuatro prendas y un accesorio largo pueden ser dos paquetes, no cinco. También puedes liberar solo un artículo urgente.", "Puntúa cotización, elegibilidad, protección, preparación y calidad de datos. Sin ruta, el plan está incompleto; con medidas estimadas, provisional; con QC abierto, bloqueado. Elige por precio solo entre planes válidos."],
      ["Asigna cada número de almacén a un solo paquete. Comprueba dirección, cantidad, descripción solicitada, ruta y elegibilidad. Revisa instrucciones y guarda cotización fechada con datos estimados. Concilia cualquier cambio de embalaje antes de pagar.", "Mantén separado el registro del paquete y los pedidos del vendedor. Un paquete puede incluir varios pedidos y una compra varios paquetes. Consolidar funciona si el plan sigue siendo elegible, protegible y explicable al precio final, no si llena la caja más grande."],
    ], bullets: ["Incluye solo artículos con QC y posventa resueltos.", "Confirma destino y ruta activa para cada artículo.", "Compara consolidado, conflicto aislado y grupos separados.", "Usa medidas finales y cotizaciones actuales.", "Da instrucciones claras que eviten daños por contacto.", "Guarda mapa artículo-paquete, cotización, pago y seguimiento."],
  },
  it: {
    ...en, label: "Guida alla pianificazione dei pacchi", title: "Consolidamento KameyMall o pacchi separati: guida pratica", intro: "Un metodo per raggruppare gli articoli in magazzino, motivare una divisione e verificare i dati prima del pagamento internazionale.", updated: "Aggiornato il 13 agosto 2026", readTime: "15 minuti di lettura", sourceNote: "Base dei fatti: pagine attuali Shopping Agent Service e guida pubblica KameyMall, verificate il 13 agosto 2026. Rotte, restrizioni, imballaggi e importi finali possono cambiare; confermali nella creazione del pacco.", primaryKeyword: "consolidamento kameymall", seoTitle: "Consolidamento KameyMall o pacchi separati", seoDescription: "Decidi se consolidare o dividere articoli KameyMall in base a rotta, forma fatturabile, imballaggio, tempi e preventivo live.", conclusionTitle: "Il pacco migliore è il piano minimo difendibile", conclusion: "Consolida articoli pronti, compatibili con la rotta e sicuri insieme. Dividi solo se tempo, idoneità, forma o protezione danno un motivo misurabile. Confronta i piani live e verifica il risultato imballato prima di pagare.",
    headings: ["La vera decisione: quali articoli nello stesso pacco?", "Quattro filtri prima del confronto prezzi", "Modellare il costo senza inventare tariffe", "Guardare la forma fatturabile, non solo il peso", "Rimuovere scatole è una scelta sul prodotto", "Bilanciare deposito ed efficienza", "Confrontare tre piani, non solo uno o molti", "Checklist finale di invio"],
    paragraphs: [
      ["Il consolidamento KameyMall raggruppa in magazzino acquisti idonei di venditori diversi. La guida attuale consente invio consolidato o separato; il servizio descrive ricezione, controllo, peso, imballaggio e spedizione. Conferma il flusso, non che un pacco grande sia sempre più economico o sicuro.", "Decidi dopo ricezione e QC accettato. Prima, peso e confezione del venditore sono stime. Verifica prima destinazione, rotta e protezione comuni. Restrizioni, scadenze o rischi opposti meritano un piano separato."],
      ["Conferma l’idoneità live di ogni articolo. Abbigliamento, batteria, liquido, magnete o oggetto lungo possono avere regole diverse. Se uno elimina tutte le rotte adatte, isolalo nel confronto. L’ingresso in magazzino non prova l’accettazione internazionale.", "Controlla indirizzo e tempi, stato post-vendita e compatibilità fisica. Tutto va a una destinazione; un venditore tardivo ferma il gruppo. Oggetti rigidi, fragili, appuntiti e morbidi possono richiedere protezioni diverse. Un filtro fallito è un motivo concreto per dividere."],
      ["Confronta preventivo live, imballaggi confermati e costi ripetuti per pacco. Piano A unisce; piano B separa un gruppo definito. Annota rotta, peso fatturabile stimato, nolo e opzioni. Lascia vuoto ciò che non conosci invece di inventare cambio, divisore o costo.", "Esempio astratto: insieme 92 unità; separato 58 più 39, totale 97. Il vantaggio è cinque. Se la divisione evita danni, libera un urgente o mantiene una rotta, il sovrapprezzo può essere sensato. Senza beneficio, è più forte il piano unito."],
      ["Il nolo può dipendere da peso, volume e rotta. Consolidare riduce imballi ripetuti, ma un pezzo lungo può allungare l’intero cartone. Due oggetti densi e uno lungo possono funzionare meglio come scatola compatta più pacco stretto che come tre pacchi.", "Non calcolare il volume finale senza formula e misure imballate. Registra misure di magazzino, confezione da conservare, piegabilità e protezione. Usa i dati dell’imballaggio o prova quando disponibili. La stima pianifica; la misura finale decide."],
      ["La guida cita la rimozione delle scatole, ma scatola scarpe, confezione da collezione o inserto possono mantenere valore e protezione. Decidi per articolo, dopo le foto, cosa sia davvero eliminabile.", "Scrivi istruzioni verificabili: conserva inserto, togli solo busta esterna, non buttare accessori, separa metallo e tessuto. Evita contraddizioni. Dividi quando nessun imballaggio ragionevole risolve il contatto tra bordi, liquidi, peso e articolo fragile."],
      ["Aspettare altri acquisti aiuta il consolidamento, ma conta la data di arrivo più vecchia. Verifica le condizioni correnti. Una prevendita o sostituzione incerta può trattenere merce pronta. Fissa una data di revisione.", "Aspetta solo se l’aggiunta sarà compatibile e resta tempo sufficiente. Altrimenti spedisci il gruppo pronto. Non trasformare un vecchio numero di giorni in regola: conserva data e condizione effettivamente controllate."],
      ["Prova massimo consolidamento compatibile, isolamento del solo conflitto e gruppi separati coerenti. Quattro capi e un accessorio lungo possono essere due pacchi, non cinque. Lo stesso vale per un solo articolo urgente.", "Valuta preventivo, idoneità, protezione, prontezza e qualità dei dati. Senza rotta il piano è incompleto; con misure stimate è provvisorio; con QC aperto è bloccato. Confronta il prezzo solo tra piani validi."],
      ["Assegna ogni numero di magazzino a un solo pacco. Verifica indirizzo, quantità, descrizione richiesta, rotta e idoneità. Rileggi le istruzioni e salva preventivo datato con stime. Confronta ogni variazione dopo l’imballo prima del pagamento.", "Tieni separati pacco e ordini venditore. Un pacco può contenere molti ordini e un haul più pacchi. Il consolidamento riesce quando resta idoneo, proteggibile e spiegabile al prezzo finale, non quando riempie la scatola più grande."],
    ], bullets: ["Includi solo articoli con QC e post-vendita conclusi.", "Conferma destinazione e rotta live per ogni articolo.", "Confronta unito, conflitto isolato e gruppi separati.", "Usa misure imballate e preventivi correnti.", "Scrivi istruzioni che proteggano parti importanti.", "Salva mappa articolo-pacco, preventivo, pagamento e tracking."],
  },
  pl: {
    ...en, label: "Poradnik planowania paczek", title: "Konsolidacja KameyMall czy osobne paczki: poradnik", intro: "Praktyczna metoda grupowania towarów w magazynie, uzasadniania podziału i sprawdzania faktów przed opłatą wysyłki międzynarodowej.", updated: "Zaktualizowano 13 sierpnia 2026", readTime: "15 minut czytania", sourceNote: "Podstawa faktów: aktualne strony Shopping Agent Service i publiczny poradnik KameyMall, sprawdzone 13 sierpnia 2026. Trasy, ograniczenia, opcje pakowania i końcowe kwoty mogą się zmieniać; potwierdź je przy składaniu paczki.", primaryKeyword: "konsolidacja kameymall", seoTitle: "Konsolidacja KameyMall czy osobne paczki", seoDescription: "Zdecyduj o konsolidacji lub podziale KameyMall według trasy, kształtu rozliczeniowego, pakowania, czasu i bieżącej wyceny.", conclusionTitle: "Najlepsza paczka to najmniejszy obroniony plan", conclusion: "Konsoliduj gotowe towary, zgodne z trasą i bezpieczne razem. Dziel tylko wtedy, gdy czas, dopuszczenie, kształt lub ochrona dają mierzalny powód. Porównaj bieżące plany i uzgodnij wynik pakowania przed zapłatą.",
    headings: ["Prawdziwa decyzja: które towary powinny być razem?", "Cztery filtry przed porównaniem cen", "Model kosztu bez wymyślania stawek", "Kształt rozliczeniowy, nie tylko masa", "Usunięcie pudełka to decyzja o produkcie", "Równowaga czasu magazynu i efektywności", "Trzy plany zamiast tylko jednego lub wielu", "Końcowa lista przed złożeniem paczki"],
    paragraphs: [
      ["Konsolidacja KameyMall grupuje w magazynie kwalifikujące się zakupy od różnych sprzedawców. Aktualny poradnik dopuszcza wysyłkę razem lub osobno, a strona usługi opisuje odbiór, kontrolę, ważenie, pakowanie i wysyłkę. Potwierdza to proces, nie automatycznie najtańszy ani najbezpieczniejszy plan.", "Decyduj po przyjęciu i zaakceptowanym QC. Wcześniej masa i opakowanie sprzedawcy są szacunkowe. Najpierw oceń zgodność celu, trasy i ochrony. Sprzeczne ograniczenia, terminy lub ryzyka uzasadniają osobne rozważenie."],
      ["Najpierw potwierdź bieżące dopuszczenie każdego towaru. Odzież, bateria, płyn, magnes lub długi przedmiot mogą mieć inne reguły. Jeśli jeden usuwa wszystkie odpowiednie trasy, odizoluj go w porównaniu. Przyjęcie w magazynie nie dowodzi zgody na przewóz międzynarodowy.", "Sprawdź adres i czas, status posprzedażowy oraz zgodność fizyczną. Wszystko idzie do jednego celu; późny sprzedawca opóźnia grupę. Sztywne, kruche, ostre i miękkie przedmioty mogą wymagać innej ochrony. Niezdany filtr to konkretny powód podziału."],
      ["Porównaj bieżącą wycenę, potwierdzone pakowanie i powtórzone koszty paczek. Plan A łączy zgodne towary, B oddziela określoną grupę. Zapisz trasę, szacowaną masę rozliczeniową, fracht i opcje. Nieznane pola zostaw puste zamiast zgadywać kurs, dzielnik lub opłatę.", "Przykład abstrakcyjny: razem 92 jednostki; osobno 58 plus 39, razem 97. Korzyść wynosi pięć. Jeśli podział chroni pudełko, przyspiesza pilny towar lub zachowuje trasę, dopłata może mieć sens. Bez korzyści lepiej udokumentowany jest plan wspólny."],
      ["Fracht może zależeć od masy, objętości i trasy. Konsolidacja ogranicza opakowania, ale długi lekki towar może wydłużyć cały karton. Dwa zwarte przedmioty i jeden długi mogą lepiej działać jako kompaktowy karton plus wąska paczka niż trzy przesyłki.", "Nie obliczaj końcowej objętości bez opublikowanego wzoru i wymiarów po pakowaniu. Zapisz wymiary, opakowanie do zachowania, możliwość złożenia i ochronę. Jeśli jest etap pakowania próbnego, użyj wyniku. Szacunek planuje; gotowy pomiar decyduje."],
      ["Poradnik wspomina usuwanie pudełek, lecz pudełko butów, kolekcjonerskie opakowanie lub wkład mogą chronić wartość. Decyduj dla każdego towaru po obejrzeniu zdjęć, co jest zbędne.", "Pisz sprawdzalne instrukcje: zachowaj wkład, usuń tylko worek kurierski, nie wyrzucaj dodatków, odseparuj metal od tkaniny. Unikaj sprzeczności. Dziel, gdy rozsądne pakowanie nie rozwiąże konfliktu krawędzi, płynu, ciężaru i delikatnego towaru."],
      ["Czekanie na zakupy umożliwia konsolidację, ale najstarsza data magazynowa ogranicza grupę. Sprawdź obecne warunki. Przedsprzedaż lub wymiana może zatrzymać gotowe towary. Wyznacz datę przeglądu.", "Czekaj tylko, gdy nowy towar będzie zgodny i pozostaje bezpieczny zapas czasu. Inaczej wyślij gotową grupę. Nie publikuj zapamiętanej liczby dni jako stałej; zapisz datę i faktycznie sprawdzony warunek."],
      ["Sprawdź maksymalną zgodną konsolidację, izolację tylko konfliktu i sensowne osobne grupy. Cztery ubrania i długi dodatek mogą dać dwie paczki, nie pięć. Pilny pojedynczy towar też może wyjść osobno.", "Oceń wycenę, dopuszczenie, ochronę, gotowość i jakość danych. Bez trasy plan jest niepełny; z szacowanymi wymiarami wstępny; z otwartym QC zablokowany. Porównuj cenę dopiero między prawidłowymi planami."],
      ["Przypisz każdy numer magazynowy do jednej paczki. Sprawdź adres, ilość, wymaganą deklarację, trasę i dopuszczenie. Przejrzyj instrukcje i zachowaj datowaną wycenę. Przed zapłatą uzgodnij zmiany po pakowaniu.", "Oddziel zapis paczki od zamówień sprzedawcy. Jedna paczka może zawierać wiele zamówień, a haul kilka numerów. Konsolidacja jest dobra, gdy pozostaje dopuszczalna, chroniona i wyjaśnialna przy końcowej cenie, a nie gdy mieści najwięcej rzeczy."],
    ], bullets: ["Uwzględnij tylko towary z zakończonym QC i obsługą posprzedażową.", "Potwierdź cel i bieżącą trasę każdego towaru.", "Porównaj plan wspólny, izolację konfliktu i grupy.", "Używaj wymiarów po pakowaniu i aktualnych wycen.", "Pisz instrukcje chroniące ważne części.", "Zachowaj mapę towar-paczka, wycenę, płatność i tracking."],
  },
};

export const consolidationArticles: Record<Locale, ArticlePageContent> = {
  en,
  ...Object.fromEntries(Object.entries(translations).map(([locale, article]) => {
    const { headings, paragraphs, bullets, ...base } = article;
    return [locale, { ...base, sections: headings.map((heading, index) => ({ heading, paragraphs: paragraphs[index], bullets: index === headings.length - 1 ? bullets : undefined })) }];
  })) as Record<Exclude<Locale, "en">, ArticlePageContent>,
};
