import type { ArticlePageContent } from "./site-articles";
import type { Locale } from "./site-content";

const en: ArticlePageContent = {
  label: "Order status guide",
  title: "KameyMall Order Status Guide: From Payment to Warehouse",
  intro: "A practical way to read KameyMall order progress, separate seller movement from warehouse work and decide when a status needs evidence rather than another guess.",
  updated: "Updated August 11, 2026",
  readTime: "14 minute read",
  sourceNote: "Fact-check basis: KameyMall’s current Shopping Agent Service page, public buying guide and live navigation labels, reviewed August 11, 2026. Interface wording and seller timing can change, so the dated order record remains the source of truth.",
  primaryKeyword: "kameymall order status",
  sections: [
    {
      heading: "Read the order as a chain of evidence",
      paragraphs: [
        "A KameyMall agent purchase is not one uninterrupted delivery. It begins with an item order, moves through a Chinese seller and domestic carrier, enters a warehouse for inspection, and only later becomes part of an international parcel. A status tells you which party probably has the next action; it does not prove that every later step is complete. That distinction prevents the two most common mistakes: treating a paid product as internationally shipped, or treating a seller tracking number as warehouse approval.",
        "KameyMall’s public buying guide directs users to My Order after payment, then to My Warehouse after receipt and inspection, and finally to My Package for international freight and tracking. The current site navigation also separates My Orders, My Parcel and Freight Forwarding. Use those separate records deliberately. The order page answers what happened to the purchase; the warehouse record answers what was received and inspected; the parcel page answers what was packed and handed toward international delivery.",
      ],
    },
    {
      heading: "Stage 1: submitted or unpaid needs a checkout check",
      paragraphs: [
        "Immediately after submitting an item, verify the exact source link, variant, quantity and Chinese domestic delivery line. A created order is not necessarily a successful purchase. Confirm that the payment record belongs to the same order number and that the displayed amount matches the checkout you approved. If the payment provider shows an authorization while KameyMall still shows an unpaid or uncertain state, do not automatically pay again. Preserve the provider reference and the platform screen before asking support to reconcile them.",
        "At this stage, the useful evidence is administrative: order number, payment time, amount, currency, selected option and any buyer note. Product photos or seller logistics do not exist yet. If the order is cancelled or needs a price adjustment, compare the new request with the source listing rather than assuming every change is a fee. A seller may change stock, price or domestic delivery. Pause when the requested variant differs from your record; speed is less valuable than buying the correct item.",
      ],
    },
    {
      heading: "Stage 2: buyer processing is not seller dispatch",
      paragraphs: [
        "After payment, the purchasing side must place or confirm the order with the Chinese seller. KameyMall’s Shopping Agent Service describes this as submitting a purchase order and having buyers purchase and store the item. During this interval, no domestic parcel may exist. A status that indicates processing or purchase progress should therefore be checked against buyer messages, price changes and stock questions, not against an international tracking website.",
        "If nothing moves, first look for a request that needs your answer. A complicated listing, manual order, presale, changed price or unavailable option can stop progress without being a logistics failure. Send one concise message containing the order number, exact variant and question. Avoid opening several tickets with different instructions. The best escalation asks for the missing milestone—whether the seller accepted the order, whether a replacement is required, or whether cancellation remains possible—not simply why the whole shipment is late.",
      ],
    },
    {
      heading: "Stage 3: seller dispatch starts Chinese domestic logistics",
      paragraphs: [
        "Once the seller dispatches, the item is moving inside China toward the agent warehouse. This is domestic logistics, not the international parcel. Record the seller carrier and tracking number when available, then watch for a first scan, movement and delivery event. KameyMall’s older public guide describes the seller-to-warehouse interval as variable and gives a broad historical range; because seller stock, presales, holidays and carrier conditions change, this article does not turn that old range into a promise.",
        "A tracking number alone is weak evidence. Some labels are created before the carrier receives the package, and one seller may split multiple items. Compare three facts: the order quantity, the number of domestic tracking numbers and the carrier’s delivered quantity. If movement stops, ask whether the seller actually handed over the parcel. If tracking says delivered but no warehouse entry appears, provide the tracking number, delivery timestamp and order number so staff can match the inbound package instead of searching from a vague description.",
      ],
    },
    {
      heading: "Stage 4: received does not yet mean approved for shipping",
      paragraphs: [
        "KameyMall’s published flow places receipt before inspection. Its buying guide tells users that after the order is received and inspected, warehouse photographs can be viewed through My Warehouse. The Shopping Agent Service also describes warehouse receipt, inspection, weighing and packing as separate work. Therefore, a carrier delivery scan should not be treated as completed QC. The inbound parcel may still need matching, opening, counting, photographing or an exception review.",
        "Use a short waiting checklist: confirm the domestic carrier shows the correct warehouse delivery, check whether all split pieces arrived, review account messages and note the time in China. If a warehouse record still does not appear after the site’s current handling window, send the exact domestic tracking evidence. Do not create a duplicate product order to solve a receiving delay. A duplicate purchase creates a second seller obligation while the first physical item may already be waiting to be identified.",
      ],
    },
    {
      heading: "Stage 5: inspection evidence creates a decision window",
      paragraphs: [
        "When warehouse photos are available, the status question changes from where is it to what was received. Compare identity, selected variant, size label, color, quantity, visible condition and explicitly included accessories with the saved order. Photos can confirm only what is visible. They do not prove authenticity, internal construction, fit, battery performance or long-term durability. If an essential detail is hidden, request a useful view instead of interpreting a shadow or promotional expectation as a defect.",
        "Classify the result as accept, clarify or seek return. Accept when the visible evidence matches and no open question changes the decision. Clarify when the image is incomplete or ambiguous. Seek after-sales help when a material mismatch is visible and the current seller and platform process still permits it. The warehouse storage clock is not automatically the return clock, so inspect promptly. Keep the source option and annotated warehouse evidence together for any request.",
      ],
    },
    {
      heading: "Stage 6: warehouse-ready is not an international tracking event",
      paragraphs: [
        "A stored item is available for a later parcel decision. It has not been exported simply because QC is finished. Before creating a parcel, close any return question, identify the oldest storage date, group only route-compatible items and compare packaging needs. KameyMall’s current Shopping Agent Service places package submission and international-freight payment after warehouse receipt. This is the second commercial decision, with its own weight, dimensions, route eligibility, packaging and address checks.",
        "After parcel submission, distinguish packed, paid, handed to the logistics provider and tracking-active evidence. A number may exist before the first public carrier scan. Check the parcel page rather than the original item order for international progress. If the parcel has not updated, capture its number, selected line, payment time, latest platform event and carrier result. Never use a product-order status to claim that a parcel is in customs or out for delivery; those belong to later logistics evidence.",
      ],
    },
    {
      heading: "Use a status exception worksheet before contacting support",
      paragraphs: [
        "Create one row per item with eight fields: KameyMall order number, source listing, selected variant, payment confirmation, seller tracking, latest carrier event, warehouse record and next action. Add a separate parcel row only after international submission. This prevents a multi-seller haul from becoming one vague timeline. For example, one hoodie can be seller-dispatched, one pair of shoes can be under inspection and one accessory can already be stored; waiting for all three is a consolidation choice, not one shared delay status.",
        "Escalate when the evidence contradicts itself or a required action is unclear. A useful message says: order 123, seller tracking XYZ shows delivered on a stated date, but no warehouse record is visible; please match the inbound parcel. An unhelpful message says only that the order is slow. Before sending, check account notices, China working time, split shipments and unanswered buyer questions. Then preserve the response beside the record so the next decision uses facts rather than repeated assumptions.",
      ],
      bullets: [
        "Match every payment to one order number and selected variant.",
        "Treat buyer processing, seller dispatch and warehouse receipt as different events.",
        "Save domestic tracking and delivery evidence before escalating a missing inbound item.",
        "Review warehouse photos before accepting or starting the international parcel.",
        "Track international movement from My Package, not the original product order.",
        "Ask support for one missing milestone and include the evidence needed to find it.",
      ],
    },
  ],
  conclusionTitle: "A useful status always points to the next proof",
  conclusion: "Read KameyMall progress as a handoff between payment, buyer, seller, domestic carrier, warehouse and international parcel. Keep those records separate, identify the missing milestone and escalate with exact evidence. That method will not make a seller faster, but it makes every follow-up clearer and prevents duplicate payments, duplicate orders and premature shipping assumptions.",
  seoTitle: "KameyMall Order Status Guide: Payment to Warehouse",
  seoDescription: "Understand KameyMall order status from payment and buyer processing to seller dispatch, warehouse receipt, QC and international parcel tracking.",
};

function localized(
  locale: Exclude<Locale, "en">,
  title: string,
  intro: string,
  label: string,
  updated: string,
  readTime: string,
  primaryKeyword: string,
  seoTitle: string,
  seoDescription: string,
  headings: string[],
  paragraphs: string[][],
  bullets: string[],
  conclusionTitle: string,
  conclusion: string,
): ArticlePageContent {
  return {
    ...en,
    label,
    title,
    intro,
    updated,
    readTime,
    sourceNote: locale === "de" ? "Faktenbasis: aktuelle KameyMall-Seite Shopping Agent Service, öffentlicher Einkaufsleitfaden und Live-Navigation, geprüft am 11. August 2026. Bezeichnungen und Verkäuferzeiten können sich ändern; maßgeblich bleibt der datierte Auftragsdatensatz."
      : locale === "fr" ? "Base factuelle : page actuelle Shopping Agent Service, guide d’achat public et libellés de navigation KameyMall, vérifiés le 11 août 2026. Les statuts et délais vendeur peuvent changer ; le dossier daté de la commande fait foi."
      : locale === "es" ? "Base factual: Shopping Agent Service, guía pública de compra y etiquetas actuales de navegación de KameyMall, revisadas el 11 de agosto de 2026. Los estados y tiempos del vendedor pueden cambiar; manda el registro fechado del pedido."
      : locale === "it" ? "Base dei fatti: pagina Shopping Agent Service, guida pubblica all’acquisto e voci di navigazione attuali KameyMall, verificate l’11 agosto 2026. Stati e tempi del venditore possono cambiare; fa fede il registro datato dell’ordine."
      : "Podstawa faktów: aktualna strona Shopping Agent Service, publiczny poradnik zakupowy i bieżące etykiety KameyMall, sprawdzone 11 sierpnia 2026. Nazwy statusów i czas sprzedawcy mogą się zmieniać; źródłem prawdy jest datowany zapis zamówienia.",
    primaryKeyword,
    sections: headings.map((heading, index) => ({ heading, paragraphs: paragraphs[index], bullets: index === headings.length - 1 ? bullets : undefined })),
    conclusionTitle,
    conclusion,
    seoTitle,
    seoDescription,
  };
}

const de = localized("de", "KameyMall-Bestellstatus: von der Zahlung bis zum Lager", "So liest du den Bestellfortschritt, trennst Verkäufertransport von Lagerarbeit und erkennst, wann ein Status Belege statt Vermutungen braucht.", "Bestellstatus-Leitfaden", "Aktualisiert am 11. August 2026", "14 Minuten Lesezeit", "kameymall bestellstatus", "KameyMall-Bestellstatus: Zahlung bis Lager", "KameyMall-Status von Zahlung und Einkauf über Verkäuferversand, Wareneingang und QC bis zum internationalen Paket verstehen.",
  ["Den Auftrag als Beweiskette lesen", "Stufe 1: eingereicht oder unbezahlt", "Stufe 2: Einkauf ist noch kein Verkäuferversand", "Stufe 3: Verkäuferversand startet die Inlandlogistik", "Stufe 4: zugestellt bedeutet noch nicht versandbereit", "Stufe 5: QC eröffnet eine Entscheidung", "Stufe 6: Lagerbestand ist kein internationales Tracking", "Vor dem Support eine Status-Tabelle führen"],
  [
    ["Ein Agentenauftrag durchläuft Produktzahlung, Einkäufer, chinesischen Verkäufer, Inlandsträger und Lager, bevor daraus ein internationales Paket wird. Ein Status zeigt den wahrscheinlichen nächsten Verantwortlichen, beweist aber keine späteren Schritte. Bezahlt heißt daher weder international versandt noch vom Lager akzeptiert.", "Der öffentliche Leitfaden trennt My Order, My Warehouse und My Package; auch die aktuelle Navigation führt Bestellungen und Pakete getrennt. Nutze den Auftragsdatensatz für Kauf und Verkäufer, den Lagerdatensatz für Eingang und Prüfung und die Paketseite erst für Verpackung und internationalen Versand."],
    ["Prüfe direkt nach Einreichung Quelllink, Variante, Menge, chinesische Lieferung und die passende Zahlungsbestätigung. Zeigt der Zahlungsanbieter eine Autorisierung, KameyMall aber keinen klaren Erfolg, zahle nicht sofort erneut. Sichere Referenz, Uhrzeit, Betrag und Bildschirm für die Abstimmung.", "Hier zählen Verwaltungsbelege: Auftragsnummer, Währung, gewählte Option und Hinweis. Bei Preisänderung oder Storno vergleiche die neue Anfrage mit dem Quellangebot. Eine Verkäuferkorrektur ist nicht automatisch eine Plattformgebühr; pausiere, wenn die Variante nicht mehr stimmt."],
    ["Nach Zahlung muss der Einkäufer die Bestellung beim Verkäufer platzieren oder bestätigen. Die aktuelle Serviceseite beschreibt den Kauf und die spätere Lagerung. In diesem Intervall kann noch kein Inlandspaket existieren; prüfe Nachrichten zu Bestand, Preis und Optionen statt internationales Tracking.", "Fehlt Bewegung, suche zuerst eine unbeantwortete Frage. Komplizierte Angebote, manuelle Bestellungen, Vorverkauf oder fehlender Bestand können den Kauf stoppen. Frage mit Nummer, Variante und einem klaren Ziel: Hat der Verkäufer bestätigt, ist Ersatz nötig oder kann noch storniert werden?"],
    ["Mit dem Verkäuferversand beginnt nur der Transport innerhalb Chinas. Speichere Träger und Nummer und beobachte Übergabe, Bewegung und Zustellung. Ältere veröffentlichte Zeitspannen sind wegen Bestand, Feiertagen und Vorverkauf keine aktuelle Garantie.", "Eine Nummer allein beweist keine Übergabe. Vergleiche Menge, mögliche Teilpakete und Zustellereignis. Bei zugestellt ohne Lagerdatensatz sende Nummer, Zeit und Auftragsnummer, damit das Eingangspaket konkret zugeordnet werden kann."],
    ["Der veröffentlichte Ablauf setzt Eingang vor Prüfung. Fotos erscheinen laut Leitfaden nach Empfang und Inspektion in My Warehouse. Ein Zustellscan ist deshalb kein fertiges QC; Zuordnung, Öffnung, Zählung, Foto oder Ausnahmeprüfung können noch fehlen.", "Prüfe Zieladresse, Teilpakete, Nachrichten und chinesische Uhrzeit. Bleibt der Lagerdatensatz nach dem aktuellen Bearbeitungsfenster aus, sende den Inlandnachweis. Erstelle keine Doppelbestellung: Das erste physische Produkt kann bereits auf Zuordnung warten."],
    ["Sobald Fotos vorliegen, frage nicht mehr wo, sondern was eingegangen ist. Vergleiche Identität, Variante, Größe, Farbe, Menge, sichtbaren Zustand und angekündigtes Zubehör. Fotos beweisen nur Sichtbares, nicht Echtheit, Innenaufbau, Passform oder Haltbarkeit.", "Ordne das Ergebnis als akzeptieren, klären oder Rückgabe prüfen ein. Unklare Bilder verlangen eine brauchbare Ansicht, sichtbare wesentliche Abweichungen eine schnelle After-Sales-Anfrage. Lagerfrist und Rückgabefrist sind nicht automatisch gleich; bewahre Quelloption und Bildbeleg zusammen auf."],
    ["Ein gelagerter Artikel ist noch nicht exportiert. Schließe Rückfragen, beachte das älteste Lagerdatum, gruppiere nur kompatible Waren und prüfe Verpackung. Die Serviceseite setzt Paketeinreichung und internationale Zahlung nach den Lagereingang.", "Trenne danach gepackt, bezahlt, an Logistik übergeben und Tracking aktiv. Eine Nummer kann vor dem ersten Scan existieren. Prüfe internationales Geschehen in My Package und sichere Paketnummer, Linie, Zahlung und letztes Ereignis statt den Produktstatus als Zollnachweis zu verwenden."],
    ["Führe je Artikel eine Zeile mit Auftragsnummer, Quelle, Variante, Zahlung, Verkäufertracking, letztem Trägerereignis, Lagerdatensatz und nächster Aktion. Erst nach Einreichung kommt eine eigene Paketzeile hinzu. Mehrere Verkäufer befinden sich oft gleichzeitig in verschiedenen Stufen.", "Eskaliere bei Widerspruch oder unklarer Aktion. Nenne Nummer, Tracking, Zustellzeit und fehlenden Lagerdatensatz. Prüfe vorher Meldungen, chinesische Arbeitszeit, Teilpakete und offene Fragen. Eine präzise fehlende Etappe ist für den Support auffindbar; langsam allein ist es nicht."],
  ],
  ["Jede Zahlung einer Auftragsnummer und Variante zuordnen.", "Einkauf, Verkäuferversand und Lagereingang getrennt behandeln.", "Inlandtracking vor Eskalation eines fehlenden Eingangs sichern.", "Lagerfotos vor Annahme oder Paketbildung prüfen.", "Internationales Tracking in My Package verfolgen.", "Beim Support eine fehlende Etappe mit Belegen nennen."],
  "Ein brauchbarer Status führt zum nächsten Beleg", "Lies den Fortschritt als Übergabe zwischen Zahlung, Einkäufer, Verkäufer, Inlandsträger, Lager und internationalem Paket. Halte die Datensätze getrennt und eskaliere die exakt fehlende Etappe. Das beschleunigt keinen Verkäufer, verhindert aber Doppelzahlungen, Doppelbestellungen und falsche Versandannahmen.");

const fr = localized("fr", "Statut de commande KameyMall : du paiement à l’entrepôt", "Une méthode pratique pour lire la progression, séparer l’acheminement vendeur du travail d’entrepôt et demander la bonne preuve au bon moment.", "Guide du statut de commande", "Mis à jour le 11 août 2026", "14 minutes de lecture", "statut commande kameymall", "Statut KameyMall : du paiement à l’entrepôt", "Comprenez le statut KameyMall du paiement à l’achat, à l’envoi vendeur, à la réception, au QC et au colis international.",
  ["Lire la commande comme une chaîne de preuves", "Étape 1 : soumise ou impayée", "Étape 2 : l’achat n’est pas l’expédition vendeur", "Étape 3 : l’envoi vendeur lance la livraison chinoise", "Étape 4 : livré ne veut pas encore dire prêt", "Étape 5 : le QC ouvre une décision", "Étape 6 : stocké n’est pas un suivi international", "Préparer une fiche d’exception avant le support"],
  [
    ["Une commande par agent passe par paiement, acheteur, vendeur chinois, transport intérieur et entrepôt avant de devenir un colis international. Un statut indique le prochain responsable probable, mais ne prouve pas les étapes suivantes. Payé ne signifie donc ni expédié à l’étranger ni accepté par l’entrepôt.", "Le guide public sépare My Order, My Warehouse et My Package ; la navigation actuelle distingue aussi commandes et colis. Utilisez la commande pour achat et vendeur, l’entrepôt pour réception et contrôle, puis le colis pour emballage et transport international."],
    ["Après soumission, vérifiez lien source, variante, quantité, livraison chinoise et confirmation correspondante. Si le prestataire montre une autorisation mais KameyMall reste incertain, ne repayez pas immédiatement. Conservez référence, heure, montant et écran pour le rapprochement.", "À ce stade, les preuves sont administratives : numéro, devise, option et note. Lors d’un ajustement, comparez la demande à l’annonce source. Une modification du vendeur n’est pas automatiquement un frais ; arrêtez-vous si la variante ne correspond plus."],
    ["Après paiement, l’acheteur doit placer ou confirmer l’ordre auprès du vendeur. Le service officiel décrit cet achat puis le stockage. Aucun colis intérieur n’existe forcément encore ; cherchez les messages sur stock, prix et option plutôt qu’un suivi international.", "En cas d’arrêt, vérifiez une question sans réponse. Une annonce complexe, une commande manuelle, une précommande ou une rupture peut bloquer. Demandez avec numéro et variante si le vendeur a confirmé, si un remplacement est nécessaire ou si l’annulation reste possible."],
    ["L’expédition vendeur lance seulement la logistique en Chine. Enregistrez transporteur et numéro, puis observez prise en charge, mouvement et livraison. Les anciennes plages publiques ne sont pas des garanties actuelles face au stock, aux fêtes ou aux précommandes.", "Un numéro seul ne prouve pas la remise au transporteur. Comparez quantité, colis fractionnés et événement livré. Si livré sans entrée, fournissez numéro, heure et commande afin que l’entrepôt puisse associer le colis reçu."],
    ["Le parcours publié place la réception avant l’inspection. Les photos apparaissent après réception et contrôle dans My Warehouse. Un scan livré n’est donc pas un QC terminé : association, ouverture, comptage, photo ou exception peuvent rester.", "Vérifiez adresse de livraison, colis divisés, messages et heure chinoise. Si l’entrée manque après le délai actif, envoyez la preuve intérieure. Ne recréez pas la commande : le premier article physique peut déjà attendre son identification."],
    ["Avec les photos, la question devient ce qui a été reçu. Comparez identité, variante, taille, couleur, quantité, état visible et accessoires annoncés. Une image ne prouve pas authenticité, intérieur, coupe ou durée de vie.", "Classez accepter, clarifier ou demander un retour. Une image ambiguë exige une vue utile ; une différence matérielle visible exige une demande rapide selon les règles actuelles. Stockage et retour n’ont pas forcément la même échéance ; gardez l’option source avec la preuve."],
    ["Un article stocké n’est pas exporté. Fermez les retours, repérez la date la plus ancienne, regroupez seulement les articles compatibles et vérifiez l’emballage. Le service actuel place soumission du colis et fret international après l’entrée en stock.", "Distinguez emballé, payé, remis au logisticien et suivi actif. Un numéro peut précéder le premier scan. Suivez l’international dans My Package et gardez numéro, ligne, paiement et dernier événement ; le statut produit ne prouve pas la douane."],
    ["Créez une ligne par article : numéro, source, variante, paiement, suivi vendeur, dernier événement, entrepôt et action suivante. Ajoutez une ligne colis seulement après soumission. Des vendeurs différents peuvent être à des étapes différentes.", "Escaladez une contradiction ou une action inconnue. Indiquez numéro, suivi, heure de livraison et entrée manquante. Vérifiez d’abord notifications, heure de travail, colis séparés et questions ouvertes. Une étape manquante précise est recherchable ; “c’est lent” ne l’est pas."],
  ],
  ["Associer chaque paiement à une commande et une variante.", "Séparer achat, envoi vendeur et réception entrepôt.", "Conserver le suivi intérieur avant d’escalader.", "Examiner les photos avant d’accepter ou créer le colis.", "Suivre l’international dans My Package.", "Demander au support une étape précise avec ses preuves."],
  "Un statut utile mène à la prochaine preuve", "Lisez la progression comme un transfert entre paiement, acheteur, vendeur, transport intérieur, entrepôt et colis international. Séparez les dossiers et demandez l’étape exacte manquante. Cela ne rend pas le vendeur plus rapide, mais évite doubles paiements, doubles commandes et conclusions prématurées.");

const es = localized("es", "Estado del pedido KameyMall: del pago al almacén", "Un método práctico para leer el progreso, separar el envío del vendedor del trabajo de almacén y pedir la evidencia correcta.", "Guía de estado del pedido", "Actualizado el 11 de agosto de 2026", "14 minutos de lectura", "estado pedido kameymall", "Estado de pedido KameyMall: pago a almacén", "Entiende el estado KameyMall desde pago y compra hasta envío del vendedor, recepción, QC y paquete internacional.",
  ["Leer el pedido como cadena de evidencias", "Etapa 1: enviado o pendiente de pago", "Etapa 2: comprar no es enviar", "Etapa 3: el vendedor inicia la logística china", "Etapa 4: entregado aún no significa listo", "Etapa 5: el QC abre una decisión", "Etapa 6: almacenado no es seguimiento internacional", "Crear una hoja de excepción antes de soporte"],
  [
    ["Una compra con agente pasa por pago, comprador, vendedor chino, transportista nacional y almacén antes del paquete internacional. Un estado apunta al siguiente responsable, pero no prueba fases posteriores. Pagado no significa enviado al extranjero ni aceptado por el almacén.", "La guía pública separa My Order, My Warehouse y My Package; la navegación actual también distingue pedidos y paquetes. Usa el pedido para compra y vendedor, almacén para recepción y control, y paquete para embalaje y transporte internacional."],
    ["Tras enviar el pedido, verifica enlace, variante, cantidad, entrega china y confirmación de pago. Si el proveedor muestra autorización pero KameyMall queda incierto, no pagues otra vez. Guarda referencia, hora, importe y pantalla.", "Aquí valen pruebas administrativas: número, moneda, opción y nota. Si hay ajuste, compáralo con el anuncio fuente. Un cambio del vendedor no es automáticamente una comisión; pausa si la variante ya no coincide."],
    ["Después del pago, el comprador debe realizar o confirmar la orden con el vendedor. El servicio oficial describe comprar y almacenar. Puede no existir paquete nacional todavía; revisa mensajes de stock, precio y opción en vez de seguimiento internacional.", "Si se detiene, busca una pregunta sin responder. Anuncios complejos, pedido manual, preventa o falta de stock pueden bloquearlo. Pregunta con número y variante si el vendedor confirmó, hace falta sustitución o aún puede cancelarse."],
    ["El envío del vendedor solo inicia el trayecto dentro de China. Guarda transportista y número y observa recogida, movimiento y entrega. Los rangos antiguos no son promesas actuales por stock, fiestas o preventas.", "Un número no demuestra recogida. Compara cantidad, paquetes divididos y evento de entrega. Si aparece entregado sin almacén, facilita número, hora y pedido para que identifiquen la entrada."],
    ["El flujo publicado sitúa recepción antes de inspección. Las fotos aparecen tras recibir y revisar en My Warehouse. Un escaneo entregado no es QC terminado: faltan asociación, apertura, conteo, fotografía o revisión de excepción.", "Comprueba dirección, piezas divididas, mensajes y hora china. Si sigue sin registro tras el plazo activo, envía la evidencia nacional. No dupliques la compra: el primer producto puede estar esperando identificación."],
    ["Con fotos, la pregunta es qué llegó. Compara identidad, variante, talla, color, cantidad, estado visible y accesorios anunciados. Las imágenes no prueban autenticidad, interior, ajuste ni durabilidad.", "Clasifica aceptar, aclarar o solicitar devolución. Una imagen ambigua requiere una vista útil; una diferencia material visible, una gestión rápida según reglas actuales. Almacenamiento y devolución no son el mismo reloj."],
    ["Un artículo almacenado no está exportado. Cierra devoluciones, anota la fecha más antigua, agrupa solo compatibles y decide embalaje. El servicio actual coloca envío del paquete y flete internacional después del almacén.", "Distingue embalado, pagado, entregado a logística y seguimiento activo. Un número puede preceder al primer escaneo. Sigue el internacional en My Package y conserva número, línea, pago y último evento."],
    ["Crea una fila por artículo con pedido, fuente, variante, pago, seguimiento vendedor, último evento, almacén y siguiente acción. Añade fila de paquete solo tras enviarlo. Varios vendedores pueden estar en fases distintas.", "Escala una contradicción concreta: número, seguimiento, hora de entrega y registro ausente. Revisa avisos, horario chino, paquetes divididos y preguntas abiertas. Una etapa faltante se puede buscar; decir solo que va lento no."],
  ],
  ["Asociar cada pago a un pedido y variante.", "Separar compra, envío vendedor y recepción.", "Guardar seguimiento nacional antes de escalar.", "Revisar fotos antes de aceptar o crear paquete.", "Seguir el internacional desde My Package.", "Pedir a soporte una etapa concreta con pruebas."],
  "Un estado útil conduce a la siguiente prueba", "Lee el progreso como relevo entre pago, comprador, vendedor, transportista nacional, almacén y paquete internacional. Mantén registros separados y señala la etapa exacta que falta. No hará más rápido al vendedor, pero evita dobles pagos, pedidos duplicados y conclusiones prematuras.");

const it = localized("it", "Stato ordine KameyMall: dal pagamento al magazzino", "Un metodo pratico per leggere l’avanzamento, separare la spedizione del venditore dal lavoro del magazzino e chiedere la prova giusta.", "Guida allo stato ordine", "Aggiornato l’11 agosto 2026", "14 minuti di lettura", "stato ordine kameymall", "Stato ordine KameyMall: pagamento e magazzino", "Capisci lo stato KameyMall da pagamento e acquisto a invio venditore, ricezione, QC e pacco internazionale.",
  ["Leggere l’ordine come catena di prove", "Fase 1: inviato o non pagato", "Fase 2: acquisto non significa spedizione", "Fase 3: il venditore avvia la logistica cinese", "Fase 4: consegnato non significa pronto", "Fase 5: il QC apre una decisione", "Fase 6: in magazzino non è tracking internazionale", "Preparare una scheda prima dell’assistenza"],
  [
    ["Un ordine tramite agente passa da pagamento, buyer, venditore cinese, corriere nazionale e magazzino prima del pacco internazionale. Uno stato indica il prossimo responsabile, ma non prova le fasi successive. Pagato non significa spedito all’estero o accettato dal magazzino.", "La guida pubblica separa My Order, My Warehouse e My Package; anche la navigazione corrente distingue ordini e pacchi. Usa l’ordine per acquisto e venditore, il magazzino per ricezione e controllo, il pacco per imballaggio e trasporto internazionale."],
    ["Dopo l’invio verifica link, variante, quantità, consegna cinese e conferma di pagamento. Se il provider mostra un’autorizzazione ma KameyMall resta incerto, non pagare di nuovo. Conserva riferimento, ora, importo e schermata.", "Qui servono prove amministrative: numero, valuta, opzione e nota. In caso di modifica confronta la richiesta con l’annuncio. Un cambiamento del venditore non è automaticamente una commissione; fermati se la variante non coincide."],
    ["Dopo il pagamento il buyer deve piazzare o confermare l’ordine al venditore. Il servizio ufficiale descrive acquisto e deposito. Potrebbe non esistere ancora un pacco nazionale; controlla messaggi su disponibilità, prezzo e opzione.", "Se il flusso si ferma, cerca una domanda senza risposta. Annunci complessi, ordini manuali, preorder o esaurimento possono bloccare. Chiedi con numero e variante se il venditore ha confermato, serve una sostituzione o è possibile annullare."],
    ["L’invio del venditore avvia solo il tragitto in Cina. Registra corriere e numero, poi osserva presa in carico, movimento e consegna. Le vecchie tempistiche non sono promesse attuali con scorte, feste e preorder.", "Un numero non prova la consegna al corriere. Confronta quantità, pacchi divisi ed evento consegnato. Se risulta consegnato senza ingresso, fornisci numero, ora e ordine per l’abbinamento."],
    ["Il flusso pubblicato pone la ricezione prima dell’ispezione. Le foto appaiono dopo ricezione e controllo in My Warehouse. Una scansione consegnata non è QC completo: possono mancare abbinamento, apertura, conteggio, foto o eccezione.", "Controlla indirizzo, colli separati, messaggi e ora cinese. Se il record manca oltre il tempo corrente, invia la prova nazionale. Non duplicare l’acquisto: il primo articolo può essere già in attesa di identificazione."],
    ["Con le foto la domanda diventa cosa è arrivato. Confronta identità, variante, taglia, colore, quantità, stato visibile e accessori dichiarati. Le immagini non provano autenticità, interno, vestibilità o durata.", "Classifica accetta, chiarisci o chiedi reso. Un’immagine ambigua richiede una vista utile; una differenza visibile importante richiede azione rapida secondo le regole correnti. Deposito e reso non hanno automaticamente la stessa scadenza."],
    ["Un articolo depositato non è esportato. Chiudi i resi, annota la data più vecchia, raggruppa solo articoli compatibili e verifica l’imballaggio. Il servizio corrente pone invio pacco e pagamento internazionale dopo il magazzino.", "Distingui imballato, pagato, consegnato al partner e tracking attivo. Un numero può precedere la prima scansione. Segui l’estero in My Package e conserva numero, linea, pagamento e ultimo evento."],
    ["Crea una riga per articolo con ordine, fonte, variante, pagamento, tracking venditore, ultimo evento, record magazzino e prossima azione. Aggiungi una riga pacco solo dopo l’invio. Venditori diversi possono essere in fasi diverse.", "Escala una contraddizione precisa con numero, tracking, ora di consegna e ingresso mancante. Prima controlla notifiche, orario cinese, colli separati e domande aperte. Una fase mancante è rintracciabile; “è lento” no."],
  ],
  ["Associare ogni pagamento a ordine e variante.", "Separare acquisto, invio venditore e ricezione.", "Salvare il tracking nazionale prima di escalare.", "Controllare le foto prima di accettare o creare il pacco.", "Seguire l’estero da My Package.", "Chiedere all’assistenza una fase precisa con prove."],
  "Uno stato utile porta alla prova successiva", "Leggi l’avanzamento come passaggio tra pagamento, buyer, venditore, corriere nazionale, magazzino e pacco internazionale. Tieni separati i record e segnala la fase esatta mancante. Non rende il venditore più veloce, ma evita doppi pagamenti, ordini duplicati e conclusioni premature.");

const pl = localized("pl", "Status zamówienia KameyMall: od płatności do magazynu", "Praktyczna metoda odczytu postępu, oddzielenia wysyłki sprzedawcy od pracy magazynu i zebrania właściwego dowodu.", "Poradnik statusu zamówienia", "Aktualizacja: 11 sierpnia 2026", "14 minut czytania", "status zamówienia kameymall", "Status KameyMall: od płatności do magazynu", "Poznaj status KameyMall od płatności i zakupu przez wysyłkę sprzedawcy, przyjęcie, QC i paczkę międzynarodową.",
  ["Czytaj zamówienie jako łańcuch dowodów", "Etap 1: złożone lub nieopłacone", "Etap 2: zakup to nie wysyłka sprzedawcy", "Etap 3: sprzedawca uruchamia logistykę krajową", "Etap 4: doręczone nie znaczy gotowe", "Etap 5: QC otwiera decyzję", "Etap 6: w magazynie to nie tracking międzynarodowy", "Przygotuj tabelę przed kontaktem z pomocą"],
  [
    ["Zamówienie przez agenta przechodzi przez płatność, kupującego, chińskiego sprzedawcę, przewoźnika krajowego i magazyn, zanim stanie się paczką międzynarodową. Status wskazuje następnego odpowiedzialnego, ale nie dowodzi późniejszych etapów. Opłacone nie oznacza wysłane za granicę ani przyjęte przez magazyn.", "Publiczny poradnik rozdziela My Order, My Warehouse i My Package; bieżąca nawigacja także oddziela zamówienia od paczek. Używaj zamówienia dla zakupu i sprzedawcy, magazynu dla przyjęcia i kontroli, a paczki dla pakowania i transportu międzynarodowego."],
    ["Po złożeniu sprawdź link, wariant, ilość, dostawę w Chinach i potwierdzenie płatności. Jeśli operator pokazuje autoryzację, a KameyMall niejasny status, nie płać ponownie. Zachowaj numer, godzinę, kwotę i ekran.", "Tu liczą się dowody administracyjne: numer, waluta, opcja i uwaga. Przy korekcie porównaj żądanie z ofertą. Zmiana sprzedawcy nie jest automatycznie opłatą; zatrzymaj się, gdy wariant już się nie zgadza."],
    ["Po płatności kupujący musi złożyć lub potwierdzić zamówienie u sprzedawcy. Oficjalny serwis opisuje zakup i magazynowanie. Paczka krajowa może jeszcze nie istnieć; sprawdź wiadomości o stanie, cenie i opcji.", "Gdy brak ruchu, szukaj pytania bez odpowiedzi. Złożona oferta, zamówienie ręczne, przedsprzedaż lub brak stanu mogą blokować. Zapytaj z numerem i wariantem, czy sprzedawca potwierdził, potrzebny jest zamiennik lub można anulować."],
    ["Wysyłka sprzedawcy rozpoczyna tylko trasę w Chinach. Zapisz przewoźnika i numer oraz obserwuj odbiór, ruch i dostarczenie. Stare widełki nie są bieżącą gwarancją przy zapasach, świętach i przedsprzedaży.", "Sam numer nie dowodzi przekazania. Porównaj ilość, rozdzielone paczki i zdarzenie dostawy. Jeśli doręczono bez wpisu magazynu, podaj numer, czas i zamówienie do dopasowania."],
    ["Opublikowany proces stawia odbiór przed kontrolą. Zdjęcia pojawiają się po przyjęciu i inspekcji w My Warehouse. Skan doręczono nie oznacza gotowego QC: może brakować dopasowania, otwarcia, liczenia, zdjęć lub obsługi wyjątku.", "Sprawdź adres, części przesyłki, wiadomości i czas chiński. Jeśli zapis nie pojawi się po aktualnym oknie obsługi, wyślij dowód krajowy. Nie duplikuj zakupu: pierwszy produkt może już czekać na identyfikację."],
    ["Po zdjęciach pytanie brzmi, co dotarło. Porównaj tożsamość, wariant, rozmiar, kolor, ilość, widoczny stan i zapowiedziane dodatki. Zdjęcia nie potwierdzają autentyczności, wnętrza, dopasowania ani trwałości.", "Wybierz zaakceptuj, wyjaśnij lub poproś o zwrot. Niejasne zdjęcie wymaga użytecznego ujęcia, a istotna widoczna różnica szybkiej obsługi według bieżących zasad. Magazyn i zwrot nie muszą mieć tego samego terminu."],
    ["Towar w magazynie nie został wyeksportowany. Zamknij zwroty, zanotuj najstarszą datę, łącz tylko kompatybilne artykuły i sprawdź opakowanie. Bieżący serwis umieszcza paczkę i płatność międzynarodową po przyjęciu.", "Oddziel spakowane, opłacone, przekazane logistyce i aktywny tracking. Numer może pojawić się przed skanem. Śledź zagraniczną część w My Package i zachowaj numer, linię, płatność i ostatnie zdarzenie."],
    ["Prowadź wiersz dla każdego artykułu: numer, źródło, wariant, płatność, tracking sprzedawcy, ostatnie zdarzenie, magazyn i kolejny krok. Wiersz paczki dodaj dopiero po złożeniu. Różni sprzedawcy mogą być na różnych etapach.", "Eskaluj konkretną sprzeczność z numerem, trackingiem, czasem doręczenia i brakującym wpisem. Najpierw sprawdź powiadomienia, czas pracy, części paczki i pytania. Brakujący etap można znaleźć; samo „wolno” nie."],
  ],
  ["Przypisz każdą płatność do zamówienia i wariantu.", "Rozdziel zakup, wysyłkę sprzedawcy i przyjęcie.", "Zachowaj tracking krajowy przed eskalacją.", "Sprawdź zdjęcia przed akceptacją lub paczką.", "Śledź zagraniczną część w My Package.", "Proś pomoc o jeden brakujący etap z dowodami."],
  "Dobry status prowadzi do następnego dowodu", "Czytaj postęp jako przekazanie między płatnością, kupującym, sprzedawcą, przewoźnikiem krajowym, magazynem i paczką międzynarodową. Oddziel zapisy i wskaż dokładnie brakujący etap. Nie przyspieszy sprzedawcy, ale zapobiegnie podwójnym płatnościom, zamówieniom i przedwczesnym wnioskom.");

export const orderStatusArticles: Record<Locale, ArticlePageContent> = { en, de, fr, es, it, pl };
