"""Generate the localized static site for the intended production domain."""
from pathlib import Path
import html, json, re
import xml.etree.ElementTree as ET
from urllib.parse import quote
from datetime import date

ROOT=Path(__file__).parent; DIST=ROOT/'dist'; SITE='https://hipobuyy-sheet.com'; SHOP='https://cnbuycha.com'
P=json.loads((ROOT/'products.json').read_text())
LANGS=['en','de','es','fr','it']
ROUTES=['','spreadsheet','finds','guide','qc','shipping','faq','articles']
SLUGS=['spreadsheet-first','qc-photo-checklist','shipping-cost-checklist',
       'order-status-workflow','return-policy-warehouse','warehouse-storage-consolidation',
       'fees-wallet-payment','customs-declaration-insurance','parcel-tracking-delivery',
       'reading-hipobuy-reviews']
CATEGORIES=['shoes','hoodies-sweaters','t-shirts','jackets','pants-shorts','accessories','jersey']

T={
'en':{
'nav':['Home','Spreadsheet','Finds','Guide','QC','Shipping','FAQ','Articles'],
'brand':'HIPOBUYY / SHEET','eyebrow':'Independent product discovery',
'hero':'Hipobuy spreadsheet finds, easier to inspect.',
'sub':'Browse a real product snapshot, compare categories and open the exact listing. Photos and USD prices come from the linked catalog; check the destination before buying.',
'search':'Search products on the catalog','searchbutton':'Search',
'aside_title':'A spreadsheet you can actually browse','aside':'Filter real listings here or use the table view. Each product opens its matching listing; category shortcuts open their matching catalog category.','tablelink':'Open the spreadsheet',
'products':'Browse product finds','products_sub':'A dated sample of catalog listings, with the first product image and displayed USD price.','viewall':'View all finds',
'categories':'Browse by category','categories_sub':'Open the matching category in the destination catalog.','how':'A clearer way to shop','how_sub':'Use the directory to narrow your options, then inspect the listing and the actual item before approving a purchase.',
'steps':['Browse by category or search for a model.','Compare the listing image, price, variants and source link.','Review warehouse QC photos and shipping quotes before checkout.'],
'reading':'Practical reading','reading_sub':'Detailed, independently written guides for the decisions that matter.','read':'Read guide',
'snapshot':'Snapshot checked on 23 September 2026. Prices and availability can change. Product images and prices reflect the linked catalog at capture time. This site does not claim to have verified the physical items or warehouse QC photos.',
'independent':'Independent directory. Not the official Hipobuy service. Product links and searches lead to the linked catalog; purchases and support happen there. Check current item details before ordering.',
'open':'Open listing','all':'All','item':'Product','category':'Category','price':'USD price','link':'Listing',
'page_titles':['Find products faster','The Hipobuy spreadsheet','Product finds','How to use the directory','How to inspect QC photos','Shipping: compare the full cost','Useful buying notes','Articles and guides'],
'page_subs':['','','Search or filter the current product snapshot. Open an exact product listing to see live details.','A short path from finding an item to deciding whether to order.','A practical visual check after an item reaches the warehouse.','Estimate the complete parcel cost before choosing a shipping method.','The details most buyers should verify before paying.','Focused articles built around product discovery, QC and shipping.'],
'article_titles':['How to use a Hipobuy spreadsheet without losing the original listing','A QC photo checklist before you approve a warehouse item','How to compare shipping quotes for a China shopping haul'],
'article_descriptions':['A repeatable way to compare listings, variants and source links.','What the standard photo angles can reveal and what they cannot.','Separate item costs, parcel weight, fees and delivery estimates.'],
'body':{
'guide':[
('Start with a product, not a promise','The directory groups a small selection of actual catalog listings by product type. Use the category controls to compare similar items, or search the destination catalog when you have a precise name. A directory entry is a starting point: it is not a guarantee that the seller still has your size or color.'),
('Keep the original listing in view','Each card links to its matching product page. Open that page and confirm the first image, model, selected variant and current price. If a marketplace or seller link is supplied there, compare it with the item you intend to buy. Do not substitute a similar product merely because its title contains the same words.'),
('Decide after the warehouse check','Product photos describe a listing, whereas warehouse QC photos document the item that arrived. Compare the material, shape, size label and visible defects. If important angles are missing, request a clearer photo through the service you used. Confirm the shipping quote separately; the item price alone does not include international delivery.')],
'qc':[
('Read the photos in a set','Look first for front, back, both sides, soles or bottoms where relevant, and a size or measurement view. Start with the overall shape and color. Then zoom into seams, printed details, hardware and the label. Compare only with the exact variant and seller listing you chose.'),
('Know what a photo cannot prove','Images can reveal obvious scuffs, mismatched colors or visible construction issues. They cannot establish durability, material composition or whether a seller’s marketing claim is true. Lighting and camera angle can also change the appearance of color and proportions.'),
('Record the decision','Save the listing, selected variant and QC image set together. If there is a visible concern, point to the specific angle and ask for an additional photo or the applicable return procedure before approving shipment. Once a parcel is sent internationally, resolution may be more difficult.')],
'shipping':[
('Calculate the complete basket','Add the current item prices, domestic delivery if charged, service or payment fees, international shipping and possible taxes. A low product price can be outweighed by heavy or bulky packaging. Do not present an estimated rate as a guaranteed final charge.'),
('Compare the billed weight','Carriers may charge by actual weight or by dimensional weight. Ask which basis a shipping line uses and whether repacking changes the parcel dimensions. Check eligible destinations, restricted items, tracking, compensation and any stated delivery range.'),
('Consolidate with care','Combining orders may reduce the number of parcels, but it can increase parcel size and change available shipping lines. Wait for all items to arrive and finish QC first. Recheck the final quote after packaging; consider customs duties and local rules for your destination.')],
'faq':[
('Prices and availability','Prices shown here are a dated USD snapshot from the linked catalog. Product pages may change; the destination listing is authoritative at checkout.'),
('Images and QC','Card images are listing images from the destination catalog. They are not warehouse QC photos. Inspect actual warehouse images before approving shipment.'),
('Search and links','The search box opens the destination catalog’s live results. Product cards and category shortcuts link to their matching destination pages.'),
('Independence','This directory is independent and is not operated by Hipobuy. Payments, order changes, returns and customer support belong to the service used for the transaction.')]
},
'articles_body':[
 [('Keep the source attached','A useful spreadsheet should make the original listing easy to find. Start with a category, open an item, and keep its product URL together with the exact selected size, color and version. Titles alone are often reused across sellers.'),('Compare the right fields','Check the displayed image, current price, variant options and seller details on the destination page. A snapshot price is useful for discovery, but the live listing determines what is available today.'),('Treat QC as a separate stage','A listing photograph is not the item that arrives at a warehouse. Review the actual QC images after purchase and raise any visible concern before approving international shipment.')],
 [('Start with the whole item','Check front, back and side views before zooming into details. Shape and proportions are easier to judge when you first see the complete product.'),('Look for measurable differences','Compare labels, seams, hardware, printed details and measurements with the selected variant. Note the exact photo angle when requesting a clarification.'),('Keep the limits clear','Photos can show visible faults, but they do not verify long-term quality or every marketing claim. If the photo set is incomplete, ask the seller or agent for another view before approving.')],
 [('Make a full-cost comparison','Write down item price, domestic delivery, service fees, international delivery and possible taxes. Compare totals for the same parcel, not just the headline shipping rate.'),('Check weight rules','The charged weight may be the physical weight or a larger dimensional weight. Packaging and consolidation can alter the quote.'),('Confirm before dispatch','Check restricted-item rules, tracking, compensation, destination customs and the final packed dimensions. Delivery windows and rates can change.')]
]
},
'de':{
'nav':['Start','Tabelle','Funde','Anleitung','QC','Versand','Hinweise','Artikel'],'brand':'HIPOBUYY / SHEET','eyebrow':'Unabhängige Produktsuche','hero':'Hipobuy Spreadsheet: Produkte leichter prüfen.','sub':'Durchsuche echte Produkte, vergleiche Kategorien und öffne den genauen Eintrag. Bilder und USD-Preise stammen aus dem verlinkten Katalog; prüfe die Zielseite vor dem Kauf.','search':'Produkte im Katalog suchen','searchbutton':'Suchen','aside_title':'Eine Tabelle zum wirklichen Stöbern','aside':'Filtere echte Einträge oder nutze die Tabellenansicht. Jedes Produkt öffnet seinen passenden Eintrag; Kategorien führen zur entsprechenden Katalogrubrik.','tablelink':'Tabelle öffnen','products':'Produkte entdecken','products_sub':'Ein kleiner geprüfter Schnappschuss aktueller Einträge mit erstem Katalogbild und USD-Preis.','viewall':'Alle Produkte','categories':'Nach Kategorie stöbern','categories_sub':'Öffne die entsprechende Rubrik im Zielkatalog.','how':'Einkaufen mit Überblick','how_sub':'Grenze die Auswahl ein und prüfe Eintrag und tatsächlichen Artikel vor der Freigabe.','steps':['Nach Kategorie stöbern oder ein Modell suchen.','Bild, Preis, Variante und Quelllink vergleichen.','Lagerfotos und Versandangebot vor dem Versand prüfen.'],'reading':'Praktische Ratgeber','reading_sub':'Unabhängige Hinweise für wichtige Entscheidungen.','read':'Artikel lesen','snapshot':'Stand: 23. September 2026. Preise und Verfügbarkeit können sich ändern. Bilder und Preise entsprechen dem verlinkten Katalog zum Erfassungszeitpunkt. Physische Artikel und Lagerfotos wurden nicht unabhängig geprüft.','independent':'Unabhängiges Verzeichnis, kein offizieller Hipobuy-Dienst. Produktlinks und Suche führen zum verlinkten Katalog. Kauf und Support erfolgen dort.','open':'Eintrag öffnen','all':'Alle','item':'Produkt','category':'Kategorie','price':'Preis in USD','link':'Eintrag','page_titles':['Produkte schneller finden','Die Hipobuy Tabelle','Produktfunde','So nutzt du das Verzeichnis','QC-Fotos richtig prüfen','Versand: Gesamtkosten vergleichen','Wichtige Kaufhinweise','Artikel und Ratgeber'],'page_subs':['','','Suche oder filtere die aktuelle Produktauswahl. Öffne den genauen Eintrag für aktuelle Angaben.','Vom Produktfund zur überlegten Kaufentscheidung.','Eine praktische Sichtprüfung nach Ankunft im Lager.','Schätze die gesamten Paketkosten vor der Wahl des Versandwegs.','Was vor der Zahlung geprüft werden sollte.','Artikel zu Produktsuche, QC und Versand.'],
'article_titles':['Hipobuy Spreadsheet nutzen und den Originaleintrag behalten','QC-Fotos vor der Freigabe eines Lagerartikels prüfen','Versandangebote für ein China-Einkaufspaket vergleichen'],'article_descriptions':['Einträge, Varianten und Quelllinks systematisch vergleichen.','Was Bilder zeigen können und was nicht.','Warenpreis, Paketgewicht, Gebühren und Laufzeit getrennt prüfen.'],
'body':{'guide':[('Mit dem Produkt beginnen','Das Verzeichnis sortiert echte Katalogeinträge nach Produkttyp. Vergleiche ähnliche Artikel über die Kategorien oder suche im Zielkatalog nach einem genauen Namen. Ein Eintrag garantiert nicht, dass Größe oder Farbe noch verfügbar sind.'),('Den Originaleintrag prüfen','Jede Karte führt zur passenden Produktseite. Prüfe dort erstes Bild, Modell, Variante und aktuellen Preis. Vergleiche einen angegebenen Verkäuferlink mit deinem gewünschten Artikel. Ähnliche Titel können unterschiedliche Produkte bezeichnen.'),('Nach der Lagerprüfung entscheiden','Katalogbilder beschreiben das Angebot; QC-Fotos zeigen den eingetroffenen Artikel. Vergleiche Material, Form, Größenetikett und sichtbare Mängel. Fordere fehlende Ansichten beim verwendeten Dienst an und prüfe Versandkosten gesondert.')],
'qc':[('Bilder als Serie lesen','Prüfe Vorder- und Rückseite, beide Seiten, gegebenenfalls Sohlen sowie Größen- oder Maßangaben. Beginne bei Form und Farbe und betrachte dann Nähte, Drucke, Beschläge und Etiketten. Vergleiche mit der exakt gewählten Variante.'),('Grenzen von Fotos kennen','Bilder können Kratzer, Farbunterschiede und sichtbare Verarbeitungsfehler zeigen. Haltbarkeit, Materialzusammensetzung oder Werbeversprechen beweisen sie nicht. Licht und Perspektive beeinflussen die Wirkung.'),('Entscheidung festhalten','Speichere Eintrag, Variante und QC-Bilder zusammen. Benenne bei Problemen die konkrete Ansicht und frage vor der Versandfreigabe nach einem weiteren Foto oder der geltenden Rückgabeoption.')],
'shipping':[('Gesamtkosten berechnen','Addiere Warenpreise, möglichen Inlandsversand, Service- und Zahlungsgebühren, internationalen Versand und mögliche Steuern. Günstige Artikel können durch schwere Verpackung teuer werden. Eine Schätzung ist keine verbindliche Endsumme.'),('Abrechnungsgewicht vergleichen','Versanddienste rechnen nach tatsächlichem oder Volumengewicht ab. Prüfe die Berechnung, Paketmaße, mögliche Beschränkungen, Sendungsverfolgung und angegebene Laufzeit.'),('Sorgfältig zusammenfassen','Gemeinsamer Versand kann die Zahl der Pakete senken, aber Größe und Versandoptionen verändern. Warte auf alle Artikel und den QC-Check. Prüfe Angebot, Zoll und lokale Regeln nach dem Verpacken erneut.')],
'faq':[('Preis und Verfügbarkeit','Die USD-Preise sind eine datierte Momentaufnahme des verlinkten Katalogs. Maßgeblich ist der aktuelle Produkteintrag beim Kauf.'),('Bilder und QC','Karten zeigen Katalogbilder, keine Lagerfotos. Prüfe die tatsächlichen QC-Fotos vor dem Versand.'),('Suche und Links','Die Suche öffnet aktuelle Ergebnisse im Zielkatalog. Karten und Kategorien führen zu den passenden Seiten.'),('Unabhängigkeit','Dieses Verzeichnis wird nicht von Hipobuy betrieben. Zahlungen, Änderungen, Retouren und Support gehören zum verwendeten Dienst.')]},
'articles_body':[[('Quelllink behalten','Eine gute Tabelle führt zum ursprünglichen Eintrag. Speichere Produkt-URL sowie genaue Größe, Farbe und Version. Ähnliche Namen können von verschiedenen Verkäufern stammen.'),('Richtige Daten vergleichen','Prüfe Bild, aktuellen Preis, Varianten und Verkäuferangaben auf der Zielseite. Ein Snapshot hilft beim Finden; für den Kauf gilt der Live-Eintrag.'),('QC getrennt betrachten','Das Katalogfoto ist nicht der eingetroffene Artikel. Prüfe Lagerbilder und melde sichtbare Probleme vor dem internationalen Versand.')],[('Gesamten Artikel ansehen','Prüfe Vorderseite, Rückseite und Seiten vor den Details. Die Gesamtform lässt sich so besser beurteilen.'),('Konkrete Unterschiede suchen','Vergleiche Etiketten, Nähte, Beschläge, Drucke und Maße mit der gewählten Variante. Nenne die genaue Ansicht, wenn du nachfragst.'),('Grenzen beachten','Fotos zeigen sichtbare Fehler, aber keine Haltbarkeit und nicht jede Produkteigenschaft. Fordere fehlende Ansichten vor der Freigabe an.')],[('Volle Kosten vergleichen','Notiere Warenpreis, Inlandstransport, Servicegebühren, internationalen Versand und mögliche Steuern. Vergleiche die Gesamtsumme für dasselbe Paket.'),('Gewichtsregeln prüfen','Berechnet werden kann tatsächliches oder höheres Volumengewicht. Verpackung und Zusammenfassung ändern das Angebot.'),('Vor Versand bestätigen','Prüfe Beschränkungen, Tracking, Entschädigung, Zoll und endgültige Paketmaße. Preise und Laufzeiten können sich ändern.')]]
},
'es':{
'nav':['Inicio','Hoja','Hallazgos','Guía','QC','Envío','Notas','Artículos'],'brand':'HIPOBUYY / SHEET','eyebrow':'Directorio independiente','hero':'Encuentra productos de Hipobuy y compáralos mejor.','sub':'Explora productos reales, compara categorías y abre el anuncio exacto. Las imágenes y los precios en USD proceden del catálogo enlazado; comprueba el destino antes de comprar.','search':'Buscar productos en el catálogo','searchbutton':'Buscar','aside_title':'Una hoja que sí puedes explorar','aside':'Filtra anuncios reales o usa la vista de tabla. Cada producto abre su ficha correcta; las categorías llevan a la sección correspondiente.','tablelink':'Abrir hoja','products':'Descubrir productos','products_sub':'Una selección comprobada de anuncios actuales, con su primera imagen y precio en USD.','viewall':'Ver todos','categories':'Explorar categorías','categories_sub':'Abre la categoría correspondiente del catálogo de destino.','how':'Compra con más claridad','how_sub':'Reduce las opciones y comprueba el anuncio y el artículo recibido antes de aprobar el pedido.','steps':['Explora categorías o busca un modelo.','Compara imagen, precio, variante y enlace de origen.','Revisa las fotos QC y el presupuesto de envío antes de despachar.'],'reading':'Lecturas útiles','reading_sub':'Guías independientes para decisiones importantes.','read':'Leer guía','snapshot':'Selección revisada el 23 de septiembre de 2026. Precios y existencias pueden variar. Las imágenes y precios reflejan el catálogo enlazado en esa fecha; no se han verificado físicamente los artículos ni sus fotos de almacén.','independent':'Directorio independiente; no es el servicio oficial de Hipobuy. Los enlaces y búsquedas llevan al catálogo indicado. Compras y asistencia se gestionan allí.','open':'Abrir ficha','all':'Todos','item':'Producto','category':'Categoría','price':'Precio USD','link':'Ficha','page_titles':['Encuentra productos más rápido','Hoja de Hipobuy','Productos encontrados','Cómo usar el directorio','Cómo revisar fotos QC','Envío: calcula el coste total','Notas antes de comprar','Artículos y guías'],'page_subs':['','','Busca o filtra esta selección. Abre la ficha exacta para consultar los datos actuales.','Del hallazgo a una compra informada.','Revisión visual cuando el artículo llega al almacén.','Calcula el coste completo antes de escoger transporte.','Datos que conviene comprobar antes de pagar.','Guías sobre productos, QC y transporte.'],
'article_titles':['Usar una hoja de Hipobuy sin perder el anuncio original','Lista de revisión de fotos QC antes de aprobar un artículo','Cómo comparar presupuestos de envío de un pedido en China'],'article_descriptions':['Compara anuncios, variantes y enlaces de origen.','Qué revelan las imágenes y cuáles son sus límites.','Separa precio, peso, comisiones y plazo de entrega.'],
'body':{'guide':[('Empieza por el producto','El directorio agrupa anuncios reales por tipo de producto. Usa las categorías para comparar opciones o busca un nombre exacto en el catálogo de destino. Una entrada no garantiza que la talla o el color sigan disponibles.'),('Conserva el anuncio original','Cada tarjeta lleva a su ficha correspondiente. Comprueba allí la primera imagen, el modelo, la variante y el precio actual. Si aparece un enlace al vendedor, compáralo con el artículo deseado. Un título parecido no asegura que sea el mismo producto.'),('Decide tras el control de almacén','Las imágenes del anuncio describen la oferta; las fotos QC muestran el artículo recibido. Compara material, forma, etiqueta de talla y defectos visibles. Pide otra foto si faltan ángulos y consulta el envío por separado.')],
'qc':[('Lee las fotos como conjunto','Busca vistas frontal, trasera y laterales, suela o base cuando proceda y una referencia de talla o medidas. Empieza por forma y color, después amplía costuras, estampados, herrajes y etiqueta. Compara la variante exacta.'),('Conoce sus límites','Las fotos pueden mostrar roces, diferencias de color o defectos visibles. No demuestran durabilidad, composición ni todas las promesas del vendedor. La iluminación cambia la apariencia.'),('Deja constancia','Guarda anuncio, variante y fotos QC juntos. Si detectas un problema, señala la vista concreta y solicita otra foto o consulta la devolución antes de aprobar el envío.')],
'shipping':[('Suma el pedido completo','Añade artículos, transporte local si procede, comisiones de servicio o pago, envío internacional y posibles impuestos. Un artículo barato puede resultar caro si ocupa mucho volumen. Una estimación no es una tarifa final garantizada.'),('Compara el peso facturable','El transportista puede cobrar por peso real o volumétrico. Consulta el cálculo, dimensiones, restricciones, seguimiento, cobertura y plazo estimado.'),('Agrupa con cuidado','Unir pedidos reduce paquetes, pero puede aumentar volumen y cambiar las opciones de envío. Espera a que lleguen todos y revisa QC. Confirma el precio final tras el embalaje y las normas de aduanas locales.')],
'faq':[('Precio y disponibilidad','Los precios en USD son una captura fechada del catálogo. La ficha actual del destino es la referencia al comprar.'),('Imágenes y QC','Las tarjetas muestran imágenes del anuncio, no fotos del almacén. Examina las fotos QC reales antes del envío.'),('Búsqueda y enlaces','La búsqueda abre resultados actuales en el catálogo. Las tarjetas y categorías llevan a las páginas correspondientes.'),('Independencia','Hipobuy no opera este directorio. Pago, cambios, devoluciones y ayuda dependen del servicio utilizado.')]},
'articles_body':[[('Guarda el origen','Una hoja útil permite encontrar el anuncio inicial. Conserva la URL con la talla, el color y la versión exactos; distintos vendedores pueden usar títulos similares.'),('Compara datos correctos','Comprueba imagen, precio actual, variantes y vendedor en la página de destino. Una captura ayuda a descubrir; la ficha activa determina la disponibilidad.'),('Separa QC del anuncio','La imagen comercial no es el artículo recibido. Revisa las fotos del almacén y plantea problemas antes del envío internacional.')],[('Mira el artículo entero','Revisa frente, espalda y laterales antes de ampliar detalles. Así es más fácil valorar la forma general.'),('Busca diferencias concretas','Compara etiquetas, costuras, herrajes, estampados y medidas con tu variante. Indica la foto exacta al pedir aclaraciones.'),('Respeta los límites','Las fotos revelan defectos visibles, pero no la durabilidad ni cada afirmación comercial. Solicita ángulos faltantes antes de aprobar.')],[('Compara el coste total','Anota producto, entrega local, comisiones, transporte internacional e impuestos posibles. Compara sumas para el mismo paquete.'),('Revisa el peso','Puede cobrarse el peso físico o uno volumétrico mayor. Embalaje y consolidación alteran la tarifa.'),('Confirma antes de enviar','Comprueba restricciones, seguimiento, indemnización, aduanas y tamaño final. Precio y plazos pueden cambiar.')]]
},
'fr':{
'nav':['Accueil','Tableau','Trouvailles','Guide','QC','Livraison','Repères','Articles'],'brand':'HIPOBUYY / SHEET','eyebrow':'Répertoire indépendant','hero':'Des trouvailles Hipobuy plus faciles à vérifier.','sub':'Parcourez des produits réels, comparez les catégories et ouvrez la fiche exacte. Images et prix en USD proviennent du catalogue lié ; vérifiez la destination avant achat.','search':'Rechercher dans le catalogue','searchbutton':'Chercher','aside_title':'Un tableau facile à parcourir','aside':'Filtrez de vraies fiches ou utilisez la vue tableau. Chaque produit ouvre sa fiche correspondante ; les catégories mènent aux rubriques du catalogue.','tablelink':'Ouvrir le tableau','products':'Découvrir les produits','products_sub':'Un échantillon vérifié de fiches actuelles avec première image et prix en USD.','viewall':'Voir tout','categories':'Explorer les catégories','categories_sub':'Ouvrez la rubrique correspondante dans le catalogue de destination.','how':'Acheter avec méthode','how_sub':'Réduisez votre sélection puis vérifiez la fiche et l’article reçu avant de valider.','steps':['Parcourez les catégories ou cherchez un modèle.','Comparez image, prix, variante et lien source.','Examinez les photos QC et le devis de livraison avant expédition.'],'reading':'Guides pratiques','reading_sub':'Des conseils indépendants pour vos décisions.','read':'Lire le guide','snapshot':'Échantillon vérifié le 23 septembre 2026. Prix et stocks peuvent changer. Images et prix reflètent le catalogue lié à cette date ; les articles physiques et photos en entrepôt ne sont pas vérifiés indépendamment.','independent':'Répertoire indépendant, non officiel. Liens et recherches mènent au catalogue lié. Achats et assistance s’effectuent auprès du service utilisé.','open':'Ouvrir la fiche','all':'Tous','item':'Produit','category':'Catégorie','price':'Prix USD','link':'Fiche','page_titles':['Trouver plus vite','Le tableau Hipobuy','Trouvailles','Utiliser le répertoire','Examiner les photos QC','Livraison : calculer le coût total','Repères avant achat','Articles et guides'],'page_subs':['','','Cherchez ou filtrez cet échantillon. Ouvrez la fiche précise pour les informations actuelles.','Du choix du produit à une décision éclairée.','Contrôle visuel après l’arrivée en entrepôt.','Évaluez le prix complet avant de choisir un transporteur.','Ce qu’il faut vérifier avant de payer.','Guides sur les produits, le QC et la livraison.'],
'article_titles':['Utiliser un tableau Hipobuy sans perdre la fiche d’origine','Liste de contrôle QC avant de valider un article en entrepôt','Comparer les devis de livraison pour une commande en Chine'],'article_descriptions':['Comparer fiches, variantes et liens sources.','Ce que montrent les photos, et leurs limites.','Distinguer prix, poids, frais et délais.'],
'body':{'guide':[('Partir du produit','Le répertoire classe de véritables fiches par type de produit. Comparez des articles similaires ou cherchez un nom précis dans le catalogue de destination. Une fiche ne garantit pas que la taille ou la couleur soit encore disponible.'),('Garder la fiche d’origine','Chaque carte ouvre la fiche correspondante. Vérifiez sa première image, son modèle, sa variante et son prix actuel. Si un lien vendeur est indiqué, assurez-vous qu’il correspond au produit voulu. Un titre proche ne suffit pas.'),('Décider après le contrôle en entrepôt','Les images commerciales décrivent une offre ; les photos QC montrent l’article reçu. Comparez matière, forme, taille et défauts visibles. Demandez une vue supplémentaire si nécessaire et vérifiez séparément les frais de livraison.')],
'qc':[('Examiner toute la série','Cherchez les vues avant, arrière et latérales, la semelle ou le dessous selon le produit, ainsi qu’une taille ou une mesure. Évaluez d’abord forme et couleur, puis coutures, impressions, pièces métalliques et étiquettes.'),('Comprendre les limites','Les images montrent parfois rayures, couleurs différentes ou défauts visibles. Elles ne prouvent ni la durée de vie, ni la composition, ni toutes les promesses commerciales. Lumière et angle modifient le rendu.'),('Conserver la décision','Gardez ensemble fiche, variante et photos QC. En cas de doute, indiquez la vue précise et demandez une autre photo ou les conditions de retour avant de valider l’expédition.')],
'shipping':[('Calculer tout le panier','Additionnez articles, livraison intérieure éventuelle, frais de service ou paiement, transport international et taxes possibles. Un produit peu cher peut coûter plus avec un emballage volumineux. Un devis reste une estimation.'),('Comparer le poids facturé','Le transporteur peut retenir le poids réel ou volumétrique. Vérifiez méthode de calcul, dimensions, restrictions, suivi, garantie et délai annoncé.'),('Regrouper prudemment','Regrouper réduit le nombre de colis, mais peut modifier volume et lignes disponibles. Attendez tous les articles et le contrôle QC. Confirmez le devis après emballage et les règles douanières locales.')],
'faq':[('Prix et disponibilité','Les prix USD sont une capture datée du catalogue lié. La fiche actuelle fait foi au moment de l’achat.'),('Images et QC','Les cartes montrent les images des annonces, pas des photos d’entrepôt. Vérifiez les vrais clichés QC avant expédition.'),('Recherche et liens','La recherche ouvre les résultats actuels du catalogue. Cartes et catégories mènent aux pages correspondantes.'),('Indépendance','Ce répertoire n’est pas géré par Hipobuy. Paiements, modifications, retours et assistance dépendent du service utilisé.')]},
'articles_body':[[('Garder la source','Un bon tableau mène à l’annonce d’origine. Conservez son URL avec taille, couleur et version exactes ; des vendeurs différents utilisent parfois le même titre.'),('Comparer les bonnes données','Vérifiez image, prix actuel, variantes et vendeur sur la destination. Une capture aide à découvrir ; la fiche en ligne détermine la disponibilité.'),('Distinguer le QC','La photo de l’annonce n’est pas l’article arrivé. Examinez les clichés de l’entrepôt avant l’expédition internationale.')],[('Voir le produit entier','Examinez avant, arrière et côtés avant les détails. La forme générale est alors plus facile à juger.'),('Chercher des écarts précis','Comparez étiquettes, coutures, impressions et mesures à la variante choisie. Indiquez l’angle précis pour demander des précisions.'),('Garder les limites en tête','Les photos montrent des défauts visibles, mais pas la durabilité ni chaque argument commercial. Demandez les vues manquantes.')],[('Comparer le coût complet','Notez produit, transport intérieur, frais de service, livraison internationale et taxes possibles. Comparez les totaux d’un même colis.'),('Vérifier le poids','La facturation peut utiliser le poids réel ou un poids volumétrique supérieur. Emballage et regroupement changent le devis.'),('Confirmer avant envoi','Vérifiez restrictions, suivi, indemnisation, douane et dimensions finales. Tarifs et délais évoluent.')]]
},
'it':{
'nav':['Home','Tabella','Prodotti','Guida','QC','Spedizione','Note','Articoli'],'brand':'HIPOBUYY / SHEET','eyebrow':'Catalogo indipendente','hero':'Trova e verifica i prodotti Hipobuy più facilmente.','sub':'Sfoglia prodotti reali, confronta categorie e apri la scheda esatta. Immagini e prezzi USD provengono dal catalogo collegato; verifica la destinazione prima di acquistare.','search':'Cerca prodotti nel catalogo','searchbutton':'Cerca','aside_title':'Una tabella davvero consultabile','aside':'Filtra le schede reali o usa la tabella. Ogni prodotto apre la scheda corrispondente e le categorie conducono alla sezione pertinente.','tablelink':'Apri la tabella','products':'Scopri i prodotti','products_sub':'Una piccola selezione verificata di schede attuali con prima immagine e prezzo USD.','viewall':'Tutti i prodotti','categories':'Esplora le categorie','categories_sub':'Apri la categoria corrispondente nel catalogo di destinazione.','how':'Acquista con più chiarezza','how_sub':'Restringi la scelta e controlla la scheda e l’articolo ricevuto prima di approvare.','steps':['Sfoglia le categorie o cerca un modello.','Confronta immagine, prezzo, variante e link originale.','Controlla foto QC e preventivo di spedizione prima di inviare.'],'reading':'Letture utili','reading_sub':'Guide indipendenti per decisioni importanti.','read':'Leggi la guida','snapshot':'Selezione verificata il 23 settembre 2026. Prezzi e disponibilità possono cambiare. Immagini e prezzi rispecchiano il catalogo collegato alla data indicata; articoli fisici e foto di magazzino non sono stati verificati indipendentemente.','independent':'Catalogo indipendente, non ufficiale. Link e ricerche portano al catalogo collegato. Acquisti e assistenza avvengono presso il servizio scelto.','open':'Apri scheda','all':'Tutti','item':'Prodotto','category':'Categoria','price':'Prezzo USD','link':'Scheda','page_titles':['Trova prodotti più in fretta','Tabella Hipobuy','Prodotti trovati','Come usare il catalogo','Come leggere le foto QC','Spedizione: calcola il costo totale','Note prima di acquistare','Articoli e guide'],'page_subs':['','','Cerca o filtra la selezione attuale. Apri la scheda esatta per dati aggiornati.','Dal prodotto alla scelta d’acquisto informata.','Controllo visivo dopo l’arrivo in magazzino.','Stima il costo completo prima di scegliere il trasporto.','Cosa verificare prima di pagare.','Guide su ricerca, QC e spedizione.'],
'article_titles':['Usare una tabella Hipobuy senza perdere la scheda originale','Controllare le foto QC prima di approvare un articolo','Confrontare i preventivi di spedizione di un ordine dalla Cina'],'article_descriptions':['Confronta schede, varianti e link originali.','Cosa rivelano le immagini e quali sono i limiti.','Separa prezzo, peso, commissioni e tempi.'],
'body':{'guide':[('Parti dal prodotto','Il catalogo raggruppa schede reali per tipo di articolo. Usa le categorie per confrontare prodotti simili o cerca un nome preciso nel catalogo di destinazione. Una scheda non garantisce che taglia o colore siano ancora disponibili.'),('Mantieni la scheda originale','Ogni card apre la pagina prodotto corrispondente. Controlla prima immagine, modello, variante e prezzo attuale. Se compare un link al venditore, verifica che sia il prodotto desiderato. Titoli simili possono riferirsi ad articoli diversi.'),('Decidi dopo il controllo in magazzino','Le immagini dell’annuncio descrivono l’offerta; le foto QC mostrano l’articolo arrivato. Confronta materiale, forma, etichetta e difetti visibili. Richiedi angoli mancanti e verifica la spedizione separatamente.')],
'qc':[('Guarda l’intera serie','Cerca fronte, retro, entrambi i lati, suola o fondo se pertinenti, e taglia o misure. Parti da forma e colore, poi ingrandisci cuciture, stampe, componenti ed etichette. Confronta la variante esatta.'),('Conosci i limiti','Le foto possono mostrare graffi, colori differenti o difetti visibili. Non provano durata, composizione o tutte le promesse del venditore. Luce e angolazione alterano l’aspetto.'),('Conserva la decisione','Salva insieme scheda, variante e foto QC. Se noti un problema, indica l’inquadratura e chiedi un’altra foto o le regole di reso prima di approvare la spedizione.')],
'shipping':[('Calcola tutto il carrello','Somma articoli, eventuale trasporto nazionale, commissioni di servizio o pagamento, spedizione internazionale e possibili imposte. Un articolo economico può costare molto con imballaggi ingombranti. Un preventivo non è un prezzo finale garantito.'),('Confronta il peso addebitato','Il vettore può usare peso effettivo o volumetrico. Verifica calcolo, dimensioni, restrizioni, tracciamento, copertura e tempi indicati.'),('Raggruppa con attenzione','Unire ordini riduce i pacchi ma può cambiare volume e linee disponibili. Aspetta tutti gli articoli e controlla QC. Ricontrolla costo finale, dogana e regole locali dopo l’imballaggio.')],
'faq':[('Prezzi e disponibilità','I prezzi USD sono una fotografia datata del catalogo. La scheda attuale di destinazione è il riferimento prima dell’acquisto.'),('Immagini e QC','Le card mostrano immagini degli annunci, non foto di magazzino. Controlla le foto QC reali prima di spedire.'),('Ricerca e link','La ricerca apre i risultati aggiornati del catalogo. Card e categorie portano alle pagine corrispondenti.'),('Indipendenza','Hipobuy non gestisce questo catalogo. Pagamenti, modifiche, resi e assistenza spettano al servizio scelto.')]},
'articles_body':[[('Conserva la fonte','Una buona tabella consente di trovare l’annuncio originale. Tieni URL, taglia, colore e versione esatti; venditori diversi possono usare nomi simili.'),('Confronta i dati giusti','Controlla immagine, prezzo attuale, varianti e venditore nella pagina finale. Una fotografia aiuta la ricerca; la scheda online determina la disponibilità.'),('QC è una fase diversa','La foto commerciale non mostra l’articolo ricevuto. Esamina le immagini del magazzino prima della spedizione internazionale.')],[('Guarda il prodotto intero','Controlla fronte, retro e lati prima dei dettagli. È più semplice valutare forma e proporzioni.'),('Cerca differenze precise','Confronta etichette, cuciture, componenti, stampe e misure con la variante selezionata. Indica la foto precisa quando chiedi chiarimenti.'),('Ricorda i limiti','Le immagini mostrano difetti visibili, non la durata o ogni promessa commerciale. Richiedi inquadrature mancanti prima di approvare.')],[('Confronta il totale','Annota prodotto, trasporto nazionale, commissioni, spedizione internazionale e possibili imposte. Confronta totali per lo stesso pacco.'),('Verifica il peso','Può essere addebitato il peso fisico o un peso volumetrico maggiore. Imballaggio e consolidamento cambiano la cifra.'),('Conferma prima di spedire','Verifica restrizioni, tracking, risarcimento, dogana e dimensioni finali. Prezzi e tempi possono variare.')]]
}
}

CAT_NAMES={'en':['Shoes','Hoodies & sweaters','T-shirts','Jackets','Pants & shorts','Accessories','Jerseys'],'de':['Schuhe','Hoodies & Pullover','T-Shirts','Jacken','Hosen & Shorts','Accessoires','Trikots'],'es':['Zapatillas','Sudaderas','Camisetas','Chaquetas','Pantalones','Accesorios','Camisetas deportivas'],'fr':['Chaussures','Sweats','T-shirts','Vestes','Pantalons','Accessoires','Maillots'],'it':['Scarpe','Felpe','T-shirt','Giacche','Pantaloni','Accessori','Maglie sportive']}
FACTS={
'en':{
'guide':[('From listing to agent order','The official Hipobuy home page describes a shopping-agent service: enter a product link, place an order, wait for the seller to ship to its Chinese warehouse, review the inspection result and then select items for international delivery. This independent directory helps with the first step. Open each card’s exact destination listing and confirm the current variant and price before ordering.'),('Order states and storage','Hipobuy’s Order Status Display distinguishes “Arrived,” which awaits inspection, from “Stored.” It states that stored orders have 90 days of free storage. Keep the seller URL, selected size or colour and order number together. A long storage period does not extend the separate return window.'),('The actual cost','Hipobuy’s Service & Fees page says its shopping-agent service is free. It separates the product price and seller-to-warehouse shipping from international delivery and customs-related charges; optional services may add costs. Check the live parcel quote instead of treating a product-card price as a delivered total.'),('Source and limits','Checked against Hipobuy’s official home page, Service & Fees, Order Status Display and Returns and Refunds notices on 23 September 2026. Platform terms and live listings can change. This independent site does not process Hipobuy orders.')],
'qc':[('Listing image versus QC evidence','The first image on a product card comes from the linked listing. It is not a photograph of your specific warehouse item. Hipobuy says it inspects goods after they reach its warehouse and provides results. Compare the received item with the exact ordered variant.'),('A useful visual check','Review overall shape, front and back, both sides, visible labels, seams and measurements when available. Request a clear view of a specific area if a key detail is missing. Photographs can show visible differences but cannot prove material composition or long-term durability.'),('Act within the return window','Hipobuy’s Returns and Refunds notice says eligible products may be requested for return within five days after the order becomes warehoused, interpreted there as 120 hours. Seller participation and item condition affect eligibility; customer-initiated returns may involve delivery charges and a RMB 5 service fee. Check the current order and policy before acting.'),('Source and limits','Checked against Hipobuy’s official home page and Returns and Refunds notice on 23 September 2026. The 90-day free-storage statement in Order Status Display is separate from return eligibility.')],
'shipping':[('Build the full-cost picture','Hipobuy’s Service & Fees notice describes free shopping-agent service. Item cost includes seller price and domestic shipping to the warehouse; international shipping and customs-related costs are separate. Optional services or a return request can have additional terms. Do not promise one flat delivered price.'),('Estimate with relevant inputs','Hipobuy’s Shipping Estimate page asks for destination and weight in grams, and offers product type and parcel dimensions. Compare routes using the same inputs. Packing can change actual or dimensional weight, so an estimate is not the final charge.'),('Check the packed quote','The official Order Status Display says a parcel waiting for packing is being weighed and prepared. “Waiting for Confirmation” can mean actual weight exceeded the estimate and extra shipping is due. Review the final packed weight, route and amount before approval.'),('Customs and protection','Hipobuy’s parcel agreement says goods are declared at actual value and rates may change. Its customs and insurance notices describe destination risks, conditions and exclusions. Follow the destination’s rules and verify the current route terms rather than assuming tax-free delivery or blanket compensation.')],
'faq':[('Product information','The product cards are a dated catalog snapshot in USD. The destination’s current listing controls price, availability, variants and the purchase decision. Card images are listing images, not warehouse QC images.'),('Warehouse milestones','Hipobuy’s official order-status page describes arrival, inspection and storage, and states 90 days of free storage for stored items. Its separate returns page sets a shorter five-day request window for eligible items after warehousing.'),('Costs and delivery','The official Service & Fees page describes free shopping-agent service but separates item, domestic delivery, international shipping and customs-related costs. Use its current estimate and confirm the packed parcel quote.'),('Scope','This directory is independent of Hipobuy. It does not sell goods or handle payments and it cannot determine an individual return or insurance claim. The statements above were checked against official pages on 23 September 2026.')]
},
'de':{
'guide':[('Vom Eintrag zur Bestellung','Die offizielle Hipobuy-Startseite beschreibt den Ablauf: Produktlink eingeben, Bestellung aufgeben, Versand des Verkäufers an das chinesische Lager abwarten, Prüfergebnis ansehen und Artikel für den internationalen Versand auswählen. Dieses unabhängige Verzeichnis hilft beim Finden; prüfe Variante und Preis auf der genauen Zielseite.'),('Status und Lagerung','Die offizielle Statusübersicht unterscheidet „Arrived“ (wartet auf Prüfung) und „Stored“. Für gelagerte Bestellungen nennt sie 90 Tage kostenlose Lagerung. Bewahre Verkäuferlink, gewählte Größe oder Farbe und Bestellnummer zusammen auf. Lagerzeit und Rückgabefrist sind unterschiedlich.'),('Tatsächliche Kosten','Laut offizieller Gebührenübersicht ist der Einkaufsagentenservice kostenlos. Warenpreis und Inlandstransport zum Lager stehen getrennt von internationalem Versand und zollbezogenen Kosten; optionale Leistungen können zusätzlich kosten. Der Kartenpreis ist kein Endpreis.'),('Quelle und Grenzen','Geprüft anhand offizieller Hipobuy-Seiten zu Start, Gebühren, Bestellstatus und Rückgabe am 23. September 2026. Bedingungen und Einträge können sich ändern; diese unabhängige Seite bearbeitet keine Bestellungen.')],
'qc':[('Anzeigenbild und QC unterscheiden','Das erste Kartenbild stammt aus der verlinkten Anzeige, nicht von deinem konkreten Lagerartikel. Hipobuy erklärt, eingetroffene Waren zu prüfen und Ergebnisse bereitzustellen. Vergleiche den erhaltenen Artikel mit der exakt bestellten Variante.'),('Sichtprüfung','Prüfe Form, Vorder- und Rückseite, beide Seiten, Etiketten, Nähte und verfügbare Maße. Bitte bei fehlenden Ansichten gezielt um ein klares Foto. Bilder zeigen sichtbare Unterschiede, beweisen aber weder Materialzusammensetzung noch Haltbarkeit.'),('Rückgabefrist beachten','Laut offizieller Rückgabeinformation kann für geeignete Artikel innerhalb von fünf Tagen nach Einlagerung ein Antrag gestellt werden; dort werden 120 Stunden genannt. Angebot des Verkäufers und Artikelzustand sind entscheidend. Bei Rückgabe auf Kundenwunsch können Versandkosten und 5 RMB Servicegebühr anfallen.'),('Quelle und Grenzen','Offizielle Hipobuy-Start- und Rückgabeseiten, geprüft am 23. September 2026. Die 90 Tage kostenlose Lagerung aus der Statusübersicht verlängern nicht die Rückgabefrist.')],
'shipping':[('Gesamtkosten sehen','Laut offizieller Gebührenübersicht ist der Agentenservice kostenlos. Warenpreis plus Verkäufertransport zum Lager, internationaler Versand und zollbezogene Kosten sind getrennte Posten. Optionale Leistungen und Rückgaben können zusätzliche Bedingungen haben.'),('Mit passenden Daten schätzen','Der offizielle Versandkostenrechner fragt Ziel und Gewicht in Gramm ab; Produkttyp und Paketmaße können angegeben werden. Vergleiche Routen mit identischen Angaben. Verpackung kann tatsächliches oder Volumengewicht ändern; eine Schätzung ist keine Endrechnung.'),('Endgültiges Angebot prüfen','Die Statusseite sagt, dass Pakete vor dem Versand verpackt und gewogen werden. „Waiting for Confirmation“ kann eine Nachzahlung bedeuten, wenn das tatsächliche Gewicht die Schätzung übersteigt. Prüfe Gewicht, Route und Betrag nach dem Verpacken.'),('Zoll und Schutz','Laut Paketbedingungen wird der tatsächliche Warenwert angegeben; Tarife können sich ändern. Zoll- und Versicherungsseiten nennen Risiken und Ausschlüsse. Prüfe lokale Regeln und aktuelle Route, statt steuerfreien Versand oder pauschalen Schutz vorauszusetzen.')],
'faq':[('Produktdaten','Karten sind eine datierte Katalogaufnahme in USD. Aktueller Preis, Bestand und Varianten stehen auf der Zielseite. Kartenbilder sind Angebotsbilder, keine QC-Fotos des Lagers.'),('Lagerstatus','Die offizielle Statusseite nennt Ankunft, Prüfung und 90 Tage kostenlose Lagerung. Die separate Rückgabeseite beschreibt eine kürzere Fünf-Tage-Frist für geeignete Artikel nach Einlagerung.'),('Kosten','Die Gebührenübersicht beschreibt einen kostenlosen Agentenservice, trennt aber Warenpreis, Inlands- und internationalen Transport sowie zollbezogene Kosten. Prüfe die aktuelle Schätzung und das fertig gepackte Paket.'),('Einordnung','Dieses Verzeichnis ist unabhängig. Es verkauft nichts, nimmt keine Zahlung entgegen und entscheidet keine individuellen Retouren oder Versicherungsfälle. Offizielle Quellen wurden am 23. September 2026 geprüft.')]
},
'es':{
'guide':[('Del anuncio al pedido','La web oficial de Hipobuy explica el proceso: introducir el enlace, realizar el pedido, esperar el envío del vendedor a su almacén en China, revisar la inspección y seleccionar productos para el envío internacional. Este directorio independiente ayuda a encontrar el producto; confirma variante y precio en la ficha exacta.'),('Estados y almacenaje','La guía oficial distingue «Arrived», pendiente de inspección, de «Stored». Indica 90 días de almacenaje gratuito para los artículos guardados. Conserva el enlace del vendedor, la talla o el color elegidos y el número de pedido. Ese plazo no amplía el de devolución.'),('Coste real','La página oficial de tarifas indica que el servicio de agente de compras es gratuito. Separa precio y transporte nacional al almacén del envío internacional y los costes aduaneros; servicios opcionales pueden añadir importes. El precio de la tarjeta no es el total entregado.'),('Fuentes y límites','Comprobado con la portada y los avisos oficiales de tarifas, estados y devoluciones de Hipobuy el 23 de septiembre de 2026. Las condiciones y fichas pueden cambiar; este directorio no gestiona pedidos.')],
'qc':[('Imagen comercial y QC','La primera imagen de la tarjeta procede del anuncio, no del artículo concreto recibido. Hipobuy afirma que inspecciona los productos en su almacén y facilita resultados. Compara el artículo con la variante exacta del pedido.'),('Revisión visual útil','Examina forma, frente, dorso, ambos lados, etiquetas, costuras y medidas disponibles. Pide una foto clara de la zona que falta. Las imágenes muestran diferencias visibles, pero no prueban composición o duración.'),('Plazo de devolución','El aviso oficial indica que puede solicitarse la devolución de artículos elegibles durante cinco días tras el ingreso en almacén; menciona 120 horas. La participación del vendedor y el estado del producto importan. Una devolución por decisión del comprador puede implicar transporte y 5 RMB de servicio.'),('Fuentes y límites','Portada y aviso oficial de devoluciones revisados el 23 de septiembre de 2026. Los 90 días de almacenaje gratuito de la guía de estados no amplían el plazo de devolución.')],
'shipping':[('Calcula el coste completo','El aviso oficial dice que el servicio de agente es gratuito. Precio del producto y transporte del vendedor al almacén, envío internacional y costes aduaneros son conceptos distintos. Servicios opcionales y devoluciones tienen condiciones adicionales.'),('Estima con datos comparables','El estimador oficial pide destino y peso en gramos y permite indicar tipo de producto y dimensiones. Compara rutas con las mismas entradas. El embalaje cambia el peso físico o volumétrico: el presupuesto no es una factura final.'),('Revisa el precio embalado','La guía de estados indica que el paquete se embala y pesa antes de salir. «Waiting for Confirmation» puede exigir un pago adicional si el peso real supera la estimación. Confirma peso, ruta e importe final.'),('Aduanas y protección','El acuerdo oficial indica que se declara el valor real y que las tarifas pueden variar. Sus avisos de aduanas y seguro describen riesgos y exclusiones. Comprueba normas locales y cobertura de la ruta, sin prometer ausencia de impuestos.')],
'faq':[('Productos','Las tarjetas son una captura fechada de un catálogo en USD. La ficha actual determina precio, disponibilidad y variantes. Las fotos de las tarjetas son anuncios, no imágenes QC de almacén.'),('Almacén','La guía oficial distingue llegada, inspección y 90 días de almacenaje gratuito. Su política de devoluciones establece un plazo más corto de cinco días para productos elegibles tras la entrada en almacén.'),('Costes','La página oficial describe agente gratuito, pero separa producto, transporte local, envío internacional y costes aduaneros. Consulta la estimación actual y el presupuesto del paquete embalado.'),('Alcance','Este directorio es independiente. No vende, cobra ni decide devoluciones o indemnizaciones individuales. Hechos comprobados con fuentes oficiales el 23 de septiembre de 2026.')]
},
'fr':{
'guide':[('De la fiche à la commande','Le site officiel de Hipobuy décrit le parcours : saisir le lien produit, commander, attendre l’envoi du vendeur vers son entrepôt chinois, consulter le contrôle puis sélectionner les articles à expédier. Ce répertoire indépendant aide à trouver le produit ; vérifiez variante et prix sur la fiche exacte.'),('Statuts et stockage','Le guide officiel distingue « Arrived », en attente de contrôle, et « Stored ». Il indique 90 jours de stockage gratuit pour les articles entreposés. Conservez lien vendeur, taille ou couleur choisie et numéro de commande. La durée de stockage ne prolonge pas la période de retour.'),('Coût réel','La page officielle des frais présente le service d’agent d’achat comme gratuit. Elle sépare prix et transport intérieur vers l’entrepôt de la livraison internationale et des frais liés aux douanes ; des services facultatifs peuvent coûter plus. Le prix de la carte n’est pas un total livré.'),('Sources et limites','Vérifié sur l’accueil officiel et les pages frais, statuts et retours de Hipobuy le 23 septembre 2026. Conditions et fiches évoluent ; ce répertoire ne gère pas les commandes.')],
'qc':[('Image de fiche et photo QC','La première image de la carte vient de l’annonce, pas de votre article en entrepôt. Hipobuy indique contrôler les marchandises reçues et fournir les résultats. Comparez l’article à la variante précise commandée.'),('Contrôle visuel utile','Examinez forme, avant, arrière, côtés, étiquettes, coutures et mesures disponibles. Demandez un cliché net de la zone manquante. Les photos montrent des écarts visibles, sans prouver composition ou durabilité.'),('Fenêtre de retour','Selon l’avis officiel, un retour peut être demandé pour les articles éligibles durant cinq jours après stockage, soit 120 heures selon le texte. Participation du vendeur et état du produit comptent. Un retour demandé par le client peut entraîner des frais de transport et 5 RMB de service.'),('Sources et limites','Accueil et politique de retour officiels consultés le 23 septembre 2026. Les 90 jours de stockage gratuit indiqués dans les statuts ne prolongent pas les retours.')],
'shipping':[('Voir le coût complet','La page officielle indique un service d’agent gratuit. Prix du produit et transport du vendeur à l’entrepôt, livraison internationale et frais douaniers sont distincts. Services facultatifs et retours ont leurs propres conditions.'),('Estimer avec les mêmes données','L’estimateur officiel demande destination et poids en grammes, avec type de produit et dimensions possibles. Comparez les routes à données égales. L’emballage peut modifier le poids réel ou volumétrique : une estimation n’est pas le montant final.'),('Vérifier le colis emballé','La page des statuts indique qu’un colis est emballé et pesé. « Waiting for Confirmation » peut signaler un supplément si le poids réel dépasse l’estimation. Contrôlez poids, route et somme définitive.'),('Douanes et protection','L’accord officiel indique une déclaration à la valeur réelle et des tarifs variables. Les avis de douane et d’assurance exposent risques et exclusions. Vérifiez les règles du pays et la couverture sans supposer livraison sans taxe ou indemnisation automatique.')],
'faq':[('Produits','Les cartes sont une capture datée du catalogue en USD. La fiche en ligne détermine prix, disponibilité et variantes. Les images ne sont pas des photos QC d’entrepôt.'),('Entrepôt','Les statuts officiels décrivent arrivée, inspection et 90 jours de stockage gratuit. La politique de retour fixe séparément cinq jours pour les articles éligibles après mise en stock.'),('Frais','La page officielle annonce un service d’agent gratuit, tout en séparant produit, transport intérieur et international et coûts douaniers. Comparez devis actuel et montant après emballage.'),('Portée','Ce répertoire indépendant ne vend pas, n’encaisse pas et ne tranche pas les retours ou indemnisations. Sources officielles consultées le 23 septembre 2026.')]
},
'it':{
'guide':[('Dalla scheda all’ordine','La home ufficiale di Hipobuy descrive il percorso: inserire il link, ordinare, attendere la spedizione del venditore al magazzino cinese, esaminare il controllo e selezionare gli articoli da spedire. Questo catalogo indipendente aiuta nella ricerca; verifica variante e prezzo nella scheda esatta.'),('Stati e deposito','La guida ufficiale distingue «Arrived», in attesa di controllo, da «Stored». Per gli articoli depositati indica 90 giorni gratuiti. Conserva link del venditore, taglia o colore e numero ordine. Questo periodo non prolunga il termine di reso.'),('Costo effettivo','La pagina ufficiale delle tariffe definisce gratuito il servizio di agente d’acquisto. Separa prezzo e trasporto nazionale al magazzino da spedizione internazionale e spese doganali; servizi facoltativi possono costare in più. Il prezzo della card non è il totale consegnato.'),('Fonti e limiti','Controllato sulla home e sulle pagine ufficiali di tariffe, stati e resi di Hipobuy il 23 settembre 2026. Condizioni e annunci possono cambiare; questo sito non gestisce gli ordini.')],
'qc':[('Immagine dell’annuncio e QC','La prima immagine della card proviene dall’annuncio, non dal tuo articolo in magazzino. Hipobuy dichiara di ispezionare gli arrivi e fornire risultati. Confronta il pezzo ricevuto con la variante ordinata.'),('Controllo visivo','Esamina forma, fronte, retro, lati, etichette, cuciture e misure disponibili. Chiedi una foto nitida del dettaglio mancante. Le immagini mostrano differenze visibili, ma non provano composizione o durata.'),('Termine di reso','L’avviso ufficiale indica cinque giorni dopo il deposito, equivalenti a 120 ore, per chiedere il reso di prodotti idonei. Contano partecipazione del venditore e condizioni del bene. Il reso su richiesta del cliente può comportare trasporto e 5 RMB di servizio.'),('Fonti e limiti','Home e politica resi ufficiali controllate il 23 settembre 2026. I 90 giorni di deposito gratuito indicati nella guida agli stati non prolungano il termine di reso.')],
'shipping':[('Somma tutti i costi','L’avviso ufficiale dice che il servizio di agente è gratuito. Prezzo del bene e trasporto al magazzino, spedizione internazionale e spese doganali sono voci diverse. Servizi facoltativi e resi possono avere costi propri.'),('Stima con dati coerenti','Il calcolatore ufficiale chiede destinazione e peso in grammi; consente tipo di prodotto e dimensioni. Confronta le rotte con gli stessi dati. L’imballaggio modifica peso fisico o volumetrico; il preventivo non è il totale finale.'),('Verifica dopo l’imballaggio','La pagina degli stati dice che il pacco viene preparato e pesato. «Waiting for Confirmation» può richiedere una differenza se il peso reale supera la stima. Controlla peso, rotta e importo finale.'),('Dogana e protezione','L’accordo ufficiale prevede dichiarazione al valore reale e possibili variazioni tariffarie. Le pagine su dogana e assicurazione descrivono rischi ed esclusioni. Verifica le regole locali e la copertura senza promettere consegna esente da imposte.')],
'faq':[('Prodotti','Le card sono una fotografia datata del catalogo in USD. La scheda attuale determina prezzo, disponibilità e varianti. Le immagini delle card sono annunci, non foto QC del magazzino.'),('Magazzino','La guida ufficiale indica arrivo, controllo e 90 giorni di deposito gratuito. La politica resi ha un diverso periodo di cinque giorni per articoli idonei dopo il deposito.'),('Costi','L’avviso ufficiale descrive un agente gratuito, ma distingue bene, trasporto interno e internazionale e oneri doganali. Controlla stima attuale e preventivo del pacco preparato.'),('Ambito','Questo catalogo è indipendente. Non vende, riceve pagamenti o decide resi e risarcimenti individuali. Fonti ufficiali controllate il 23 settembre 2026.')]
}}
for locale in LANGS:
    T[locale]['body'].update(FACTS[locale])
FAQS={locale:json.loads((ROOT/'content'/'faq'/f'{locale}.json').read_text(encoding='utf-8')) for locale in LANGS}
ARTICLE_META=json.loads((ROOT/'content'/'article_meta.json').read_text(encoding='utf-8'))
for locale in LANGS:
    assert len(FAQS[locale])==20
    T[locale]['body']['faq']=FAQS[locale]
    T[locale]['article_titles'].extend(x['title'] for x in ARTICLE_META[locale])
    T[locale]['article_descriptions'].extend(x['description'] for x in ARTICLE_META[locale])
    assert len(T[locale]['article_titles'])==len(SLUGS)
LOCAL={'en':('PUBLIC REVIEW','Independent Hipobuy spreadsheet','Main navigation','Photo','GUIDE','No products in this category.','Independent discovery resource'),
       'de':('ÖFFENTLICHE VORSCHAU','Unabhängige Hipobuy Tabelle','Hauptnavigation','Foto','RATGEBER','Keine Produkte in dieser Kategorie.','Unabhängige Produktsuche'),
       'es':('VISTA PÚBLICA','Hoja independiente de Hipobuy','Navegación principal','Foto','GUÍA','No hay productos en esta categoría.','Directorio independiente'),
       'fr':('APERÇU PUBLIC','Tableau Hipobuy indépendant','Navigation principale','Photo','GUIDE','Aucun produit dans cette catégorie.','Répertoire indépendant'),
       'it':('ANTEPRIMA PUBBLICA','Tabella Hipobuy indipendente','Navigazione principale','Foto','GUIDA','Nessun prodotto in questa categoria.','Catalogo indipendente')}
def e(v):return html.escape(str(v),quote=True)
def href(lang,path=''):return f'/{lang}/'+(path.strip('/')+'/' if path else '')
def meta(lang,path,title,description):
    alts=''.join(f'<link rel="alternate" hreflang="{l}" href="{SITE}{href(l,path)}">' for l in LANGS)+f'<link rel="alternate" hreflang="x-default" href="{SITE}{href("en",path)}">'
    return f'<!doctype html><html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)} | Hipobuyy Sheet</title><meta name="description" content="{e(description)}"><link rel="canonical" href="{SITE}{href(lang,path)}">{alts}<link rel="stylesheet" href="/assets/site.css"><script defer src="/assets/site.js"></script></head>'
def shell(lang,path,title,description,body,home=False):
    t=T[lang];nav=''.join(f'<a class="{"active" if path.strip("/")==r else ""}" href="{href(lang,r)}">{e(t["nav"][i])}</a>' for i,r in enumerate(ROUTES))
    opts=''.join(f'<option value="{href(l,path)}" {"selected" if l==lang else ""}>{l.upper()}</option>' for l in LANGS)
    logo='<span class="logo-image-shell"><img class="logo-image" src="/assets/hipobuy-logo.png" width="244" height="56" alt="HIPOBUY"></span><span class="logo-suffix">SHEET</span>'
    head=f'<div class="topline"><div class="wrap"><strong>{e(LOCAL[lang][0])}</strong> · {e(LOCAL[lang][1])}</div></div><header><div class="wrap nav"><a class="logo" href="{href(lang)}" aria-label="Hipobuyy Sheet">{logo}</a><nav class="navlinks" aria-label="{e(LOCAL[lang][2])}">{nav}</nav><select class="langs" id="language" aria-label="Language">{opts}</select></div></header>'
    footer=f'<footer class="foot"><div class="wrap"><div class="foot-grid"><div><a class="logo" href="{href(lang)}" aria-label="Hipobuyy Sheet">{logo}</a><p>{e(t["independent"])}</p></div><nav>{"".join(f"<a href={chr(34)+href(lang,r)+chr(34)}>{e(t[chr(110)+chr(97)+chr(118)][i])}</a>" for i,r in enumerate(ROUTES[1:],1))}</nav></div><div class="foot-base">© 2026 Hipobuyy Sheet · {e(LOCAL[lang][6])}</div></div></footer>'
    document_head=meta(lang,path,title,description)
    if path.startswith('articles/'):
        image={'spreadsheet-first':'article-listing.jpg','qc-photo-checklist':'article-qc.jpg','shipping-cost-checklist':'article-shipping.jpg'}.get(path.rsplit('/',1)[-1],'article-listing.jpg')
        changed='2026-09-24' if path.rsplit('/',1)[-1] in SLUGS[3:] else '2026-09-23'
        schema={'@context':'https://schema.org','@type':'Article','headline':title,'description':description,'image':SITE+'/assets/'+image,'author':{'@type':'Organization','name':'Hipobuyy Sheet'},'publisher':{'@type':'Organization','name':'Hipobuyy Sheet'},'datePublished':changed,'dateModified':changed,'inLanguage':lang,'mainEntityOfPage':SITE+href(lang,path)}
        document_head=document_head.replace('</head>','<script type="application/ld+json">'+json.dumps(schema,ensure_ascii=False).replace('<','\\u003c')+'</script></head>')
    elif path=='faq':
        schema={'@context':'https://schema.org','@type':'FAQPage','mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':answer}} for q,answer in FAQS[lang]]}
        document_head=document_head.replace('</head>','<script type="application/ld+json">'+json.dumps(schema,ensure_ascii=False).replace('<','\\u003c')+'</script></head>')
    main_class=' class="home"' if not path else ''
    return document_head+f'<body>{head}<main{main_class}>{body}</main>{footer}</body></html>'
def save(lang,path,body,title,desc):
    directory=DIST/lang/path;directory.mkdir(parents=True,exist_ok=True)
    (directory/'index.html').write_text(shell(lang,path,title,desc,body),encoding='utf-8')
def button_search(lang):
    t=T[lang];return f'<form class="search" data-shop-search><input required type="search" aria-label="{e(t["search"])}" placeholder="{e(t["search"])}"><button type="submit">{e(t["searchbutton"])} ↗</button></form>'
def product(p,lang):
    t=T[lang];cat=CAT_NAMES[lang][CATEGORIES.index(p['category'])]
    return f'<article class="card" data-product-category="{e(p["category"])}"><a class="photo" href="{e(p["detail"])}" rel="noopener"><img src="{e(p["local_image"])}" width="500" height="500" loading="lazy" alt="{e(p["title"])}"></a><div class="card-body"><span class="tag">{e(cat)}</span><h3>{e(p["title"])}</h3><div class="card-bottom"><strong class="price">${p["price"]:.2f}</strong><a href="{e(p["detail"])}" rel="noopener">{e(t["open"])} ↗</a></div></div></article>'
def product_grid(lang,products):return '<div class="cards">'+''.join(product(p,lang) for p in products)+'</div>'
def article_cards(lang,limit=None):
    t=T[lang];return '<div class="article-grid">'+''.join(f'<a class="article-card" href="{href(lang,"articles/"+s)}"><span class="tag">{i+1:02d} / {e(LOCAL[lang][4])}</span><h3>{e(t["article_titles"][i])}</h3><p>{e(t["article_descriptions"][i])}</p><span>{e(t["read"])} →</span></a>' for i,s in enumerate(SLUGS[:limit]))+'</div>'
def section_header(title,sub,link=''):
    return f'<div class="section-top"><div><h2>{e(title)}</h2><p>{e(sub)}</p></div>{link}</div>'
def head(lang,idx):
    t=T[lang];return f'<div class="page-head wrap"><span class="eyebrow">{e(t["eyebrow"])}</span><h1>{e(t["page_titles"][idx])}</h1><p>{e(t["page_subs"][idx])}</p></div>'
def text_sections(sections):return '<div class="prose">'+''.join(f'<h2>{e(title)}</h2><p>{e(copy)}</p>' for title,copy in sections)+'</div>'
def article_html(lang,slug):
    """Render our deliberately small, audited editorial Markdown subset."""
    source=(ROOT/'content'/lang/f'{slug}.md').read_text(encoding='utf-8')
    blocks=[]
    for block in re.split(r'\n\s*\n',source.strip()):
        block=block.strip()
        if block.startswith('## '): blocks.append('<h2>'+e(block[3:])+'</h2>')
        elif block.startswith('!['):
            match=re.fullmatch(r'!\[([^\]]+)\]\((/assets/[a-z0-9-]+\.jpg)\)',block)
            if not match: raise ValueError(f'Unsupported image: {block}')
            alt,src=match.groups()
            if not (DIST/src.lstrip('/')).exists(): raise ValueError(f'Missing article image: {src}')
            blocks.append(f'<figure><img src="{src}" width="680" height="680" loading="lazy" alt="{e(alt)}"><figcaption>{e(alt)}</figcaption></figure>')
        elif block.startswith('|'):
            rows=[[cell.strip() for cell in line.strip().strip('|').split('|')] for line in block.splitlines()]
            if len(rows)<3 or not all(len(row)==len(rows[0]) for row in rows[1:]) or not all(re.fullmatch(r':?-{3,}:?',cell) for cell in rows[1]):
                raise ValueError(f'Unsupported article table in {lang}/{slug}')
            blocks.append('<div class="article-tablewrap"><table><thead><tr>'+''.join('<th>'+e(cell)+'</th>' for cell in rows[0])+'</tr></thead><tbody>'+''.join('<tr>'+''.join(f'<td data-label="{e(rows[0][j])}">'+e(cell)+'</td>' for j,cell in enumerate(row))+'</tr>' for row in rows[2:])+'</tbody></table></div>')
        elif block.startswith('- '): blocks.append('<ul>'+''.join(f'<li>{e(line[2:])}</li>' for line in block.splitlines())+'</ul>')
        else: blocks.append('<p>'+e(' '.join(block.splitlines()))+'</p>')
    return '<article class="prose longread">'+''.join(blocks)+'</article>'

for lang in LANGS:
 t=T[lang]
 cats=''.join(f'<a class="cat" href="{SHOP}/{c}/"><span>{e(CAT_NAMES[lang][i])}</span><span aria-hidden="true">↗</span></a>' for i,c in enumerate(CATEGORIES))
 hero=f'<div class="hero"><div class="wrap hero-grid"><div><span class="eyebrow">{e(t["eyebrow"])}</span><h1>{e(t["hero"])}</h1><p>{e(t["sub"])}</p>{button_search(lang)}<div class="quicklinks">'+''.join(f'<a class="pill" href="{SHOP}/{c}/">{e(CAT_NAMES[lang][i])} ↗</a>' for i,c in enumerate(CATEGORIES[:5]))+f'</div></div><div class="hero-aside"><span class="label">HIPOBUYY / 2026</span><strong>{e(t["aside_title"])}</strong><p>{e(t["aside"])}</p><a href="{href(lang,"spreadsheet")}">{e(t["tablelink"])} →</a></div></div></div>'
 link=f'<a class="text-link" href="{href(lang,"finds")}">{e(t["viewall"])} →</a>'
 home=hero+f'<section><div class="wrap">{section_header(t["products"],t["products_sub"],link)}{product_grid(lang,P[:8])}</div></section>'
 home+=f'<section style="background:#edf3f8"><div class="wrap">{section_header(t["categories"],t["categories_sub"])}<div class="cat-grid">{cats}</div></div></section>'
 home+=f'<section><div class="wrap"><div class="panel"><div><h2>{e(t["how"])}</h2><p>{e(t["how_sub"])}</p><p style="margin-top:16px"><a class="inline-action" href="{href(lang,"guide")}">{e(t["nav"][3])} →</a></p></div><div class="steps">'+''.join(f'<div class="step"><b>{i+1}</b><span>{e(s)}</span></div>' for i,s in enumerate(t['steps']))+'</div></div></div></section>'
 all_articles=f'<a class="text-link" href="{href(lang,"articles")}">{e(t["nav"][7])} →</a>'
 home+=f'<section style="background:#edf3f8"><div class="wrap">{section_header(t["reading"],t["reading_sub"],all_articles)}{article_cards(lang,3)}</div></section>'
 home+=f'<div class="wrap"><p class="note">{e(t["snapshot"])}</p></div>'
 save(lang,'',home,t['hero']+' | 2026',t['sub'])
 filters=''.join(f'<button type="button" data-category-filter="{c}" class="{"on" if c=="all" else ""}">{e(t["all"] if c=="all" else CAT_NAMES[lang][CATEGORIES.index(c)])}</button>' for c in ['all']+CATEGORIES)
 finds=head(lang,2)+f'<div class="wrap route">{button_search(lang)}<div style="height:20px"></div><div class="filterbar">{filters}</div>{product_grid(lang,P)}<p class="empty hide" id="empty">{e(LOCAL[lang][5])}</p><p class="note">{e(t["snapshot"])}</p></div>'
 save(lang,'finds',finds,t['page_titles'][2],t['page_subs'][2])
 rows=''.join(f'<tr><td data-label="{e(LOCAL[lang][3])}"><img src="{e(p["local_image"])}" loading="lazy" alt=""></td><td data-label="{e(t["item"])}">{e(p["title"])}</td><td data-label="{e(t["category"])}">{e(CAT_NAMES[lang][CATEGORIES.index(p["category"])])}</td><td data-label="{e(t["price"])}">${p["price"]:.2f}</td><td data-label="{e(t["link"])}"><a href="{e(p["detail"])}" rel="noopener">{e(t["open"])} ↗</a></td></tr>' for p in P)
 table=f'<div class="tablewrap"><table class="sp-table"><thead><tr><th>{e(LOCAL[lang][3])}</th><th>{e(t["item"])}</th><th>{e(t["category"])}</th><th>{e(t["price"])}</th><th>{e(t["link"])}</th></tr></thead><tbody>{rows}</tbody></table></div>'
 spreadsheet=head(lang,1)+f'<div class="wrap route">{button_search(lang)}<div style="height:21px"></div>{table}<p class="note">{e(t["snapshot"])}</p></div>'
 save(lang,'spreadsheet',spreadsheet,t['page_titles'][1],t['products_sub'])
 for route,idx in [('guide',3),('qc',4),('shipping',5),('faq',6)]:
  page=head(lang,idx)+f'<div class="wrap route">{text_sections(t["body"][route])}<p><a class="inline-action" href="{href(lang,"spreadsheet")}">{e(t["tablelink"])} →</a></p></div>'
  save(lang,route,page,t['page_titles'][idx],t['page_subs'][idx])
 articles=head(lang,7)+f'<div class="wrap route">{article_cards(lang)}</div>'
 save(lang,'articles',articles,t['page_titles'][7],t['page_subs'][7])
 for i,slug in enumerate(SLUGS):
  path='articles/'+slug
  related_idxs=list(dict.fromkeys([0,max(0,i-1),min(len(SLUGS)-1,i+1)]))
  related='<nav class="related-guides" aria-label="Related guides"><strong>'+e(t['reading'])+'</strong>'+''.join(f'<a href="{href(lang,"articles/"+SLUGS[j])}">{e(t["article_titles"][j])} →</a>' for j in related_idxs if j!=i)+'</nav>'
  article=f'<div class="page-head wrap"><span class="eyebrow">{e(t["eyebrow"])}</span><h1>{e(t["article_titles"][i])}</h1><p>{e(t["article_descriptions"][i])}</p></div><div class="wrap route">{article_html(lang,slug)}{related}<p><a class="inline-action" href="{href(lang,"spreadsheet")}">{e(t["tablelink"])} →</a></p></div>'
  save(lang,path,article,t['article_titles'][i],t['article_descriptions'][i])

(DIST/'index.html').write_text('<!doctype html><html><head><meta charset="utf-8"><meta name="robots" content="noindex,nofollow"><meta http-equiv="refresh" content="0;url=/en/"><title>Hipobuyy Sheet</title></head><body><a href="/en/">Open site</a></body></html>')
(DIST/'robots.txt').write_text(f'User-agent: *\nAllow: /\nSitemap: {SITE}/sitemap.xml\n')
(DIST/'_headers').write_text('/sitemap.xml\n  Content-Type: application/xml; charset=utf-8\n  X-Content-Type-Options: nosniff\n',encoding='utf-8')
SITEMAP_NS='http://www.sitemaps.org/schemas/sitemap/0.9'
XHTML_NS='http://www.w3.org/1999/xhtml'
ET.register_namespace('',SITEMAP_NS)
ET.register_namespace('xhtml',XHTML_NS)
sitemap=ET.Element(f'{{{SITEMAP_NS}}}urlset')
for route in ROUTES+[f'articles/{slug}' for slug in SLUGS]:
 for lang in LANGS:
  url=ET.SubElement(sitemap,f'{{{SITEMAP_NS}}}url')
  ET.SubElement(url,f'{{{SITEMAP_NS}}}loc').text=SITE+href(lang,route)
  for alternate in LANGS+['x-default']:
   target='en' if alternate=='x-default' else alternate
   ET.SubElement(url,f'{{{XHTML_NS}}}link',{'rel':'alternate','hreflang':alternate,'href':SITE+href(target,route)})
ET.indent(sitemap,space='  ')
ET.ElementTree(sitemap).write(DIST/'sitemap.xml',encoding='utf-8',xml_declaration=True)
print('Built',len(list(DIST.rglob('index.html'))),'localized pages and',len(ROUTES+SLUGS),'route groups with a sitemap')
