"""Shared reader tools and topic links for the five localized static editions."""
import html

def related_slugs(slug):
    groups=[
        ['hipobuy-tracking-not-updating','order-status-workflow','parcel-tracking-delivery','return-policy-warehouse'],
        ['hipobuy-rehearsal-packing','hipobuy-shipping-calculator','shipping-cost-checklist','warehouse-storage-consolidation','fees-wallet-payment','customs-declaration-insurance','hipobuy-coupon-shipping-discounts'],
        ['hipobuy-hoodie-finds','hipobuy-football-jersey-finds','hipobuy-clothing-spreadsheet','hipobuy-size-guide','hipobuy-qc-photos-2026','hipobuy-shoes-spreadsheet'],
        ['hipobuy-spreadsheet-2026','spreadsheet-first','best-hipobuy-finds-2026','qc-photo-checklist','reading-hipobuy-reviews']
    ]
    if slug=='shipping':return ['hipobuy-shipping-calculator','hipobuy-rehearsal-packing','hipobuy-tracking-not-updating']
    if slug=='qc':return ['qc-photo-checklist','hipobuy-qc-photos-2026','hipobuy-size-guide']
    if slug=='guide':return ['spreadsheet-first','order-status-workflow','hipobuy-tracking-not-updating']
    group=next((g for g in groups if slug in g),groups[-1])
    return [s for s in group if s!=slug][:3]

def editorial_products(lang,slug,products,render):
    ids={'hipobuy-hoodie-finds':['3373','3372','3439'],'hipobuy-football-jersey-finds':['3407','3207','3203','3202']}.get(slug)
    if not ids:return ''
    title={'en':'Catalog examples to compare','de':'Katalogbeispiele zum Vergleichen','es':'Ejemplos del catálogo para comparar','fr':'Exemples du catalogue à comparer','it':'Esempi del catalogo da confrontare'}[lang]
    note={'en':'USD item-price snapshot: 23 September 2026. Listing images, not warehouse QC. Open the exact listing to confirm current options and price.',
    'de':'Artikelpreise in USD, Stand 23. September 2026. Angebotsbilder, keine Lager-QC-Fotos. Prüfe aktuelle Varianten und Preise im jeweiligen Angebot.',
    'es':'Precios de artículos en USD registrados el 23 de septiembre de 2026. Imágenes del anuncio, no fotos QC del almacén. Comprueba opciones y precio actuales en cada ficha.',
    'fr':'Prix des articles en USD relevés le 23 septembre 2026. Images des annonces, pas de contrôle QC en entrepôt. Vérifiez les variantes et prix actuels sur chaque fiche.',
    'it':'Prezzi degli articoli in USD rilevati il 23 settembre 2026. Immagini degli annunci, non foto QC del magazzino. Controlla opzioni e prezzi attuali nella scheda esatta.'}[lang]
    chosen=[next(p for p in products if str(p['id'])==i) for i in ids]
    return '<section class="editorial-products"><h2>'+title+'</h2><p class="note">'+note+'</p>'+render(lang,chosen)+'</section>'

CALC={
'en':{'title':'Plan parcel weight and cost','note':'Illustrative starting measurements. Replace them with your own parcel data and the current route rules. No live rates are loaded.','weight':'Packed weight (kg)','length':'Length (cm)','width':'Width (cm)','height':'Height (cm)','divisor':'Route volumetric divisor','basis':'Billing basis','both':'Greater of actual and volumetric','actual':'Actual weight only','rounding':'Round up to (kg)','rate':'Optional rate (USD/kg)','fee':'Optional fixed fee (USD)','button':'Calculate estimate','actual_label':'Actual weight','volume_label':'Volumetric weight','billed_label':'Planning billed weight','cost_label':'Estimated linear-rate cost','norate':'Add a current rate to model cost.','error':'Enter valid positive measurements, a divisor and rounding step; optional prices must be zero or greater.','limit':'Model: fixed fee + billed kg × entered rate. Initial-weight tiers, minimum charges, taxes and other surcharges are not included. The live eligible parcel quote controls payment.'},
'de':{'title':'Paketgewicht und Kosten planen','note':'Die Anfangswerte sind ein Rechenbeispiel. Ersetze sie durch deine Paketdaten und die aktuellen Regeln der Versandlinie. Keine Live-Tarife.','weight':'Paketgewicht (kg)','length':'Länge (cm)','width':'Breite (cm)','height':'Höhe (cm)','divisor':'Volumendivisor der Versandlinie','basis':'Abrechnungsgrundlage','both':'Höherer Wert aus Real- und Volumengewicht','actual':'Nur tatsächliches Gewicht','rounding':'Aufrunden auf (kg)','rate':'Optionaler Tarif (USD/kg)','fee':'Optionale Grundgebühr (USD)','button':'Schätzung berechnen','actual_label':'Tatsächliches Gewicht','volume_label':'Volumengewicht','billed_label':'Geschätztes Abrechnungsgewicht','cost_label':'Geschätzter linearer Tarif','norate':'Trage einen aktuellen Tarif für die Kostenschätzung ein.','error':'Gib positive Maße, einen Divisor und Rundungsschritt ein. Optionale Preise dürfen nicht negativ sein.','limit':'Modell: Grundgebühr + abgerechnete kg × eingegebener Tarif. Gewichtsstufen, Mindestentgelte, Steuern und weitere Zuschläge fehlen. Maßgeblich ist das verfügbare aktuelle Paketangebot.'},
'es':{'title':'Estima el peso y coste del paquete','note':'Las medidas iniciales son un ejemplo. Sustitúyelas por tus datos y las reglas actuales de la ruta. No se cargan tarifas en directo.','weight':'Peso embalado (kg)','length':'Largo (cm)','width':'Ancho (cm)','height':'Alto (cm)','divisor':'Divisor volumétrico de la ruta','basis':'Base de facturación','both':'Mayor entre peso real y volumétrico','actual':'Solo peso real','rounding':'Redondear hacia arriba a (kg)','rate':'Tarifa opcional (USD/kg)','fee':'Cargo fijo opcional (USD)','button':'Calcular estimación','actual_label':'Peso real','volume_label':'Peso volumétrico','billed_label':'Peso facturable estimado','cost_label':'Coste estimado con tarifa lineal','norate':'Introduce una tarifa actual para estimar el coste.','error':'Introduce medidas, divisor y redondeo positivos. Los precios opcionales deben ser iguales o superiores a cero.','limit':'Modelo: cargo fijo + kg facturables × tarifa introducida. No incluye tramos iniciales, mínimos, impuestos ni otros recargos. El presupuesto actual de una ruta admisible determina el pago.'},
'fr':{'title':'Estimer le poids et le coût du colis','note':'Les valeurs initiales sont un exemple. Remplacez-les par les mesures du colis et les règles actuelles de la ligne. Aucun tarif en direct.','weight':'Poids emballé (kg)','length':'Longueur (cm)','width':'Largeur (cm)','height':'Hauteur (cm)','divisor':'Diviseur volumétrique de la ligne','basis':'Base de facturation','both':'Maximum du poids réel et volumétrique','actual':'Poids réel uniquement','rounding':'Arrondir au palier supérieur (kg)','rate':'Tarif facultatif (USD/kg)','fee':'Frais fixes facultatifs (USD)','button':'Calculer une estimation','actual_label':'Poids réel','volume_label':'Poids volumétrique','billed_label':'Poids facturable estimé','cost_label':'Coût estimé au tarif linéaire','norate':'Saisissez un tarif actuel pour estimer le coût.','error':'Saisissez des mesures, un diviseur et un palier positifs. Les prix facultatifs doivent être positifs ou nuls.','limit':'Modèle : frais fixes + kg facturables × tarif saisi. Les tranches initiales, minimums, taxes et suppléments ne sont pas inclus. Le devis actuel d’une ligne admissible détermine le paiement.'},
'it':{'title':'Stima peso e costo del pacco','note':'Le misure iniziali sono un esempio. Sostituiscile con i dati del pacco e le regole attuali della rotta. Nessuna tariffa in tempo reale.','weight':'Peso imballato (kg)','length':'Lunghezza (cm)','width':'Larghezza (cm)','height':'Altezza (cm)','divisor':'Divisore volumetrico della rotta','basis':'Base di fatturazione','both':'Maggiore tra peso reale e volumetrico','actual':'Solo peso reale','rounding':'Arrotondamento per eccesso (kg)','rate':'Tariffa opzionale (USD/kg)','fee':'Costo fisso opzionale (USD)','button':'Calcola la stima','actual_label':'Peso reale','volume_label':'Peso volumetrico','billed_label':'Peso fatturabile stimato','cost_label':'Costo stimato con tariffa lineare','norate':'Inserisci una tariffa attuale per stimare il costo.','error':'Inserisci misure, divisore e arrotondamento positivi. I prezzi opzionali non possono essere negativi.','limit':'Modello: costo fisso + kg fatturabili × tariffa inserita. Sono esclusi scaglioni iniziali, minimi, imposte e supplementi. Il preventivo attuale di una rotta idonea determina il pagamento.'}}

def calculator(lang):
    t=CALC[lang];e=html.escape
    inputs=''
    for field,value in [('weight','2'),('length','40'),('width','30'),('height','30'),('divisor','6000'),('rounding','0.5'),('rate',''),('fee','0')]:
        optional=field in ['rate','fee']
        inputs+=f'<label>{e(t[field])}<input name="{field}" type="number" step="any" min="{"0" if optional else "0.0001"}" value="{value}" {"" if optional else "required"} inputmode="decimal"></label>'
    select=f'<label>{e(t["basis"])}<select name="basis"><option value="both">{e(t["both"])}</option><option value="actual">{e(t["actual"])}</option></select></label>'
    attrs=' '.join('data-'+key.replace('_','-')+'="'+e(t[key],quote=True)+'"' for key in ['actual_label','volume_label','billed_label','cost_label','norate','error'])
    return f'<section class="parcel-calculator" id="parcel-calculator"><h2>{e(t["title"])}</h2><p>{e(t["note"])}</p><form data-parcel-calculator {attrs}><div class="calculator-fields">{inputs}{select}</div><button type="submit">{e(t["button"])}</button><output aria-live="polite"></output></form><p class="calculator-limit">{e(t["limit"])}</p></section>'
