export const articles = {
  "how-to-check-a-cssbuy-product-link": {
    label: "CSSBUY SPREADSHEET GUIDE · 12 MIN",
    title: "CSSBuy Spreadsheet Guide 2026: How to Check a Product Link Before You Order",
    description: "A fact-checked, step-by-step CSSBuy spreadsheet guide covering product links, variations, the two-payment workflow, warehouse inspection, returns, storage, and total parcel cost.",
    sections: [
      ["Use a CSSBuy spreadsheet for discovery—not as proof", [
        "A CSSBuy spreadsheet can shorten the search for products that are difficult to describe or translate, but a row in a spreadsheet is not a quality certificate. It cannot prove that a seller still has stock, that the product matches a promotional image, that a size label will fit, or that an item can travel on every international route. Treat the spreadsheet as an organized starting point. The useful part is the direct path to a current product page, a clear category, a recorded price, and a visible date showing when the link was last reviewed.",
        "CSSBuy states on its public pages that the products shown through its shopping-agent service come from third-party Chinese marketplaces and are not sold directly by CSSBuy. That distinction matters. CSSBuy can purchase, receive, inspect, store, pack, and ship an order, but the underlying seller controls the product listing and product quality. Before paying, reopen the destination, compare the current images and option names, and decide what evidence you will need when the item reaches the warehouse."
      ]],
      ["Confirm that the destination still matches the find", [
        "Begin with the page reached by the product button. It should be an individual item, not a generic home page, an unrelated category, or a search result that happens to contain similar products. Compare the current title, first image, full image set, price range, available colors, sizes, bundles, and seller notes with the information shown in the index. A link can remain technically reachable even after a seller replaces the original product with another item, so a successful page load is only the first check.",
        "Pay close attention to the original marketplace URL or item identifier when it is available. On marketplaces such as Taobao, Tmall, JD, 1688, and Weidian, sellers may edit the visible content while the address remains the same. If the images, option names, or price no longer describe the find, stop and search again. A transparent link-check date is more honest than a permanent “verified” badge because marketplace listings can change after any review date."
      ]],
      ["Select the exact variation before treating the price as real", [
        "The smallest number on a listing is often only the lowest price in a range. It may belong to a child size, an accessory, a deposit, a single component, or a basic version rather than the product shown in the main photograph. Select the precise color, size, model, quantity, and bundle before comparing sellers. If translated option text is unclear, keep a screenshot and ask CSSBuy to clarify the seller's option rather than guessing. One wrong variation can make every later price and QC comparison meaningless.",
        "Keep the Chinese-yuan value as the primary reference. A USD figure on this site is a rounded comparison based on the recorded CNY value, not a promise about the amount charged at checkout. The seller can change its price, domestic delivery may be added, and the payment exchange rate or transaction costs can differ. Recheck the selected variation immediately before submitting the order and save the option details you expect CSSBuy to purchase."
      ]],
      ["Understand CSSBuy's two-payment workflow", [
        "CSSBuy's public item pages describe the transaction in two stages. The first payment covers the goods and the Chinese domestic delivery needed to move the order from the seller to the CSSBuy warehouse. CSSBuy then purchases the selected item on the shopper's behalf. This means the first checkout is not the complete delivered price, and it should not be compared with a local retail price as though international delivery were already included.",
        "The second payment comes after the goods enter the warehouse, are inspected, and are prepared as an international parcel. At that point the shopper chooses an available shipping line and pays the international shipping charge. Optional services, packaging choices, route restrictions, the parcel's recorded weight and dimensions, and current service terms may affect the total. Planning around these two payments prevents a common mistake: spending the entire budget on products and leaving too little for the parcel."
      ]],
      ["Plan the warehouse inspection before the item arrives", [
        "CSSBuy says its warehouse inspection covers visible basics such as style, quantity, color, size, model, and damage. That is useful, but a standard inspection is not a laboratory test or an authenticity service. It cannot establish fabric composition, battery health, electrical compliance, waterproofing, internal construction, long-term durability, or whether a branded item is authorized. Write down the visible features that would make you accept or reject the item before the warehouse images arrive.",
        "Make the checklist specific to the product. For shoes, look for the selected size, pair alignment, outsole shape, obvious glue marks, and an insole measurement if fit is uncertain. For a hoodie or jacket, check the size label, flat measurements, print placement, stains, hardware, and overall shape. For a jersey, confirm the chosen version, player print, patches, badge position, and shirt width. If the standard photographs do not show a decision-critical detail, request an additional angle or measurement before approving international shipping."
      ]],
      ["Use measurements instead of familiar size labels", [
        "International shoppers often recognize labels such as M, XL, EU 43, or US 10 and assume the same fit. Seller sizing is not consistent enough for that shortcut. For clothing, compare chest width, shoulder, sleeve, waist, and garment length in centimeters with a similar item that already fits. Check whether a chart shows flat width or body circumference. For footwear, identify whether the seller gives foot length, insole length, or outsole length; those numbers are not interchangeable.",
        "When a measurement is missing, the sensible response is not to choose one size larger automatically. Ask the seller through CSSBuy before purchase or request a warehouse ruler photo after arrival. Allow for a small photography or measuring difference, but take a large mismatch seriously. Returning an unsuitable item while it is still in China is normally simpler than paying to ship it internationally and discovering the fit problem at home."
      ]],
      ["Know the published return and storage limits", [
        "CSSBuy's public FAQ says it can help return an item when the seller accepts the return, the product has been in the warehouse for fewer than seven days, and the shopper pays the return delivery cost. That is a conditional service, not a universal right to return every item. Custom goods, seller restrictions, and marketplace rules may remove the option. Inspect warehouse photographs promptly and use the current order page to confirm the deadline instead of waiting until parcel submission.",
        "The public CSSBuy pages also require careful reading on storage. The homepage says items receive 90 days of free warehouse storage and describes a paid monthly extension. Some public item pages distinguish between 90 days for common items and 30 days for sensitive items. Because those statements are not identical, use the deadline shown in the account for the specific order as the controlling information. A spreadsheet should never turn a general storage statement into a guarantee for every product category."
      ]],
      ["Calculate the delivered decision, not only the product price", [
        "A realistic comparison includes the exact item variation, domestic seller-to-warehouse delivery, payment or service costs shown at checkout, optional photographs or services, packaging, and international shipping. Parcel charges can depend on actual weight, parcel dimensions, the billing method used by the selected line, destination, and product restrictions. Bulky shoes with boxes and puffer jackets may occupy much more parcel space than their product price suggests, while dense items may be expensive mainly because of weight.",
        "CSSBuy provides a shipping-fee estimator, but an early estimate is still an estimate. The warehouse measurement and the route available at parcel submission are more useful than a rate copied from an old article or social post. Compare a few parcel scenarios: keeping or removing nonessential packaging, shipping items together, or separating restricted goods. Do not remove protection from fragile or structured items just to chase the smallest possible number."
      ]],
      ["A final pre-order checklist", [
        "Before the first payment, confirm five things: the page still describes the intended item; the exact option and current CNY price are selected; measurements are usable; domestic delivery is understood; and the item is not obviously unsuitable for the destination or likely shipping routes. Save the listing and option details so the warehouse images can be compared with what was actually ordered. Do not rely on a product name alone when several versions share similar photos.",
        "Before the second payment, confirm the item and option, inspect visible condition, compare requested measurements, review the return deadline, check the recorded weight and parcel dimensions, choose appropriate packaging, and compare current routes in the CSSBuy account. This process takes longer than clicking the cheapest row in a spreadsheet, but it is what turns a product list into a useful buying tool. The spreadsheet helps you find; evidence from the current listing and warehouse helps you decide."
      ]]
    ],
  },
  "cssbuy-spreadsheet-categories-explained": {
    label: "CATEGORY BUYING CHECKS · 11 MIN",
    title: "Best CSSBuy Spreadsheet Categories: Shoes, Hoodies, Jerseys and Smarter Buying Checks",
    description: "A practical guide to browsing CSSBuy spreadsheet categories and applying the right listing, sizing, warehouse QC, and parcel checks to each type of product.",
    sections: [
      ["Why a category-first CSSBuy spreadsheet is more useful", [
        "A spreadsheet with thousands of mixed rows can look comprehensive while making comparison harder. Shoes, jerseys, jackets, bags, and electronics do not fail in the same ways, and they do not create the same parcel questions. A category-first index reduces repetitive scrolling and places similar products together so shoppers can compare the information that matters for that type of item. It also gives a search engine a clear page for specific queries such as “CSSBuy shoes spreadsheet” instead of forcing every search intent onto one generic page.",
        "Category organization does not make a product safer or better. It makes the research task clearer. Every category should still lead to an individual product page with a current price, images, options, and a visible check date. Once a product is selected, CSSBuy's official process remains the same: purchase and domestic delivery form the first stage; warehouse receipt and inspection come next; international parcel submission and shipping form the second paid stage."
      ]],
      ["Use browsing when the idea is broad and search when it is exact", [
        "Start with a category when you know the product type but not the specific model—for example, a lightweight jacket, football jersey, or pair of runners. Category pages help reveal price ranges, common option patterns, and the checks that repeat across comparable listings. Use keyword search when you already know a product name, team, garment type, material, or style. A good search keeps the shopper's actual phrase instead of replacing every query with a generic all-products result.",
        "CSSBuy's public site accepts a product URL or a keyword, reflecting two common buying paths. A marketplace URL is usually the better input when the exact listing is already known, because it reduces ambiguity. A keyword is more useful during discovery. In either case, verify the exact seller page and option before payment. Similar product photographs can lead to different materials, measurements, bundles, or sellers."
      ]],
      ["Shoes: size evidence, pair alignment, and parcel volume", [
        "For shoes, the familiar size number is not enough. Look for a chart in centimeters and identify whether it refers to foot length, removable insole length, internal length, or outsole length. Compare the same type of measurement with a pair that fits. Check whether the selected option includes a box and whether the seller's main image shows the exact color. A low headline price may represent a different size range, accessory, or version, so select the SKU before recording the cost.",
        "At the CSSBuy warehouse, confirm that both shoes match in size, color, shape, and visible finish. Inspect toe shape, heel alignment, outsole pattern, obvious glue, stains, and crushing. Ask for a ruler photo if sizing remains uncertain. Shoe boxes can add significant parcel volume; removing one may lower volume but also reduce protection. Decide based on the shoe structure and your tolerance for deformation, not from a universal “always remove boxes” rule."
      ]],
      ["Hoodies, T-shirts, and jackets: measurements before labels", [
        "Clothing listings often use the same letter labels across very different measurement charts. Compare flat chest width, shoulder, sleeve, and garment length with clothing you already own. Note whether the seller recommends a body size or gives the actual garment measurement, and whether the fabric is described as stretchy. The exact color and graphic option should be saved with the order because translated names can be vague. If the material description matters, ask before payment rather than inferring it from a studio photograph.",
        "Warehouse photos can confirm visible style, selected size label, color, print placement, obvious marks, and overall shape. They cannot prove fabric composition or warmth. For a jacket, check zippers, snaps, pockets, missing pieces, and apparent filling distribution. Thick hoodies and puffer jackets may be light but bulky, so their international cost can be driven by parcel dimensions. Compression may reduce volume, but aggressive packing can crease structured pieces or damage prints."
      ]],
      ["Jerseys: version, print, patches, and fit", [
        "A football jersey listing may contain fan versions, player versions, youth sizes, long sleeves, short sleeves, player names, and optional patches under one page. Select every element deliberately. A player version commonly has a closer cut than a fan version, so compare the specific measurement chart rather than transferring a size choice between versions. Check whether a name and number are included in the displayed price or added as a paid option.",
        "When warehouse photographs arrive, match the team, season or design, size label, player print, sleeve patches, badge placement, sponsor print, and collar. Look for visible lifting, crooked positioning, stains, or missing elements. Standard photos may not show the back or every sleeve, so request the necessary view before approving shipment. Printing can be damaged by heat or folding; choose packaging that avoids severe creasing and follow appropriate care after delivery."
      ]],
      ["Accessories and bags: dimensions, hardware, and included parts", [
        "Accessories are easy to misjudge because a photograph does not communicate scale. Confirm length, width, depth, strap range, and interior capacity in centimeters. For a bag, examine closure type, pocket arrangement, strap attachment, and whether small accessories shown in promotional photos are actually included. For hats or headwear, check circumference or adjustability. For watches or similar items, verify the exact model and materials described without assuming appearance proves specification.",
        "Warehouse inspection should cover visible color, quantity, included parts, stitching, hardware, zippers, shape, scratches, and major construction flaws. Ask for interior and measurement photographs when they are missing. Structured bags may require internal support or careful packing, while soft accessories may consolidate easily. Metal, batteries, liquids, magnets, or other components can also affect route availability, so the product category name alone is not enough to predict shipping."
      ]],
      ["Electronics: route eligibility and limits of visual QC", [
        "Electronics deserve a separate category because batteries, plugs, magnets, and radio components may restrict the shipping lines available to a destination. Confirm the model, voltage, plug, included cable, battery status, and seller description before paying. Check current CSSBuy route rules for the item rather than relying on an old list, because carriers and customs requirements can change. A product that can be purchased in China is not automatically eligible for every international route.",
        "Warehouse photographs can show the model label, visible condition, quantity, plug, and included accessories, but they do not establish battery health, electrical safety, regulatory compliance, internal components, or long-term operation. Ask what testing, if any, is available, and do not describe a photographed device as “quality checked” beyond the visible inspection actually performed. High-value or fragile electronics also require deliberate packaging and a clear understanding of current insurance coverage and exclusions."
      ]],
      ["Move from a category find to a CSSBuy order", [
        "Once a category helps you identify a product, reopen the exact listing and select the variation. Record the product price and domestic delivery shown for the first stage. If a marketplace URL is available, submit that exact address through CSSBuy and make sure the order notes identify anything translation could confuse. CSSBuy says orders are usually handled within 24 hours after payment, but “usually” is not a delivery guarantee; seller dispatch and domestic transport still affect warehouse arrival.",
        "When the order reaches the warehouse, compare the received item with the category-specific checklist instead of approving it automatically. CSSBuy's published basic inspection covers visible attributes such as style, quantity, color, size, model, and damage. Use extra photographs or measurements for details the standard set does not reveal. If a return is necessary, act quickly: CSSBuy's public FAQ describes a seller-accepted return while the item has been in the warehouse for fewer than seven days, with return delivery paid by the shopper."
      ]],
      ["Build useful category pages, not doorway pages", [
        "For shoppers and search engines, a good category page needs more than a title and repeated product cards. It should explain the product-specific decisions, link to relevant individual pages, use descriptive image text, and avoid claims that cannot be supported. A shoes page should discuss sizing and box volume; a jersey page should discuss versions and printing; an electronics page should discuss restrictions and the limits of visual inspection. This makes each page meaningfully different rather than a thin doorway to the same destination.",
        "The strongest browsing order is simple: begin with the department, narrow to a product, verify the current listing and exact option, plan the warehouse evidence, and reserve budget for the second shipping payment. Category pages make discovery faster, but the shopper still controls the quality of the decision. A well-organized CSSBuy spreadsheet is valuable because it reduces search friction while keeping the important checks visible—not because it promises that every listed item will be suitable."
      ]]
    ],
  },
  "cssbuy-shipping-cost-planning": {
    label: "CSSBUY SHIPPING COST · 12 MIN",
    title: "CSSBuy Shipping Cost Guide 2026: Two Payments, Parcel Weight and Total Cost",
    description: "A fact-based explanation of CSSBuy's two payment stages, domestic delivery, warehouse inspection, packaging, chargeable weight, route estimates, storage, returns, and realistic parcel budgeting.",
    sections: [
      ["Why the product price is not the delivered cost", [
        "A low listing price is easy to compare because it appears before the order begins. The international parcel cost is harder because it depends on information that often does not exist until the item reaches a warehouse. CSSBuy's public item pages explain that the process has two paid stages. The first covers the goods and shipping within China to the CSSBuy warehouse. The second covers international shipping after the goods have been received, inspected, combined, and packed into a parcel.",
        "This separation is the most important fact in CSSBuy shipping-cost planning. A spreadsheet price should never be presented as the final delivered price, and an approximate USD conversion should not be described as a checkout quote. A useful budget keeps product purchasing and parcel shipping separate from the beginning, then updates the estimate when real warehouse measurements and current route choices become available."
      ]],
      ["Stage one: exact variation, domestic delivery, and payment", [
        "Start with the price of the exact color, size, model, quantity, or bundle. Many marketplace pages show a range whose lowest value belongs to a different variation from the main image. Add Chinese domestic delivery if the seller charges it. This first transport leg moves the order to CSSBuy's warehouse; it is not the international shipment. Any payment, exchange-rate, or service amounts shown in the current checkout should also be reviewed before authorizing the first payment.",
        "Avoid articles that apply one universal fee percentage to every order. Payment methods, promotions, currency handling, and service terms can change, and the account checkout is the current source for the transaction. Keep the source amount in CNY alongside any display conversion so comparisons remain understandable. If two sellers offer apparently identical items, compare the same variation and domestic-delivery conditions rather than selecting the smallest headline number."
      ]],
      ["Warehouse arrival changes the quality of the estimate", [
        "Before warehouse arrival, weight and size may be seller estimates, copied catalog values, or entirely absent. After arrival, CSSBuy can record the item and provide warehouse photographs. Its public pages describe a basic visible inspection of style, quantity, color, size, model, and damage. That checkpoint is where the shopper should confirm the order and decide whether to keep, return, or request more evidence before spending money on international delivery.",
        "Warehouse data also makes parcel planning more concrete. A shoe with a rigid box, a dense accessory, a large puffer jacket, and a compact T-shirt can have very different effects on the parcel. Do not approve items only because domestic purchase has already taken time. If the wrong item or an obvious defect is visible, investigate the return option while the published time window may still be available. Shipping an unwanted item internationally turns a manageable warehouse problem into a much more expensive one."
      ]],
      ["Stage two: international parcel submission", [
        "Once the chosen items are ready, the shopper submits a parcel, selects available services and packaging, reviews eligible shipping lines, completes the declaration requested by the service, and pays the international charge. The lines shown can depend on destination, parcel weight and dimensions, the nature of the goods, and carrier restrictions. CSSBuy publishes a shipping-fee estimator, but the useful comparison is the one generated with current parcel information rather than a price copied from an old social post.",
        "Delivery-time ranges are estimates rather than guaranteed appointments. Carrier processing, export handling, flights, customs, local delivery, weather, and peak seasons can all change the result. Compare routes by eligibility, billing method, tracking, expected timing, compensation or insurance terms, and restrictions—not only by the lowest displayed amount. Check the current route details inside CSSBuy immediately before payment because names, prices, limits, and availability can change."
      ]],
      ["Actual weight, dimensions, and chargeable weight", [
        "Actual weight is the parcel's measured mass. Some shipping lines can also use a dimensional or volumetric calculation based on parcel length, width, and height. The precise formula and billing rule belong to the selected line, so do not assume one divisor or method applies to every CSSBuy route. In practical terms, dense goods tend to be driven by actual weight, while light but bulky goods can cost more than their mass alone suggests.",
        "Shoe boxes, structured bags, helmets, plush items, and thick jackets are common examples of volume-sensitive products. Books, metal accessories, and compact hardware can be weight-sensitive. The best early estimate uses realistic product dimensions and weight ranges, but the best final estimate uses warehouse and parcel data. If a parcel is close to a route limit or billing step, leave some margin for packaging rather than budgeting to the exact gram or centimeter."
      ]],
      ["Packaging and consolidation are cost-and-risk choices", [
        "CSSBuy says it can combine and pack warehouse orders and uses protective packing materials. Its public pages also mention splitting orders and multiple packing options. Consolidating compatible goods can avoid paying separate base charges, but the largest or most restricted item can influence which lines remain available. Splitting may be sensible when products have different restrictions, values, destinations, or protection needs. There is no single parcel arrangement that is cheapest and safest for every order.",
        "Removing a shoe box or other nonessential retail packaging may reduce volume, while vacuum compression may help some soft textiles. Reinforcement, waterproof wrapping, corner protection, and bubble wrap can add weight and size while reducing damage risk. Fragile goods, electronics, structured bags, and items with delicate prints should not be stripped of protection simply to minimize the estimate. Ask what each service changes and choose based on the item's vulnerability and the selected route."
      ]],
      ["Returns and storage affect the parcel timeline", [
        "CSSBuy's public FAQ says a return can be assisted when the seller accepts it, the item has been in the warehouse for fewer than seven days, and the shopper pays the Chinese return-delivery cost. This is why QC should happen promptly. Waiting to inspect until every planned product arrives can allow an earlier item's return window to expire. Track each order separately and resolve wrong options or visible defects before building the final parcel.",
        "Published storage information also needs nuance. CSSBuy's homepage states 90 days of free storage and describes a paid extension of 15 CNY per order per month. Some public product pages say common items receive 90 days and sensitive items 30 days. Because the public statements differ by context, check the deadline shown for each order in the account. Do not use a general article to override a product-specific warehouse deadline, and do not treat free storage as a reason to postpone inspection."
      ]],
      ["Insurance, customs, and restricted goods", [
        "Insurance or compensation should be evaluated from the current policy and selected line, including covered events, excluded goods, evidence requirements, value limits, and claim deadlines. Do not write that a parcel is “fully insured” merely because an insurance option exists. High-value, fragile, battery-powered, liquid, magnetic, branded, regulated, or unusually large goods may have special restrictions or exclusions. Confirm eligibility before purchasing when shipping feasibility is essential to the decision.",
        "Customs treatment is separate from the agent's product and shipping charges. Import rules, taxes, duties, de minimis thresholds, prohibited goods, and declaration responsibilities depend on the destination and can change. Neither a spreadsheet nor a past delivery proves that another parcel will receive the same treatment. Use truthful order information, follow the current declaration process, and check official destination-country guidance for anything with legal, safety, or tax uncertainty."
      ]],
      ["Build a realistic CSSBuy cost worksheet", [
        "Use a simple structure instead of one misleading total. Stage-one estimate: exact product variation plus Chinese domestic delivery plus the current checkout costs. Warehouse decision: optional photographs or services plus any return cost if the item fails inspection. Stage-two estimate: packaging and parcel services plus the current international line, with a separate note for possible destination taxes or duties. Keep the assumptions and date beside every estimate so an old number is not mistaken for a current quote.",
        "Run at least two parcel scenarios when cost matters. One can preserve retail packaging and stronger protection; another can remove only clearly unnecessary volume. Compare the route eligibility and risk, not just the number. If the purchase only looks attractive under an unrealistically low weight or a shipping rate that is no longer available, it is not a sound plan. The best time to discover that is before the first payment, not after several orders have accumulated in the warehouse."
      ]],
      ["Final shipping checklist", [
        "Before parcel submission, confirm that every item is correct, the return decisions are finished, and no storage deadline is close. Review the warehouse weight and dimensions, decide which original packaging to keep, select protection appropriate to the goods, and check whether combining the items changes route eligibility. Compare the current CSSBuy estimator or account options using the same parcel assumptions, then read the chosen line's restrictions, billing method, tracking, estimated time, and insurance or compensation conditions.",
        "A CSSBuy shipping estimate becomes trustworthy only when its assumptions are visible. Product price is a useful first number, not the answer. The practical sequence is: choose the exact variation, budget for domestic delivery, inspect promptly in the warehouse, use real weight and dimensions, package for the item, compare current routes, and reserve for destination charges where relevant. That approach produces a more honest delivered-cost decision than any spreadsheet promising one fixed shipping figure."
      ]]
    ],
  },
  "order-taobao-weidian-1688-links-with-cssbuy": {
    label: "MARKETPLACE LINK CHECKS · 13 MIN",
    title: "How to Order Taobao, Weidian and 1688 Links with CSSBuy",
    description: "A step-by-step CSSBuy link-ordering guide for checking Taobao, Weidian and 1688 listings, variants, minimum quantities, notes, warehouse evidence and parcel readiness.",
    published: "2026-08-09",
    checked: "August 9, 2026",
    sections: [
      ["Start with the marketplace link, not a copied product name", [
        "When you already know the product you want, the original marketplace link is the cleanest starting point. CSSBuy's current Buy For Me page tells shoppers to copy a product link from a Chinese ecommerce website and paste it into the CSSBuy search field. That preserves more context than retyping a translated name: the seller, listing, option structure and item identifier can travel together. A keyword search remains useful for discovery, but it can return near-matches from different sellers, materials or bundles.",
        "A working import is not proof that the listing is current or suitable. Open the source and the parsed CSSBuy page side by side. Compare the first image, full title, seller identity where visible, price range, domestic delivery, available colors, sizes, models and quantities. Stop if CSSBuy shows a different item, an empty result, a manual-order screen you do not understand, or options that no longer match the source. The goal is not merely to make the link load; it is to preserve the exact buying decision."
      ]],
      ["Know what CSSBuy publicly supports", [
        "CSSBuy's current Buy For Me instructions describe two discovery methods. Shoppers can paste a Chinese marketplace URL, or search by product name and choose results from Taobao, Tmall and 1688.com. The same page lists additional supported sources and points people to Expert Buy when normal search cannot retrieve an item. Current CSSBuy product interfaces also show Taobao, 1688 and Weidian as marketplace categories. These are platform statements about workflow, not a guarantee that every seller page will parse successfully.",
        "Some links fail because a listing requires login, changes its option data, blocks retrieval or has been removed. CSSBuy provides a manual-order route when product information cannot be retrieved. Use it only when you can supply the source URL, exact variant, quantity, unit price, domestic shipping and clear notes. Unclear fields should trigger a question rather than a guess."
      ]],
      ["Taobao links: lock the exact SKU before payment", [
        "A Taobao listing can place many choices under one URL. The lowest displayed price may belong to a small size, accessory, deposit or basic version rather than the main photograph. Select every relevant property on the original listing and again on CSSBuy: color, size, model, bundle and quantity. If the option names are translated differently, compare their position, thumbnail and price instead of relying on one English word. Save a screenshot of the chosen combination so the warehouse item can later be checked against a stable reference.",
        "Treat a size label as an identifier, not a fit guarantee. Record measurements in centimeters and note whether a chart describes the garment, body, foot or insole. Repeat any promised accessory or special print in the order note. CSSBuy says its purchasing team can contact the seller, but the note must be specific enough to act on."
      ]],
      ["Weidian links: verify the seller page and translated options", [
        "Weidian links often circulate through spreadsheets, image albums and social posts after their original context has disappeared. First confirm that the address still opens the intended individual listing rather than a shop home page, expired item or unrelated replacement. Compare the current seller images with the find that led you there. If the visual, title or option set changed, the old recommendation no longer describes the present listing even though the URL still responds.",
        "Check that all Weidian options imported and their prices align with the source. Short Chinese names can mean a color, batch, size range, version or deposit. Repeat the exact option text, thumbnail and required measurement in the note. If a necessary choice is missing, use the available enquiry or manual path rather than a close-looking substitute."
      ]],
      ["1688 links: calculate minimum quantity before comparing price", [
        "CSSBuy's current Buy For Me page warns that many 1688 products have a minimum order quantity and tells shoppers to follow the supplier's minimum. A 1688 page may also show price tiers linked to quantity. The appealing first number is therefore not automatically the cost of one item. Identify the commercial unit first—one piece, one pair, one set, one pack or one carton—then record the minimum quantity, allowed increments and tier that applies to the amount you actually want.",
        "Use a simple pre-payment calculation: required units multiplied by the unit price at that quantity, plus the displayed domestic delivery. For a hypothetical listing sold in packs of three, wanting four individual units does not mean entering quantity four until you know whether CSSBuy and the supplier interpret that as four pieces or four packs. Do not invent a workaround for a supplier minimum. If colors can be mixed within the minimum, or if a tier applies across variants, ask for confirmation and keep the response with the order."
      ]],
      ["Build an order note that a purchaser can follow", [
        "A useful note resolves ambiguity; it does not repeat the product name. Write the marketplace, exact source URL, option text, size or measurement, color, version, quantity and any included part that must be present. If the seller's image contains a code, quote that code. Explain what to do if the chosen option is unavailable: contact you, cancel, or accept a named alternative. Never write a vague instruction such as “best quality” or “same as photo” when the listing itself contains several photos and versions.",
        "Keep requests observable. “Confirm the label says size 44” can be checked; “make sure it fits me” cannot. Asking whether a pack includes two laces is actionable; “choose the good one” is not. Clear notes reduce back-and-forth, but they do not change seller stock or create a guarantee."
      ]],
      ["Understand the first payment and what it does not include", [
        "CSSBuy's public item pages divide the process into two paid stages. The first payment covers the selected goods and Chinese domestic delivery to the CSSBuy warehouse, after which CSSBuy purchases from the third-party seller. Review the exact CNY item amount, selected quantity and domestic delivery before paying. Any current payment or service amount shown at checkout belongs in the decision, but there is no safe universal percentage to copy into an article because methods and terms can change.",
        "The first payment is not a delivered total. International shipping follows warehouse receipt, inspection, consolidation and packing, so reserve budget for that stage. A cheap listing can still be poor value when the variant is wrong, the minimum creates unwanted units, the item is bulky or its attributes restrict available lines."
      ]],
      ["Use warehouse evidence to check the order you actually placed", [
        "CSSBuy's public product pages describe a visible inspection covering style, quantity, color, size, model and damage. Begin with those basics and compare them with the saved source and order note. For a Taobao garment, match the exact color and size label, then request a useful flat measurement if fit remains uncertain. For a Weidian shoe, compare both shoes, the size tag, shape, outsole and selected color. For a 1688 order, count the pieces and verify whether mixed variants arrived as agreed.",
        "Warehouse photographs cannot prove authenticity, composition, internal construction, battery health, electrical safety or durability. Decide before arrival which visible facts would make you accept, question or return the item. If a decision-critical feature is missing, request the relevant angle or measurement promptly through the current account options."
      ]],
      ["Resolve mismatches before building an international parcel", [
        "If the received option, quantity or visible condition differs from the order, identify the exact mismatch and attach the relevant evidence. CSSBuy's public FAQ says it can assist with a return when the seller accepts it, the item has been in the warehouse for fewer than seven days and the shopper pays return delivery. That statement is conditional. A seller's rules, customized goods, the marketplace transaction and the order status can still prevent a return, so the deadline shown for the specific order should control.",
        "Do not approve an obvious mistake merely because the source link took time to find. International shipment makes correction harder. On the other hand, do not reject an item because warehouse lighting changes color slightly or a wide-angle photograph distorts shape. Compare several images, ask a focused question and separate a visible defect from uncertainty. The decision should trace back to the exact option and note submitted at purchase, not to an idealized product image found elsewhere."
      ]],
      ["A final link-to-parcel checklist", [
        "Before the first payment, confirm the marketplace page is current; the CSSBuy import matches it; every SKU property is selected; the quantity and commercial unit are understood; the 1688 minimum and price tier are satisfied where relevant; domestic delivery is visible; measurements are usable; and the order note contains only actionable requirements. Save the source, selected option and date. If the page fails to import cleanly, use the supported enquiry or manual route only after you can fill every important field accurately.",
        "Before the second payment, match the warehouse item to the saved order, count units, inspect visible condition, resolve return questions, check actual item data, choose protection and compare the current eligible routes. CSSBuy says some products can be restricted for particular delivery methods and presents recommended choices at parcel submission. Recheck that live information rather than assuming a marketplace category determines eligibility. A good CSSBuy link workflow is a chain of evidence: current source, exact option, clear note, warehouse proof and a parcel decision made with current data."
      ]]
    ],
    related: [
      ["Check a product link before ordering", "/articles/how-to-check-a-cssbuy-product-link"],
      ["Plan the full parcel cost", "/articles/cssbuy-shipping-cost-planning"],
      ["Browse checked product finds", "/products"]
    ],
  },
} as const;

export type ArticleSlug = keyof typeof articles;
