export const germanResearchExtras: Record<string, string> = {
  "July 23, 2026": "23. Juli 2026",
  "Verified UUFinds functions": "Geprüfte UUFinds-Funktionen",
  "How it works / Fact-checked July 23, 2026": "So funktioniert es / Fakten geprüft am 23. Juli 2026",
  "Match the link.": "Gleiche den Link ab.",
  "Read the evidence.": "Prüfe die Belege.",
  "Verify what changed.": "Prüfe, was sich geändert hat.",
  "UUFinds publicly describes a QC finder for photos and videos, image recognition, and link handling for Taobao, Weidian, 1688 and shopping agents. Those tools can support research, but the exact live listing still decides the current price, variants and availability.": "UUFinds beschreibt öffentlich eine QC-Suche für Fotos und Videos, Bilderkennung sowie Link-Verarbeitung für Taobao, Weidian, 1688 und Shopping-Agenten. Diese Werkzeuge unterstützen die Recherche, doch das genaue aktuelle Angebot bestimmt weiterhin Preis, Varianten und Verfügbarkeit.",
  "QC media": "QC-Medien",
  "UUFinds says its QC finder can surface available product photos and videos.": "UUFinds gibt an, dass seine QC-Suche verfügbare Produktfotos und -videos anzeigen kann.",
  "Supported inputs": "Unterstützte Eingaben",
  "Its public app information names 1688, Taobao, Weidian and shopping-agent link conversion.": "Die öffentlichen App-Informationen nennen 1688, Taobao, Weidian und die Umwandlung von Shopping-Agent-Links.",
  "Platform boundary": "Grenzen der Plattform",
  "UUFinds states that it does not sell products directly or indirectly.": "UUFinds erklärt, dass es Produkte weder direkt noch indirekt verkauft.",
  "MATCH": "ABGLEICHEN",
  "Preserve the exact source": "Die genaue Quelle bewahren",
  "Keep the full marketplace or agent link. Compare the item ID, seller and visible variant before treating an album as a match. Image recognition may find a visually similar item, but similarity alone does not prove it is the same listing or batch.": "Bewahre den vollständigen Marktplatz- oder Agentenlink auf. Vergleiche Artikel-ID, Verkäufer und sichtbare Variante, bevor du ein Album als Treffer wertest. Die Bilderkennung kann einen optisch ähnlichen Artikel finden, doch Ähnlichkeit allein beweist weder dasselbe Angebot noch dieselbe Charge.",
  "Build a category shortlist →": "Kategorie-Auswahlliste erstellen →",
  "INSPECT": "PRÜFEN",
  "Read every available angle": "Jede verfügbare Ansicht prüfen",
  "Start with silhouette and proportion, then inspect construction, finish and measurements. Note the QC date and whether more than one example exists. Record missing angles as unknowns instead of turning them into assumptions.": "Beginne mit Silhouette und Proportionen und prüfe danach Verarbeitung, Oberfläche und Maße. Notiere das QC-Datum und ob mehrere Beispiele vorhanden sind. Erfasse fehlende Ansichten als unbekannt, statt daraus Annahmen zu machen.",
  "CONFIRM": "BESTÄTIGEN",
  "Check today’s listing facts": "Die heutigen Angebotsdaten prüfen",
  "Open the exact CNBuy Sheet product page and re-check the identifier, current price, variants, size information and availability. An older QC set can inform the decision, but it cannot confirm what the seller offers today.": "Öffne die genaue CNBuy-Sheet-Produktseite und prüfe Kennung, aktuellen Preis, Varianten, Größenangaben und Verfügbarkeit erneut. Ein älteres QC-Set kann die Entscheidung unterstützen, aber nicht das heutige Angebot des Verkäufers bestätigen.",
  "Tool versus conclusion": "Werkzeug und Schlussfolgerung",
  "Know what each signal can prove.": "Verstehe, was jedes Signal belegen kann.",
  "This distinction prevents a useful research tool from being mistaken for a product guarantee.": "Diese Unterscheidung verhindert, dass ein nützliches Recherchewerkzeug mit einer Produktgarantie verwechselt wird.",
  "QC PHOTOS": "QC-FOTOS",
  "Useful for visible condition": "Nützlich für den sichtbaren Zustand",
  "They can show shape, stitching, print placement, hardware and measurements on the photographed item.": "Sie können Form, Nähte, Druckposition, Beschläge und Maße des fotografierten Artikels zeigen.",
  "They cannot guarantee another unit or later batch.": "Sie können keinen anderen Artikel oder eine spätere Charge garantieren.",
  "QC VIDEO": "QC-VIDEO",
  "Useful for movement": "Nützlich für Bewegung",
  "Video can reveal fabric drape, zipper movement, sole flex and angles that a still image may hide.": "Video kann Stofffall, Reißverschlussbewegung, Sohlenflex und Ansichten zeigen, die ein Standbild verbirgt.",
  "It cannot establish durability or internal electronic condition.": "Es kann Haltbarkeit oder den inneren Zustand von Elektronik nicht belegen.",
  "IMAGE RECOGNITION": "BILDERKENNUNG",
  "Useful for finding candidates": "Nützlich zum Finden von Kandidaten",
  "A similar image can help locate related listings when the original link is missing or incomplete.": "Ein ähnliches Bild kann helfen, verwandte Angebote zu finden, wenn der Originallink fehlt oder unvollständig ist.",
  "It cannot replace the seller and item-ID match.": "Es ersetzt nicht den Abgleich von Verkäufer und Artikel-ID.",
  "LIVE PRODUCT PAGE": "AKTUELLE PRODUKTSEITE",
  "Useful for current facts": "Nützlich für aktuelle Fakten",
  "The destination page is where price, available options, seller details and stock must be checked again.": "Auf der Zielseite müssen Preis, verfügbare Optionen, Verkäuferangaben und Bestand erneut geprüft werden.",
  "It still does not promise that every received item will match an older sample.": "Auch sie verspricht nicht, dass jeder erhaltene Artikel einem älteren Muster entspricht.",
  "Five-line decision record": "Entscheidungsnotiz in fünf Zeilen",
  "Write this down before you continue.": "Notiere dies, bevor du fortfährst.",
  "Match:": "Abgleich:",
  "exact, probable, or visual reference only.": "genau, wahrscheinlich oder nur visuelle Referenz.",
  "Evidence:": "Belege:",
  "which photos, video, angles and measurements were available.": "welche Fotos, Videos, Ansichten und Maße verfügbar waren.",
  "Unknowns:": "Unbekannt:",
  "missing views, material claims, sizing or internal condition.": "fehlende Ansichten, Materialangaben, Größen oder innerer Zustand.",
  "Live check:": "Live-Prüfung:",
  "current ID, price, variants and availability on CNBuy Sheet.": "aktuelle ID, Preis, Varianten und Verfügbarkeit bei CNBuy Sheet.",
  "Decision:": "Entscheidung:",
  "keep, compare with another listing, or pause for more evidence.": "behalten, mit einem anderen Angebot vergleichen oder auf weitere Belege warten.",
  "Research boundary": "Grenzen der Recherche",
  "Discovery expands options. QC reduces uncertainty. The live listing confirms current facts.": "Produktsuche erweitert die Auswahl. QC verringert Unsicherheit. Das aktuelle Angebot bestätigt die gegenwärtigen Fakten.",
  "Official claims reviewed: UUFinds QC finder, QC browsing copy, product-detail disclaimer, account pages and public app information. No UUFinds outbound link is included on this site.": "Geprüfte offizielle Angaben: UUFinds-QC-Suche, QC-Seitentexte, Produkt-Haftungsausschluss, Kontoseiten und öffentliche App-Informationen. Diese Website enthält keinen ausgehenden UUFinds-Link.",
  "Read the complete buying guide →": "Vollständigen Kaufratgeber lesen →",

  "Finds / UUFinds research + 09 direct routes": "Funde / UUFinds-Recherche + 09 direkte Wege",
  "Discover broadly.": "Breit entdecken.",
  "Match precisely.": "Genau abgleichen.",
  "UUFinds publicly describes both QC discovery and personalized pages that combine items, purchasing-agent routes and social content. Use discovery to create a shortlist—then keep the exact source link so a popular image or shared page is never mistaken for proof of one specific listing.": "UUFinds beschreibt öffentlich sowohl QC-Suche als auch personalisierte Seiten, die Artikel, Einkaufsagenten-Wege und soziale Inhalte verbinden. Nutze die Suche für eine Auswahlliste und bewahre dann den genauen Quelllink, damit ein populäres Bild oder eine geteilte Seite nicht als Beleg für ein bestimmtes Angebot missverstanden wird.",
  "What the official pages establish": "Was die offiziellen Seiten belegen",
  "A find is a starting point.": "Ein Fund ist ein Ausgangspunkt.",
  "The official public descriptions support product discovery, link handling, QC media and shareable item pages. They do not establish that every shared item has recent QC material or unchanged seller data.": "Die offiziellen öffentlichen Beschreibungen belegen Produktsuche, Link-Verarbeitung, QC-Medien und teilbare Artikelseiten. Sie belegen nicht, dass jeder geteilte Artikel aktuelles QC-Material oder unveränderte Verkäuferdaten hat.",
  "SHARED ITEM PAGE": "GETEILTE ARTIKELSEITE",
  "Useful for collecting leads": "Nützlich zum Sammeln von Kandidaten",
  "UUFinds describes personalized pages that integrate items, purchasing agents and social content and can be shared through one link.": "UUFinds beschreibt personalisierte Seiten, die Artikel, Einkaufsagenten und soziale Inhalte verbinden und über einen Link geteilt werden können.",
  "Save the original item or seller link before researching quality.": "Speichere vor der Qualitätsrecherche den ursprünglichen Artikel- oder Verkäuferlink.",
  "QC FINDER": "QC-SUCHE",
  "Useful after discovery": "Nützlich nach der Entdeckung",
  "The official QC finder describes photos, videos and image recognition. Availability depends on what material exists for the product or link.": "Die offizielle QC-Suche beschreibt Fotos, Videos und Bilderkennung. Die Verfügbarkeit hängt davon ab, welches Material zum Produkt oder Link existiert.",
  "A visually similar result is not automatically the same seller, variant or batch.": "Ein optisch ähnliches Ergebnis ist nicht automatisch derselbe Verkäufer, dieselbe Variante oder Charge.",
  "CATEGORY ROUTE": "KATEGORIEWEG",
  "Useful when you only know the type": "Nützlich, wenn nur die Art bekannt ist",
  "Begin with Shoes, Hoodies, T-Shirts, Jackets, Pants, Headwear, Accessories, Jerseys or Electronics when no exact link exists yet.": "Beginne mit Schuhen, Hoodies, T-Shirts, Jacken, Hosen, Kopfbedeckungen, Accessoires, Trikots oder Elektronik, wenn noch kein genauer Link vorhanden ist.",
  "Shortlist two or three candidates before comparing evidence.": "Wähle zwei oder drei Kandidaten aus, bevor du Belege vergleichst.",
  "EXACT PRODUCT": "GENAUES PRODUKT",
  "Useful for the final match": "Nützlich für den letzten Abgleich",
  "Open an individual CNBuy Sheet detail page and compare its product ID, images, price and variants with the item you researched.": "Öffne eine einzelne CNBuy-Sheet-Detailseite und vergleiche Produkt-ID, Bilder, Preis und Varianten mit dem recherchierten Artikel.",
  "Use the live page for current facts that a shared find cannot preserve.": "Nutze die aktuelle Seite für Fakten, die ein geteilter Fund nicht bewahren kann.",
  "A practical discovery routine": "Eine praktische Entdeckungsroutine",
  "Turn browsing into a traceable shortlist.": "Mache aus dem Browsen eine nachvollziehbare Auswahlliste.",
  "Name the intent:": "Ziel benennen:",
  "inspiration, category comparison, or verification of one exact link.": "Inspiration, Kategorievergleich oder Prüfung eines genauen Links.",
  "Keep the source:": "Quelle bewahren:",
  "preserve the full item URL and visible seller or item identifier.": "vollständige Artikel-URL und sichtbare Verkäufer- oder Artikelkennung speichern.",
  "Narrow the field:": "Auswahl eingrenzen:",
  "compare category, model, material, price band and visible variants.": "Kategorie, Modell, Material, Preisbereich und sichtbare Varianten vergleichen.",
  "Research evidence:": "Belege recherchieren:",
  "check whether matched QC photos or video exist and how recent they are.": "prüfen, ob passende QC-Fotos oder Videos existieren und wie aktuell sie sind.",
  "Finish live:": "Live abschließen:",
  "confirm today’s information on the exact CNBuy Sheet product page.": "heutige Informationen auf der genauen CNBuy-Sheet-Produktseite bestätigen.",
  "Source boundary / Reviewed July 23, 2026": "Quellengrenze / Geprüft am 23. Juli 2026",
  "Function claims on this page were checked against UUFinds’ public QC finder, QC browsing page, personalized display page, product disclaimer and app information. Category and shopping buttons remain exclusive to CNBuy Sheet.": "Die Funktionsangaben auf dieser Seite wurden anhand der öffentlichen UUFinds-QC-Suche, QC-Seite, personalisierten Anzeigeseite, des Produkthaftungsausschlusses und der App-Informationen geprüft. Kategorie- und Shopping-Schaltflächen führen weiterhin ausschließlich zu CNBuy Sheet.",

  "Products / 08 direct listing routes": "Produkte / 08 direkte Angebotswege",
  "See the listing.": "Sieh dir das Angebot an.",
  "Separate it from QC evidence.": "Trenne es von QC-Belegen.",
  "The images below come from the corresponding CNBuy Sheet listings; they are not labeled as UUFinds warehouse QC albums. Open a detail page, note the exact item ID, then use the official UUFinds research functions only when matched QC media is available for that source.": "Die Bilder unten stammen aus den entsprechenden CNBuy-Sheet-Angeboten; sie sind nicht als UUFinds-Lager-QC-Alben gekennzeichnet. Öffne eine Detailseite, notiere die genaue Artikel-ID und nutze die offiziellen UUFinds-Recherchefunktionen nur, wenn passendes QC-Material für diese Quelle verfügbar ist.",
  "Listing image versus QC evidence": "Angebotsbild und QC-Beleg",
  "Do not grade the wrong photo set.": "Bewerte nicht den falschen Fotosatz.",
  "UUFinds says it can help find QC photos and videos. The first job is still matching that material to the exact item you intend to open.": "UUFinds gibt an, bei der Suche nach QC-Fotos und -Videos zu helfen. Die erste Aufgabe bleibt, dieses Material dem genauen Artikel zuzuordnen, den du öffnen willst.",
  "LISTING IMAGE": "ANGEBOTSBILD",
  "Shows how the product is presented": "Zeigt, wie das Produkt präsentiert wird",
  "Use it to identify the model, color, design and seller-facing description on the current product page.": "Nutze es, um Modell, Farbe, Design und Verkäuferbeschreibung auf der aktuellen Produktseite zu erkennen.",
  "It may be a catalog or promotional image rather than a warehouse sample.": "Es kann ein Katalog- oder Werbebild statt eines Lagermusters sein.",
  "MATCHED QC PHOTO": "PASSENDES QC-FOTO",
  "Shows one photographed item": "Zeigt einen fotografierten Artikel",
  "Use it to inspect visible shape, construction, finish and measurements when the source link or item ID agrees.": "Nutze es zur Prüfung von sichtbarer Form, Verarbeitung, Oberfläche und Maßen, wenn Quelllink oder Artikel-ID übereinstimmen.",
  "It documents a sample, not every future unit.": "Es dokumentiert ein Muster, nicht jeden zukünftigen Artikel.",
  "Adds motion and hidden angles": "Ergänzt Bewegung und verborgene Ansichten",
  "Use video to examine fabric drape, zipper movement, sole flex, reflective material or angles missing from still images.": "Nutze Video, um Stofffall, Reißverschlussbewegung, Sohlenflex, reflektierendes Material oder in Fotos fehlende Ansichten zu prüfen.",
  "It does not confirm durability, authenticity or internal specifications.": "Es bestätigt weder Haltbarkeit noch Echtheit oder interne Spezifikationen.",
  "LIVE DESTINATION": "AKTUELLES ZIEL",
  "Confirms current listing data": "Bestätigt aktuelle Angebotsdaten",
  "Use CNBuy Sheet to re-check the product ID, current price, available variants, size details and destination link.": "Prüfe bei CNBuy Sheet Produkt-ID, aktuellen Preis, verfügbare Varianten, Größenangaben und Ziellink erneut.",
  "If live information conflicts with an older guide, use the live page.": "Wenn aktuelle Informationen einem älteren Leitfaden widersprechen, nutze die aktuelle Seite.",
  "Research rule / Reviewed July 23, 2026": "Rechercheregel / Geprüft am 23. Juli 2026",
  "UUFinds publicly supports QC-photo and QC-video discovery, image recognition and marketplace or agent-link handling, but it does not sell the products. These product cards lead only to CNBuy Sheet, where current listing information must be confirmed.": "UUFinds unterstützt öffentlich die Suche nach QC-Fotos und -Videos, Bilderkennung sowie Marktplatz- oder Agentenlinks, verkauft die Produkte jedoch nicht. Diese Produktkarten führen nur zu CNBuy Sheet, wo aktuelle Angebotsdaten bestätigt werden müssen.",

  "Articles / Official functions checked July 23, 2026": "Artikel / Offizielle Funktionen geprüft am 23. Juli 2026",
  "Search-led guides.": "Suchorientierte Ratgeber.",
  "Source-led claims.": "Quellenbasierte Aussagen.",
  "Each article separates what UUFinds publicly confirms from the practical inspection method added by this independent guide. Shopping and product routes remain exclusive to CNBuy Sheet.": "Jeder Artikel trennt öffentlich bestätigte UUFinds-Funktionen von der praktischen Prüfmethode dieses unabhängigen Leitfadens. Shopping- und Produktwege führen weiterhin ausschließlich zu CNBuy Sheet.",
  "Claim standard": "Standard für Aussagen",
  "Feature statements must be supported by UUFinds’ public QC, account, product or app information.": "Funktionsaussagen müssen durch öffentliche QC-, Konto-, Produkt- oder App-Informationen von UUFinds gestützt sein.",
  "Advice standard": "Standard für Ratschläge",
  "Inspection advice must clearly distinguish a visible observation from an unsupported conclusion.": "Prüfratschläge müssen sichtbare Beobachtungen klar von unbelegten Schlussfolgerungen trennen.",
  "Link standard": "Link-Standard",
  "Every shopping, category and product destination on this site points only to CNBuy Sheet.": "Jedes Shopping-, Kategorie- und Produktziel dieser Website führt ausschließlich zu CNBuy Sheet.",
  "Editorial source set": "Redaktioneller Quellensatz",
  "The current guide set was reviewed against UUFinds’ public QC finder and QC browsing copy, product-detail disclaimers, account pages, personalized display description and public app information. Where those sources do not establish a fact—such as a guaranteed number of recent QC sets, shipping price or product quality—the articles do not invent one.": "Die aktuellen Ratgeber wurden anhand der öffentlichen UUFinds-QC-Suche, QC-Seitentexte, Produkthaftungsausschlüsse, Kontoseiten, Beschreibung personalisierter Anzeigen und App-Informationen geprüft. Wo diese Quellen keine Tatsache belegen – etwa eine garantierte Anzahl aktueller QC-Sets, Versandpreise oder Produktqualität – erfinden die Artikel keine.",

  "These are images published with the corresponding CNBuy Sheet listing, not a claimed UUFinds QC album. Use the item ID to keep the listing traceable, then compare separately matched QC material when it exists.": "Dies sind Bilder des entsprechenden CNBuy-Sheet-Angebots, kein behauptetes UUFinds-QC-Album. Nutze die Artikel-ID zur Nachverfolgung und vergleiche separat passendes QC-Material, wenn es existiert.",
  "The displayed price and images are a dated snapshot. Confirm the current CNBuy Sheet listing for price, availability, sizes, colors, seller or source link and other live details.": "Der angezeigte Preis und die Bilder sind eine datierte Momentaufnahme. Bestätige im aktuellen CNBuy-Sheet-Angebot Preis, Verfügbarkeit, Größen, Farben, Verkäufer- oder Quelllink und weitere Live-Details.",
  "Apply the UUFinds research method": "UUFinds-Recherchemethode anwenden",
  "Three checks, three different jobs.": "Drei Prüfungen, drei verschiedene Aufgaben.",
  "Match the exact source": "Die genaue Quelle abgleichen",
  ". If UUFinds returns QC media, compare its source link, seller and visible variant—not only a similar thumbnail.": ". Wenn UUFinds QC-Medien liefert, vergleiche Quelllink, Verkäufer und sichtbare Variante – nicht nur ein ähnliches Vorschaubild.",
  "Inspect the visible evidence": "Sichtbare Belege prüfen",
  ". Compare more than one angle and record missing views or measurements as unknowns.": ". Vergleiche mehrere Ansichten und notiere fehlende Ansichten oder Maße als unbekannt.",
  "Verify current facts": "Aktuelle Fakten bestätigen",
  "Check the current price, available variants, size information, availability and seller or source details on the CNBuy Sheet product page before deciding.": "Prüfe vor der Entscheidung aktuellen Preis, verfügbare Varianten, Größenangaben, Verfügbarkeit und Verkäufer- oder Quelldetails auf der CNBuy-Sheet-Produktseite.",
  "Evidence boundary": "Grenzen der Belege",
  "Listing media is not automatically QC media.": "Angebotsmedien sind nicht automatisch QC-Medien.",
  "UUFinds publicly describes QC-photo and QC-video discovery, image recognition and supported link handling, while also stating that it does not sell products. This independent page likewise does not process an order. It identifies the CNBuy Sheet product, explains what to inspect and keeps the final destination explicit.": "UUFinds beschreibt öffentlich die Suche nach QC-Fotos und -Videos, Bilderkennung und unterstützte Link-Verarbeitung und erklärt zugleich, keine Produkte zu verkaufen. Auch diese unabhängige Seite bearbeitet keine Bestellung. Sie identifiziert das CNBuy-Sheet-Produkt, erklärt die Prüfung und kennzeichnet das endgültige Ziel eindeutig.",
  "Function claims were reviewed on July 23, 2026 against UUFinds’ public QC finder and QC browsing copy, product-detail disclaimer, account pages, personalized display description and public app information. Those sources support QC-photo and QC-video discovery, image recognition, link handling and shareable item pages. They do not support a guarantee of product quality, current stock, shipping cost or identical future batches.": "Die Funktionsangaben wurden am 23. Juli 2026 anhand der öffentlichen UUFinds-QC-Suche und QC-Seitentexte, des Produkt-Haftungsausschlusses, der Kontoseiten, der Beschreibung personalisierter Anzeigen und öffentlicher App-Informationen geprüft. Diese Quellen stützen die Suche nach QC-Fotos und -Videos, Bilderkennung, Link-Verarbeitung und teilbare Artikelseiten. Sie stützen keine Garantie für Produktqualität, aktuellen Bestand, Versandkosten oder identische spätere Chargen.",
  "The UUFinds functions in this beginner guide were checked on July 23, 2026 against the official public QC finder, QC browsing copy, account pages and public app information. Marketplace and agent-link handling, QC media and image-search features are documented; availability of matched media for any particular listing is not guaranteed.": "Die UUFinds-Funktionen in diesem Einsteigerleitfaden wurden am 23. Juli 2026 anhand der offiziellen öffentlichen QC-Suche, QC-Seitentexte, Kontoseiten und App-Informationen geprüft. Marktplatz- und Agentenlink-Verarbeitung, QC-Medien und Bildsuche sind dokumentiert; passende Medien für ein bestimmtes Angebot werden nicht garantiert.",
  "This comparison was reviewed on July 23, 2026 against UUFinds’ public description of QC-photo and QC-video discovery, image recognition and link handling, together with CNBuy Sheet’s live category and product-page structure. The comparison distinguishes documented platform functions from independent inspection advice.": "Dieser Vergleich wurde am 23. Juli 2026 anhand der öffentlichen UUFinds-Beschreibung von QC-Foto- und Videosuche, Bilderkennung und Link-Verarbeitung sowie der aktuellen Kategorie- und Produktseitenstruktur von CNBuy Sheet geprüft. Er trennt dokumentierte Plattformfunktionen von unabhängigen Prüfratschlägen.",
};

export const polishResearchExtras: Record<string, string> = {
  "July 23, 2026": "23 lipca 2026",
  "Verified UUFinds functions": "Zweryfikowane funkcje UUFinds",
  "How it works / Fact-checked July 23, 2026": "Jak to działa / Fakty sprawdzone 23 lipca 2026",
  "Match the link.": "Dopasuj link.",
  "Read the evidence.": "Przeanalizuj dowody.",
  "Verify what changed.": "Sprawdź, co się zmieniło.",
  "UUFinds publicly describes a QC finder for photos and videos, image recognition, and link handling for Taobao, Weidian, 1688 and shopping agents. Those tools can support research, but the exact live listing still decides the current price, variants and availability.": "UUFinds publicznie opisuje wyszukiwarkę zdjęć i filmów QC, rozpoznawanie obrazów oraz obsługę linków Taobao, Weidian, 1688 i agentów zakupowych. Narzędzia te wspierają analizę, ale dokładna aktualna oferta nadal określa cenę, warianty i dostępność.",
  "QC media": "Materiały QC",
  "UUFinds says its QC finder can surface available product photos and videos.": "UUFinds podaje, że jego wyszukiwarka QC może wyświetlać dostępne zdjęcia i filmy produktów.",
  "Supported inputs": "Obsługiwane dane",
  "Its public app information names 1688, Taobao, Weidian and shopping-agent link conversion.": "Publiczne informacje o aplikacji wymieniają 1688, Taobao, Weidian i konwersję linków agentów zakupowych.",
  "Platform boundary": "Granice platformy",
  "UUFinds states that it does not sell products directly or indirectly.": "UUFinds oświadcza, że nie sprzedaje produktów bezpośrednio ani pośrednio.",
  "MATCH": "DOPASUJ",
  "Preserve the exact source": "Zachowaj dokładne źródło",
  "Keep the full marketplace or agent link. Compare the item ID, seller and visible variant before treating an album as a match. Image recognition may find a visually similar item, but similarity alone does not prove it is the same listing or batch.": "Zachowaj pełny link z marketplace lub agenta. Porównaj identyfikator, sprzedawcę i widoczny wariant, zanim uznasz album za dopasowany. Rozpoznawanie obrazu może znaleźć podobny produkt, lecz samo podobieństwo nie dowodzi tej samej oferty ani partii.",
  "Build a category shortlist →": "Utwórz listę z kategorii →",
  "INSPECT": "SPRAWDŹ",
  "Read every available angle": "Sprawdź każde dostępne ujęcie",
  "Start with silhouette and proportion, then inspect construction, finish and measurements. Note the QC date and whether more than one example exists. Record missing angles as unknowns instead of turning them into assumptions.": "Zacznij od sylwetki i proporcji, potem sprawdź wykonanie, wykończenie i wymiary. Zapisz datę QC i liczbę przykładów. Brakujące ujęcia oznacz jako niewiadome, zamiast zamieniać je w założenia.",
  "CONFIRM": "POTWIERDŹ",
  "Check today’s listing facts": "Sprawdź dzisiejsze dane oferty",
  "Open the exact CNBuy Sheet product page and re-check the identifier, current price, variants, size information and availability. An older QC set can inform the decision, but it cannot confirm what the seller offers today.": "Otwórz dokładną stronę produktu CNBuy Sheet i ponownie sprawdź identyfikator, cenę, warianty, rozmiary i dostępność. Starszy zestaw QC może pomóc w decyzji, ale nie potwierdza dzisiejszej oferty sprzedawcy.",
  "Tool versus conclusion": "Narzędzie a wniosek",
  "Know what each signal can prove.": "Wiedz, co może potwierdzić każdy sygnał.",
  "This distinction prevents a useful research tool from being mistaken for a product guarantee.": "To rozróżnienie zapobiega myleniu użytecznego narzędzia badawczego z gwarancją produktu.",
  "QC PHOTOS": "ZDJĘCIA QC",
  "Useful for visible condition": "Przydatne do oceny widocznego stanu",
  "They can show shape, stitching, print placement, hardware and measurements on the photographed item.": "Mogą pokazać kształt, szwy, położenie nadruku, okucia i wymiary sfotografowanego produktu.",
  "They cannot guarantee another unit or later batch.": "Nie gwarantują innej sztuki ani późniejszej partii.",
  "QC VIDEO": "FILM QC",
  "Useful for movement": "Przydatny do oceny ruchu",
  "Video can reveal fabric drape, zipper movement, sole flex and angles that a still image may hide.": "Film może pokazać układanie się tkaniny, działanie zamka, elastyczność podeszwy i ujęcia niewidoczne na zdjęciu.",
  "It cannot establish durability or internal electronic condition.": "Nie potwierdza trwałości ani wewnętrznego stanu elektroniki.",
  "IMAGE RECOGNITION": "ROZPOZNAWANIE OBRAZU",
  "Useful for finding candidates": "Przydatne do znajdowania kandydatów",
  "A similar image can help locate related listings when the original link is missing or incomplete.": "Podobny obraz może pomóc znaleźć powiązane oferty, gdy oryginalny link jest niepełny lub go brakuje.",
  "It cannot replace the seller and item-ID match.": "Nie zastępuje dopasowania sprzedawcy i identyfikatora produktu.",
  "LIVE PRODUCT PAGE": "AKTUALNA STRONA PRODUKTU",
  "Useful for current facts": "Przydatna do aktualnych danych",
  "The destination page is where price, available options, seller details and stock must be checked again.": "Na stronie docelowej trzeba ponownie sprawdzić cenę, opcje, dane sprzedawcy i stan magazynowy.",
  "It still does not promise that every received item will match an older sample.": "Nadal nie gwarantuje, że każda otrzymana sztuka będzie zgodna ze starszą próbką.",
  "Five-line decision record": "Pięciopunktowy zapis decyzji",
  "Write this down before you continue.": "Zapisz to przed kontynuowaniem.",
  "Match:": "Dopasowanie:",
  "exact, probable, or visual reference only.": "dokładne, prawdopodobne lub tylko wizualne.",
  "Evidence:": "Dowody:",
  "which photos, video, angles and measurements were available.": "jakie zdjęcia, filmy, ujęcia i wymiary były dostępne.",
  "Unknowns:": "Niewiadome:",
  "missing views, material claims, sizing or internal condition.": "brakujące ujęcia, deklaracje materiału, rozmiar lub stan wewnętrzny.",
  "Live check:": "Sprawdzenie na żywo:",
  "current ID, price, variants and availability on CNBuy Sheet.": "aktualny identyfikator, cena, warianty i dostępność w CNBuy Sheet.",
  "Decision:": "Decyzja:",
  "keep, compare with another listing, or pause for more evidence.": "zachowaj, porównaj z inną ofertą lub poczekaj na więcej dowodów.",
  "Research boundary": "Granice analizy",
  "Discovery expands options. QC reduces uncertainty. The live listing confirms current facts.": "Odkrywanie rozszerza wybór. QC zmniejsza niepewność. Aktualna oferta potwierdza bieżące fakty.",
  "Official claims reviewed: UUFinds QC finder, QC browsing copy, product-detail disclaimer, account pages and public app information. No UUFinds outbound link is included on this site.": "Sprawdzone oficjalne informacje: wyszukiwarka QC UUFinds, treści stron QC, zastrzeżenia produktu, strony konta i publiczne informacje o aplikacji. Ta strona nie zawiera linków wychodzących do UUFinds.",
  "Read the complete buying guide →": "Przeczytaj pełny poradnik zakupowy →",

  "Finds / UUFinds research + 09 direct routes": "Znaleziska / analiza UUFinds + 09 bezpośrednich tras",
  "Discover broadly.": "Odkrywaj szeroko.",
  "Match precisely.": "Dopasowuj precyzyjnie.",
  "UUFinds publicly describes both QC discovery and personalized pages that combine items, purchasing-agent routes and social content. Use discovery to create a shortlist—then keep the exact source link so a popular image or shared page is never mistaken for proof of one specific listing.": "UUFinds publicznie opisuje zarówno wyszukiwanie QC, jak i spersonalizowane strony łączące produkty, agentów zakupowych i treści społecznościowe. Użyj odkrywania do utworzenia listy, a potem zachowaj dokładny link źródłowy, aby popularny obraz lub udostępniona strona nie zostały uznane za dowód konkretnej oferty.",
  "What the official pages establish": "Co potwierdzają oficjalne strony",
  "A find is a starting point.": "Znalezisko jest punktem wyjścia.",
  "The official public descriptions support product discovery, link handling, QC media and shareable item pages. They do not establish that every shared item has recent QC material or unchanged seller data.": "Oficjalne opisy potwierdzają odkrywanie produktów, obsługę linków, materiały QC i strony produktów do udostępniania. Nie potwierdzają, że każdy udostępniony produkt ma aktualne QC lub niezmienione dane sprzedawcy.",
  "SHARED ITEM PAGE": "UDOSTĘPNIONA STRONA PRODUKTU",
  "Useful for collecting leads": "Przydatna do zbierania propozycji",
  "UUFinds describes personalized pages that integrate items, purchasing agents and social content and can be shared through one link.": "UUFinds opisuje spersonalizowane strony łączące produkty, agentów zakupowych i treści społecznościowe, które można udostępnić jednym linkiem.",
  "Save the original item or seller link before researching quality.": "Zapisz oryginalny link produktu lub sprzedawcy przed analizą jakości.",
  "QC FINDER": "WYSZUKIWARKA QC",
  "Useful after discovery": "Przydatna po znalezieniu produktu",
  "The official QC finder describes photos, videos and image recognition. Availability depends on what material exists for the product or link.": "Oficjalna wyszukiwarka QC opisuje zdjęcia, filmy i rozpoznawanie obrazu. Dostępność zależy od materiałów istniejących dla produktu lub linku.",
  "A visually similar result is not automatically the same seller, variant or batch.": "Wizualnie podobny wynik nie oznacza automatycznie tego samego sprzedawcy, wariantu ani partii.",
  "CATEGORY ROUTE": "TRASA KATEGORII",
  "Useful when you only know the type": "Przydatna, gdy znasz tylko typ produktu",
  "Begin with Shoes, Hoodies, T-Shirts, Jackets, Pants, Headwear, Accessories, Jerseys or Electronics when no exact link exists yet.": "Zacznij od butów, bluz, T-shirtów, kurtek, spodni, nakryć głowy, akcesoriów, koszulek sportowych lub elektroniki, gdy nie masz jeszcze dokładnego linku.",
  "Shortlist two or three candidates before comparing evidence.": "Wybierz dwóch lub trzech kandydatów przed porównaniem dowodów.",
  "EXACT PRODUCT": "DOKŁADNY PRODUKT",
  "Useful for the final match": "Przydatny do końcowego dopasowania",
  "Open an individual CNBuy Sheet detail page and compare its product ID, images, price and variants with the item you researched.": "Otwórz szczegółową stronę CNBuy Sheet i porównaj identyfikator, zdjęcia, cenę i warianty z analizowanym produktem.",
  "Use the live page for current facts that a shared find cannot preserve.": "Użyj aktualnej strony do danych, których udostępnione znalezisko nie może zachować.",
  "A practical discovery routine": "Praktyczna rutyna odkrywania",
  "Turn browsing into a traceable shortlist.": "Zamień przeglądanie w listę możliwą do prześledzenia.",
  "Name the intent:": "Określ cel:",
  "inspiration, category comparison, or verification of one exact link.": "inspiracja, porównanie kategorii lub weryfikacja jednego dokładnego linku.",
  "Keep the source:": "Zachowaj źródło:",
  "preserve the full item URL and visible seller or item identifier.": "zapisz pełny URL produktu oraz widoczny identyfikator sprzedawcy lub produktu.",
  "Narrow the field:": "Zawęź wybór:",
  "compare category, model, material, price band and visible variants.": "porównaj kategorię, model, materiał, zakres cen i widoczne warianty.",
  "Research evidence:": "Sprawdź dowody:",
  "check whether matched QC photos or video exist and how recent they are.": "ustal, czy istnieją dopasowane zdjęcia lub filmy QC i jak są aktualne.",
  "Finish live:": "Zakończ na żywo:",
  "confirm today’s information on the exact CNBuy Sheet product page.": "potwierdź dzisiejsze dane na dokładnej stronie produktu CNBuy Sheet.",
  "Source boundary / Reviewed July 23, 2026": "Granice źródeł / Sprawdzono 23 lipca 2026",
  "Function claims on this page were checked against UUFinds’ public QC finder, QC browsing page, personalized display page, product disclaimer and app information. Category and shopping buttons remain exclusive to CNBuy Sheet.": "Funkcje opisane na tej stronie sprawdzono na podstawie publicznej wyszukiwarki QC UUFinds, strony QC, spersonalizowanej strony prezentacji, zastrzeżenia produktu i informacji o aplikacji. Przyciski kategorii i zakupów nadal prowadzą wyłącznie do CNBuy Sheet.",

  "Products / 08 direct listing routes": "Produkty / 08 bezpośrednich tras ofert",
  "See the listing.": "Zobacz ofertę.",
  "Separate it from QC evidence.": "Oddziel ją od dowodów QC.",
  "The images below come from the corresponding CNBuy Sheet listings; they are not labeled as UUFinds warehouse QC albums. Open a detail page, note the exact item ID, then use the official UUFinds research functions only when matched QC media is available for that source.": "Poniższe zdjęcia pochodzą z odpowiednich ofert CNBuy Sheet; nie są oznaczone jako magazynowe albumy QC UUFinds. Otwórz stronę szczegółów, zapisz dokładny identyfikator i użyj funkcji badawczych UUFinds tylko wtedy, gdy dla tego źródła dostępne są dopasowane materiały QC.",
  "Listing image versus QC evidence": "Zdjęcie oferty a dowody QC",
  "Do not grade the wrong photo set.": "Nie oceniaj niewłaściwego zestawu zdjęć.",
  "UUFinds says it can help find QC photos and videos. The first job is still matching that material to the exact item you intend to open.": "UUFinds podaje, że pomaga znajdować zdjęcia i filmy QC. Pierwszym zadaniem nadal jest dopasowanie materiału do dokładnego produktu, który chcesz otworzyć.",
  "LISTING IMAGE": "ZDJĘCIE OFERTY",
  "Shows how the product is presented": "Pokazuje sposób prezentacji produktu",
  "Use it to identify the model, color, design and seller-facing description on the current product page.": "Użyj go do rozpoznania modelu, koloru, projektu i opisu sprzedawcy na aktualnej stronie produktu.",
  "It may be a catalog or promotional image rather than a warehouse sample.": "Może to być zdjęcie katalogowe lub promocyjne, a nie próbka magazynowa.",
  "MATCHED QC PHOTO": "DOPASOWANE ZDJĘCIE QC",
  "Shows one photographed item": "Pokazuje jedną sfotografowaną sztukę",
  "Use it to inspect visible shape, construction, finish and measurements when the source link or item ID agrees.": "Użyj go do sprawdzenia widocznego kształtu, wykonania, wykończenia i wymiarów, gdy link źródłowy lub identyfikator się zgadza.",
  "It documents a sample, not every future unit.": "Dokumentuje próbkę, nie każdą przyszłą sztukę.",
  "Adds motion and hidden angles": "Dodaje ruch i ukryte ujęcia",
  "Use video to examine fabric drape, zipper movement, sole flex, reflective material or angles missing from still images.": "Użyj filmu do oceny układania się tkaniny, działania zamka, elastyczności podeszwy, materiału odblaskowego lub ujęć brakujących na zdjęciach.",
  "It does not confirm durability, authenticity or internal specifications.": "Nie potwierdza trwałości, autentyczności ani wewnętrznych parametrów.",
  "LIVE DESTINATION": "AKTUALNA STRONA DOCELOWA",
  "Confirms current listing data": "Potwierdza aktualne dane oferty",
  "Use CNBuy Sheet to re-check the product ID, current price, available variants, size details and destination link.": "W CNBuy Sheet ponownie sprawdź identyfikator, cenę, warianty, rozmiary i link docelowy.",
  "If live information conflicts with an older guide, use the live page.": "Jeśli aktualne dane różnią się od starszego poradnika, użyj bieżącej strony.",
  "Research rule / Reviewed July 23, 2026": "Zasada analizy / Sprawdzono 23 lipca 2026",
  "UUFinds publicly supports QC-photo and QC-video discovery, image recognition and marketplace or agent-link handling, but it does not sell the products. These product cards lead only to CNBuy Sheet, where current listing information must be confirmed.": "UUFinds publicznie obsługuje wyszukiwanie zdjęć i filmów QC, rozpoznawanie obrazu oraz linki marketplace i agentów, lecz nie sprzedaje produktów. Te karty prowadzą wyłącznie do CNBuy Sheet, gdzie trzeba potwierdzić aktualne dane oferty.",

  "Articles / Official functions checked July 23, 2026": "Artykuły / Oficjalne funkcje sprawdzone 23 lipca 2026",
  "Search-led guides.": "Poradniki oparte na wyszukiwaniu.",
  "Source-led claims.": "Twierdzenia oparte na źródłach.",
  "Each article separates what UUFinds publicly confirms from the practical inspection method added by this independent guide. Shopping and product routes remain exclusive to CNBuy Sheet.": "Każdy artykuł oddziela publicznie potwierdzone funkcje UUFinds od praktycznej metody kontroli dodanej przez ten niezależny przewodnik. Trasy zakupowe i produktowe prowadzą wyłącznie do CNBuy Sheet.",
  "Claim standard": "Standard twierdzeń",
  "Feature statements must be supported by UUFinds’ public QC, account, product or app information.": "Opis funkcji musi być poparty publicznymi informacjami UUFinds o QC, koncie, produkcie lub aplikacji.",
  "Advice standard": "Standard porad",
  "Inspection advice must clearly distinguish a visible observation from an unsupported conclusion.": "Porada kontrolna musi jasno odróżniać widoczną obserwację od niepopartego wniosku.",
  "Link standard": "Standard linków",
  "Every shopping, category and product destination on this site points only to CNBuy Sheet.": "Każdy link zakupowy, kategorii i produktu na tej stronie prowadzi wyłącznie do CNBuy Sheet.",
  "Editorial source set": "Zestaw źródeł redakcyjnych",
  "The current guide set was reviewed against UUFinds’ public QC finder and QC browsing copy, product-detail disclaimers, account pages, personalized display description and public app information. Where those sources do not establish a fact—such as a guaranteed number of recent QC sets, shipping price or product quality—the articles do not invent one.": "Obecne poradniki sprawdzono na podstawie publicznej wyszukiwarki QC UUFinds, treści strony QC, zastrzeżeń produktu, stron konta, opisu spersonalizowanej prezentacji i informacji o aplikacji. Gdy źródła nie potwierdzają faktu — np. gwarantowanej liczby nowych zestawów QC, ceny wysyłki lub jakości — artykuły go nie wymyślają.",

  "These are images published with the corresponding CNBuy Sheet listing, not a claimed UUFinds QC album. Use the item ID to keep the listing traceable, then compare separately matched QC material when it exists.": "To zdjęcia opublikowane z odpowiednią ofertą CNBuy Sheet, a nie deklarowany album QC UUFinds. Użyj identyfikatora, aby zachować możliwość śledzenia oferty, a potem porównaj osobno dopasowane materiały QC, jeśli istnieją.",
  "The displayed price and images are a dated snapshot. Confirm the current CNBuy Sheet listing for price, availability, sizes, colors, seller or source link and other live details.": "Wyświetlana cena i zdjęcia są datowaną migawką. W aktualnej ofercie CNBuy Sheet potwierdź cenę, dostępność, rozmiary, kolory, sprzedawcę lub link źródłowy i inne bieżące dane.",
  "Apply the UUFinds research method": "Zastosuj metodę analizy UUFinds",
  "Three checks, three different jobs.": "Trzy kontrole, trzy różne zadania.",
  "Match the exact source": "Dopasuj dokładne źródło",
  ". If UUFinds returns QC media, compare its source link, seller and visible variant—not only a similar thumbnail.": ". Jeśli UUFinds zwróci materiały QC, porównaj link źródłowy, sprzedawcę i widoczny wariant, a nie tylko podobną miniaturę.",
  "Inspect the visible evidence": "Sprawdź widoczne dowody",
  ". Compare more than one angle and record missing views or measurements as unknowns.": ". Porównaj więcej niż jedno ujęcie i zapisz brakujące widoki lub wymiary jako niewiadome.",
  "Verify current facts": "Potwierdź aktualne fakty",
  "Check the current price, available variants, size information, availability and seller or source details on the CNBuy Sheet product page before deciding.": "Przed decyzją sprawdź na stronie produktu CNBuy Sheet aktualną cenę, warianty, rozmiary, dostępność oraz dane sprzedawcy lub źródła.",
  "Evidence boundary": "Granice dowodów",
  "Listing media is not automatically QC media.": "Materiały oferty nie są automatycznie materiałami QC.",
  "UUFinds publicly describes QC-photo and QC-video discovery, image recognition and supported link handling, while also stating that it does not sell products. This independent page likewise does not process an order. It identifies the CNBuy Sheet product, explains what to inspect and keeps the final destination explicit.": "UUFinds publicznie opisuje wyszukiwanie zdjęć i filmów QC, rozpoznawanie obrazu i obsługę linków, jednocześnie stwierdzając, że nie sprzedaje produktów. Ta niezależna strona również nie obsługuje zamówień. Identyfikuje produkt CNBuy Sheet, wyjaśnia kontrolę i jasno wskazuje końcowe miejsce docelowe.",
  "Function claims were reviewed on July 23, 2026 against UUFinds’ public QC finder and QC browsing copy, product-detail disclaimer, account pages, personalized display description and public app information. Those sources support QC-photo and QC-video discovery, image recognition, link handling and shareable item pages. They do not support a guarantee of product quality, current stock, shipping cost or identical future batches.": "Opisy funkcji sprawdzono 23 lipca 2026 r. na podstawie publicznej wyszukiwarki QC i treści QC UUFinds, zastrzeżenia produktu, stron konta, opisu spersonalizowanej prezentacji i informacji o aplikacji. Źródła potwierdzają wyszukiwanie zdjęć i filmów QC, rozpoznawanie obrazu, obsługę linków i udostępniane strony produktów. Nie gwarantują jakości, bieżącego stanu, kosztu wysyłki ani identycznych przyszłych partii.",
  "The UUFinds functions in this beginner guide were checked on July 23, 2026 against the official public QC finder, QC browsing copy, account pages and public app information. Marketplace and agent-link handling, QC media and image-search features are documented; availability of matched media for any particular listing is not guaranteed.": "Funkcje UUFinds w tym poradniku sprawdzono 23 lipca 2026 r. na podstawie oficjalnej publicznej wyszukiwarki QC, treści strony QC, stron konta i informacji o aplikacji. Obsługa linków marketplace i agentów, materiały QC oraz wyszukiwanie obrazem są udokumentowane; dopasowane materiały dla konkretnej oferty nie są gwarantowane.",
  "This comparison was reviewed on July 23, 2026 against UUFinds’ public description of QC-photo and QC-video discovery, image recognition and link handling, together with CNBuy Sheet’s live category and product-page structure. The comparison distinguishes documented platform functions from independent inspection advice.": "Porównanie sprawdzono 23 lipca 2026 r. na podstawie publicznego opisu wyszukiwania zdjęć i filmów QC, rozpoznawania obrazu i obsługi linków UUFinds oraz aktualnej struktury kategorii i produktów CNBuy Sheet. Rozróżnia ono udokumentowane funkcje platformy od niezależnych porad kontrolnych.",
};

export const portugueseResearchExtras: Record<string, string> = {
  "July 23, 2026": "23 de julho de 2026",
  "Verified UUFinds functions": "Funções verificadas do UUFinds",
  "How it works / Fact-checked July 23, 2026": "Como funciona / Fatos verificados em 23 de julho de 2026",
  "Match the link.": "Confirme o link.",
  "Read the evidence.": "Analise as evidências.",
  "Verify what changed.": "Confira o que mudou.",
  "UUFinds publicly describes a QC finder for photos and videos, image recognition, and link handling for Taobao, Weidian, 1688 and shopping agents. Those tools can support research, but the exact live listing still decides the current price, variants and availability.": "O UUFinds descreve publicamente um localizador de fotos e vídeos de QC, reconhecimento de imagem e tratamento de links do Taobao, Weidian, 1688 e agentes de compras. Essas ferramentas ajudam na pesquisa, mas o anúncio exato e atual ainda determina preço, variações e disponibilidade.",
  "QC media": "Materiais de QC",
  "UUFinds says its QC finder can surface available product photos and videos.": "O UUFinds informa que seu localizador de QC pode mostrar fotos e vídeos disponíveis dos produtos.",
  "Supported inputs": "Entradas compatíveis",
  "Its public app information names 1688, Taobao, Weidian and shopping-agent link conversion.": "As informações públicas do aplicativo citam 1688, Taobao, Weidian e conversão de links de agentes de compras.",
  "Platform boundary": "Limites da plataforma",
  "UUFinds states that it does not sell products directly or indirectly.": "O UUFinds declara que não vende produtos direta nem indiretamente.",
  "MATCH": "CORRESPONDER",
  "Preserve the exact source": "Mantenha a fonte exata",
  "Keep the full marketplace or agent link. Compare the item ID, seller and visible variant before treating an album as a match. Image recognition may find a visually similar item, but similarity alone does not prove it is the same listing or batch.": "Guarde o link completo do marketplace ou agente. Compare o ID, o vendedor e a variação visível antes de considerar um álbum correspondente. O reconhecimento de imagem pode encontrar algo parecido, mas semelhança não comprova o mesmo anúncio ou lote.",
  "Build a category shortlist →": "Criar uma lista por categoria →",
  "INSPECT": "INSPECIONAR",
  "Read every available angle": "Analise todos os ângulos disponíveis",
  "Start with silhouette and proportion, then inspect construction, finish and measurements. Note the QC date and whether more than one example exists. Record missing angles as unknowns instead of turning them into assumptions.": "Comece pela silhueta e proporção; depois verifique construção, acabamento e medidas. Anote a data do QC e se há mais de um exemplo. Registre ângulos ausentes como incógnitas, sem transformá-los em suposições.",
  "CONFIRM": "CONFIRMAR",
  "Check today’s listing facts": "Confira os dados atuais do anúncio",
  "Open the exact CNBuy Sheet product page and re-check the identifier, current price, variants, size information and availability. An older QC set can inform the decision, but it cannot confirm what the seller offers today.": "Abra a página exata do produto no CNBuy Sheet e confira novamente identificador, preço, variações, tamanhos e disponibilidade. Um QC antigo pode ajudar na decisão, mas não confirma o que o vendedor oferece hoje.",
  "Tool versus conclusion": "Ferramenta versus conclusão",
  "Know what each signal can prove.": "Saiba o que cada sinal pode comprovar.",
  "This distinction prevents a useful research tool from being mistaken for a product guarantee.": "Essa distinção evita que uma ferramenta útil de pesquisa seja confundida com garantia do produto.",
  "QC PHOTOS": "FOTOS DE QC",
  "Useful for visible condition": "Úteis para o estado visível",
  "They can show shape, stitching, print placement, hardware and measurements on the photographed item.": "Podem mostrar formato, costura, posição da estampa, ferragens e medidas do item fotografado.",
  "They cannot guarantee another unit or later batch.": "Não garantem outra unidade ou lote posterior.",
  "QC VIDEO": "VÍDEO DE QC",
  "Useful for movement": "Útil para movimento",
  "Video can reveal fabric drape, zipper movement, sole flex and angles that a still image may hide.": "O vídeo pode mostrar caimento do tecido, movimento do zíper, flexão da sola e ângulos ocultos em uma foto.",
  "It cannot establish durability or internal electronic condition.": "Não comprova durabilidade nem o estado interno de eletrônicos.",
  "IMAGE RECOGNITION": "RECONHECIMENTO DE IMAGEM",
  "Useful for finding candidates": "Útil para encontrar candidatos",
  "A similar image can help locate related listings when the original link is missing or incomplete.": "Uma imagem semelhante pode ajudar a localizar anúncios relacionados quando o link original está ausente ou incompleto.",
  "It cannot replace the seller and item-ID match.": "Não substitui a correspondência do vendedor e do ID do item.",
  "LIVE PRODUCT PAGE": "PÁGINA ATUAL DO PRODUTO",
  "Useful for current facts": "Útil para dados atuais",
  "The destination page is where price, available options, seller details and stock must be checked again.": "Na página de destino, preço, opções, dados do vendedor e estoque devem ser conferidos novamente.",
  "It still does not promise that every received item will match an older sample.": "Ainda assim, ela não promete que todo item recebido será igual a uma amostra antiga.",
  "Five-line decision record": "Registro de decisão em cinco linhas",
  "Write this down before you continue.": "Anote isto antes de continuar.",
  "Match:": "Correspondência:",
  "exact, probable, or visual reference only.": "exata, provável ou apenas referência visual.",
  "Evidence:": "Evidências:",
  "which photos, video, angles and measurements were available.": "quais fotos, vídeos, ângulos e medidas estavam disponíveis.",
  "Unknowns:": "Incógnitas:",
  "missing views, material claims, sizing or internal condition.": "vistas ausentes, alegações de material, tamanho ou estado interno.",
  "Live check:": "Verificação atual:",
  "current ID, price, variants and availability on CNBuy Sheet.": "ID, preço, variações e disponibilidade atuais no CNBuy Sheet.",
  "Decision:": "Decisão:",
  "keep, compare with another listing, or pause for more evidence.": "manter, comparar com outro anúncio ou aguardar mais evidências.",
  "Research boundary": "Limites da pesquisa",
  "Discovery expands options. QC reduces uncertainty. The live listing confirms current facts.": "A descoberta amplia opções. O QC reduz incertezas. O anúncio atual confirma os fatos atuais.",
  "Official claims reviewed: UUFinds QC finder, QC browsing copy, product-detail disclaimer, account pages and public app information. No UUFinds outbound link is included on this site.": "Declarações oficiais revisadas: localizador de QC, textos da área de QC, aviso de produto, páginas de conta e informações públicas do aplicativo UUFinds. Este site não inclui links externos para o UUFinds.",
  "Read the complete buying guide →": "Ler o guia completo de compra →",

  "Finds / UUFinds research + 09 direct routes": "Achados / pesquisa UUFinds + 09 rotas diretas",
  "Discover broadly.": "Descubra amplamente.",
  "Match precisely.": "Faça a correspondência com precisão.",
  "UUFinds publicly describes both QC discovery and personalized pages that combine items, purchasing-agent routes and social content. Use discovery to create a shortlist—then keep the exact source link so a popular image or shared page is never mistaken for proof of one specific listing.": "O UUFinds descreve publicamente a descoberta de QC e páginas personalizadas que reúnem itens, agentes de compras e conteúdo social. Use a descoberta para criar uma lista e guarde o link exato da fonte, evitando confundir uma imagem popular ou página compartilhada com prova de um anúncio específico.",
  "What the official pages establish": "O que as páginas oficiais comprovam",
  "A find is a starting point.": "Um achado é um ponto de partida.",
  "The official public descriptions support product discovery, link handling, QC media and shareable item pages. They do not establish that every shared item has recent QC material or unchanged seller data.": "As descrições públicas oficiais confirmam descoberta de produtos, tratamento de links, materiais de QC e páginas compartilháveis. Elas não comprovam que todo item compartilhado tenha QC recente ou dados inalterados do vendedor.",
  "SHARED ITEM PAGE": "PÁGINA COMPARTILHADA",
  "Useful for collecting leads": "Útil para reunir opções",
  "UUFinds describes personalized pages that integrate items, purchasing agents and social content and can be shared through one link.": "O UUFinds descreve páginas personalizadas que integram itens, agentes de compras e conteúdo social e podem ser compartilhadas por um único link.",
  "Save the original item or seller link before researching quality.": "Salve o link original do item ou vendedor antes de pesquisar a qualidade.",
  "QC FINDER": "LOCALIZADOR DE QC",
  "Useful after discovery": "Útil depois da descoberta",
  "The official QC finder describes photos, videos and image recognition. Availability depends on what material exists for the product or link.": "O localizador oficial de QC descreve fotos, vídeos e reconhecimento de imagem. A disponibilidade depende do material existente para o produto ou link.",
  "A visually similar result is not automatically the same seller, variant or batch.": "Um resultado visualmente parecido não é automaticamente do mesmo vendedor, variação ou lote.",
  "CATEGORY ROUTE": "ROTA DE CATEGORIA",
  "Useful when you only know the type": "Útil quando você sabe apenas o tipo",
  "Begin with Shoes, Hoodies, T-Shirts, Jackets, Pants, Headwear, Accessories, Jerseys or Electronics when no exact link exists yet.": "Comece por Tênis, Moletons, Camisetas, Jaquetas, Calças, Bonés, Acessórios, Camisas esportivas ou Eletrônicos quando ainda não houver um link exato.",
  "Shortlist two or three candidates before comparing evidence.": "Selecione dois ou três candidatos antes de comparar evidências.",
  "EXACT PRODUCT": "PRODUTO EXATO",
  "Useful for the final match": "Útil para a correspondência final",
  "Open an individual CNBuy Sheet detail page and compare its product ID, images, price and variants with the item you researched.": "Abra uma página individual do CNBuy Sheet e compare ID, imagens, preço e variações com o item pesquisado.",
  "Use the live page for current facts that a shared find cannot preserve.": "Use a página atual para fatos que um achado compartilhado não consegue preservar.",
  "A practical discovery routine": "Uma rotina prática de descoberta",
  "Turn browsing into a traceable shortlist.": "Transforme a navegação em uma lista rastreável.",
  "Name the intent:": "Defina o objetivo:",
  "inspiration, category comparison, or verification of one exact link.": "inspiração, comparação de categoria ou verificação de um link exato.",
  "Keep the source:": "Mantenha a fonte:",
  "preserve the full item URL and visible seller or item identifier.": "guarde a URL completa e o identificador visível do vendedor ou item.",
  "Narrow the field:": "Reduza as opções:",
  "compare category, model, material, price band and visible variants.": "compare categoria, modelo, material, faixa de preço e variações visíveis.",
  "Research evidence:": "Pesquise evidências:",
  "check whether matched QC photos or video exist and how recent they are.": "verifique se há fotos ou vídeos de QC correspondentes e quão recentes são.",
  "Finish live:": "Finalize na página atual:",
  "confirm today’s information on the exact CNBuy Sheet product page.": "confirme os dados de hoje na página exata do produto no CNBuy Sheet.",
  "Source boundary / Reviewed July 23, 2026": "Limite das fontes / Revisado em 23 de julho de 2026",
  "Function claims on this page were checked against UUFinds’ public QC finder, QC browsing page, personalized display page, product disclaimer and app information. Category and shopping buttons remain exclusive to CNBuy Sheet.": "As funções desta página foram verificadas no localizador público de QC, página de QC, página personalizada, aviso de produto e informações do aplicativo UUFinds. Os botões de categoria e compra continuam exclusivos do CNBuy Sheet.",

  "Products / 08 direct listing routes": "Produtos / 08 rotas diretas de anúncios",
  "See the listing.": "Veja o anúncio.",
  "Separate it from QC evidence.": "Separe-o das evidências de QC.",
  "The images below come from the corresponding CNBuy Sheet listings; they are not labeled as UUFinds warehouse QC albums. Open a detail page, note the exact item ID, then use the official UUFinds research functions only when matched QC media is available for that source.": "As imagens abaixo vêm dos anúncios correspondentes no CNBuy Sheet; não estão identificadas como álbuns de QC do armazém UUFinds. Abra a página de detalhes, anote o ID exato e use as funções de pesquisa do UUFinds somente quando houver materiais de QC correspondentes para essa fonte.",
  "Listing image versus QC evidence": "Imagem do anúncio versus evidência de QC",
  "Do not grade the wrong photo set.": "Não avalie o conjunto de fotos errado.",
  "UUFinds says it can help find QC photos and videos. The first job is still matching that material to the exact item you intend to open.": "O UUFinds informa que pode ajudar a encontrar fotos e vídeos de QC. A primeira tarefa continua sendo corresponder esse material ao item exato que você pretende abrir.",
  "LISTING IMAGE": "IMAGEM DO ANÚNCIO",
  "Shows how the product is presented": "Mostra como o produto é apresentado",
  "Use it to identify the model, color, design and seller-facing description on the current product page.": "Use-a para identificar modelo, cor, design e descrição do vendedor na página atual do produto.",
  "It may be a catalog or promotional image rather than a warehouse sample.": "Pode ser uma imagem de catálogo ou promocional, e não uma amostra de armazém.",
  "MATCHED QC PHOTO": "FOTO DE QC CORRESPONDENTE",
  "Shows one photographed item": "Mostra um item fotografado",
  "Use it to inspect visible shape, construction, finish and measurements when the source link or item ID agrees.": "Use-a para verificar formato, construção, acabamento e medidas quando o link da fonte ou ID corresponder.",
  "It documents a sample, not every future unit.": "Documenta uma amostra, não todas as unidades futuras.",
  "Adds motion and hidden angles": "Adiciona movimento e ângulos ocultos",
  "Use video to examine fabric drape, zipper movement, sole flex, reflective material or angles missing from still images.": "Use o vídeo para analisar caimento, movimento do zíper, flexão da sola, material refletivo ou ângulos ausentes nas fotos.",
  "It does not confirm durability, authenticity or internal specifications.": "Não confirma durabilidade, autenticidade nem especificações internas.",
  "LIVE DESTINATION": "DESTINO ATUAL",
  "Confirms current listing data": "Confirma dados atuais do anúncio",
  "Use CNBuy Sheet to re-check the product ID, current price, available variants, size details and destination link.": "No CNBuy Sheet, confira novamente ID, preço, variações, tamanhos e link de destino.",
  "If live information conflicts with an older guide, use the live page.": "Se os dados atuais divergirem de um guia antigo, use a página atual.",
  "Research rule / Reviewed July 23, 2026": "Regra de pesquisa / Revisado em 23 de julho de 2026",
  "UUFinds publicly supports QC-photo and QC-video discovery, image recognition and marketplace or agent-link handling, but it does not sell the products. These product cards lead only to CNBuy Sheet, where current listing information must be confirmed.": "O UUFinds oferece publicamente busca de fotos e vídeos de QC, reconhecimento de imagem e tratamento de links de marketplace ou agente, mas não vende produtos. Estes cartões levam apenas ao CNBuy Sheet, onde os dados atuais do anúncio devem ser confirmados.",

  "Articles / Official functions checked July 23, 2026": "Artigos / Funções oficiais verificadas em 23 de julho de 2026",
  "Search-led guides.": "Guias orientados pela busca.",
  "Source-led claims.": "Afirmações orientadas por fontes.",
  "Each article separates what UUFinds publicly confirms from the practical inspection method added by this independent guide. Shopping and product routes remain exclusive to CNBuy Sheet.": "Cada artigo separa o que o UUFinds confirma publicamente do método prático de inspeção deste guia independente. As rotas de compra e produto continuam exclusivas do CNBuy Sheet.",
  "Claim standard": "Padrão de afirmações",
  "Feature statements must be supported by UUFinds’ public QC, account, product or app information.": "Afirmações de recursos devem ser sustentadas por informações públicas de QC, conta, produto ou aplicativo do UUFinds.",
  "Advice standard": "Padrão de orientação",
  "Inspection advice must clearly distinguish a visible observation from an unsupported conclusion.": "A orientação de inspeção deve diferenciar claramente observação visível de conclusão sem respaldo.",
  "Link standard": "Padrão de links",
  "Every shopping, category and product destination on this site points only to CNBuy Sheet.": "Todo destino de compra, categoria e produto deste site aponta somente para o CNBuy Sheet.",
  "Editorial source set": "Conjunto de fontes editoriais",
  "The current guide set was reviewed against UUFinds’ public QC finder and QC browsing copy, product-detail disclaimers, account pages, personalized display description and public app information. Where those sources do not establish a fact—such as a guaranteed number of recent QC sets, shipping price or product quality—the articles do not invent one.": "O conjunto atual de guias foi revisado com base no localizador público de QC, textos de QC, avisos de produto, páginas de conta, descrição personalizada e informações do aplicativo UUFinds. Quando essas fontes não comprovam um fato — como número garantido de QC recentes, preço de envio ou qualidade — os artigos não o inventam.",

  "These are images published with the corresponding CNBuy Sheet listing, not a claimed UUFinds QC album. Use the item ID to keep the listing traceable, then compare separately matched QC material when it exists.": "Estas são imagens publicadas com o anúncio correspondente no CNBuy Sheet, não um suposto álbum de QC do UUFinds. Use o ID para manter o anúncio rastreável e compare materiais de QC correspondentes separadamente quando existirem.",
  "The displayed price and images are a dated snapshot. Confirm the current CNBuy Sheet listing for price, availability, sizes, colors, seller or source link and other live details.": "O preço e as imagens exibidos são um registro datado. Confirme no anúncio atual do CNBuy Sheet preço, disponibilidade, tamanhos, cores, vendedor ou link de origem e outros dados atuais.",
  "Apply the UUFinds research method": "Aplique o método de pesquisa do UUFinds",
  "Three checks, three different jobs.": "Três verificações, três funções diferentes.",
  "Match the exact source": "Corresponda a fonte exata",
  ". If UUFinds returns QC media, compare its source link, seller and visible variant—not only a similar thumbnail.": ". Se o UUFinds retornar materiais de QC, compare link de origem, vendedor e variação visível, não apenas uma miniatura parecida.",
  "Inspect the visible evidence": "Analise as evidências visíveis",
  ". Compare more than one angle and record missing views or measurements as unknowns.": ". Compare mais de um ângulo e registre vistas ou medidas ausentes como incógnitas.",
  "Verify current facts": "Confirme os fatos atuais",
  "Check the current price, available variants, size information, availability and seller or source details on the CNBuy Sheet product page before deciding.": "Antes de decidir, confira na página do produto no CNBuy Sheet preço, variações, tamanhos, disponibilidade e dados do vendedor ou fonte.",
  "Evidence boundary": "Limites das evidências",
  "Listing media is not automatically QC media.": "Materiais do anúncio não são automaticamente materiais de QC.",
  "UUFinds publicly describes QC-photo and QC-video discovery, image recognition and supported link handling, while also stating that it does not sell products. This independent page likewise does not process an order. It identifies the CNBuy Sheet product, explains what to inspect and keeps the final destination explicit.": "O UUFinds descreve publicamente a busca de fotos e vídeos de QC, reconhecimento de imagem e tratamento de links, declarando também que não vende produtos. Esta página independente também não processa pedidos. Ela identifica o produto no CNBuy Sheet, explica o que verificar e deixa o destino final explícito.",
  "Function claims were reviewed on July 23, 2026 against UUFinds’ public QC finder and QC browsing copy, product-detail disclaimer, account pages, personalized display description and public app information. Those sources support QC-photo and QC-video discovery, image recognition, link handling and shareable item pages. They do not support a guarantee of product quality, current stock, shipping cost or identical future batches.": "As alegações de função foram revisadas em 23 de julho de 2026 no localizador público e nos textos de QC do UUFinds, no aviso de produto, nas páginas de conta, na descrição personalizada e nas informações do aplicativo. Essas fontes sustentam busca de fotos e vídeos de QC, reconhecimento de imagem, tratamento de links e páginas compartilháveis. Não garantem qualidade, estoque atual, custo de envio ou lotes futuros idênticos.",
  "The UUFinds functions in this beginner guide were checked on July 23, 2026 against the official public QC finder, QC browsing copy, account pages and public app information. Marketplace and agent-link handling, QC media and image-search features are documented; availability of matched media for any particular listing is not guaranteed.": "As funções do UUFinds neste guia para iniciantes foram verificadas em 23 de julho de 2026 no localizador oficial de QC, nos textos da área de QC, nas páginas de conta e nas informações públicas do aplicativo. Tratamento de links de marketplace e agentes, materiais de QC e busca por imagem são documentados; não há garantia de materiais correspondentes para um anúncio específico.",
  "This comparison was reviewed on July 23, 2026 against UUFinds’ public description of QC-photo and QC-video discovery, image recognition and link handling, together with CNBuy Sheet’s live category and product-page structure. The comparison distinguishes documented platform functions from independent inspection advice.": "Esta comparação foi revisada em 23 de julho de 2026 com base na descrição pública do UUFinds sobre busca de fotos e vídeos de QC, reconhecimento de imagem e tratamento de links, junto à estrutura atual de categorias e produtos do CNBuy Sheet. A comparação separa funções documentadas da plataforma de orientações independentes de inspeção.",
};
